### ISSUE TITLE
Use Fractal Transformers in OrderController for Pimcore Backend

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1005]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes

I currently need to extend and customize the order detail view in the Pimcore backend. So after some work I thought, wouldn't it be better if the data is prepared via extendable Fractal Transformers. This would make it much easier to add data.
https://fractal.thephpleague.com/transformers/

**Comment by dpfaffenbauer** [comment]
not sure fractal is the right lib for it, it doesn't seem to support multiple "transformers"

**Comment by davidhoeck** [comment]
Fractal supports multiple transformers. Usually you create a transformer for every entity and those can be combined. If they are defined as services they could also be decorated and extended.

**Comment by dpfaffenbauer** [comment]
still, since we are talking about serialization in some sort, I don't think it is the right lib.
