### ISSUE TITLE
Enable variants on product model

### ISSUE THREAD

**Issue by gicuturetchi** [coreshop/CoreShop#1008]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
Hello, I tried to allow variants on product model, so I checked : "Allow inheritance" && "Allow variants", but I get the error : 
```
An exception has been thrown during the rendering of a template ("Warning: count(): Parameter must be an array or an object that implements Countable").
```

**Comment by dpfaffenbauer** [comment]
on saving the class definition? it works in the deom

**Comment by gicuturetchi** [comment]
![Screenshot from 2019-05-30 10-52-25](https://user-images.githubusercontent.com/6445778/58617568-20b0b600-82c9-11e9-8d99-88c45f95337f.png)
![Screenshot from 2019-05-30 10-52-49](https://user-images.githubusercontent.com/6445778/58617571-23131000-82c9-11e9-8a8a-723cd33e0ccd.png)

@dpfaffenbauer  You can see the error and what modifications I did.

**Comment by gicuturetchi** [comment]
ok, solved..the problem was that the product didn't have attached an image... strange :)
