### ISSUE TITLE
Product Variants are not displayed in front office

### ISSUE THREAD

**Issue by gicuturetchi** [coreshop/CoreShop#1009]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

Hello, I created 2 new variations for a product in demo backoffice, but these variations are not displayed in front backoffice. Any ideas @dpfaffenbauer ?

**Comment by dpfaffenbauer** [comment]
CoreShop doesn't solve that problem, you have to care about that yourself. Variants are very different from project to project.
