### ISSUE TITLE
Get the liste of variations

### ISSUE THREAD

**Issue by gicuturetchi** [coreshop/CoreShop#1011]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
I rewrite the ProductController.php and I tried to get the liste of variations in detailAction(). I have for this product 2 variations, so I tried :
```
Empty Array : 
dump($product->getVariantDifferences('en', 'classificationstore', 'classificationStore'));die();
Empty Array : 
dump($product->getVariantDifferences('en'));die();
```
Any ideas ?

**Comment by dpfaffenbauer** [comment]
That function is deprecated and should not be used anymore. As I said, you have to solve it yourself!
