### ISSUE TITLE
Errors after update to the new version

### ISSUE THREAD

**Issue by gicuturetchi** [coreshop/CoreShop#1012]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

Hello guys, I update the coreshop to the version 2.0.8, to be able to use import/definitions plugin.
So I did :
```
composer require coreshop/core-shop:2.0.8
```
composer runs whitout problems, but now I have the error when I reload the browser  : 
```
Attempted to load class "ProductUnitDefinitions" from namespace "CoreShop\Bundle\ProductBundle\CoreExtension".
 var/classes/definition_CoreShopProduct.php
``` 
I tried to rebuild classe like 
```
bin/console pimcore:deployment:classes-rebuild -c
```
But I have the same issue :confused:

**Comment by dpfaffenbauer** [comment]
it seems you downgraded your version. ProductUnitDefinitions was introduce in the master (2.1-dev) branch

**Comment by dpfaffenbauer** [comment]
manually clear your definition file and remove fields that aren't in 2.0 and rebuild the classes

**Comment by gicuturetchi** [comment]
@dpfaffenbauer what is the last version that I need to update ?

**Comment by dpfaffenbauer** [comment]
the latest version is 2.0.8. But if you installed 2.1-dev, downgrading is possible, but difficult. A lot of new things have been introduced. You are better if you completely reinstall.

**Comment by gicuturetchi** [comment]
@dpfaffenbauer  So I need to remove actual coreshop, and install : 2.0.8 ? in order to be  able to use product variants, import/definitions, etc ?
Thx

**Comment by dpfaffenbauer** [comment]
you can also use 2.1-dev.....

**Comment by gicuturetchi** [comment]
composer require coreshop/core-shop:2.1-dev : 
Error :   Could not find package coreshop/core-shop in a version matching 2.1-dev  
@dpfaffenbauer any ideas please ?

**Comment by dpfaffenbauer** [comment]
can you please read the composer docs.
