### ISSUE TITLE
Error when try to get product repository

### ISSUE THREAD

**Issue by turgic** [coreshop/CoreShop#1018]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

Hello guys, I created a new api using https://github.com/DivanteLtd/coreshop-vsbridge : 
```
/**
     * @Route("/vsbridge/product/get/{product}")
     * @Method("POST")
     *
     * @param Request           $request
     * @param CartResponse      $cartResponse
     *
     * @return JsonResponse
     */
    public function testProduct(
        Request $request
    ) {
//        $product = $this->get('coreshop.repository.stack.purchasable')->find($request->get('product'));
        $productRepository = $this->get('coreshop.repository.product');

        return $this->json([
            'status' => 200,
            'result' => [$productRepository],
        ]);
    }
```
But I get the error :
```
CoreShop\Component\Product\Model\Product of \CoreShop\Component\Product\Model\Product::getIsAvailableWhenOutOfStock() needs to be implemented by Pimcore. (500 Internal Server Error)
```
You have an idea ? thx in advance

**Comment by dpfaffenbauer** [comment]
Yes, the function isn't available anymore and only exists for BC reasons, just don't use it anymore.

**Comment by turgic** [comment]
In which version is deleted this function @dpfaffenbauer  ? Because I use Coreshop 2.1.0

**Comment by dpfaffenbauer** [comment]
it's has not been deleted yet. To be honest, it should have been deleted before 2.0, but we forgot about it. I will delete it with 2.1 and create a PR for it.

**Comment by turgic** [comment]
Thank you @dpfaffenbauer

**Comment by turgic** [comment]
I have a new error : 
```
Call to a member function isAdmin() on null (500 Internal Server Error)
```
I try to access an api with authorisation token. Have you an idea ?

**Comment by dpfaffenbauer** [comment]
no

**Comment by turgic** [comment]
Hello @dpfaffenbauer 
I made an /usr/local/bin/composer require coreshop/core-shop:^2.1-dev
But I still have fonctions getIsAvailableWhenOutOfStock(), setIsAvailableWhenOutOfStock()
Could you confirm that these functions was already deleted ? Thx

**Comment by dpfaffenbauer** [comment]
I confirm it is deleted

**Comment by turgic** [comment]
Hm strange, why are not deleted after this execution : composer require coreshop/core-shop:^2.1-dev ?
Or I need to do a composer update  @dpfaffenbauer ?
