### ISSUE TITLE
Call to a member function getPrice() on array

### ISSUE THREAD

**Issue by turgic** [coreshop/CoreShop#1027]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

Hello guys, I tried to get the price for a product with specific rules, I do :
```
use CoreShop\Component\Product\Calculator\ProductPriceCalculator;
...
$productPrice = $priceCalculator->getPrice($variant, $shopperContext->getContext())
```
But I get the error :
```
Call to a member function getPrice() on array
```
From what I debug the error comes from `/vendor/coreshop/core-sho/src/CoreShop/Component/Core/Product/Calculator/StoreProductPriceCalculator.php `:
```
if (0 === $storeValues->getPrice()) {
    throw new NoRetailPriceFoundException(__CLASS__);
}
```

The problem appear only for variants.
So for basic product `$storeValues = $subject->getStoreValues($context['store']);`
the return is object
But for variants the return is an array of objects.

I use `dev-master` branch. Any ideas ?

**Comment by dpfaffenbauer** [comment]
Please don't create multiple issues for the same Problem!

**Comment by dpfaffenbauer** [comment]
related to #1026
