### ISSUE TITLE
Can't create a category, get an exception

### ISSUE THREAD

**Issue by turgic** [coreshop/CoreShop#1033]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
Hello guys, I tried to create a product category and I get an error, my code : 
```
$rootCategory = new CoreShopCategory();
$rootCategory->setName($config['categoryRoot']);
$rootCategory->setPublished(true);
$rootCategory->setKey($config['categoryRoot']);
$rootCategory->save();
```
The error is : 
```
ParentID and ID is identical, an element can't be the parent of itself.
```
Have you an idea ?

**Comment by dpfaffenbauer** [comment]
Please check how the Pimcore API works before you create issues here.
