### ISSUE TITLE
Adapt UI for Pimcore 6

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#1034]
| Q                | A
| ---------------- | -----
| Bug report?      |  no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

**Comment by aarongerig** [comment]
@dpfaffenbauer If you need special icons for that, let me know. ;)

**Comment by dpfaffenbauer** [comment]
@aarongerig no thanks, it's basically just css and making some icons white.
