### ISSUE TITLE
cleanup Front-End

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#104]
Do some cleanup and polish up the website-example views.

**DES Tasks, added at 29.06.2016:**
- [x] add new CoreShop logo
- [x] update CI colors
- [ ] add flat bootstrap (https://github.com/tui2tone/flat-admin-bootstrap-templates) 

**DEV Tasks, added at 29.06.2016:**
- [x] better form validation handling (add mandatory information in fieldcollections, so client and server validation can be served)
- [ ] one page checkout as additional example
- [ ] remove executive php lines from views as much as possible

**Comment by dpfaffenbauer** [comment]
see https://github.com/coreshop/website-example/commit/9dfa2b9531159a85a6fd15091938292c14a37ae7

**Comment by dpfaffenbauer** [comment]
Closed tue to inactivity
