### ISSUE TITLE
Transform cart item to oder item, save in wrong path

### ISSUE THREAD

**Issue by turgic** [coreshop/CoreShop#1044]
Hello guys, seems this is a coreshop bug. I trying to transform cart item to order item and create an order with those items but the items are saving in the root document of the project. My code is :
```
private function createOrder($cart, $cartItems)
{
        /** @var CoreShopOrder $order */
        $order = $this->orderFactory->createNew();
        $order->setPublished(true);
        $order->setOrderDate(Carbon::now());
        $order->setStore($this->shopperContext->getStore());
        $order->setCustomer($this->customer);
        $order->setBaseCurrency($cart->getStore()->getCurrency());
        $order->setCurrency($cart->getStore()->getCurrency());
        $order->setKey(uniqid());
        $order->setParent(Service::createFolderByPath($this->orderKey));
        foreach ($cartItems as $cartItem) {
            $this->cartItemToOrderItemTransformer->transform($order, $cartItem, $this->orderItemFactory->createNew());
        }
        $order->save();
        return $order;
}
```
The result is : 
![Screenshot from 2019-07-12 07-37-53](https://user-images.githubusercontent.com/6445778/61102841-46a8a900-a478-11e9-96c5-7d92e16581c1.png)

Have you an idea about that ? Thx in advance

**Comment by dpfaffenbauer** [comment]
That is not a CoreShop issues, and I already told you!

**Comment by turgic** [comment]
@dpfaffenbauer but the transformer that did that from CartItem to OrderItem is from coreshop

**Comment by dpfaffenbauer** [comment]
yes, but you have some custom code there that does something.

Try saving the order before running the CartItemTransformer, that could be the issue.
