### ISSUE TITLE
[Index] Bug in Iterator interpreter

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1046]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Following gets called in  the `getForm` method of the `iterator.js` file
```js
this.getStore().clearFilter();
```
There `getStore` method actually returns an object 
```js
getStore: function() {
        return {
            type: 'coreshop_index_interpreters'
        }
    },
```
So we get an error 
```console 
this.getStore(...).clearFilter is not a function
```

**Comment by dpfaffenbauer** [comment]
what version? 2.0 or 2.1?

**Comment by dpfaffenbauer** [comment]
nvm, figured it out
