### ISSUE TITLE
Open an order in admin

### ISSUE THREAD

**Issue by turgic** [coreshop/CoreShop#1049]
Hello, like we discussed on gitter @dpfaffenbauer , I discover an issue when try to open an order from admin. I get : 
```
    GET http://test.loc/admin/object/get?_dc=1563262507177&id=11124

    the message coreshop_carriers should be added as valid store
    btw when I try to open a order item works fine
```
Can you please fix that ? Thx in advance.

**Comment by dpfaffenbauer** [comment]
I can't reproduce it, it also works on demo2.coreshop.org which is the latest master....

Anything special you did? Have you tried opening the dev-tools, load Pimcore and see what errors appear?

**Comment by turgic** [comment]
Nothing special @dpfaffenbauer, I get on the firefox console only : `coreshop_carriers should be added as valid store` and the return : 
![Screenshot from 2019-07-16 15-07-14](https://user-images.githubusercontent.com/6445778/61293064-899db000-a7db-11e9-892a-12f52a6ee9c2.png)

**Comment by dpfaffenbauer** [comment]
that doesn't help me to find your problem.

can you check if this file gets loaded: `/bundles/coreshopshipping/pimcore/js/resource.js`

**Comment by turgic** [comment]
@dpfaffenbauer I check and seems this files is not loaded :(

**Comment by turgic** [comment]
I want to show you how I created the order : 
```
private function createOrder($cart, $cartItems, $supplierId)
    {
        $orderFolder = $this->objectService->createFolderByPath(sprintf('%s/%s', 'project', 'orders'));
        $tokenGenerator = new UniqueTokenGenerator();
        /** @var CoreShopOrder $order */
        $order = $this->orderFactory->createNew();
        $order->setPublished(true);
        $order->setOrderDate(Carbon::now());
        $order->setStore($this->shopperContext->getStore());
        $order->setCustomer($this->customer);
        $order->setBaseCurrency($cart->getStore()->getCurrency());
        $order->setCurrency($cart->getStore()->getCurrency());
        $order->setKey(uniqid());
        $order->setParent($orderFolder);
        $order->setSupplier([IaBtpProductSupplier::getById($supplierId)]);
        $order->setBusiness($cart->getBusiness());
        $order->setStatus(OrderStatus::WAITING);
        $order->setToken($tokenGenerator->generate(10));
        $order->setLocaleCode($this->shopperContext->getLocaleCode());
        $order->save();
        foreach ($cartItems as $cartItem) {
            $order->addItem($this->cartItemToOrderItemTransformer->transform($order, $cartItem, $this->orderItemFactory->createNew()));
        }
        $order->save();

        return $order;
    }
```
Maybe I'm missing some setters ?

**Comment by dpfaffenbauer** [comment]
that cannot be the problem, there must be something else off, but I have no idea what that might be

**Comment by turgic** [comment]
hmm, strange... @dpfaffenbauer no ideas for moment ? it's a point that block :(, I tried to identify the problem but whitout success

**Comment by dpfaffenbauer** [comment]
Sorry, but there is nothing I can do. the issue only appears on your installation. It works for my local setup and the demo as well as for other production setups.

**Comment by turgic** [comment]
@dpfaffenbauer is normal that I don't have the icon for coreshop in the left ? 
![Screenshot from 2019-07-18 16-11-30](https://user-images.githubusercontent.com/6445778/61460117-c6ea7500-a976-11e9-8e1d-f5a0906d07b0.png)
any ideas ?

**Comment by dpfaffenbauer** [comment]
no, it's not normal. As said, there is something off with your setup.

Check following:

 - Permissions? Maybe it cannot load files due to wrong permissions
 - Assets symlinked/hardcopies created? Run ```bin/console assets:install --symlink web```

**Comment by turgic** [comment]
@dpfaffenbauer thank you for the answer, I made : 
1. bin/console assets:install --symlink web ---> success
2. Permissions -->  chmod -R 777 web/ ----> succcess
What I'm missing with the install ?

**Comment by dpfaffenbauer** [comment]
you are installed and that should now be it for you to load the resources.

Sorry turgic, I can't help you with this, since we verified that the assets are not loaded, there is nothing wrong with CoreShop itself, it's something with your setup/configuration.

**Comment by turgic** [comment]
I understand but what wrong if I install step-by-step pimcore and coreshop, can be a problem with versions ? pimcore : 5.8.4 and coreshop : dev-master ? @dpfaffenbauer

**Comment by dpfaffenbauer** [comment]
I don't know, CoreShop dev-master works with Pimcore 5.8.4. Can you please try to find it out yourself, there is nothing I can do for you
