### ISSUE TITLE
Check installed template when updating coreshop

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#105]
when installing CoreShop, some snippets, documents and emails will be additionally installed.
- do we need to install snippets by default? (only necessary when using the website-example, so maybe move them to the website-example with an instruction for users how to install them) 
- when updating coreshop, the snippets and documents should not be installed again because maybe the user removed them on purpose.

**Comment by dpfaffenbauer** [comment]
- we could add a option at installation to disable document installation?
- do you have a idea to solve the problem and also provide a way that new (required) documents are installed?

**Comment by dpfaffenbauer** [comment]
Could now be done using the Demo Installer Plugin? What do you think?

**Comment by dpfaffenbauer** [comment]
Not necessary anymore for CoreShop 2
