### ISSUE TITLE
[Index] Saving index column configuration not working when choosing 'iterator' as Interpreter

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1063]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When choosing`iterator` as interpreter and trying to save, the button click performs no further noticeable action.

**Comment by dpfaffenbauer** [comment]
any error?

**Comment by davidhoeck** [comment]
@dpfaffenbauer nothing - no error or any other output in the console. the click on the button does basically nothing.
