### ISSUE TITLE
Admin menu on pimcore 6.0

### ISSUE THREAD

**Issue by tymon82** [coreshop/CoreShop#1064]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I've updated Pimcore to 6.0 and got console error in admin panel:

Loading failed for the <script> with source “https://shop.loc/admin/coreshop/coreshop.main/menu.js?_dc=1565171109”.
TypeError: "coreshop.menu is undefined"

Already clean cache (symfony & pimcore)

**Comment by dpfaffenbauer** [comment]
What Version of CoreShop do you use?

**Comment by tymon82** [comment]
2.1-dev

**Comment by dpfaffenbauer** [comment]
nginx webserver?

**Comment by tymon82** [comment]
Yes

**Comment by dpfaffenbauer** [comment]
https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html

Please check your configuration, there was a change in the docs couple of months ago.
