### ISSUE TITLE
[ProductQuantityPriceRules] Default unit definition should be optional

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1071]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Sometimes you don't want to have a unit definition connected to a product, therefore a user should be able to leave the field "default unit definition" empty.

**Comment by dpfaffenbauer** [comment]
why don't you want it?

**Comment by davidhoeck** [comment]
Because with for example digital products you don't need a default unit definition. Also for other products it does not always make sense. I think in general it is better to give the user the option, but not force him to have it.

**Comment by dpfaffenbauer** [comment]
@solverat your opinion?

**Comment by dpfaffenbauer** [comment]
IMO: A Product only needs a default unit definition when it has unit definitions, right?

**Comment by davidhoeck** [comment]
I don't think so - if you have multiple product types, why should every product type have a default unit definition if only one type requires it?

**Comment by dpfaffenbauer** [comment]
what do you mean by product type?

**Comment by davidhoeck** [comment]
Like if you have two DataObjects `DefaultProduct` and `DigitalProduct` and they both extend `BaseProduct` which extends the `CoreShop\Component\Core\Model\Product` but only the `DefaultProduct` requires the unit definitions and the `DigitalProducts` can use the unit definitions but they are optional.

**Comment by dpfaffenbauer** [comment]
Reason is:

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/units/builder.js#L88
https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/ProductBundle/Resources/public/pimcore/js/product/units/builder.js#L262

@solverat, if we just remove those two lines, we don't pre-select a unit anymore. WDYT?

**Comment by dpfaffenbauer** [comment]
ping @solverat

**Comment by solverat** [comment]
I'm not sure about that. Either you use units or you don't. You're able to use coreshop without any defined units but you cannot mix them. Using a default unit like `item` or `piece` would be true in any case, right? Even your digital product is an `item` somehow. It's quite difficult to train customers if there is no rule in general. If a customer don't need any units, you can skip this completely. If he does, he needs to define it like that - in any case. "Decisions before options" is the trigger here! 😄

**Comment by davidhoeck** [comment]
@solverat considered theoretically you are right, practically it is a different thing. I think I will close this for now, but I will keep it mind, if I have some better examples to explain it.
