### ISSUE TITLE
[OrderBundle] Improve or lower the amount of data loaded for the order detail view

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1080]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes

Currently there is a lot of data that is loaded but not really used in the view. This is because the `OrderController` uses a class called `DataLoader` that loads all the data of the objects - **recursively**.

**Comment by dpfaffenbauer** [comment]
Yes, the idea is to have all the data ready to access. So you don't have to extend it for most cases.

Whats you use case, do you have such a big object structure?

**Comment by davidhoeck** [comment]
@dpfaffenbauer closing this with the PRs made in the last days. 
#1129
