### ISSUE TITLE
QUESTION: Multi-Vendor Ticket Reservation System

### ISSUE THREAD

**Issue by spencerthayer** [coreshop/CoreShop#109]
I'm curious how possible would be to modify Coreshop into a mutl-vendor platform focused on ticket reservations.

Thanks! And sorry for using the issues system to reach out to you.

**Comment by dpfaffenbauer** [comment]
What do you actually mean by "Multi Vendor Ticket Reservation"?

Something like "buying tickets for events" where multiple vendors can have multiple themes with different (or same) tickets?

**Comment by spencerthayer** [comment]
Thanks for the quick response.

A multi vendor store that functions like an Etsy or AirBNB marketplace with separate seller product collections and separate seller information. This would allow us to then build on top of it ratings and commissions.

As far as the ticketing goes I mean to say that the vendors in the marketplace are not selling physical products but rather tickets to events and activities. So a booking system for tickets for specific dates in which the events are happening.

**Comment by dpfaffenbauer** [comment]
Got it. Yes, CoreShop is capable of doing it. You need to make some changes on the Product Class and some controllers. But: Yes, it's possible.

If you have some further questions, please contact me via skype or gitter.

Skype: dominik.pfaffenbauer
Gitter: dpfaffenbauer

**Comment by spencerthayer** [comment]
Awesome. Do you have a login to the backend of your demo? Thanks again!
