### ISSUE TITLE
Adding store via backend does not work

### ISSUE THREAD

**Issue by D37R4C7** [coreshop/CoreShop#1108]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

On adding a new store via backend I get following error:

**baseCountry: This value is not valid.**

Adding only works in database directly "coreshop_store", but then I can only choose Austria in my customer country drop down, although I changed the database entries in "coreshop_store_countries" accordingly.

**Comment by dpfaffenbauer** [comment]
version?

**Comment by D37R4C7** [comment]
Pimcore 6.2.0
CoreShop 4d0050c0fd02633acac1ef8c5ffd067a9dc594df

**Comment by dpfaffenbauer** [comment]
can you check if the country, which you want to use as base country, is actually enabled?

**Comment by D37R4C7** [comment]
It wasn't. Sorry I didn't see that I has to activate it somewhere else.
