### ISSUE TITLE
Statische Map Bilder im Adressfeld bei einer Bestellung 

### ISSUE THREAD

**Issue by nexus23** [coreshop/CoreShop#111]
Integration des Google API Keys oder Herausnahme von statischen Map Bildern
As of June 22, 2016 we are making the following changes to the Google Maps APIs Standard Plan

**Comment by solverat** [comment]
you need to add a browser api key in pimcore => settings => google api.

**Comment by dpfaffenbauer** [comment]
@solverat You are right, but CoreShop also needs to use the key ;)
