### ISSUE TITLE
CoreShop 2.1: Icon/CS-Menu missing in pimcore admin

### ISSUE THREAD

**Issue by macmastermike** [coreshop/CoreShop#1114]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

when i install coreshop 2.1 or upgrade from 2.0 the coreshop menu (icon) in the backend ...
chrome says those files are missing (404 not found):

/admin/coreshop/coreshop.main/menu.js
/bundles/coreshopproductquantitypricerules/pimcore/css/product-quanity-price-rules.css

i use debian/nginx for my installations.

**Comment by dpfaffenbauer** [comment]
check the pimcore docs for the nginx configuration. it changed and thats why you don't see any menu.

https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Nginx_Configuration.html

**Comment by justbane** [comment]
GAH! do you know which part changed that causes this? I have a fairly big sblock - any clue to what to look for would be great so I don't have to sped the next 3 hours poking at it.

**Comment by macmastermike** [comment]
i think it was the assets location block if i remember correctly....
just make a diff of new and current config - that helped me

**Comment by dpfaffenbauer** [comment]
https://github.com/pimcore/pimcore/commit/9bee593f2e06e5c1237efe2116ab4120d8fc1de4#diff-67e2e0293d6ae15b887642dc9a3d8d78
