### ISSUE TITLE
Bugs in migration scripts

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1115]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When updating coreshop, the following migrations are broken:
migrating 20190415095007

> Migration 20190415095007 failed during Execution. Error You have requested a non-existent service "coreshop.resource.installer.shared_translations".
> 15:56:03 ERROR [console] Error thrown while running command "pimcore:migrations:migrate -b CoreShopCoreBundle". Message: "You have requested a non-existent service "coreshop.resource.installer.shared_translations"." ["exception" => Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException^ { …},"command" => "pimcore:migrations:migrate -b CoreShopCoreBundle","message" => "You have requested a non-existent service "coreshop.resource.installer.shared_translations"."]
> 
> In Container.php line 277:
> 
> You have requested a non-existent service "coreshop.resource.installer.shared_translations".

migrating 20190528090625

 

> -> ALTER TABLE `coreshop_product_quantity_price_rule_range`
>                  CHANGE `range_from` `range_starting_from` int(11) NOT NULL AFTER `unit_definition`,
>                  DROP `range_to`;
> 
> Migration 20190528090625 failed during Execution. Error An exception occurred while executing 'ALTER TABLE coreshop_product_quantity_price_rule_range
> CHANGE range_from range_starting_from int(11) NOT NULL AFTER unit_definition,
> DROP range_to;':
> 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'unit_definition' in 'coreshop_product_quantity_price_rule_range'
> 16:18:44 ERROR [console] Error thrown while running command "pimcore:migrations:migrate -b CoreShopCoreBundle". Message: "An exception occurred while executing 'ALTER TABLE coreshop_product_quantity_price_rule_range\n CHANGE range_from range_starting_from int(11) NOT NULL AFTER unit_definition,\n DROP range_to;':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'unit_definition' in 'coreshop_product_quantity_price_rule_range'" ["exception" => Doctrine\DBAL\Exception\InvalidFieldNameException^ { …},"command" => "pimcore:migrations:migrate -b CoreShopCoreBundle","message" => """ An exception occurred while executing 'ALTER TABLE coreshop_product_quantity_price_rule_range\n CHANGE range_from range_starting_from int(11) NOT NULL AFTER unit_definition,\n DROP range_to;':\n \n SQLSTATE[42S22]: Column not found: 1054 Unknown column 'unit_definition' in 'coreshop_product_quantity_price_rule_range' """]
> 
> In AbstractMySQLDriver.php line 60:
> 
> An exception occurred while executing 'ALTER TABLE coreshop_product_quanti ty_price_rule_range
> CHANGE range_from range_starting_from int(11) NOT
> NULL AFTER unit_definition,
> DROP range_to;':
> 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'unit_definition' in
> 'coreshop_product_quantity_price_rule_range'
> 
> In PDOConnection.php line 90:
> 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'unit_definition' in
> 'coreshop_product_quantity_price_rule_range'
> 
> In PDOConnection.php line 88:
> 
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'unit_definition' in
> 'coreshop_product_quantity_price_rule_range'

**Comment by dpfaffenbauer** [comment]
1st issue is solvable, will provide a PR for it.

2nd one is more difficult, can you check if the migration `20190226122625` ran?

**Comment by Cruiser13** [comment]
Yes the migration ran at 2019-04-08 11:02:59 - I believe that was the date I installed coreshop on this instance.

**Comment by dpfaffenbauer** [comment]
can you reset the migration, update and try again?

**Comment by Cruiser13** [comment]
@dpfaffenbauer I did delete the migration in the database and patched the file installer.yml.
But it did not work, error message:

> Migration 20190415095007 failed during Execution. Error You have requested a non-existent service "coreshop.resource.installer.shared_translations".
11:08:41 ERROR     [console] Error thrown while running command "pimcore:migrations:migrate -b CoreShopCoreBundle". Message: "You have requested a non-existent service "coreshop.resource.installer.shared_translations"." ["exception" => Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException^ { …},"command" => "pimcore:migrations:migrate -b CoreShopCoreBundle","message" => "You have requested a non-existent service "coreshop.resource.installer.shared_translations"."]
> In Container.php line 277:
> You have requested a non-existent service "coreshop.resource.installer.shared_translations".

**Comment by dpfaffenbauer** [comment]
can you try changing the installer.yml for the one service to like:

```yml
    coreshop.resource.installer.shared_translations: 
        alias: 'CoreShop\Bundle\ResourceBundle\Installer\PimcoreSharedTranslationsInstaller'
        public: true
        
```

**Comment by Cruiser13** [comment]
This worked for me after cleaning the cache.

>   ++ migrating 20190415095007
> Migration 20190415095007 was executed but did not result in any SQL statements.

Thanks!

**Comment by Cruiser13** [comment]
@dpfaffenbauer is the failure of 20190528090625 also fixed?

**Comment by dpfaffenbauer** [comment]
right, missed that. will look at it later

**Comment by solverat** [comment]
20190528090625 needs to be removed.

**Comment by dpfaffenbauer** [comment]
Why should 20190528090625 be removed?

**Comment by albertmueller** [comment]
i had the same issue on dev-master, the column "unit_definition" was misssing

**Comment by dpfaffenbauer** [comment]
@Cruiser13 Has this migration been executed Version20190226122625?

**Comment by Cruiser13** [comment]
Yes, migrated at 2019-04-08 11:02:59

**Comment by dpfaffenbauer** [comment]
Odd, I am not sure what is going on here, but I moved the range_from migration to the migration where we also add sales-units, maybe that helps.

So, for everybody that has this problem, you have to manually resolve it by executing the SQL which renames the column

**Comment by janszky** [comment]
@dpfaffenbauer 
I am curious, is it possible to migrate for example between MySQL - MariaDB - PgSQL currently without the need to hack SQL queries manually?

**Comment by janszky** [comment]
@dpfaffenbauer I did not know PimCore does not support PgSQL. As of the other two, they are not fully compatible. https://mariadb.com/kb/en/compatibility-differences/
