### ISSUE TITLE
[ProductBundle] Saving product results in unique constraint error because of duplicate entry in  "coreshop_product_unit_definitions"

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1118]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Behaviour 
When saving an product with product unit definitions editable an `duplicate entry for <productId>` error occurs. Searched for the entry with the product ID in the DB, deleted them. After that the first save worked, on the second save the exact same error occurs again. 

## Expected Behaviour 
Just save the product without error. More technically: Don't try to `INSERT INTO coreshop_product_unit_definitions` but try some `UPDATE coreshop_product_unit_definitions WHERE...`

<img width="705" alt="Pimcore error dialog" src="https://user-images.githubusercontent.com/24294584/65977438-377f3900-e472-11e9-8d31-fe66d8e3d7b8.png">

**Comment by dpfaffenbauer** [comment]
Reproduced on the Demo as well?

**Comment by davidhoeck** [comment]
No - but we are facing this bug in four installation of four different clients. All of them on dev-master - so i don't think that this is a project specific bug. Tried do debug it further, but just got a exception and a stack trace with four entries. So for me it is not clear where the error occurs exactly.

**Comment by dpfaffenbauer** [comment]
fixed
