### ISSUE TITLE
[Index] Index tables generated with wrong collation

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1135]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Behaviour 
The index tables are created with the `utf8_unicode_ci` instead of the `utf8mb4_unicode_ci`.
<img width="1281" alt="coreshop_index_wrong_collation" src="https://user-images.githubusercontent.com/24294584/67074299-2419e080-f189-11e9-83d9-91700366baa6.png">

## Expected Behaviour 
Create it with the `utf8mb4_unicode_ci` collation

**Comment by dpfaffenbauer** [comment]
fixed
