### ISSUE TITLE
[Countries] Missing Translation on Installation

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1136]
| Q                | A
| ---------------- | -----
| Bug report?      | sort of
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Countries:
![image](https://user-images.githubusercontent.com/700119/67144095-5142bd80-f273-11e9-9f56-91aba6a0ac9a.png)

Stores:
![image](https://user-images.githubusercontent.com/700119/67144099-66b7e780-f273-11e9-8270-07595aea24dc.png)

**Comment by solverat** [comment]
Reason: All country labels are empty after a fresh installation.

**Comment by dpfaffenbauer** [comment]
What Language?

**Comment by solverat** [comment]
In my case german

**Comment by dpfaffenbauer** [comment]
de_DE
de_AT
de_CH

which german?

**Comment by solverat** [comment]
just "de"

**Comment by solverat** [comment]
I only had "de" enabled in my installation, maybe that's the issue here.

**Comment by albertmueller** [comment]
i just had a new installation with the pimcore languages "en" and "de", and it works in this case.

**Comment by dpfaffenbauer** [comment]
![Bildschirmfoto 2019-10-31 um 11 54 59](https://user-images.githubusercontent.com/5981845/67941125-483bdf80-fbd5-11e9-90e5-bbbf5b2d9fba.png)
![Bildschirmfoto 2019-10-31 um 11 55 01](https://user-images.githubusercontent.com/5981845/67941127-483bdf80-fbd5-11e9-926a-8806474f8501.png)


worked for me as well

**Comment by solverat** [comment]
because german AND english is installed (in my installation, only de was enabled)

**Comment by dpfaffenbauer** [comment]
ok, will try again then

**Comment by dpfaffenbauer** [comment]
![Uploading Bildschirmfoto 2019-10-31 um 12.06.31.png…]()

also works

**Comment by solverat** [comment]
I have no clue why this happened in my installation, never had that issue again.
