### ISSUE TITLE
SEO Extractor Improvements

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1148]
| Q                | A
| ---------------- | -----
| Bug report?      | sort of
| Feature request? | sort of
| BC Break report? | no
| RFC?             | no

- Add `priority` to extractor: Allow overruling existing extractors
- Already stored data: Skip data enrichment in title, description extractor

**Comment by dpfaffenbauer** [comment]
What do you mean with "Already stored data: Skip data enrichment in title, description extractor" exactly?

**Comment by solverat** [comment]
I think that's obsolete, if we can define priorities. Intentionally I was thinking about:

first `titleExtractor` => setData
second `titleExtractor` => setData 

=> second `titleExtractor` should not set any data, if first `titleExtractor` already has defined some values.

**Comment by dpfaffenbauer** [comment]
I think that is 1. solved with priority, and 2. a responsability for each extractor

**Comment by solverat** [comment]
Done.
