### ISSUE TITLE
[Rules] Allow TargetGroup as Rule Condition

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1162]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

It would be nice to determinate some price rules based on assigned target groups (Defined in "Personalization / Targeting")

**Comment by dpfaffenbauer** [comment]
Since Targeting is only frontend-wise available: we also have to store the target-group into the cart/order/quote in order to get it for rules...
