### ISSUE TITLE
Express-Checkout

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1166]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

![image](https://user-images.githubusercontent.com/700119/68371487-14196f00-013f-11ea-883b-900b513f4eb4.png)

## Motivation
Allow customer a very convenient and fast way to order their products. 

## Examples
**Example A**: Order products from social channels like Facebook or Instagram: A product can be ordered without going through a 5-step checkout. In fact, they don't even have to leave the platform context, and they also don't have to know anything about the website itself. Gateways like apple pay / pp express already storing address information which will transferred to the order object later on. 

**Example B**: Add fast checkout buttons on cart layer:  Instead of guiding a user trough a checkout, just allow them to instant buy from cart.

**Comment by dpfaffenbauer** [comment]
can be done with payment plugins. we did it with amazon pay

**Comment by sebastianSchmidt86** [comment]
@dpfaffenbauer May you share your amazon pay implementation (payum)?

**Comment by dpfaffenbauer** [comment]
@sebastianSchmidt86 sorry no, we did it for another company and we are not allowed to open source it
