### ISSUE TITLE
[CSRF] addCsrfTokenToUrl invalid in Pimcore 6.3

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1177]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Because of a nice BC break in pimcore 6.3 `addCsrfTokenToUrl` returns the umodified url. Use `pimcore.settings['csrfToken']` instead. We should send it via post instead of get.

https://github.com/pimcore/pimcore/commit/4c5d4f81c243dbfa5507d6b8f9a754d0e70fed66#diff-66d4022a84886b78ae96724d1ceffb71

**Comment by dpfaffenbauer** [comment]
actually, we use that only for get-requests anyway, and it should work for get without the token...
