### ISSUE TITLE
Message to customer cannot be sent when no thread is existing

### ISSUE THREAD

**Issue by danielklimsa** [coreshop/CoreShop#118]
A message to a customer cannot be sent when no message thread is existing (by using the message feature in the order overview).

You're receiving a PDO-Exception:
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'shopId' cannot be null`

Solution could be adding the following in the Admin/OrderController (SendMessageAction):
`$thread->setShopId(\CoreShop\Model\Shop::getShop()->getId());`

**Comment by dpfaffenbauer** [comment]
you right. But I think using the Orders ShopId is the better solution :)

**Comment by danielklimsa** [comment]
i was lazy – i've just copy/paste from the line above ,)
