### ISSUE TITLE
Setting the price of a child product resets the price of parent

### ISSUE THREAD

**Issue by symos** [coreshop/CoreShop#1180]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

We're having the problem mentioned in the title, also confirmed in the online demo installation.

Steps to reproduce:

- Enable "Allow inheritance" for the CoreShopProduct class
- In "Data Objects" -> "demo" -> "products-with-unit" choose a product and right click to add a child product (via "Add Object" -> "CoreShop" -> "Product")
- Give the product a title and save, then Save & Publish
- Now go into the child product, change its price and Save & Publish again
- Now go into the parent and refresh, you'll see the parent's price is now shown as zero (in reality I think that in the DB the price is completely lost)

**Comment by solverat** [comment]
done with #1181
