### ISSUE TITLE
demo is broken

### ISSUE THREAD

**Issue by nosovk** [coreshop/CoreShop#1195]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
 Feature request? | no
| BC Break report? | no
| RFC?             |  no

Curently demo admin panel provided in docs is broken
https://demo2.coreshop.org/admin (500 error)
it remains broken for a week now.

**Comment by dpfaffenbauer** [comment]
pimcores fault.... https://github.com/pimcore/skeleton/issues/15

Using another skeleton version now, demo is up and running again
