### ISSUE TITLE
How do I fully uninstall coreshop

### ISSUE THREAD

**Issue by adriangordon1231** [coreshop/CoreShop#1197]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I no longer need to use coreshop for a project I am working on, however after disabling the "CoreShop - core" bundle I am not seeing an option to actually uninstall it. How do I go about doing so?

**Comment by dpfaffenbauer** [comment]
Remove the bundles, the classes and delete the tables...
