### ISSUE TITLE
ItemPriceGross and ItemPriceNet empty if no tax rule is present

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1198]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When using variants and putting a variant to cart getItemPrice (and resulting the price in the cart) will be 0 (or empty). The cart object does not have values set for ItemPriceGross and ItemPriceNet, so this will return 0:
https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Component/Order/Model/CartItem.php#L60

What's interesting about this is that item.getTotal is working fine. So if I place two pieces of some item (with a price of 99,00 €) in the cart, the following data is visible in the backend:
![coreshop-pricevariant](https://user-images.githubusercontent.com/2771909/70806241-22e8e680-1dbb-11ea-94f1-001475445f21.png)

**Comment by dpfaffenbauer** [comment]
not reproducable, either locally nor on the demo. maybe related to https://github.com/coreshop/CoreShop/issues/1180

**Comment by Cruiser13** [comment]
You are right @dpfaffenbauer it's not the variant. The above behaviour is created if the tax rule is empty at the product. Reproducable at the demo by removing the AT tax rule from a product (set empty).

**Comment by dpfaffenbauer** [comment]
see #1200

**Comment by Cruiser13** [comment]
This does fix my issue, thanks @dpfaffenbauer
