### ISSUE TITLE
[Bug] Cannot install on Pimcore demo.

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#1206]
Hello,

Trying to install on the pimcore demo package (https://github.com/pimcore/demo) freshly installed (default composer.json of the demo), the following error is returned by composer:

```
Using version ^2.1 for coreshop/core-shop
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for coreshop/core-shop ^2.1 -> satisfiable by coreshop/core-shop[2.1.0].
    - coreshop/core-shop 2.1.0 requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[2.x-dev, v2.0.0, v2.0.1] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

I think it come from here: https://github.com/pimcore/demo/blob/master/composer.json#L14

So CoreShop cannot be installed on the demo, but only skeleton ? Maybe it should be added in the coreshop doc/readme.md that only skeleton is supported ?

Thanks!

**Comment by dpfaffenbauer** [comment]
That is a version conflict and has nothing todo with the demo itself.... anyway, there is no point installing it on the demo anyway

**Comment by Yivan** [comment]
Thanks @dpfaffenbauer for your answer. Yes I know this is a dependency problem, but I was thinking maybe this dependency (guzzle6-adapter) could be downgraded to v1. But it is better the pimcore demo upgrade it to v2 i think.
I opened an issue for this: https://github.com/pimcore/demo/issues/166

To answer to the purpose, as I state it in this Pimcore issue 166:

> We are trying to put a global demo of Pimcore (aka this demo repository) with some main/famous extensions. We manage to add formbuilder, but there is an incompatibility with coreshop because of dependencies.

> Purpose is to be able to show the power of Pimcore along an unique Pimcore instance for showcases (and showing that native ecommerce can work alongside coreshop and vice-versa).

**Comment by dpfaffenbauer** [comment]
They should update it to v2...
