### ISSUE TITLE
Random bug on insert into db tables - gedmo datetime fields always null

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#1207]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I had a strange random bug in useage of gedmo/doctrine-extensions, all gedmo date fields was null.
Im not sure, from which repo the issue comes, but after a update it works again.
Here the complete composer update list:
Loading composer repositories with package information
Installing dependencies from lock file:
  - Removing endroid/installer (1.1.5)
> Pimcore\Composer::prePackageUpdate
  - Removing ocramius/package-versions (1.4.0)
  - Installing ocramius/package-versions (1.4.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing colinmollenhour/credis (1.10.1)
  - Installing colinmollenhour/credis (1.11.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/lexer (1.1.0)
  - Installing doctrine/lexer (1.2.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/annotations (v1.7.0)
  - Installing doctrine/annotations (v1.8.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/event-manager (v1.0.0)
  - Installing doctrine/event-manager (1.1.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/collections (v1.6.2)
  - Installing doctrine/collections (1.6.4)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/cache (v1.8.0)
  - Installing doctrine/cache (1.10.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/persistence (1.1.1)
  - Installing doctrine/persistence (1.3.3)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/inflector (v1.3.0)
  - Installing doctrine/inflector (1.3.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/data-fixtures (v1.3.2)
  - Installing doctrine/data-fixtures (1.4.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/service-contracts (v1.1.6)
  - Installing symfony/service-contracts (v2.0.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-mbstring (v1.12.0)
  - Installing symfony/polyfill-mbstring (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-ctype (v1.12.0)
  - Installing symfony/polyfill-ctype (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing twig/twig (v2.11.3)
  - Installing twig/twig (v2.12.3)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-php70 (v1.12.0)
  - Installing symfony/polyfill-php70 (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-util (v1.12.0)
  - Installing symfony/polyfill-util (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-php56 (v1.12.0)
  - Installing symfony/polyfill-php56 (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/symfony (v3.4.35)
  - Installing symfony/symfony (v3.4.36)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-intl-icu (v1.12.0)
  - Installing symfony/polyfill-intl-icu (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-apcu (v1.12.0)
  - Installing symfony/polyfill-apcu (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing psr/log (1.1.0)
  - Installing psr/log (1.1.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing fig/link-util (1.0.0)
  - Installing fig/link-util (1.1.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/doctrine-cache-bundle (1.3.5)
  - Installing doctrine/doctrine-cache-bundle (1.4.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/dbal (v2.9.2)
  - Installing doctrine/dbal (v2.10.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/doctrine-bundle (1.11.2)
  - Installing doctrine/doctrine-bundle (1.12.6)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/instantiator (1.2.0)
  - Installing doctrine/instantiator (1.3.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing doctrine/orm (v2.6.4)
  - Installing doctrine/orm (v2.7.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing egulias/email-validator (2.1.11)
  - Installing egulias/email-validator (2.1.13)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing endroid/qr-code (3.6.1)
  - Installing endroid/qr-code (3.7.5)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing fzaninotto/faker (v1.8.0)
  - Installing fzaninotto/faker (v1.9.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing gedmo/doctrine-extensions (v2.4.37)
  - Installing gedmo/doctrine-extensions (v2.4.38)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing composer/ca-bundle (1.2.4)
  - Installing composer/ca-bundle (1.2.5)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing maxmind/web-service-common (v0.5.0)
  - Installing maxmind/web-service-common (v0.6.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing maxmind-db/reader (v1.4.1)
  - Installing maxmind-db/reader (v1.6.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing geoip2/geoip2 (v2.9.0)
  - Installing geoip2/geoip2 (v2.10.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing google/apiclient-services (v0.115)
  - Installing google/apiclient-services (v0.121)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing guzzlehttp/guzzle (6.3.3)
  - Installing guzzlehttp/guzzle (6.5.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing google/auth (v1.5.2)
  - Installing google/auth (v1.6.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing hybridauth/hybridauth (v2.16.0)
  - Installing hybridauth/hybridauth (v2.17.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing league/csv (9.3.0)
  - Installing league/csv (9.5.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing linfo/linfo (v4.0.1)
  - Installing linfo/linfo (v4.0.4)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing mjaschen/phpgeo (2.1.0)
  - Installing mjaschen/phpgeo (2.3.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing mpratt/embera (1.9.3)
  - Installing mpratt/embera (1.9.6)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing myclabs/deep-copy (1.9.3)
  - Installing myclabs/deep-copy (1.9.4)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing neitanod/forceutf8 (v2.0.2)
  - Installing neitanod/forceutf8 (v2.0.4)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing nesbot/carbon (2.24.0)
  - Installing nesbot/carbon (2.28.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-php73 (v1.12.0)
  - Installing symfony/polyfill-php73 (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/http-client-contracts (v1.1.6)
  - Installing symfony/http-client-contracts (v2.0.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/http-client (v4.3.4)
  - Installing symfony/http-client (v5.0.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing payum/payum-bundle (2.3.3)
  - Installing payum/payum-bundle (2.3.4)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing phpoption/phpoption (1.5.0)
  - Installing phpoption/phpoption (1.7.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing mustangostang/spyc (0.6.2)
  - Installing mustangostang/spyc (0.6.3)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing piwik/device-detector (3.12.0)
  - Installing piwik/device-detector (3.12.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing presta/sitemap-bundle (v1.7.0)
  - Installing presta/sitemap-bundle (v1.7.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing ramsey/uuid (3.8.0)
  - Installing ramsey/uuid (3.9.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing sabre/vobject (4.2.0)
  - Installing sabre/vobject (4.2.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing scheb/two-factor-bundle (v3.23.0)
  - Installing scheb/two-factor-bundle (v3.26.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-php72 (v1.12.0)
  - Installing symfony/polyfill-php72 (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-intl-idn (v1.12.0)
  - Installing symfony/polyfill-intl-idn (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/mime (v4.3.4)
  - Installing symfony/mime (v5.0.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing sensiolabs/security-checker (v6.0.2)
  - Installing sensiolabs/security-checker (v6.0.3)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony-cmf/routing (2.1.0)
  - Installing symfony-cmf/routing (2.1.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony-cmf/routing-bundle (2.1.1)
  - Installing symfony-cmf/routing-bundle (2.2.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing monolog/monolog (1.25.1)
  - Installing monolog/monolog (1.25.3)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/monolog-bundle (v3.4.0)
  - Installing symfony/monolog-bundle (v3.5.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/polyfill-iconv (v1.12.0)
  - Installing symfony/polyfill-iconv (v1.13.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing swiftmailer/swiftmailer (v6.2.1)
  - Installing swiftmailer/swiftmailer (v6.2.3)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/swiftmailer-bundle (v3.2.8)
  - Installing symfony/swiftmailer-bundle (v3.3.1)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing symfony/webpack-encore-bundle (v1.6.2)
  - Installing symfony/webpack-encore-bundle (v1.7.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing tijsverkoyen/css-to-inline-styles (2.2.1)
  - Installing tijsverkoyen/css-to-inline-styles (2.2.2)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing vrana/adminer (v4.7.3)
  - Installing vrana/adminer (v4.7.5)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing webmozart/assert (1.5.0)
  - Installing webmozart/assert (1.6.0)
    Loading from cache

> Pimcore\Composer::prePackageUpdate
  - Removing zendframework/zend-code (3.3.2)
  - Installing zendframework/zend-code (3.4.1)
    Loading from cache

**Comment by dpfaffenbauer** [comment]
I checked the history of the gemdo extension repo, but couldn't found anything related to it, maybe it was a symfony bug that was fixed with the update...
