### ISSUE TITLE
[FR] Maximum Quantity to Order

### ISSUE THREAD

**Issue by HuppertzL** [coreshop/CoreShop#1209]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I'm currently working on a Shop which is also selling Tickets for a Venue.
Currently Stockkeeping of a Product is able to handle a "Minimum Quantity To Order".
But for cases like Tickets it would also be good to have a "Maximum Quantity To Order" to be able to set a maximum Limit to avoid bulk purchases of some black market dealers.

**Comment by dpfaffenbauer** [comment]
Good idea, would you be able to provide a PR with it?

**Comment by HuppertzL** [comment]
I'll try, but i'm not familiar with the Behat thingy.
So if it's okay, i'd just focus on the business logic itself.
