### ISSUE TITLE
Quote is missing paymentProvider and states

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1211]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If a quote is created (using the usual purchase process in the frontend) the paymentProvider is not saved although selected during the purchase process. The fields paymentProvider and paymentSettings do not even exist for quote class in the initial coreshop setup.

Since payment type can be selected during the purchase we should also save the paymentProvider selected as it could be important (for example if somebody would like to pay by invoice or pay upfront via bankwire).

Quotes should also have states (so we can use notification rules for example). At least one default Field quoteState (similar to orderState) should be given.

**Comment by dpfaffenbauer** [comment]
true, but they are not ready and not actively used. They lack a lot of abilities and they will come.

**Comment by Cruiser13** [comment]
Why are they not ready to use? I did not see any notice that they are not in a stable stage.
Are PRs expected to be merged if these missing fields are added?

**Comment by dpfaffenbauer** [comment]
Quotes are in practice not usable as they are, there are plans to improve that though. Ever had a quoting system where quotes are not amendable?

But yes, PRs get merged.
