### ISSUE TITLE
[FR] Allow comments on quotes

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1212]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Quotes usually have even more discussion need then orders do. The comment feature (found at order detail in the administration area) of the orders should be available for the quotes too.

**Comment by dpfaffenbauer** [comment]
Since quotes are currently not really actively used and they lack the ability to be changed, I currently don't see the need to add something like this until quotes really work the way they should.
