### ISSUE TITLE
Undefined index: default_resolvers

### ISSUE THREAD

**Issue by D37R4C7** [coreshop/CoreShop#1234]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

CoreShop Master
Pimcore 6.3.6
PHP Version 7.3.13
Symfony 4.4.2

```
Undefined index: default_resolvers
 /opt/project/vendor/coreshop/core-shop/src/CoreShop/Bundle/ThemeBundle/DependencyInjection/CoreShopThemeExtension.php:36
 /opt/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php:76
 /opt/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
 /opt/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:94
 /opt/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:762
 /opt/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:626
 /opt/project/vendor/pimcore/pimcore/lib/Kernel.php:183
 /opt/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:136
 /opt/project/vendor/pimcore/pimcore/lib/Kernel.php:162
 /opt/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php:79
```

**Comment by solverat** [comment]
@D37R4C7 see https://github.com/pimcore/pimcore/pull/5590. 

But yea, coreshop should also resolve all notice errors.

**Comment by solverat** [comment]
Until then: you should keep the `error_reporting` with `E_ALL & ~E_NOTICE & ~E_STRICT`.

**Comment by D37R4C7** [comment]
@solverat Thank you.

@dpfaffenbauer told me to open a new issue.

Your error_reporting trick did not solved my problem. Set it via php.ini as well as 

`ini_set('error_reporting', E_ALL & ~E_NOTICE & ~E_STRICT);`

in my phpunit `bootstrap.php`

**Comment by solverat** [comment]
try it with the env variable: `PIMCORE_PHP_ERROR_REPORTING="E_ALL & ~E_NOTICE & ~E_STRICT"`

**Comment by D37R4C7** [comment]
Doesn't work either...

![2020-01-15 13_39_17-VirtualBoxVM](https://user-images.githubusercontent.com/4516197/72434731-aa4fbe00-379c-11ea-8449-ac03faf1ff92.jpg)

**Comment by dpfaffenbauer** [comment]
@D37R4C7 can you try if PR #1235 fixes it for you?

**Comment by D37R4C7** [comment]
@dpfaffenbauer yes it does

**Comment by D37R4C7** [comment]
When will it be merged?

**Comment by dpfaffenbauer** [comment]
just did.
