### ISSUE TITLE
Cart discount is not considered in tax calculation

### ISSUE THREAD

**Issue by danielklimsa** [coreshop/CoreShop#124]
Tax calculation is not correct, when having activated a cart discount (see screenie). The calculated tax is based on the net prices without the discount.

The challenge will be the calculation of tax when having more tax rates (e.g. Germanys 7% and 19%): Then the calculated discount (in percent) has to be adapted on all tax rates.

If you made this, your shop is better than e.g. Shopware – this shop has the same problem. ,)

![screen shot 2016-11-03 at 16 10 39](https://cloud.githubusercontent.com/assets/20857191/19971902/bda5af5a-a1e0-11e6-9d1e-671257d46862.png)

**Comment by dpfaffenbauer** [comment]
well, discounts are applied post-taxation. I don't really see a problem?

(item1+item2+shipping)-discount = total
(99,98+0,18+5,90)-10,02

**Comment by danielklimsa** [comment]
the total calculation is correct, but not the total tax. when you have a discount, also the total tax must be less.

**Comment by dpfaffenbauer** [comment]
You are right. Can you take a look at the fix?

**Comment by danielklimsa** [comment]
perfect! :) i've made some tests and the total tax was always totally correct.

but i'am having an issue with orders having items with e. g. two taxes. have a look at this cart calculation:

4x 49,99 (19%) = 199,97
(note: here we have another problem due to not rounded product prices, normally should be 199,96)
1x 8,98 (7%) = 8,98

tax is then calculated as follows with 10% discount:
19% = 28,83 (should be 28,73: 199,97*0,9/1,19-(199,97*0,9) )
7% = 0,43 (should be 0,53: 8,98*0,9/1,07-(8,98*0,9) )

in total the tax is absolutely correct, but not splitted on tax rates. and you know what tax accountants are thinking about this. ,)

**Comment by dpfaffenbauer** [comment]
you right again, I think I over-complicated the discounted tax-amount calculation.

Please try the new fix

**Comment by danielklimsa** [comment]
man, you're fast...

now i get this (same cart):
19% = 28,83 (nothing changed)
7% = 0,53 (correct – perfect!)

so we have 0,10 more tax than before...

**Comment by dpfaffenbauer** [comment]
strange... I added 4x49,99 (19%) and 1x8,98 (7%) and get the right taxes:

TAX (7DE):	€ 0,53
TAX (19DE):	€ 28,73
TOTAL TAX:	€ 29,26

**Comment by danielklimsa** [comment]
my apologies – the fault was on my side. everything is fine – thx a lot for your quick fix!

(i must have changed a line of code somewhere and forgot to redo it – after recopying the latest coreshop files it works. sorry for this.)
