### ISSUE TITLE
[Core] ProductsConditionChecker not working with multiple Product Models 

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1240]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

## Description
Currently the service `coreshop.repository.product` gets injected into the `ProductsConditionChecker` and therefore also used by the `ProductVariantsCheckerTrait`. When using multiple product models that condition is only working for the default CoreShop products. 

## Suggestion
I would inject the `coreshop.repository.stack.product` and move the process of finding the variant ids recursively into the `ProductVariantsCheckerTrait`. As a result the condition could be also used with multiple product models. If you @dpfaffenbauer are happy with that solution I would provide a proper PR.

**Comment by dpfaffenbauer** [comment]
That is fine. Go for it. Please create it for the 2.1 branch

**Comment by dpfaffenbauer** [comment]
done
