### ISSUE TITLE
Inherited Store Values cannot be reset

### ISSUE THREAD

**Issue by saturion** [coreshop/CoreShop#1243]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Coreshop version dev-master (7b22f55c)
Pimcore version 6.4.0 (ede8ed7e)

**Observed Behavior**
Variant products can inherit the store value from their parents. You can also override the parent's store value for different variants (e.g. phone with 64GB is 100€ cheaper than 128GB, etc.) by providing a different value. The variant's store value replaces the inherited amount from the parent.
In case you want to switch back to the inherited value, you'd expect this to work as with other Pimcore Fields (i.e. set value to NULL). 
However, there is no way of doing this right now in the UI. Validation errors occur when providing NULL as a value to the store value.

**How to recreate**
- Enable Pimcore inheritance
- Create a product with some variants
- Set the product's store value (e.g. 100€)
- Set the variant's store value to a different amount (e.g. 150€)
- Try to unset the variant's store value and publish

**Expected Behavior**
When deleting the store value AND there is a parent object to inherit from, take over the parent's value (i.e. enable inheritance again).

**Stack Trace & Error Message:**

`
Timestamp: Tue Jan 21 2020 15:41:20 GMT+0100 (Mitteleuropäische Normalzeit)
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: Expected argument of type "int", "null" given at property path "price".
Trace: 
in /mnt/c/dev/rics/data/www/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:198
#0 /mnt/c/dev/rics/data/www/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php(118): Symfony\Component\PropertyAccess\PropertyAccessor::throwInvalidArgumentException('int', Array, 0, 'price')
#1 /mnt/c/dev/rics/data/www/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php(86): Symfony\Component\PropertyAccess\PropertyAccessor->setValue(Object(CoreShop\Component\Core\Model\ProductStoreValues), Object(Symfony\Component\PropertyAccess\PropertyPath), NULL)
#2 /mnt/c/dev/rics/data/www/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(632): Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapFormsToData(Object(RecursiveIteratorIterator), Object(CoreShop\Component\Core\Model\ProductStoreValues))
#3 /mnt/c/dev/rics/data/www/vendor/coreshop/core-shop/src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php(563): Symfony\Component\Form\Form->submit(Array)
#4 /mnt/c/dev/rics/data/www/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1258): CoreShop\Bundle\CoreBundle\CoreExtension\StoreValues->getDataFromEditmode(Array, Object(Pimcore\Model\DataObject\CoreShopProduct))
#5 /mnt/c/dev/rics/data/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(146): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#6 /mnt/c/dev/rics/data/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#7 /mnt/c/dev/rics/data/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#8 /mnt/c/dev/rics/data/www/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#9 {main}
`

**Comment by dpfaffenbauer** [comment]
That is not as easy as you might think. What I tried so far:
 - If price is null (eg empty), remove it. But that is not possible, since we use Symfony Form to resolve editmode data, and the model behind it needs a price. Which is valid. Also, just removing the price is not actually valid for inheritance restoral, since there might be other values like Unit Prices or even custom extensions....
 - Add a "restore" inheritance Button to the form field, but, I don't know in JS or PHP if the object itself has a valid parent thus I cannot display a button.

I would suggest just add a generic button to restore all store values to the CoreShop Product Menu:

WDYT?

![Bildschirmfoto 2020-02-10 um 13 02 11](https://user-images.githubusercontent.com/5981845/74148365-91082900-4c05-11ea-9d1c-60bffbee205d.png)

**Comment by saturion** [comment]
I totally agree, we were discussing this internally as well and did not come up with a quick way of fixing this.

**@Restore button:** wouldn't a check like this be sufficient?
`if (object->getParent() && object->getParent() instanceof CoreShopProduct) `

Aside from that I agree that a manual option would be best for the user (either button works). It's better than having some magic work in the background.

**Comment by dpfaffenbauer** [comment]
Yes, but I cannot get that from where the data is loaded from Pimcore. It actually calls the same load function with the parent object and not giving me any information about the context it is calling it from.

So, we'll stick to a menu button then?

**Comment by saturion** [comment]
Yep general menu button sounds good

**Comment by dpfaffenbauer** [comment]
@saturion I found a way:

![](http://g.recordit.co/Vcmt86YIkb.gif)

**Comment by saturion** [comment]
awesome! thank you!
