### ISSUE TITLE
"Invoice Address is Shipping Address" checkbox results in form error

### ISSUE THREAD

**Issue by GALCF** [coreshop/CoreShop#1257]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Coreshop version 2.2.0 (current demo)
Pimcore version 6.4.2

While ordering with an invoice address that is not a shipping address, checking "Invoice Address is Shipping Address" and submitting the form results in a form error that is not shown because the checkbox hides the error with the shipping address input.

**Expanded View (error not visible while checked):**

![image](https://user-images.githubusercontent.com/14803394/73734031-48e89280-473d-11ea-8f4c-e1405b4f926f.png)

**Comment by dpfaffenbauer** [comment]
ok, so that is only a UI problem right?

**Comment by GALCF** [comment]
Yes, UI as in the error cannot be seen, or maybe a "workflow" problem, that some invoice addresses may not be a shipping address too (if the checkbox is present, which is also UI-only?)

**Comment by dpfaffenbauer** [comment]
Yes. I'd say thats just how you display things. Since the introduction of address-identifiers that problem can happen. Not sure how to solve properly.... Guess we should have a different select for addresses allowed for shipping as well and swap these two based on the checkbox.

**Comment by solverat** [comment]
@GALCF could you please check the user: just open the cart customer, then open the address object from "default address". Is there a defined "address identifier"?
 
![image](https://user-images.githubusercontent.com/700119/86234251-ecc45600-bb96-11ea-8665-80544e6a9900.png)

**Comment by solverat** [comment]
@GALCF btw, we're using this in frontend: 

```twig
{% set hide_shipment_selector = hasShippableItems == false or (form.useInvoiceAsShipping is defined and form.useInvoiceAsShipping.vars.data and form.shippingAddress.vars.valid != false) %}
```
 instead of

```twig 
{% if hasShippableItems == true and form.useInvoiceAsShipping.vars.data %}
```

which should be the default i think.

**Comment by solverat** [comment]
I'll fix this in my latest PR (https://github.com/coreshop/CoreShop/pull/1440).

**Comment by dpfaffenbauer** [comment]
fixed
