### ISSUE TITLE
Remove id numbers from URLs

### ISSUE THREAD

**Issue by Zyles** [coreshop/CoreShop#1262]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | no

Can you remove the ID numbers from URLs for products and categories? I don't understand why they are necessary and in 2020, you shouldn't need them.

The current structure allows for a negative SEO attack generating duplicate content:

https://demo2.coreshop.org/en/shop/asdsadaasdasdasdasdsdasd~p61

A proper URL structure could be:
```
example.com/category/
example.com/category/subcategory/

example.com/product.html
```

Product urls will be unique and persistent. No category names in them as they could exist in multiple categories or moved between categories.

Category urls are hierarchical like a directory on an operating system.

**Comment by solverat** [comment]
Available after this PR has been releases: 
https://github.com/pimcore/pimcore/issues/5575

BTW: there is no real proof of negative seo impact but A LOT of blog entries and opinions of so called „seo experts“. But yea, i also think it‘s time for some nice slugs! 👍

**Comment by dpfaffenbauer** [comment]
@Zyles  Welcome to 2020 as well, feel free to create a PR request for that feature if it annoys you that much. It just wasn't generically possible in Pimcore before pimcore/pimcore#5575 so just give it time.
