### ISSUE TITLE
Company Workflow

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1266]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Definition
- It should be possible to assign customers to a company object
- There should be no BC break and also no change in the current workflow but should allow us to decide which workflow we want to use

## Company Object
- Introduce new object `company`
- Fields: `name`

## Customer Object
- Add optional `1-to-1 relation` field for `company`

## Addresses
Address assignment: By default, every address object gets assigned to a customer object. This is standard by now and should stay that way **except** if a customer is bounded to company: There should be a configuration event for that: 
- User can choose addresses from company
- User can/cannot add new addresses to himself or to company

## Registration
**Guest Registration**: Same as now. New customer object with `isGuest` flag
**Default Registration**: Same as now. New customer object with given data. **But**: there should be a possibility to hook into this process: If a user needs to set a company name, I may want to create a company object and append the user to it by automatization.

## Cart
After a user has been logged in, we're able to detect a company by `hasCompanyRelation()`. By default, this should be enough.

## Checkout
Addresses: See `Address` section. Which address should be shown? Make it configurable:
- Addresses from company
- Addresses from customer
- Addresses from company and customer

## Backend
- Add new configuration panel `customer`
- Add new sub configuration `Customer to New Company`
  - Create `company`object by adding a name (check for duplicates) 
  - Move `customer` as child object to new `company`
  - Allow choosing between `keep addresses to customer` or `move addresses to company`
  - Fire Event to allow projects to do some more data assignment
- Add new sub configuration `Customer to Existing Company`
  - Choose customer and company
  - Move `customer` as child object to new `company`
  - Allow choosing between `keep addresses to customer` or `move addresses to company`
  - Fire Event to allow projects to do some more data assignment
- Show Company field in Order Overview if available

## Migration
- Create new `company` object

**Comment by albertmueller** [comment]
great idea, already had two use cases especially when you have to connect SAP via API etc.
would still recommend to add a VAT number field in the register process, with a already exist validation.
nice to have: special rules, condition based on company for custom prices, shipping and payment

**Comment by solverat** [comment]
![image](https://user-images.githubusercontent.com/700119/74536558-9e405300-4f38-11ea-926f-4a234411c98d.png)

![image](https://user-images.githubusercontent.com/700119/74536772-0727cb00-4f39-11ea-8895-2b804911ff54.png)

![image](https://user-images.githubusercontent.com/700119/74536662-ce87f180-4f38-11ea-8962-813ec9e946d0.png)

![image](https://user-images.githubusercontent.com/700119/74536641-c6c84d00-4f38-11ea-8125-9474bf2a98bd.png)

![image](https://user-images.githubusercontent.com/700119/74536721-ee1f1a00-4f38-11ea-8888-2f6fd9ab0dbf.png)

**Comment by solverat** [comment]
## Frontend

![image](https://user-images.githubusercontent.com/700119/74536844-2de60180-4f39-11ea-86bf-022d2c0a70bb.png)

If user has access type `own & company`, he's able to switch address affiliation.
