### ISSUE TITLE
error "Only variables should be passed by reference"

### ISSUE THREAD

**Issue by breed-id** [coreshop/CoreShop#128]
error "Only variables should be passed by reference" in \website\views\scripts\coreshop\template\default\scripts\coreshop\checkout\address.php line 66 and line 79
please change reset(\CoreShop::getTools()->getUser()->getAddresses())) to reset($addresses)

**Comment by dpfaffenbauer** [comment]
thank you

**Comment by dpfaffenbauer** [comment]
PS: Pull Requests are always welcome :)
