### ISSUE TITLE
[Dynamic Dropdowns] Values don't get saved

### ISSUE THREAD

**Issue by aarongerig** [coreshop/CoreShop#1297]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When adding any of the dynamic dropdown data types to an object, the values don't get saved (see attached video).

[dynamic_dropdown_bug.mov.zip](https://github.com/coreshop/CoreShop/files/4230853/dynamic_dropdown_bug.mov.zip)

**Comment by kubaplas** [comment]
If you take a look into versions tab, you'll see that values are saved, but are not displayed in edit mode.

**Comment by piotrecky** [comment]
In line vendor/coreshop/pimcore-bundle/Resources/public/pimcore/js/coreExtension/tags/coreShopDynamicDropdown.js:134 is: value: this.data but should be value: this.data.id

**Comment by dpfaffenbauer** [comment]
Issue is caused by Pimcore... Since CoreShop 2.2 will only be released for Pimcore > 6.6, it is fixed for that without a BC fix
