### ISSUE TITLE
Cannot create store

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#1298]
Hello !

On the online demo, creating a new store, completion for base country don't work and when filling it and saving the object an error message is sent: `
baseCountry: This value is not valid.`

![image](https://user-images.githubusercontent.com/9025839/74976206-9b59cc80-5428-11ea-8188-4d47154ad541.png)

The bug is reproductible on a standalone install too.

Thanks

**Comment by solverat** [comment]
You need to enable the selected country first in localization => countries.

@dpfaffenbauer i think we should restrict the country store to active countries only to prevent such issues

**Comment by Yivan** [comment]
Thanks for your answer. Sorry i didn't know I need to activate the country before.
Tested and works now.

Yes it would be better it list only activated country and having an helper message to explain only activated countries are listed (because end user can be blocked if list is empty and think something get wrong).

By the way, the filter don't work, when we type it does not filter but I think this is linked to the related issue maybe ; )

![image](https://user-images.githubusercontent.com/9025839/75059575-8d19b800-54dd-11ea-98c1-0519fe4ccedc.png)

On the same subject, just to give my experience, i created a customer, but didn't create adresses for it, and when creating an order for him, the adresses selector were empty and i get some times to get it, my fault, but an helper message saying "an adress must be created" could help. I think some sort of small things could make the BO more user friendly than he is alreay (i like it very much!!).

Best regards.

**Comment by Yivan** [comment]
Just tested it, I confirm works fine now. Thanks a lot for this speedy fix!
