### ISSUE TITLE
error invalid key for object with id [ 0 ] key is: [1]

### ISSUE THREAD

**Issue by breed-id** [coreshop/CoreShop#130]
when process checkout ex: http://rnddevelopmentecomm-coreshop.localhost/en/shop/payment/payment/Bankwire
I found error invalid key for object with id [ 0 ] key is: [1] 
in \plugins\CoreShop\lib\CoreShop\Model\Order.php line 222

**Comment by breed-id** [comment]
But success when i changed code setkey to $item->setKey(uniqid()); in line 185

**Comment by dpfaffenbauer** [comment]
Thats really strange, it should use the $i for the Key. Can you give me some more information on your setup? PHP-Version?

**Comment by breed-id** [comment]
I using PHP Version 5.6.25

**Comment by dpfaffenbauer** [comment]
actually this is a problem that appears in the latest versions of pimcore (4.4)
