### ISSUE TITLE
Backend: Receiving threads in Customer Service needs a lot of memory

### ISSUE THREAD

**Issue by danielklimsa** [coreshop/CoreShop#131]
Currently I'am having four message threads in the Customer Service section in the backend.

With memory_limit=128M I'am able to get details for the the second and the third thread. Thread one and four are ending in:

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/pimcore/lib/Pimcore/Tool/Serialize.php on line 82
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /var/www/pimcore/lib/Pimcore.php on line 964
PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0
```

Raising memory_limit to 768M doesn't help (also due to capacity limits):

```
PHP Fatal error:  Out of memory (allocated 773849088) (tried to allocate 20480 bytes) in /var/www/pimcore/lib/Pimcore/Tool/Serialize.php on line 74
PHP Fatal error:  Out of memory (allocated 773849088) (tried to allocate 65536 bytes) in /var/www/pimcore/lib/Pimcore.php on line 964
PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0
```

Sounds like a need for some optimization. ,)

(P.S.: Before I had the effect, that I'am able to open thread one and two, but not three and four. Maybe this info helps.)

**Comment by dpfaffenbauer** [comment]
do you know where this actually happens? 

I am not sure if this happens because of messaging, they don't use any serialization whatsoever.

**Comment by dpfaffenbauer** [comment]
Wait.

What Pimcore Version are you using?

**Comment by danielklimsa** [comment]
I haven't digged into this yet, sorry – Pimcore's php.log doesn't bring up more information.

I'am using version 4.3.1 (Build: 3961).

**Comment by danielklimsa** [comment]
ok, it seems to be this line in the MessagingThreadController (getAction):

```
$this->_helper->json(array('success' => true, 'data' => ['thread' => $thread->getObjectVars(), 'messages' => $this->getMessagesForAjax($thread)]));
```

not passing the object vars "resolves" the problem – message thread are opening but (of course) sending a message in the thread ends in an error. but it should be a hint for you. 
```
$this->_helper->json(array('success' => true, 'data' => ['thread' => [], 'messages' => $this->getMessagesForAjax($thread)]));
```

**Comment by dpfaffenbauer** [comment]
I just pushed a fix, can you try it and confirm if it works for you?

**Comment by danielklimsa** [comment]
it works like a charm! perfect. thx!
