### ISSUE TITLE
[Core] Inject tax calculator into tax calculator factory instead of manually instantiating it 

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1327]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no

Maybe we should inject the tax calculator which should be used, so we don't need to complete create a new class to use a custom tax calculator. 

https://github.com/coreshop/CoreShop/blob/e3e6522011b8acbf9a783f5dc75bc09e3e50c073/src/CoreShop/Component/Core/Taxation/TaxCalculatorFactory.php#L63

**Comment by dpfaffenbauer** [comment]
I don't agree. The default Tax calc behavior depends on a specific set of configurations (countries, states and behavior). The factory resolves that configurations and creates the calculator. If you have a different calculation behavior, just create your own Factory.
