### ISSUE TITLE
missing event(s) on coreshop.cart

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1336]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In the docs are some events listed which should be available on cart. But they are not available in V2.1
i.e ```coreshop.cart.item_add_post``` was removed in 2.1

The docs should be corrected so that only existing events are listed and missing events are added to code and doc.

**Comment by dpfaffenbauer** [comment]
see https://github.com/coreshop/CoreShop/pull/1676
