### ISSUE TITLE
Voucher code usage is not increased in price rule

### ISSUE THREAD

**Issue by danielklimsa** [coreshop/CoreShop#134]
As far as I see, a voucher code usage should be increased in the overview (of voucher codes) in the pricerule, when an order is created.

But it isn't.

I would say, it's because of "$order->getVoucher()" in "applyOrder(){}" in the PriceRule model – but the property "voucher" isn't filled with a value (any more).

**Comment by dpfaffenbauer** [comment]
thats not true. Total Usage per Voucher means how often one customer can use the same voucher code.

**Comment by danielklimsa** [comment]
i'am talking about this ("uses" is not increased after an order): ,)

![screen shot 2016-11-18 at 18 50 01](https://cloud.githubusercontent.com/assets/20857191/20440320/e5635b7e-adbf-11e6-8c47-c76b43145c67.png)

**Comment by dpfaffenbauer** [comment]
you are right. There was still some deprecated parts for this.

**Comment by danielklimsa** [comment]
sorry, had no time to test it completely earlier.

now, when checking for the validity of a voucher code, Cart/PriceRule::getTotalUsesForPriceRule() is setting a condition on the fields priceRule and voucher (which do not exist any more).

**Comment by dpfaffenbauer** [comment]
fixed

**Comment by danielklimsa** [comment]
perfect. thx. but please remove the echo in Cart/PriceRule. ,-)

**Comment by dpfaffenbauer** [comment]
of course, sorry. It's removed now
