### ISSUE TITLE
Allow Product Sets

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1342]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | currently yes

- New Class `CoreShopProductSet`
- Allow adding Products via relations
- Allow defining new price via Store Price
- More to define

**Comment by dpfaffenbauer** [comment]
Already possible using Core Features. Just add the class, decide if it as Product or Purchasable, create a Price Calculator, allow new Class to be used within OrderItem/CartItem/QuoteItem  relations, create UI and done.

Don't think more than that is needed.

**Comment by dpfaffenbauer** [comment]
Will not come within the Core, would be a good use case for a plugin though.
