### ISSUE TITLE
Allow Backend Preview of Unpublished Products

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1344]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Like everything else in pimcore it should be possible to preview products from backend, even if they are unpublished.

https://github.com/coreshop/CoreShop/blob/f8e6572d49968fbd00b843005edbd40a28781c3c/src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php#L49-L50

**Comment by dpfaffenbauer** [comment]
I do not consider this a bug honestly. Just because it's not implemented, it's not a bug.
