### ISSUE TITLE
Improve filters on the online demo

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#136]
Actualy it is hard to find on the demo a page with filters demontration (by price, color, attributs, ...).
I wanted to see it in action, but i found just one page : https://demo.coreshop.org/en/shop/tv-gerate~c11

Maybe the demo could be improved to show the power of CoreShop on this subject ?

**Comment by dpfaffenbauer** [comment]
I do have a large list of todos, one of them is to create a seperate plugin "CoreShopDemo" where it installs a lot of things to showcase the power of CoreShop.

**Comment by Yivan** [comment]
Ho great! I am happy to hear it. Yes it will show all the potential of your plugin.
Thanks.

**Comment by dpfaffenbauer** [comment]
First part for this issue: https://github.com/coreshop/CoreShop-Demo. This plugin lets you install some demo-data like products/categories and taxes. Still some things to follow like filters/indexes.

**Comment by dpfaffenbauer** [comment]
https://github.com/coreshop/CoreShop-Demo: now also includes filters, indexes, manufacturers and carriers

**Comment by Yivan** [comment]
Thanks a lot!
I saw index are localized now, this is great : )

**Comment by dpfaffenbauer** [comment]
Yeah, but only for mysql by now.
