### ISSUE TITLE
Better default registration

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1371]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

The default registration has very bad usability and user experience: https://demo2.coreshop.org/en/shop/register
There are a lot of fields to be filled multiple times (salutation 2x and gender), firstname doubled and so on... that's something every developer will have to change so we could directly change it from the start and make some improvements here. May be a good fit for 2.3/3.0?

**Comment by solverat** [comment]
So true. Also checkout comes with too much steps. A better approach would be to decouple frontend bundle (remove it completely from base) and create a coreshop-twig-storefront (and in future maybe a coreshop-react-storefront - with datahub).

You need to copy the complete view folder anyway.

**Comment by aarongerig** [comment]
@solverat I‘d be happy to provide a `coreshop-vue-storefront` bundle then. 😏

**Comment by dpfaffenbauer** [comment]
will not come with 3.0
