### ISSUE TITLE
Version 2.2 : Unknown column 't0.indexLastVersion' in 'field list'

### ISSUE THREAD

**Issue by D37R4C7** [coreshop/CoreShop#1381]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

After updating to version 2.2 I get this error:

```
An exception occurred while executing 'SELECT t0.id AS id_1, t0.class AS class_2, t0.name AS name_3, t0.worker AS worker_4, t0.configuration AS configuration_5, t0.indexLastVersion AS indexLastVersion_6, t0.creation_date AS creation_date_7, t0.modification_date AS modification_date_8 FROM coreshop_index t0 WHERE t0.id = ?' with params [1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.indexLastVersion' in 'field list'
```

**Comment by D37R4C7** [comment]
I don't know why the migrations where not executed:

`vendor/coreshop/core-shop/src/CoreShop/Bundle/IndexBundle/Migrations/Version20200224161101.php
`

Will do it manual now.

**Comment by dpfaffenbauer** [comment]
did you run the migrations script? `bin/console coreshop:migrate`?

**Comment by D37R4C7** [comment]
Arghh... Sorry my fault. I thought this is normally triggered via composer by default.
