### ISSUE TITLE
Combine filter types

### ISSUE THREAD

**Issue by aarongerig** [coreshop/CoreShop#140]
If possible, it would be nice to combine several and different filter types into one group. In the Frontend the output would look something like this:

<img width="262" alt="bildschirmfoto 2016-12-02 um 11 56 34" src="https://cloud.githubusercontent.com/assets/17384333/20831669/6be4d63e-b886-11e6-948d-760c4e48884a.png">

**Comment by dpfaffenbauer** [comment]
see 3e9274b82a55892554a927ac94471da1e1bbedfb
