### ISSUE TITLE
$rawValues in render method is not sorted

### ISSUE THREAD

**Issue by rigelsoft** [coreshop/CoreShop#142]
\lib\CoreShop\Model\Product\Filter\Condition\Range.php - **render** method

$rawValues can be unsorted. So taking first value to $minValue

`$minValue = count($rawValues) > 0 ? $rawValues[0]['value'] : 0;`

and last value to $maxValue is incorrect.

`$maxValue = count($rawValues) > 0 ? $rawValues[count($rawValues)-1]['value'] : 0;`

**Comment by dpfaffenbauer** [comment]
can you test the fix please?
