### ISSUE TITLE
Specific Price Rule label is not being saved

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1428]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The label of the specific price rules is not being saved. Reproducable on coreshop demo.

![Screenshot_2020-06-15 demo2 coreshop org Pimcore](https://user-images.githubusercontent.com/2771909/84681240-214bd700-af34-11ea-8d1e-16c5b97d6cc5.png)
Label "English Label" is gone after save&publish of the product.

**Comment by dpfaffenbauer** [comment]
has already been fixed here: https://github.com/coreshop/CoreShop/pull/1447

**Comment by ramundomario** [comment]
@dpfaffenbauer the issue is still present on the demo
