### ISSUE TITLE
Simplify Order States

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#143]
## Overview
| Identifier | Name | Description | Task | 
|----------|:-------------|------|------:|
| PENDING_PAYMENT |  pending payment | set after order has been created  | - |
| QUEUE | Awaiting check payment | - | not in use, remove? |
| PAYMENT | Payment accepted | - | - |
| PREPERATION | Preparation in progress | - | - |
| SHIPPING | Shipped | - | - |
| DELIVERED | Delivered | - | - |
| CANCELED | Canceled | - | - |
| REFUND | Refunded | - | - |
| ERROR | Payment error | - | - |
| OUTOFSTOCK | On backorder (paid) | - | - |
| OUTOFSTOCK_UNPAID | On backorder (not paid) | - | - |
| BANKWIRE | Awaiting bank wire payment | - | remove from coreshop, install via bankwire plugin |
| COD | Awaiting Cash On Delivery validation | - | remove from coreshop, install via cod plugin |

## Improvements

* [x] remove Order States from Configuration, move Identifier to DB, disallow deletion of system OrderStates. see 07d736cc465c6af727eff270a0a06c4ed29dca6a.
* [x] remove `SYSTEM.MAIL.CONFIRMATION` from settings. Only orderState should handle email flow of order progress. see 16320a24241393e3cc564eee819a6e95e016248a
* [ ] discuss and clean up Order States, remove deprecated or move to corresponding plugin (see table above)
* [ ] allow `states` and `status` (do not change state, only create note?).
* improve order gui:
    * [ ]  Show order state history notes

**Comment by dpfaffenbauer** [comment]
What are the benefits of states and status?

**Comment by dpfaffenbauer** [comment]
Regarding Order State History: We already show the history, but currently it's not possible to add notes to it.

**Comment by solverat** [comment]
because of the rebuild of OrderStates to Workflows (see #145), this task has been marked as obsolete.
