### ISSUE TITLE
[Specific Price Rule] Unable to edit saved rule

### ISSUE THREAD

**Issue by ramundomario** [coreshop/CoreShop#1437]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

It isn't possible to edit a saved specific price rule

![specific_price_rule_bug](https://user-images.githubusercontent.com/16133208/86222248-453f2780-bb86-11ea-918d-6090f0ad1298.gif)

The only way I have found is to delete the price rule and create another one, reproducible on latest demo

**Comment by dpfaffenbauer** [comment]
@ramundomario would you mind testing the PR?

**Comment by ramundomario** [comment]
> @ramundomario would you mind testing the PR?

Tested successfully, but don't know if it could break anything else
