### ISSUE TITLE
[Orders] Unable to edit grid options to add/remove fields

### ISSUE THREAD

**Issue by ramundomario** [coreshop/CoreShop#1438]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no

It isn't possible to edit grid options to add/remove fields in Orders panel due to JS errors
![orders_grid_add](https://user-images.githubusercontent.com/16133208/86224106-c0094200-bb88-11ea-8a03-007e2beece01.gif)

![orders_grid_delete](https://user-images.githubusercontent.com/16133208/86223815-57ba6080-bb88-11ea-8975-5c07ff59d026.gif)

Reproducible on latest demo

**Comment by dpfaffenbauer** [comment]
I honestly don't think that is a CoreShop Problem. We use the standard Pimcore Grid here.

**Comment by solverat** [comment]
@dpfaffenbauer i'm not sure about that, i just checked it on pimcore demo, there is also the `TypeError: Cannot read property 'tdCls' of null` error, but no uncaught type error.

**Comment by davidhoeck** [comment]
@dpfaffenbauer I also encountered some errors when changing grid configuration, but mostly when I clicked "apply". Backend was broken after that, but it was working in the default grid view of folders for example.

**Comment by dpfaffenbauer** [comment]
the warnings aren't a CoreShop issue, that is a Pimcore issue. But the rendering issue came from CoreShop.
