### ISSUE TITLE
[Voucher] Solution for a unique voucher code generation

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#1453]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no

As discussed, try to generate a code until it is unique, currently i got a exception that the code already exists.

My current solution:
```
        $uniqueCode = false;
        while (!$uniqueCode) {
            $codes = $this->cartPriceRuleVoucherCodeGenerator->generateCodes($voucherCodeConfiguration);
            $code = reset($codes);

            $existingCode = $this->cartPriceRuleVoucherRepository->findByCode($code->getCode());
            if (!$existingCode) {
                $uniqueCode = true;
            }
        }
```

**Comment by davidhoeck** [comment]
Great solution. Maybe we can also implement a user feedback in the backend to show those codes which would have been duplicates.

**Comment by dpfaffenbauer** [comment]
@davidhoeck ?
