### ISSUE TITLE
[IndexBundle] Huge performance issue when using relational select or multiselect with a lot of indexables

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1457]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

When having thousands of products (objects), using the relational selects or multiselects is almost impossible, because the database queries will be increased extremely. 

### Example 

Here we have a list of ~ 60.000 Products. Every product has multiple related objects which are used to create the filter options. When using the filter processor to prepare the conditions, we have around 47.000 database queries for a single request. 
When we are not processing the database queries we only have about 100 database queries. That's a lot less then with the filter options. 

__With filter conditions preperation__
![Screenshot-mit-Filter](https://user-images.githubusercontent.com/24294584/87558146-0c8c6b80-c6b9-11ea-9540-b52e03923be0.PNG)

__Without filter conditions preperation__
![Screenshot-ohne-Filter](https://user-images.githubusercontent.com/24294584/87558178-16ae6a00-c6b9-11ea-8f93-ac81e9d579f1.PNG)

Is there a solution for that problem or is that a problem we have to live with when using the relational selects?

**Comment by dpfaffenbauer** [comment]
Guess you are reaching the limits of a Database Index....

**Comment by davidhoeck** [comment]
Closing it for now - I think it's Pimcore "fault" ...

**Comment by dpfaffenbauer** [comment]
how did you solve it now?

**Comment by davidhoeck** [comment]
We switched to a default select and persisted the name of the object in the index table. Way faster because no object need to be loaded, but not the way we wanted to implement it...
