### ISSUE TITLE
fresh installation currently not possible

### ISSUE THREAD

**Issue by fashxp** [coreshop/CoreShop#146]
When CoreShop Plugin is activated and installed, CoreShop menu doesn't appear > installation not possible.

This is because of getSettingsAction in Admin_SettingsController returns lots of warnings within  `\CoreShop::getPimcoreClasses();` since CoreShop Pimcore object classes are not created yet. 

Tested with Windows & XAMPP.

**Comment by dpfaffenbauer** [comment]
thanks
