### ISSUE TITLE
Exception on sites with no store

### ISSUE THREAD

**Issue by roynilsson** [coreshop/CoreShop#1463]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I have a multi site setup where some of the sites are not connected to a Coreshop store. Am using latest commit (fd87c6f99aa1af520190b52793866afa2fe59c40) of the master branch.

When trying to access the site without store I get the following error.

> Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Return value of CoreShop\Component\Store\Context\RequestBased\SiteBasedRequestResolver::findStore() must implement interface CoreShop\Component\Store\Model\StoreInterface, null returned in /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Component/Store/Context/RequestBased/SiteBasedRequestResolver.php on line 38

The type hint of the findStore method does not allow null values but in this case it tries to return null. I changed the type hint to allow null and this seemed to work for me. Got past the error. I am unsure if this is a good solution or not. There is a StoreNotFoundException thrown when the default store is not found. Maybe throwing that exception would be the expected behaviour? Then again would that mean that it is not possible to have sites without a store?

I think someone who knows Coreshop better than me need to figure this out.

**Comment by dpfaffenbauer** [comment]
Yep, that is the right solution. Could you create a PR?
