### ISSUE TITLE
[CoreBundle] Don't validate maximum or minimum order quantity when value is 0

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1467]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Sometimes users enter `0` in the maximum or minimum order quantity and especially when you enter it in the maximum order quantity field, the product can not be added to the cart.

**Comment by dpfaffenbauer** [comment]
The customer cannot add 0, since the field is validated?!

![Bildschirmfoto 2020-07-24 um 11 36 41](https://user-images.githubusercontent.com/5981845/88378782-f447db00-cda1-11ea-9ed7-9f5c846802a2.png)

**Comment by dpfaffenbauer** [comment]
Anyway, I changed it a bit to allow 0 and 0 disables the behaviour
