### ISSUE TITLE
Coreshop Order Overview broken if a value is null

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1470]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If you have a customer with an empty field (in this case lastname) and you try to add the field as column to the order overview, it'll fail with the error message "Uncaught TypeError: k.el is null" in console. Order overview will be broken afterwards.
![coreshop-order-overview-null-values](https://user-images.githubusercontent.com/2771909/88391343-4a287d00-cdba-11ea-8e73-5dda2be4cb92.png)

Reproducable at pimcore demo with coreshop 2.2.3 and in our environment on coreshop 2.1 series.

This is a huge problem because the concenated name given by coreshop by default is not searchable. So you can not find the orders of a specific customer easily at the moment. Only searchable field is email - as long as there is no customer without a email adress.

**Comment by dpfaffenbauer** [comment]
I cannot reproduce it, but I also think that it is a Pimcore Problem, since the `lastname` field uses standard Pimcore Grid Field Transformers and not CoreShop specific ones.

**Comment by Cruiser13** [comment]
Hi @dpfaffenbauer did you follow my description? You have to use the custom view "order overview", not a default grid view in a folder (which will work). It's not a problem of the lastname field - I can reproduce this with every field a customer has, even with normal text input fields.

**Comment by dpfaffenbauer** [comment]
Yes, still not reproduceable . maybe related to https://github.com/coreshop/CoreShop/issues/1438

**Comment by Cruiser13** [comment]
Looks like something in Coreshop 2.2.4 fixed this issue.

**Comment by Cruiser13** [comment]
Indeed, fixed by this commit: https://github.com/coreshop/CoreShop/pull/1454/commits/c23164616794fb35714e94b0e16eba644f48c335
Since the file did not change much from 2.1 to 2.2 we could easily backport this to the 2.1 series aswell.

**Comment by dpfaffenbauer** [comment]
2.1 is not maintained anymore.

**Comment by Cruiser13** [comment]
So there will be no 2.1 release anymore @dpfaffenbauer ?  2.1.9 is final verison for 2.1 series?

**Comment by dpfaffenbauer** [comment]
yep
