### ISSUE TITLE
100% discount is not 0

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1475]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Expected: 100% discount equals 0 euro/currency to pay.

Reproduced on the current 2.2.4 demo, issue does also exist for the 2.1 series by:

1. Create a product without a tax rule or use a tax rule but include tax in the product price:
![Screenshot_2020-08-04 demo2 coreshop org Pimcore](https://user-images.githubusercontent.com/2771909/89322268-4cc18700-d684-11ea-8138-bc6f3a9b8a6c.png)

2. Create a 100% price rule (without restrictions but it doesn't matter):
![Screenshot_2020-08-04 demo2 coreshop org Pimcore(1)](https://user-images.githubusercontent.com/2771909/89322310-5ba83980-d684-11ea-9401-4926b6a226a9.png)
![Screenshot_2020-08-04 demo2 coreshop org Pimcore(2)](https://user-images.githubusercontent.com/2771909/89322322-5ea32a00-d684-11ea-8607-bf088b1f7c07.png)

3. Create a new backend order and add your product from step 1
![Screenshot_2020-08-04 demo2 coreshop org Pimcore(3)](https://user-images.githubusercontent.com/2771909/89322365-69f65580-d684-11ea-88c0-6382f1143b2d.png)

4. Price is not 0:
![Screenshot_2020-08-04 demo2 coreshop org Pimcore(4)](https://user-images.githubusercontent.com/2771909/89322394-7084cd00-d684-11ea-9661-2b2685a870a0.png)

This does also work for other amounts:
![Screenshot_2020-08-04 demo2 coreshop org Pimcore(5)](https://user-images.githubusercontent.com/2771909/89322476-8b574180-d684-11ea-8bc6-b66d5d43afcc.png)

![Screenshot_2020-08-04 demo2 coreshop org Pimcore(6)](https://user-images.githubusercontent.com/2771909/89322488-8eeac880-d684-11ea-9b6f-525316d87ba5.png)

In this case it might be a shipping tax problem but even without shipping fees we sometimes got a 0,01 € with 100% discount. Might be a rounding issue too?

**Comment by dpfaffenbauer** [comment]
this only happens when the product does not have a tax-rule applied. I think it might come from the fact that the discount is calculated against the items and is also calculated against taxes. (discount removes taxes as well).

it is an interesting find anyway and I will look into it.

**Comment by dpfaffenbauer** [comment]
Ok, there is a conceptual issue. We have to remove the selection of 'total' and 'subtotal' to solve that. We can never apply 100% discount on total, that is impossible right now, cause we can't calculate certain taxes for adjustments (eg. shipping). 

The solution might be: use subtotal and add free-shipping if it really should be free.

**Comment by Cruiser13** [comment]
Sorry to disappoint you but I think the issue is even bigger. I could now reproduce the following at the demo:
![Screenshot_2020-08-05 demo2 coreshop org Pimcore](https://user-images.githubusercontent.com/2771909/89407445-1f75e700-d71f-11ea-8b9a-f10853b4a5f5.png)

![Screenshot_2020-08-05 demo2 coreshop org Pimcore(1)](https://user-images.githubusercontent.com/2771909/89407455-23a20480-d71f-11ea-83fb-59c71b110f4f.png)


tax rate is 16%
store price for the product is 99 €
coreshop store settings: "store price with vat" yes

Same behaviour in the 2.1 series aswell, tested in public demo 2.2.4

**Comment by dpfaffenbauer** [comment]
discount rule with total or subtotal?

**Comment by dpfaffenbauer** [comment]
can you test the PR? actually, don't use total there, as that is the main source of the problem. use subtotal and free-shipping

**Comment by Cruiser13** [comment]
@dpfaffenbauer same result with total and subtotal.

**Comment by Cruiser13** [comment]
I can not test the PR directly because I only have 2.1 shops at the moment. Could you apply the patch to the demo shop?

**Comment by dpfaffenbauer** [comment]
nope, demo runs on dev-2.2 on a nightly setup

**Comment by Cruiser13** [comment]
Okay. I'll see if I can adapt the changes to 2.1 in this case and see if the issue is fixed then.

**Comment by Cruiser13** [comment]
Actually the PR should be the same result if we use "subtotal" in the apply to. Since I can reproduce this bug using a discount rule with subtotal, it'll not fix the issue I think @dpfaffenbauer

**Comment by dpfaffenbauer** [comment]
you're right, I could find the issues and adapted the PR and added further tests
