### ISSUE TITLE
Use Condition/Action for Email-Workflow

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#148]
Allow user to create custom mail-actions based on different conditions. Use different global types to filter those conditions.
This allows us to provide highly flexible and extendible mail-workflows.

## Order
**Conditions**
* _Payment_
   * all
   * payment 1
   * payment 2
* _OrderState (From => To)_
   * all (means, from some state to another state)
   * dropdown 1, dropdown 2
* _Shipping_ 
   * all
   * shipping method 1 
   * shipping method 2
* _Invoice is available (complete)_
* _Invoice is available (partial billing)_
* _Shipping Note is available (complete)_
* _Shipping Note is available (partial shipment)_

**Actions**
* Send Mail
   * Select Mail for each language

## User

**Conditions**
* _Type_
   * new account
   * reset password

**Actions**
* Send Mail
   * Select Mail for each language

## Messages

**Conditions**
* _Type_
   * customer
   * customer-reply
   * contact

**Actions**
* Send Mail
   * Select Mail for each language

**Comment by dpfaffenbauer** [comment]
Refactored extendable conditions/actions/filters/similarities: Todo Documentation
