### ISSUE TITLE
Error when opening a field collection

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#1483]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Since last week i got this error if i open a field collection:
![image](https://user-images.githubusercontent.com/2986829/91851708-f4b87900-ec5f-11ea-8997-5dab4e6552c4.png)

**Comment by dpfaffenbauer** [comment]
what versions are you on?

**Comment by albertmueller** [comment]
pimcore 6.7.2
coreshop dev-master
but currently i can no longer reproduce

**Comment by dpfaffenbauer** [comment]
ok, interesting... I'd say we close it for now then. If it happens again, feel free to create a new ticket.
