### ISSUE TITLE
Price of products is set to 0 when a variant is added and its price is changed

### ISSUE THREAD

**Issue by Brainshaker95** [coreshop/CoreShop#1486]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Coreshop version 2.2.3
Pimcore version 6.6.9

**Steps to reproduce:**

* Add a product and set its price
![image](https://user-images.githubusercontent.com/20670106/92687319-98c6b200-f33b-11ea-83c1-ec9ce6b91e99.png)

* On CoreShopProduct set "allowInherit" and "allowVariants" to true
![image](https://user-images.githubusercontent.com/20670106/92687420-cb70aa80-f33b-11ea-9f13-5ec24b2fc353.png)

* Add a product variant and change its price
![image](https://user-images.githubusercontent.com/20670106/92687745-62d5fd80-f33c-11ea-9579-8588c585581f.png)

Table "coreshop_product_store_values" before changing the price:
![image](https://user-images.githubusercontent.com/20670106/92687676-4c2fa680-f33c-11ea-9a68-492e7049c505.png)

And after changing the price (and saving the variant of course)
![image](https://user-images.githubusercontent.com/20670106/92687822-8436e980-f33c-11ea-99fd-ff7270b1ecbb.png)

The whole data record is replaced with the store value of the variant.

I'm not sure how to fix it or else I would've done it myself and opened a PR. I'm at least quite positive that the actual setting of the price is happening here (I know that the problem has something to do with the reference to the store values table, but maybe this helps):

`CoreShop\Bundle\CoreBundle\CoreExtension\StoreValues`, around line 550

```php
//Fill missing stores with empty values
$storeData[$store->getId()] = [
    'name' => $store->getName(),
    'currencySymbol' => $store->getCurrency()->getSymbol(),
    'values' => ['price' => 0],
    'inheritable' => $inheritable
];
```

**Comment by dpfaffenbauer** [comment]
this might have fixed it: https://github.com/coreshop/CoreShop/pull/1404

**Comment by Brainshaker95** [comment]
Seems like the issue is still present

**Comment by dpfaffenbauer** [comment]
can you reproduce it at the demo? (demo2.coreshop.org/admin)

**Comment by Brainshaker95** [comment]
Yes, exactly the same behaviour as described above

**Comment by dpfaffenbauer** [comment]
PR #1491 fixes it

**Comment by Brainshaker95** [comment]
This seems to work, but doesn't `getDataFromEditmode`  also mean that you can't create variants programmatically. But that would maybe be a feature request instead of a bug

**Comment by dpfaffenbauer** [comment]
You can create variants manually, and CoreShop also takes care about coping price information if you change it here: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php#L357

For some reason, that didn't work for variants though....

**Comment by GALCF** [comment]
Adding a new variant to the master product seems to make the new variant the master, the "delete store values" button is only shown on the variant children, not the master, but after adding variants, this is flipped:

*Master*
![image](https://user-images.githubusercontent.com/14803394/99374995-7f099400-28c3-11eb-998e-c4b564e76568.png)

*Newly created variant*
![image](https://user-images.githubusercontent.com/14803394/99375108-a1031680-28c3-11eb-8e2b-c58a0e12b730.png)

**Comment by dpfaffenbauer** [comment]
@GALCF what version do you use currently?

**Comment by GALCF** [comment]
> @GALCF what version do you use currently?

CoreShop with 2.1.9 and Pimcore 6.5.3

**Comment by GALCF** [comment]
After a quick debugging-installation: The issue does not seem to occur anymore in CoreShop 2.2.6 with Pimcore 6.7.3

**Comment by dpfaffenbauer** [comment]
A lot has happened with StoreValues and inheritance in the meantime, try updating to 2.2.x.
