### ISSUE TITLE
Improve Order Overview

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#149]
some improvements to beautify the handling of order processing. :)

- [ ] allow filter for states
- [ ] allow custom layouts (allow custom fields like "customer" or "payment type" in list view) 
- [x] save config for each user (?)

**Comment by dpfaffenbauer** [comment]
save config is implement using extjs stateful grid

**Comment by dpfaffenbauer** [comment]
Solved in CoreShop 2, not going to backward it to CoreShop 1 though
