### ISSUE TITLE
[ResourceBundle] Make ResourceBundle compatible with JMSSerializerBundle 3.x

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#1499]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes/no
| RFC?             | yes/no

Some other bundles are not compatible with CoreShop anymore because they use the newer version of JMS and the symfony bundle. Therefore I think we should upgrade.

**Comment by dpfaffenbauer** [comment]
yes, but only with CoreShop 3.0

**Comment by dpfaffenbauer** [comment]
done with 3.0
