### ISSUE TITLE
Wrong migration order

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1506]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Coreshop Migration 20200427113206 triggered an error for me on Update:

> Migration 20200427113206 failed during Execution. Error An exception occurred while executing 'SELECT t0.id AS id_1, t0.code AS code_2, t0.used AS used_3, t0.uses AS uses_4, t0.creditUsed AS creditUsed_5, t0.creditAvailable AS creditAvailable_6, t0.isCreditCode AS isCreditCode_7, t0.creationDate AS creationDate_8, t0.modificationDate AS modificationDate_9, t0.cartPriceRuleId AS cartPriceRuleId_10, t0.currencyId AS currencyId_11 FROM coreshop_cart_price_rule_voucher_code t0 WHERE t0.cartPriceRuleId = ?' with params [1]:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.creditUsed' in 'field list'

Looks like Migration 20200617120130 is adding those fields to the table - but is executed after 20200427113206.

Manually running the SQL statement from 20200617120130 worked for me, I was able to run all migrations after that.

**Comment by dpfaffenbauer** [comment]
These should be completely independent from each other. I don't understand how one triggers another....

**Comment by Cruiser13** [comment]
@dpfaffenbauer 20200617120130 is adding the field creditUsed but it's already required in 20200427113206 which will be executed before 20200617120130. Guess the order of the migrations is wrong.

**Comment by dpfaffenbauer** [comment]
no, creditUsed is not directly used in 20200427113206

**Comment by Cruiser13** [comment]
@dpfaffenbauer weird because it threw the error in the first post. Well, maybe it was just our environment somehow, no idea.
