### ISSUE TITLE
Order details are no longer working

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1507]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

We just updated to coreshop 2.2.6 and now we can no longer open order detail pages for existing orders.

GET | https://protect19.werbeagentur.work/admin/coreshop/order/detail response:

> LONG JSON... {"label":"Stornieren","transition":"cancel","color":"#f2583e"}]}],"payments":[],"shipments":[],"paymentCreationAllowed":true,"invoiceCreationAllowed":false,"shipmentCreationAllowed":true,"shippingPayment":{"carrier":"standard","weight":0,"cost":750}}}<br />
<b>Fatal error</b>:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: ReflectionProperty::setValue(): Cannot assign to an array of nodes (duplicate subnodes or attr detected) in /serverpath/pimcore/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:252

**Comment by davidhoeck** [comment]
Hi @Cruiser13 we also experienced that problem. Looks like it is related to https://github.com/pimcore/pimcore/pull/7060 as far as I can see. When working on Pimcore 6.8.x the problem occurs, when working on 6.7.x it is not ... 

@dpfaffenbauer would be great to get some feedback of yours here.

**Comment by Cruiser13** [comment]
Following the discussions on gitter the following code makes the order details work again:

services.yml
```
    AppBundle\EventSubscriber\DeepCopySubscriber:
        public: true
```

AppBundle\EventSubscriber\DeepCopySubscriber.php
```
<?php

namespace AppBundle\EventSubscriber;

use DeepCopy\DeepCopy;
use DeepCopy\Filter\Doctrine\DoctrineCollectionFilter;
use DeepCopy\Matcher\PropertyTypeMatcher;
use Pimcore\Event\SystemEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\EventDispatcher\GenericEvent;

class DeepCopySubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            SystemEvents::SERVICE_PRE_GET_DEEP_COPY => 'addDoctrineCollectionFilter',
        ];
    }

    public function addDoctrineCollectionFilter(GenericEvent $event)
    {
        /**
         * @var DeepCopy $copier
         */
        $copier = $event->getArgument('copier');
        $copier->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));
        $event->setArgument('copier', $copier);
    }
}


```

Credits to @ramundomario

**Comment by dpfaffenbauer** [comment]
fixed with https://github.com/coreshop/CoreShop/pull/1534
