### ISSUE TITLE
Company class has no effect

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#1508]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | maybe
| BC Break report? | no
| RFC?             | yes

The new company class seems to have no effect yet. The field vatIdentificationNumber is not used anywhere in the code and no company is created on registration of a customer (even is company field is filled).

We implemented some of the company fields (like the vatIdentificationNumber ) in our customer class in coreshop 2.1 and now seeing duplicate functionality from the fields in 2.2. Since there are no docs for the company feature I'd like to know if there is any effect yet and if we should start using it instead of our custom fields?

Maybe @solverat can give me some clue about it here.

**Comment by seybsen** [comment]
I think it's related to this #1266

**Comment by dpfaffenbauer** [comment]
The company class has effects, mainly now to share addresses for users. Fields like VAT Number are just there for preparation for future events.

Start using it now to get future positive effects. it is good to have it in place early with unused fields, rather than not having it and migrate later.

**Comment by solverat** [comment]
Actually, there are a lot of effects :). But it needs some further work from project side (see my ticket #1266 mentioned by @seybsen) if you want to use it. There is no out-of-the box logic to assign customers/registration processes to companies. But with this PR it's super simple to implement company/customer workflows.

**Comment by Cruiser13** [comment]
Thanks for the feedback dpfaffenbauer and solverat! We'll create companies with registration in this case and move our vat number logic to the company class. Looking forward to the future positive effects.
