### ISSUE TITLE
[FeatureRequest]Possibility to redirect CoreShop urls

### ISSUE THREAD

**Issue by plexmaniax** [coreshop/CoreShop#1512]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

As a coreshop owner it should be possible to redirect moved and disabled coreshop urls.

**current behaviour**:

old url : domain.tld/de/shop/oldpath-p212 
new url : domain.tld/de/shop/newpath-p212 

Your are able to reach the product by both urls - good userexpierence - bad google indexing (dupe content I guess)
I`m unable to redirect the old url in pimcore itself, just by .htaccess. This is very unhandy for customers.

**should behaviour**:

old url : domain.tld/de/shop/oldpath-p212
new url : domain.tld/de/shop/newpath-p212 

At my opinion by renaming a procduct/category there should be added an automaticly redirect like pimcore does.
Maybe you should remove the routing depending on the last section of product url, so the user will have the possibility to redirect the urls on pimcore redirect section.

**Comment by dpfaffenbauer** [comment]
I don't see that as a CoreShop feature, that should be something handled with from Pimcore or any other 3rd party bundle. Nothing we should add directly to CoreShop though, even you are 100% right.
