### ISSUE TITLE
Add multiple conditions to the MysqlWorker/Listing

### ISSUE THREAD

**Issue by mackrais** [coreshop/CoreShop#1523]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

### For example want get all filtered products with category and sub category.

I can`t  do this because $filteredList->setCategory($category).

**In your code i found `addUserSpecificConditions`   //variant handling and userspecific conditions**

But when I try set relation

```   
         $filteredList->addRelationCondition(
                new InCondition('dest', $categoryIds),
                'parentCategoryIds'
            );
```

**I got something like this:** 

```   
SELECT DISTINCT
	q.o_virtualObjectId AS o_id 
FROM
	coreshop_index_mysql_localized_rezashop_en q 
WHERE
	( q.`active` = '1' ) 
	AND (
		q.o_id IN (
		SELECT DISTINCT
			src 
		FROM
			coreshop_index_mysql_relations_rezashop q 
		WHERE
		q.`dest` IN ( '113', '259', '260' ))) 
	AND ( q.`stores` LIKE '%,1,%' ) 
GROUP BY
	q.o_virtualObjectId 
ORDER BY
	q.`name` ASC 
	LIMIT 12
```   

**In this case relation is wrong because table** `coreshop_index_mysql_relations_rezashop` **has column fieldname  q.dest it`s can by id other relations**

Correct query view something like that: 

```   
---
q.o_id IN (
		SELECT DISTINCT
			src 
		FROM
			coreshop_index_mysql_relations_rezashop q 
		WHERE q.fieldname = 'parentCategoryIds' AND  q.`dest` IN ( '113', '259', '260' )
		)
	) 
---
```

**Comment by dpfaffenbauer** [comment]
Sorry, I don't get what you are trying to tell me? You have several options in adding different queries to how the system works. Categories is quite a special one for the index, if it doesn't work for you, use custom extension to solve it?
