### ISSUE TITLE
Cart Price Rules without voucher code error

### ISSUE THREAD

**Issue by msoroka** [coreshop/CoreShop#1528]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no

Hi,
I have created cart price rule with free shipping, when order amount is above 200 without voucher rule. It assigns correctly, but on final step when I try to go to payment I have an error on route /shop/checkout-do
![image](https://user-images.githubusercontent.com/25011263/99389284-16c4ad80-28d7-11eb-8799-15e7dc945831.png)
![image](https://user-images.githubusercontent.com/25011263/99389315-25ab6000-28d7-11eb-9bee-91ca0ec93b26.png)
![image](https://user-images.githubusercontent.com/25011263/99389337-2d6b0480-28d7-11eb-881b-2c70ebdb04ca.png)
![image](https://user-images.githubusercontent.com/25011263/99389349-352aa900-28d7-11eb-91db-bf903e99d2bc.png)

In order object:
![image](https://user-images.githubusercontent.com/25011263/99389391-45db1f00-28d7-11eb-936e-2f1b03565f4d.png)

CoreShop Version: 3.0.0-alpha
PHP Version 7.3.20
Pimcore Version 6.7.3

**Comment by dpfaffenbauer** [comment]
3.0.0 is not even alpha and should not be used yet. it is still under heavy development and also is not intended to work with Pimcore 6.x (might be able to work with 6.9, but not sure yet).

**Comment by dpfaffenbauer** [comment]
fixed
