### ISSUE TITLE
Demo Shop - Can not open products or orders in admin:  Error

### ISSUE THREAD

**Issue by danielerne** [coreshop/CoreShop#1529]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

There's an error in demo. Orders or products can not be opened. It shows a getSymbols() error:
Call to a member function getSymbol() on null

**Comment by dpfaffenbauer** [comment]
should be fixed with the next release
