### ISSUE TITLE
Unable to save quantity price rules for product variants

### ISSUE THREAD

**Issue by seybsen** [coreshop/CoreShop#1531]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

Pimcore 6.8.4
CoreShop 2.2.6

When trying to add quantity price rules for product variants following error gets thrown:

```
Status: 422 | 
URL: /admin/object/save?task=publish
Method: PUT
Message: Invalid unit definition reference. Please reload the object and adjust the unit definitions first.
```

![](https://files.gitter.im/55312f3f15522ed4b3df29a4/DdsK/Bildschirmfoto-2020-11-23-um-17.16.40.png)

**Comment by dpfaffenbauer** [comment]
please reopen if so
