### ISSUE TITLE
NotificationRulePass detects a addtional empty tag

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#1532]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no

CoreShop dev-master / Pimcore 6.8.4 / PHP 7.4

I found an strage behaviour as i added a custom notification rule:
![image](https://user-images.githubusercontent.com/2986829/100071021-e03ce480-2e3a-11eb-8f2c-376fa487620f.png)

After adding i got this issue:
![image](https://user-images.githubusercontent.com/2986829/100071242-1da17200-2e3b-11eb-9844-6b4e15fe1491.png)

A look on AbstractNotificationRulePass shows me a additional empty tag:
![image](https://user-images.githubusercontent.com/2986829/100071394-4d507a00-2e3b-11eb-9c0e-14f4f9973817.png)

Maybe a possible quick fix:
```
foreach ($container->findTaggedServiceIds($this->tag) as $id => $attributes) {
            foreach ($attributes as $tag) {
                if (!$tag) {
                    continue;
                }
```

**Comment by dpfaffenbauer** [comment]
pretty sure autoloading is activated where you also manually specify the tag?

**Comment by albertmueller** [comment]
yes, the other rules in shipping and cart works well.

**Comment by dpfaffenbauer** [comment]
should be done already
