### ISSUE TITLE
Class overrides support

### ISSUE THREAD

**Issue by zoidbergx** [coreshop/CoreShop#1533]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no

CoreShop 2.2.6 / Pimcore 6.8.4 

We want to use a field collection with a Superbox Select with following configuration

![grafik](https://user-images.githubusercontent.com/1992165/100585850-8337a780-32ee-11eb-95d5-efc0562b041e.png)

Now if you want to select the configured relation the Dropdown is empty 

![grafik](https://user-images.githubusercontent.com/1992165/100586130-f3dec400-32ee-11eb-8f5c-e39d618c8792.png)

The reason is that we're using a "class override" for this relation to: "{PATH_TO_OWN_BUNDLE}\Model\Product\Category"

The Problem could be in the DynamicDropdownController in the "walkPath()" method. 
There is a static path to the DataObject.

![grafik](https://user-images.githubusercontent.com/1992165/100585613-23d99780-32ee-11eb-9ef8-253c7a9e8f99.png)

Maybe there is an option to support that or we missed something in the configuration?

**Comment by dpfaffenbauer** [comment]
should be fixed
