### ISSUE TITLE
Can't install CoreShop in Pimcore

### ISSUE THREAD

**Issue by mcules** [coreshop/CoreShop#154]
installed the Pimcore from composer and Coreshop Stable from composer too.
Installing the Extension is working fine but Install CoreShop gives the error below.
Tried the stable CoreShop and dev-master. Both installed by composer.

`Please wait ...
Error
Server threw exception - could not perform action. Please reload the admin interface and try again.

Status: 500 | 
URL: /plugin/CoreShop/admin_install/install
Method: post
Message: 

Fatal error:  Uncaught exception 'CoreShop\Exception' with message 'Unable to initiate list class - class not found or invalid configuration' in /var/www/clients/client3/web163/web/plugins/CoreShop/lib/CoreShop/Model/Base.php:124
Stack trace:
#0 /var/www/clients/client3/web163/web/plugins/CoreShop/lib/CoreShop/Plugin/Install.php(610): CoreShop\Model\Base::getList()
#1 /var/www/clients/client3/web163/web/plugins/CoreShop/controllers/Admin/InstallController.php(36): CoreShop\Plugin\Install->installWorkflow()
#2 /var/www/clients/client3/web163/web/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): CoreShop_Admin_InstallController->installAction()
#3 /var/www/clients/client3/web163/web/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#4 /var/www/clients/client3/web163/web/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controll in /var/www/clients/client3/web163/web/plugins/CoreShop/lib/CoreShop/Model/Base.php on line 124`

**Comment by dpfaffenbauer** [comment]
just pushed a fix, can you try again please? #84ed05385609e905ecee68ef55e298217248e8d6

**Comment by dpfaffenbauer** [comment]
reopen this ticket if error still occurs on your installation.
