### ISSUE TITLE
[Admin Order detail] Carrier name not shown with legacy serialization of Orders

### ISSUE THREAD

**Issue by ramundomario** [coreshop/CoreShop#1540]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no

Carrier name is not shown in the shipment block in the admin order detail panel (Reproduced on latest demo).
![bug](https://user-images.githubusercontent.com/16133208/101160308-19413a00-362f-11eb-9aef-64a11e8e94e3.png)

Doing some debugging I noticed the `carrierName` is not present in the response if the `coreshop.order.legacy_serialization` parameter is true (default).
https://github.com/coreshop/CoreShop/blob/8304171034d39a982aa74ee53907b21262725fbc/src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php#L348-L383

A solution would be to manually add the carrier identifier taken from the `shipment` if legacy serialization is true (default).
wdyt? @dpfaffenbauer 
I could open a pull request

**Comment by dpfaffenbauer** [comment]
@ramundomario should be basically the same as here: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/CoreBundle/Resources/config/serializer/Model.OrderShipment.yml#L7
