### ISSUE TITLE
Notification Rule - not able to send more then one email

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#1557]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no

Tryed to set more then one email template in notification rule, what happen if you press save:
![image](https://user-images.githubusercontent.com/2986829/104914109-efe62e80-598e-11eb-9347-d6ca5555ad64.png)

After a look in the db table: coreshop_rule_action, it shows the same id from the latest template in both entry configuration.

**Comment by ramundomario** [comment]
Tested it and the email is sent 2 times with the same mail document (unless you manually change the id from the database)

My use case: Send order confirmation email to both the customer and the store team

![Screenshot from 2021-02-12 14-27-16](https://user-images.githubusercontent.com/16133208/107773783-71d33880-6d3e-11eb-9e13-4ae95e085f75.png)
The last mail document (id: 12) is used as mail in both actions as visible from the database:
![Screenshot from 2021-02-12 14-23-38](https://user-images.githubusercontent.com/16133208/107773787-739cfc00-6d3e-11eb-8d9c-6a4296016662.png)

Reproduced on [latest demo](http://demo2.coreshop.org/)

**Comment by dpfaffenbauer** [comment]
guess that is fixed with #1657
