### ISSUE TITLE
GridConfig (Order Overview) with dataType href is invalid

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1570]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

![image](https://user-images.githubusercontent.com/700119/105638851-5da1c700-5e75-11eb-8fff-5ee53f8ba4b5.png)

Guess `href` is not supported anymore (since pimcore 6.8?) and needs to be replaced by `relation`.

**Comment by solverat** [comment]
FYI: Field "email", "firstname", "lastname" with relation customer needs to be reassigned.

**Comment by dpfaffenbauer** [comment]
https://github.com/coreshop/CoreShop/pull/1576
