### ISSUE TITLE
__CG__CoreShopComponentAddressModelZone.php: failed to open stream: Operation not permitted

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1571]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

This pops up randomly on my local installation.

**Comment by dpfaffenbauer** [comment]
I did not get it anymore after this https://github.com/coreshop/CoreShop/pull/1580
