### ISSUE TITLE
optimistic-entity-lock-bundle getComposerPackageName should return Package name not version

### ISSUE THREAD

**Issue by brainsbucket** [coreshop/CoreShop#1572]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi,
On the coreshop/optimistic-entity-lock-bundle V2.2.8, the getComposerPackageName function should return the package name, not the version.

Because of this you cannot access to the extension manager of pimcore (V6.8.7), it open a panel with this message : 
```
Package "2.2.8.0" is not installed

Server threw exception - could not perform action. Please reload the admin interface and try again
```

Thanks

**Comment by solverat** [comment]
Done with #1577.
