### ISSUE TITLE
Watch unique customer login identifier on backend changes

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1584]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

While creating customers in frontend passes a uniqueness listener based on `coreshop.customer.security.login_identifier` (email OR username), it is possible to create ambiguous customer objects in backend. 
This could lead (in our case it already did) to very dangerous workflows. 

- Add pre_update listener
- check for unique values, based on  `coreshop.customer.security.login_identifier`

**Comment by dpfaffenbauer** [comment]
we have that already: https://github.com/coreshop/CoreShop/blob/2.2/src/CoreShop/Bundle/CoreBundle/EventListener/CustomerSecurityValidationListener.php#L69

**Comment by solverat** [comment]
I see. However, it's not working (anymore) because of this line:

https://github.com/coreshop/CoreShop/blob/a6de3d7e353c479dfc9c1c561f4ae479534a01f6/src/CoreShop/Bundle/CoreBundle/EventListener/CustomerSecurityValidationListener.php#L69-L70

BTW the copyright header looks wrong.

**Comment by dpfaffenbauer** [comment]
that is resolved in 3.x with the user being extracted into a separate entity.
