### ISSUE TITLE
Payment Description should be translatable / changeable

### ISSUE THREAD

**Issue by danielerne** [coreshop/CoreShop#1598]
The line 'Payment contains %s item(s) for a total of %s.' should be translatable.

https://github.com/coreshop/CoreShop/blob/1c77e76c7ad536db29bf5ddeb6d053a68d1b426e/src/CoreShop/Component/Order/Payment/OrderPaymentProvider.php#L66

**Comment by solverat** [comment]
Just for the record: This change introduces corrupt hash signatures in other languages (like DE which contains "Einträge" now) of some payment providers (PostFinance for example). My fast fix was to change all translations back to the english one.
