### ISSUE TITLE
Please update readme.md of ThemeBundle

### ISSUE THREAD

**Issue by manh-trinhquoc** [coreshop/CoreShop#1607]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The current link to the document of ThemeBundle is 404. Please update!
https://docs.coreshop.org/2.1.0/Bundles/Theme_Bundle.html

**Comment by dpfaffenbauer** [comment]
there is no docs for that yet.
