### ISSUE TITLE
[3.0] invalid entities

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#1624]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes/no
| RFC?             | yes/no

system: docker apache php 8.0.5 / pimcore x and coreshop dev-master up-to-date

on startup:
![image](https://user-images.githubusercontent.com/2986829/117288790-2b3c3880-ae6c-11eb-97e5-57075c4b208a.png)

**Comment by dpfaffenbauer** [comment]
fixed
