### ISSUE TITLE
Error with incorrect tag {{region_short}} in address format

### ISSUE THREAD

**Issue by bitfactory-timon-vandermeulen** [coreshop/CoreShop#1634]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The countries in Coreshop contain a default address format. For some countries (like Italy, Ireland, Portugal and Ukraine) this address format contains a wrong tag "{{region_short}}". This field is not in the default address class. This causes an error on any page that shows the address in the corshop address format ("coreshop_format_address").

I have replaced it with "%Text(region_short);" which fixes the issue for now but i think this should be removed or replaced by another value.

Example (Italy):
```
%Text(company);
%Text(salutation); %Text(firstname); %Text(lastname);
%Text(street); %Text(number);
%Text(postcode); %Text(city); {{region_short}}
%DataObject(country,{"method" : "getName"}); %Text(phone);
```

**Comment by dpfaffenbauer** [comment]
fixed. but only works for new installs.
