### ISSUE TITLE
[3.0] shipping rules cannot be created

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#1639]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no

system: docker apache php 8.0.5 / pimcore x and coreshop dev-master up-to-date

reproducible:
Try to click in coreshop menu -> shipping -> shipping rules -> add -> enter a name and click on save

**Comment by dpfaffenbauer** [comment]
fixed with #1641
