### ISSUE TITLE
Improvement: assign products to category from the category object

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#164]
It would be a great enhancement to be able to assign products to category directly from the category object.

Actually, we need to open each product to assign it to a category. It is convenient for product by product management. But for some other use cases, it could be more convenient to assign them directly from the category object. For instance if adding a new category, products can be directly assigned to it without having to open each product one by one.

To handle this maybe the Pimcore "non owner" field type could be used.

**Comment by dpfaffenbauer** [comment]
FYI: I will wait for Pimcore 5 before doing any changes.

**Comment by Yivan** [comment]
Do you mean the final Pimcore 5 release, so several month without any added feature ?
Will bug fix be made during this period ?

Thanks

**Comment by dpfaffenbauer** [comment]
As soon as the first alpha is here, I am going to port CoreShop and after that, I am going to address your Issue. Can't tell yet if I am going to make this change backward compatible. Propaply not.

**Comment by Yivan** [comment]
Thanks!
Alpha is here (great!), and ecommerce framework extension is included (great too!). Do you think you will use this ecommerce framework for CoreShop on Pimcore 5 or CoreShop will stay a totally independant alternative not relying on it ?

**Comment by dpfaffenbauer** [comment]
see #90a0dca73a60ff89c20aac9621bf60da0e4f58f2

I used a non-owner field, simply grab the new export file, import it and you are got to go.

PS: Thanks for the hint with non-owner field, works awesome :)

**Comment by Yivan** [comment]
Thanks a lot for this change! It make product assignement more flexible.
