### ISSUE TITLE
Typo in classname - SelectFilterConditionFromMulitselectProcessor

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1642]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

name of class ha s a small typo: 
SelectFilterConditionFrom**Mulit**selectProcessor 
instead of 
SelectFilterConditionFrom**Multi**selectProcessor

path to class:
CoreShop/Component/Index/Filter/SelectFilterConditionFromMulitselectProcessor.php

**Comment by dpfaffenbauer** [comment]
fix: https://github.com/coreshop/CoreShop/pull/1655
