### ISSUE TITLE
DeepCopy subscriber causing huge redis consumption

### ISSUE THREAD

**Issue by kkarkus** [coreshop/CoreShop#1644]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Cache entries because of PR below can be more than 1MB size (in our case it's almost 4MB for a product), it stores all the DoctrineCollections serialized, and so on
https://github.com/coreshop/CoreShop/pull/1534/files

**Comment by dpfaffenbauer** [comment]
any ideas on how to solve it? Unfortunately this is how Pimcore works...

**Comment by kkarkus** [comment]
Nope :disappointed: 
I know this is how Pimcore works, but let's say we have 260k products, let's do a math 4MB * 260k = too much needed ram
For now, we had to set null filter for DoctrineCollections, it seems everything works for us but we don't use e.g. order details on the frontend

**Comment by dpfaffenbauer** [comment]
> For now, we had to set null filter for DoctrineCollections

How exactly did you do that?

**Comment by dpfaffenbauer** [comment]
ping @kkarkus
