### ISSUE TITLE
Unique ID for Quantity Type

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1647]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

QuantityType should generate unique ids:

https://demo2.coreshop.org/en/shop

![image](https://user-images.githubusercontent.com/700119/120638182-1b664300-c470-11eb-84ff-169be250716e.png)

**Comment by dpfaffenbauer** [comment]
why`

**Comment by solverat** [comment]
Because it's against w3 standards:

![image](https://user-images.githubusercontent.com/700119/120783742-9e989f00-c52b-11eb-86e8-dbe2fc8a2ed2.png)

**Comment by solverat** [comment]
Which also gets recognized as a violation in chrome btw:
![image](https://user-images.githubusercontent.com/700119/120786129-2bdcf300-c52e-11eb-8782-8fd1b1868f3f.png)

**Comment by dpfaffenbauer** [comment]
interesting, doesn't symfony form already handle that? Why doesn't it here?

**Comment by dpfaffenbauer** [comment]
ah, just understood: that happens on the overview page where multiple add-to-cart buttons appear

**Comment by dpfaffenbauer** [comment]
that solves it https://github.com/coreshop/CoreShop/pull/1648
