### ISSUE TITLE
Product specific prices bug

### ISSUE THREAD

**Issue by JulienHenchoz** [coreshop/CoreShop#166]
Hi,
If found an issue while editing a product, in the "Specific price" tab. Here are the steps to reproduce it. I'm running on CoreShop 1.2.2 with Pimcore 4.4.3.

- Create a product
- Create a specific price for this product (in my case : shop condition + discountPercent action)
- Save the product
- Reload the product form 
- Here's what the specific price looks like : 
![veloland2-pimcore_cobweb_red____pimcore](https://cloud.githubusercontent.com/assets/888157/25961966/5bbe01da-367c-11e7-95f2-f2c1b564c2e7.jpg)
- And the actions tab : 
![veloland2-pimcore_cobweb_red____pimcore](https://cloud.githubusercontent.com/assets/888157/25961986/699935b8-367c-11e7-879a-f8ada9b71485.jpg)

By comparing with the "Specific price" "Price rules" codes, I tracked the issue down to /plugins/CoreShop/lib/CoreShop/Model/Product/SpecificPrice.php. The data that are returned here are not properly serialized, and are missing the "type" field, which prevents the saved actions and conditions from being displayed properly.
The fix I found was to add this piece of code right after the $list->getData() call  : 

```
$objects = $list->getData();
foreach ($objects as &$object) {
     if ($object instanceof SpecificPrice) {
         $object = $object->serialize();
   }
}

```

Are you able to reproduce this bug ? I did not have the occasion to try it on a fresh Pimcore installation.

Thank you !

**Comment by dpfaffenbauer** [comment]
Hi,

I am able to reproduce it. I am quite unsure why this didn't happen earlier. Your solution works, but it's not the right place for it. It should be int Pimcore\Model\Object\ClassDefinition\Data\CoreShopSpecificPrices::getDataForEditmode.

I'll prepare a fix for it, but need to check why this didn't happen earlier.

regards
dominik

**Comment by JulienHenchoz** [comment]
Thank you for your quick reply ! I am quite confused too, because I'm pretty sure I saw it working earlier.

I found a side effect to my fix though, it prevents the product from being saved again after the specific price has been added.
The ajax call returns  :
`Uncaught Error: Call to a member function getId() on array in /home/clients/b510fe4c762b134bbad68c5fc29dd813/veloland/vh_pimcore/plugins/CoreShop/lib/Pimcore/Model/Object/ClassDefinition/Data/CoreShopSpecificPrices.php:126` 

But maybe it's because it's placed in the wrong file as you said !

**Comment by dpfaffenbauer** [comment]
Well, I know why it is happening, I just don't know how this worked before o.O

Cheers for your report, it is fixed and working now.

**Comment by JulienHenchoz** [comment]
I found a bug that might be a side effect of the fix for this issue : 
Calling "getValidSpecificPriceRules" on a product that has a product specific price throws a fatal error  : 
`Call to a member function getConditions() on array on /plugins/CoreShop/lib/CoreShop/Model/Product.php at line 309 `

The error happens on the second call to getSpecificPrices (on line 303 of /plugins/CoreShop/lib/CoreShop/Model/Product.php), which returns an array or arrays.
The first call to getSpecificPrices returns a correct array of SpecificPrices/PriceRules objects.

Since it crashes only on the second call, I feel like the problem comes when getting data from cache ?

**Comment by dpfaffenbauer** [comment]
You are working on dev master? I did some more changes yesterday.

**Comment by JulienHenchoz** [comment]
I applied the 3 commits you did yesterday.

**Comment by dpfaffenbauer** [comment]
ok, I will take a look at it.

**Comment by dpfaffenbauer** [comment]
Could not reproduce your problem. Did you forget to remove your suggested solution? Seems this affects your problem.

**Comment by JulienHenchoz** [comment]
You are absolutely right. Sorry for the bother!
