### ISSUE TITLE
Unable to install coreshop

### ISSUE THREAD

**Issue by manjunathkg** [coreshop/CoreShop#167]
Hi,

Installed PimCore and tested. Its simply too good. Thanks for making it open source!
But I'm now trying to install coreshop. But I'm not able to see the shop application in the admin screen. Here is the issue.

1) I downloaded and installed the coreshop plugin by using admin extension manager. plugin shows green activated button. I have also copied website-example files to website folder. Even after refresh after plugin install I don't see shop application in the menu. Also no error in the admin screen. (plugin version 1.2.2 and pimcore version 4.4.3)

2) I tried a little bit of troubleshooting. I see that in the startup.js (static/js/startup.js) there is an ajax call to /plugin/CoreShop/admin_settings/get-settings   I don't see any folder called "admin_settings" under CoreShop. Is this why admin screen is not showing shop menu? I see rest of the admin screen setup depends on ajax call success. 

Can you pls help me to troubleshoot? I would love to install and checkout coreshop. Looks awesome in the demo.

Regards,
M

**Comment by dpfaffenbauer** [comment]
2. no, that's not the issue. It is a route, which will end up in CoreShop/Controller/Admin/Settings.php.

Could you please check the log file for issues?

**Comment by dpfaffenbauer** [comment]
case will be closed due to inactivity. If you still have this issue, you can re-open this case or issue a new one.
