### ISSUE TITLE
Add CoreShopCustomerGroups to available conditions

### ISSUE THREAD

**Issue by JulienHenchoz** [coreshop/CoreShop#168]
It would be nice to be able to set customer groups as conditions for cart rules, price rules, personas, etc.
What do you think ?

**Comment by dpfaffenbauer** [comment]
They do exist for Cart Price Rules and Specific Price Rules:

![bildschirmfoto 2017-05-16 um 10 59 21](https://cloud.githubusercontent.com/assets/5981845/26098067/dadc958c-3a26-11e7-84b9-40f2280c1ea7.png)
![bildschirmfoto 2017-05-16 um 10 59 59](https://cloud.githubusercontent.com/assets/5981845/26098068/dae5490c-3a26-11e7-942f-f89e44af3760.png)

What do you mean exactly?

**Comment by JulienHenchoz** [comment]
Ah indeed, I generalized a bit too fast, sorry!
I was looking at the Product Specific Price when I noticed they weren't there. Is it on purpose ?
The use case I see would be : a client in the VIP group should have 10% off on all the products in the shop, and the reduction should be able to show in the products list and detail, not only in the cart view.

I also think it would be interesting to be able to include them into the Personas conditions.

![veloland2-pimcore_cobweb_red____pimcore](https://cloud.githubusercontent.com/assets/888157/26098501/37c07614-3a28-11e7-80ee-69206387433f.jpg)

**Comment by dpfaffenbauer** [comment]
Should be fairly easy to add them to Product Price Rules, but I am not sure about Personas. Would make sense though, I will have a look at it.

**Comment by dpfaffenbauer** [comment]
Customer Group for Product Price Rules is added. I am not gonna implement Customer Group for Personas, cause I see a lot of issues that could happen here. Personas are not really made to be extend, I mean, they can, but as said, I can smell problems here.

Pimcore already said they're gonna refactor personas. So I'll just wait until its done and add this to my list of features for CoreShop2.

**Comment by dpfaffenbauer** [comment]
PS: It still is possible to make this yourself. There would be no need to extend CoreShop.
