### ISSUE TITLE
Wrong user permissions for permission_coreshop_permission_tax_rate

### ISSUE THREAD

**Issue by breakone** [coreshop/CoreShop#1680]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Setting the permission for tax_rates in backend `"permission_coreshop_permission_tax_rate":true` has no effect, because in `MainMenuBuilder` the permissions attribute for tax_rates is different:

![image](https://user-images.githubusercontent.com/4848121/125751772-b9841bf3-f6d4-43f6-9bf7-cceb1b5efba8.png)

![image](https://user-images.githubusercontent.com/4848121/125751250-adfc4b96-614b-472e-9951-58b77b2abffe.png)

**Comment by dpfaffenbauer** [comment]
fixed
