### ISSUE TITLE
[3.0][SEO - ImageExtractor] Thumbnail definition "seo" does not exist

### ISSUE THREAD

**Issue by ramundomario** [coreshop/CoreShop#1682]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

![Screenshot from 2021-07-17 19-40-59](https://user-images.githubusercontent.com/16133208/126045487-dd3733a8-f0d4-44df-93ad-bf0fe57f289e.png)

**Comment by ramundomario** [comment]
@dpfaffenbauer We should add the thumbnail in https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/image-thumbnails.yml, WDYT?

**Comment by dpfaffenbauer** [comment]
We should rename it to `coreshop_seo` and add it to 2.2 branch as well.

**Comment by ramundomario** [comment]
I was thinking exactly the same thing.  
how do we make the thumbnail?  
I could provide a PR

**Comment by dpfaffenbauer** [comment]
> I was thinking exactly the same thing.
> how do we make the thumbnail?

Add it here: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/image-thumbnails.yml

> I could provide a PR

Please :)

**Comment by ramundomario** [comment]
> > I was thinking exactly the same thing.
> > how do we make the thumbnail?
> 
> Add it here: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/image-thumbnails.yml
> 
Yes 😄 I meant the thumbail spec, there are a lot of opinions about it

**Comment by dpfaffenbauer** [comment]
That is use case dependent. Try to use something similar to what we have with product detail and overview images.

**Comment by dpfaffenbauer** [comment]
thanks @ramundomario
