### ISSUE TITLE
[Shipping] Ability to hide carrier from checkout

### ISSUE THREAD

**Issue by ramundomario** [coreshop/CoreShop#1690]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

**Use case:** A store could have multiple carries and ships with different carriers depending on external factors
**Possibile solution:** There is only one carrier (Standard) visible to the user (in checkout).
When the shipment is made, the store manager will choose the choosed carrier in order to communicate its information (such as tracking links).
We could add a checkbox in Carriers configuration to hide carrier in checkout.
![Screenshot from 2021-07-20 00-28-01](https://user-images.githubusercontent.com/16133208/126235469-06f59a38-78a9-4738-89eb-ec9c7cde5cb8.png)

WDYT?

**Comment by dpfaffenbauer** [comment]
I guess it does make sense
