### ISSUE TITLE
CustomerAndStoreBasedCartContext does not respect RememberMe Dispatch

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1699]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             | no

Because of this:
https://github.com/coreshop/CoreShop/blob/002f9cf782c9d647174a38bac638b37a9eae1db8/src/CoreShop/Bundle/OrderBundle/Context/CustomerAndStoreBasedCartContext.php#L49-L50

...which has been introduced in https://github.com/coreshop/CoreShop/pull/340.

⚠️ **This route check is still valid and cannot be changed otherwise issues like described in #340 will reoccur.** 

***

Also: There should **not**  be an exact result check  in `findLatestByStoreAndCustomer` => `count($objects) >= 1` should be enough. Otherwise, the cart blamer will never find a cart again if two or more are available:

https://github.com/coreshop/CoreShop/blob/002f9cf782c9d647174a38bac638b37a9eae1db8/src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/CartRepository.php#L65-L66

***

## Reproduction
- Login and hit "remember me"
- Add some products to cart
- Close Browser (Completely)
- Reopen Browser, open Store
- Cart is empty

## Issue
A lot of new persisted carts and weird user experiences (Empty cart after re-visiting store).

## Solution
Not easy. I had to do a quick fix by setting a request attribute in `CartBlamerListener::onInteractiveLogin()`:

```php
$force = $interactiveLoginEvent->getAuthenticationToken() instanceof RememberMeToken;
$interactiveLoginEvent->getRequest()->attributes->set('coreshop.force_cart_blame', $force);
```

Then I added a custom CartContext which will dispatch the `$this->cartRepository->findLatestByStoreAndCustomer($store, $customer);` if this attribute is available in the request.
Since we cannot pass any parameters via `cartContext->getCart()` this seems to be the only solution by now.

**Comment by dpfaffenbauer** [comment]
What was the use case https://github.com/coreshop/CoreShop/pull/340 again? How does a user come back to the Site and is still in the Order process without actually coming back to the revise page?

**Comment by solverat** [comment]
- add items as guest
- log in ⇒ guest cart will be attached to the user (1)
- log off
- add items as guest
- log in ⇒ guest cart will be attached to the user (2)
- checkout and complete purchase
- cart (1) gets attached

That's why it should stay that way.

**Comment by dpfaffenbauer** [comment]
@benwalch absolutely, you mind creating a PR for that?
