### ISSUE TITLE
getProductName returns null for variant with no name, even if parent has a name

### ISSUE THREAD

**Issue by JulienHenchoz** [coreshop/CoreShop#170]
This happens for : 

1. OrderItem
2. ShipmentItem
3. InvoiceItem

When calling "getProductName", I think we should fetch the parent's name if the variant name is empty, since it's supposed to be inherited.

The current behaviour has a consequences for example in the Order screen in backend (see screenshot), and in the order confirmation e-mail : the product name does not appear in the "Product" column.

![veloland2-pimcore_cobweb_red____pimcore](https://cloud.githubusercontent.com/assets/888157/26100534/70f4e306-3a2e-11e7-915d-45a31bc77591.jpg)

**Comment by dpfaffenbauer** [comment]
fixed
