### ISSUE TITLE
Unable to pass Parameters to LinkGenerator

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1700]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If you want to pass some additional query parameters via route generator, these parameters will be ignored:

```twig
{{ coreshop_path(product, 'coreshop_product_detail', { myQueryParam: queryValue } ) }}
```

That's because the `DataObjectLinkGenerator` does not pass /merge existing values from`$params` here:

https://github.com/coreshop/CoreShop/blob/002f9cf782c9d647174a38bac638b37a9eae1db8/src/CoreShop/Bundle/CoreBundle/Pimcore/LinkGenerator/DataObjectLinkGenerator.php#L49-L54

**Comment by dpfaffenbauer** [comment]
Yes, I don't see that as a bug or issue. The 'default' LinkGenerator is for super simple use-cases. If we pass all params to the UrlGenerator, we might end up having a lot of different issues. I like for example pass very often to the Pimcore Link Generator the Site/SiteId it should generate the link for, but if you pass that to the Symfony URL Generator, you would get something like `?siteId=1`.

So, no bug, you have to implement a custom link generator for more advanced use cases.
