### ISSUE TITLE
Can't open customer groups in backend

### ISSUE THREAD

**Issue by jure-knezovic** [coreshop/CoreShop#1709]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Trying to open customer groups in pimcore backend returns following error in console:

```
Error: The route "/admin/coreshop/customer_groups/folder-configuration" does not exist.
```

Error present also on https://demox.coreshop.org/, so it seems to be not something bad on my side.

**Comment by dpfaffenbauer** [comment]
https://github.com/coreshop/CoreShop/pull/1710

**Comment by dpfaffenbauer** [comment]
fixed
