### ISSUE TITLE
Country names translations

### ISSUE THREAD

**Issue by JulienHenchoz** [coreshop/CoreShop#171]
Is it possible to translate the country names ?
Currently all the names are in English, which would look a bit odd for the user in frontend when browsing the site in French or German for example. I couldn't find a way to translate those for now.

This could also potentially apply to states.

**Comment by dpfaffenbauer** [comment]
Yes, I can see the use of this. But I probably not gonna implement this in CoreShop1, since it would need migrations scripts as well. But I am going to implement this for CoreShop 2.

You can use Shared Translations instead.
