### ISSUE TITLE
[DOC] Tax Rates based on Shipping Address

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1714]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Since [1st of july 2021 all eshops within the EU](https://ec.europa.eu/taxation_customs/modernising-vat-cross-border-e-commerce_en) need to calculate tax rates based on shipping address. 

There should be a documentation how to change that (like Sylius does it [here](https://docs.sylius.com/en/1.10/cookbook/taxation/customize-tax-by-address.html).

**Comment by dpfaffenbauer** [comment]
we use the shipping address since forever....

**Comment by solverat** [comment]
True. But there seems to be an issue then (that's why i thought it's not the default behavior):

- enable AT end DE in countries
- allow all countries in default store
- create two tax rules:
  - AT (Country: Austria, State: All, Tax Rate: "AT" 20%)
  - DE (Country: Germany, State: All, Tax Rate: "DE" 19%)
- create a product with tax rule "AT"
- go to frontend:
  - add product to cart
  - create user with address with country "DE" and another address with country "AT"
  - go to checkout step "addresses" and select address with country "DE"
  - go to cart or summary:
    - taxes: `0,-` (empty amount)
  - go back to addresses and select address with country "AT"
  - go to cart or summary:
    - taxes: `xy,-` (right amount)

However, if you change the tax rule for the given product to "DE", the tax amount will show up correctly.

**Comment by dpfaffenbauer** [comment]
We currently calculate the shipping costs based on the shipping country, shipping tax is calculated based on the tax-rule defined in the carrier. so if you have a tax-rate configured there for DE19%, it should use that.

You would have to create 2 tax-rules: AT20% for the tax of the goods and one for Shipping. Where the Shipping one has Country AT with 20% and DE with 19%.

**Comment by solverat** [comment]
I'm not talking about shipping costs. The complete cart/order tax calculation needs to be done based on the country, defined in shipping address. Just check out my example above, it's a quick way to get the issue here.

**Comment by dpfaffenbauer** [comment]
works too if you configure it correct. checkout demo2.coreshop.org, I just configured it

**Comment by dpfaffenbauer** [comment]
TaxRule does not mean one per country, tax-rule should be more like different tax-rates per product category. like we have here in austria (20% and 10%)

**Comment by solverat** [comment]
This is what @dpfaffenbauer meant: 
![image](https://user-images.githubusercontent.com/700119/129730743-c7185c6e-1ece-4638-ad38-5e5fb4bbf9aa.png)

***

Perfect! Thank you. Just for the record, in case someone is also looking for a hint:

### Create a Tax Rule, call it "Europe" and add all required countries you want to provide:
![image](https://user-images.githubusercontent.com/700119/129731205-22da6e6d-5710-4348-a709-a8e363c9f34f.png)

### Apply this tax rule in your product
![image](https://user-images.githubusercontent.com/700119/129731285-f7f6cfec-a782-432f-9811-cd957ee8ee8a.png)
