### ISSUE TITLE
CartPriceRule causes error in registration

### ISSUE THREAD

**Issue by Theux94** [coreshop/CoreShop#1718]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I created an active cart price rule with no conditions and free gift item Action. This causes an error after submitting a valid registration formular: root-node cannot be deleted (DataObject| Folder->delete(true)).

The applyRule function of the GiftProductActionProcessor is being called two times because of the CartBlameListener.
https://github.com/coreshop/CoreShop/blob/58d29030b24bdf225625764e010fc371553814e8/src/CoreShop/Bundle/CoreBundle/EventListener/CartBlamerListener.php#L82-L90

https://github.com/coreshop/CoreShop/blob/58d29030b24bdf225625764e010fc371553814e8/src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php#L119-L123

First time the free gift item is being added, second time the removeCartItem method is called and tries to delete the non persisted cartItem (ID 0). 

Error occurs for all cart price rules that apply (If all conditions set are valid). For example current date is in range of time span condition.

**Possible Fix:**
Only delete if CartItem has ID.

**Comment by dpfaffenbauer** [comment]
@Theux94 I just tried to replicate that on CoreShop 3.0-dev, and it worked for me. Can you describe the exact steps?

**Comment by lukadschaak** [comment]
I can reproduce the error on CoreShop 3.0-dev with demo locally. I installed demo to have registration form ui.

Steps:
- Install Coreshop 3.0-dev with demo
- Create Cart price rule
- Set active: true
- Set voucher rule: false
- Leave conditions empty (always  matching rule)
- Add the action gift product
- Use any product from the demo products for the action
- Go to /de/shop/register, fill out the form and send it.
- Results in error "root-node cannot be deleted"

Mention also: I tried to recreate the error in the demo2.coreshop.org. Same steps as explained, but no error occured.
Pimcore X Demo is not working at the moment.

**Comment by dpfaffenbauer** [comment]
this fixes it: https://github.com/coreshop/CoreShop/issues/1718

**Comment by lukadschaak** [comment]
Nice, smooth and clean. Thank you :+1:
