### ISSUE TITLE
Error when Superbox Select field is not editable

### ISSUE THREAD

**Issue by alexloetscher95** [coreshop/CoreShop#1723]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Coreshop 2 (not tested in version 3), Pimcore 6.9
"Superbox Select" fields which are configured as "Not editable" generate an error and breaks the pimcore admin.

Javascript error: 
```console
Uncaught TypeError: Cannot read properties of undefined (reading 'data')
```
in the file /bundles/pimcoreadmin/js/pimcore/object/tags/manyToManyRelation.js ([pimcore git link](https://github.com/pimcore/pimcore/blob/9a33afacc268d9779bf6419639e8c208355e50c0/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js#L420)) in the getLayoutShow function (enableTextSelection listener) at line 420.

Somehow the store isn't available at the moment when the refresh listener is called.
Interestingly when the field is editable, this refresh listener is never called (but I'm honestly a little overwhelmed and do not see the connections yet, Sorry!).

All the other dynamic select types are working fine.

Also tested on demo2.coreshop.org.

**Comment by dpfaffenbauer** [comment]
fixed
