### ISSUE TITLE
Price Rules: Taking Adjustments into Account

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1729]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I want to share some thoughts about this since this is a difficult one for sure.
We developed some huge ecommerce platforms with coreshop in the last months, and everytime we struggled with a conceptional problem: Price rule conditions are not able to determinate adjustment states.

This is obvious and understandable in a technical point of view. All adjustments are getting cleared before cart recalculation, therefor no other prices than product prices are available when it comes to price rule calculation. 

Let me provide some examples:

### Example A
- Cart Rule: `Free Shipping if total >= 100,-`  
- Add `Product A (100,-)` to cart
- Apply `Voucher A (50%)`

Currently, the `free shipping` rule gets applied, because total still returns `100,-` at time of rule calculation. In our case, the ecommerce managers wanted to apply free shipping only if subtotal incl voucher subtraction is `>= 100,-`.

***

### Example B
- Custom Adjustment: `Additional surcharge if special condition selected: += 20,-`
- Add `Product A (100,-)` to cart
- Apply `Voucher A (50%)`

Currently, the `Voucher A 50%` gets applied on `100.-`, so the new total would be `50,-` which is more "obvious wrong" than the example above.  In this case, the total should be `60,-`.
 
***

To deliver solutions at the fast lane, we integrated some "cart" checkups in our custom price rules and incremented the total value "manually", which is more than hacky and still feels terrible wrong.

I'm not sure, but a maybe a "temporary price rule stack" should be available at runtime, so we don't lose all the previous calculation information. Working with prioritized rules could be part of a solution too.

**Comment by dpfaffenbauer** [comment]
is this just a priority problem?

**Comment by dpfaffenbauer** [comment]
ping @solverat

**Comment by solverat** [comment]
@dpfaffenbauer: Nope. Just tested it: Switching prio of `CartRuleAutoProcessor` and `CartAdjustmentClearer` would pass the right values to the rule processor. But then, the freshly created rules get wiped out via CartAdjustmentClearer.
