### ISSUE TITLE
Issue with coreshopv3.0

### ISSUE THREAD

**Issue by i2cute** [coreshop/CoreShop#1734]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Having some issue with coreshop v3.0.0-alpha but working fine with coreshop v2.2.9
- Page broken after edit Settings
- Additional Unit Definitions not working. Product tabs turn into blank and not editable after enable it
- Paginator having TypeError
	Knp\Component\Pager\Paginator::paginate(): Argument #2 ($page) must be of type int, string given, called in /opt/pimcoreX/vendor/coreshop/core-shop/src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php on line 168
- Shop log in page having RuntimeException
	You must configure the check path to be handled by the firewall.
- Bundles & Bricks having error after enable coreshop.
	Attempted to call an undefined method named "fetch" of class "Symfony\Component\Console\Output\NullOutput".
	Server threw exception - could not perform action. Please reload the admin interface and try again.
- Product Information Definition data object having error: 
	CoreShop\Bundle\ProductBundle\Doctrine\ORM\ProductUnitDefinitionsRepository::findOneForProduct(): Argument #1 ($product) must be of type CoreShop\Component\Product\Model\ProductInterface, Pimcore\Model\DataObject\ProductTest given, called in /opt/pimcoreX/vendor/coreshop/core-shop/src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php on line 274

	Server threw exception - could not perform action. Please reload the admin interface and try again.

- Store Values data object having error: 
	CoreShop\Bundle\CoreBundle\Doctrine\ORM\ProductStoreValuesRepository::findForProduct(): Argument #1 ($product) must be of type CoreShop\Component\Core\Model\ProductInterface, Pimcore\Model\DataObject\ProductTest given, called in /opt/pimcoreX/vendor/coreshop/core-shop/src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php on line 332

	Server threw exception - could not perform action. Please reload the admin interface and try again.

**Comment by dpfaffenbauer** [comment]
> Additional Unit Definitions not working. Product tabs turn into blank and not editable after enable it

fixed with https://github.com/coreshop/CoreShop/pull/1737

> Paginator having TypeError
> Knp\Component\Pager\Paginator::paginate(): Argument Updatability #2 ($page) must be of type int, string given, called in /opt/pimcoreX/vendor/coreshop/core-shop/src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php on line 168

fixed with https://github.com/coreshop/CoreShop/pull/1737

> Shop log in page having RuntimeException
> You must configure the check path to be handled by the firewall.

Cannot be reproduced.

> Bundles & Bricks having error after enable coreshop.
> Attempted to call an undefined method named "fetch" of class "Symfony\Component\Console\Output\NullOutput".
> Server threw exception - could not perform action. Please reload the admin interface and try again.

Cannot be reproduced.

> Product Information Definition data object having error:
> CoreShop\Bundle\ProductBundle\Doctrine\ORM\ProductUnitDefinitionsRepository::findOneForProduct(): Argument Documentation #1 ($product) must be of type CoreShop\Component\Product\Model\ProductInterface, Pimcore\Model\DataObject\ProductTest given, called in /opt/pimcoreX/vendor/coreshop/core-shop/src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductUnitDefinitions.php on line 274
> Server threw exception - could not perform action. Please reload the admin interface and try again.

Error on your side, make sure that "ProductTest" actually implements `ProductInterface`

> Store Values data object having error:
> CoreShop\Bundle\CoreBundle\Doctrine\ORM\ProductStoreValuesRepository::findForProduct(): Argument Documentation #1 > ($product) must be of type CoreShop\Component\Core\Model\ProductInterface, Pimcore\Model\DataObject\ProductTest given, called in /opt/pimcoreX/vendor/coreshop/core-shop/src/CoreShop/Bundle/CoreBundle/CoreExtension/StoreValues.php on line 332
> Server threw exception - could not perform action. Please reload the admin interface and try again.

Error on your side, make sure that "ProductTest" actually implements `ProductInterface`
