### ISSUE TITLE
Add a FilterableInterface

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#1735]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Currently `CoreShop\Component\Core\Model\CategoryInterface` has `getFilter()`, but there's nothing intrinsic about a category having a filter. In my use case, I'd like to attach a filter to brands, product series and other custom objects which are similar to categories in nature (a collection of products), but different.

This would also mean I'd be able to use my custom (Elasticsearch based) filtering on custom objects which are filterable.

**Comment by dpfaffenbauer** [comment]
Filtering and Processing the Filters done in the Controller is quite heavy as well, maybe we can introduce a FilterableInterface and some sort of Service processing that returning a Pageable Listing?

**Comment by dkarlovi** [comment]
Yes, that's exactly what I'm currently doing in my own project. :)

**Comment by dpfaffenbauer** [comment]
@dkarlovi Any progress in your Project? Maybe something we can re-use here?

**Comment by dpfaffenbauer** [comment]
I'll close this for now since if you need that, you can always do it custom in a project.
