### ISSUE TITLE
Coreshop 3-0 - dev-master - unknown 'coreshop_path' function

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1736]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Coreshop 3.0 - dev-master

After update to newest dev-master version with installed demo

When calling forntend -main-page: [url]/en/shop
```
Unknown "coreshop_path" function.
```

![image](https://user-images.githubusercontent.com/23456403/135853807-ce0a27ae-a756-4de6-a54c-8cf7a41ed587.png)

**Comment by dpfaffenbauer** [comment]
yes, it got removed. a new one was introduced called `pimcore_object_path`
