### ISSUE TITLE
Checkout :: addresss :: Add new billing/shipping address not working

### ISSUE THREAD

**Issue by ivicafactory** [coreshop/CoreShop#1746]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

On checkout, as a logged-in user, I want to add a new billing address. The expected result is that I can enter that address and what happens is that I get redirected to the homepage. The same issue is with the shipping address.

Video: https://watch.screencastify.com/v/Q3qnkXSgyd1G3UYYLTKS

**Comment by dpfaffenbauer** [comment]
Interesting, it doesn't appear that you are logged in. Is it possible you used guest checkout?

**Comment by dpfaffenbauer** [comment]
does it still happen for you @ivicafactory ?

**Comment by valentin-** [comment]
@dpfaffenbauer when adding a new address from the checkout or in the customer address settings as logged in user, I get an error as well.

In my case `$address->getParent()` is null and therefore throws an error on `getId()`

https://github.com/coreshop/CoreShop/blob/94c133f65a704a8486e9bb1cd9687f852028e937/src/CoreShop/Component/Core/Customer/CustomerTransformHelper.php#L129

**Comment by m0nken** [comment]
I also ran into this. As this occurred when I tried adding a new address, I would think the problem lies within `$this->isNewEntity($address)` which should return true for a newly added address and therefore the second part `$address->getParent()->getId() !== $newParent->getId()` should not be called at all in this case.

**Comment by m0nken** [comment]
Nevermind. I just saw that this has already been addressed [here](https://github.com/coreshop/CoreShop/commit/de54b6069c416edda5784fa384a6a020d9eed936).
