### ISSUE TITLE
Cart Price Rules: Filterable Action Dispatcher

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1752]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

In some cases, the ecommerce manager wants to apply rule actions on specific cart items only. Examples:

## Example I
- Voucher rule exists (`-50%`)
- => Only apply action (`-50%`) on cart items without reduced prices (without applied specific price rules)

## Example II
- Cart rule exists (`-50% if cart > 1.000,-`
- => Only apply action (`-50%`) on cart items without reduced prices (without applied specific price rules)

Proposal: Adding a `isApplyableForRule` filter event in cart rule process could be a solution. Don't know if there could be a priority issue, though (Not resolved items at this very moment, for example). This could be related to https://github.com/coreshop/CoreShop/issues/1729

**Comment by dpfaffenbauer** [comment]
with the introduction of Cart Item Actions with conditions, this should be possible.
