### ISSUE TITLE
Duplicate Entry Exception when Copy/Paste Product

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#1765]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Create Product
- Set default unit definition
- save and publish
- copy object
- past object:

![image](https://user-images.githubusercontent.com/700119/139847946-7ac5a9fa-941a-4ccb-a90d-7ec88eb10b58.png)

![image](https://user-images.githubusercontent.com/700119/139847781-70c3b4fb-6813-4d2c-a9d4-975fefce4fa8.png)

**Comment by dpfaffenbauer** [comment]
Version?

**Comment by solverat** [comment]
2.2

**Comment by solverat** [comment]
also on x. reproducable on demox.

**Comment by ramundomario** [comment]
On demox, when copy/paste, there is an additional error regarding uniqueness of slug:
![Screenshot from 2021-11-02 14-11-06](https://user-images.githubusercontent.com/16133208/139853409-94d63906-61d8-4598-95f6-4b62efed2f7f.png)

**Comment by dpfaffenbauer** [comment]
@ramundomario Slug hast been solved already. The SluggableListener now checks for uniqueness and adds a -1 if one already exists.
