### ISSUE TITLE
Problem "Could not open input file: bin/console"

### ISSUE THREAD

**Issue by RolandoPer** [coreshop/CoreShop#177]
I'm installing CoreShop 2, in Pimcore 4.6.0 with composer.
I have executed the command:
composer require coreshop/core-shop dev-master
without problems.
However when executing the command:
php bin/console coreshop:install
i get:
Could not open input file: bin/console

Any help, please?

**Comment by solverat** [comment]
Hello, Coreshop2 is for pimcore5 only! Please use the coreshop1 branch for pimcore4.

**Comment by RolandoPer** [comment]
Thanks @solverat
