### ISSUE TITLE
CoreShop3 - inheritance of categories not working correctly

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1775]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If you wat to display varinats on category-page, no variants are shown in listing, only master-products are listed.

Way to reproduce:
- Having actual CoreShop3 version with pimcore 10.2.3 installed
- Having class CoreShopProduct - enabled inheritance and variants, and showing variants in tree
- Configure coreshop to show variants in category-listing ( Coreshop - Settings - Category - Variant mode - Show )
- Defining variant-products as you like (ie TShirts with color/size) for products in one category
- leave category relations to inherited ones, no changes
- go to category-page - no variants are listed

Expected: Product-variants are listed on category-page

Workaround: in variants tab - open variant, delete inherited category, add same category again manualy. Variants are now shown in category-listing.

**Comment by dpfaffenbauer** [comment]
This is a problem in Pimcore. The relation for category is not persisted in the Product Variant. Better user coreshop index/filter to solve that.
