### ISSUE TITLE
Store gets lost when saving a payment provider in the admin backend

### ISSUE THREAD

**Issue by jdreesen** [coreshop/CoreShop#1781]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When trying to create a payment provider in the admin backend, the selected store is not persisted when saving the new provider (which is only visible when closing and re-opening the new provider after it was saved).

This results in the payment provider not being displayed in the frontend.

**Comment by dpfaffenbauer** [comment]
3.x?

**Comment by jdreesen** [comment]
Oh sorry, forgot to mention the version. Yes, it's `3.0.0-beta.1`.

**Comment by dpfaffenbauer** [comment]
https://github.com/coreshop/CoreShop/pull/1783
