### ISSUE TITLE
CoreShop3 - error on opening product-indices

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1786]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

CoreShop-3 Beta-1, pimcore 10.2.4

Trying to open CoreShop Product-Indexes in pimcore Backend - CoreShop - Product - Indices
Shows following error:

```
Attempted to load class "OrderItemUnit" from namespace "CoreShop\Component\Order\Model". Did you forget a "use" statement for another namespace?

Server threw exception - could not perform action. Please reload the admin interface and try again.
```

On error-detail-page:

![image](https://user-images.githubusercontent.com/23456403/142623683-5f11871c-61ba-4e62-9864-da8a110deaa6.png)

**Comment by JustMe69** [comment]
yes, and updated to beta

**Comment by dpfaffenbauer** [comment]
OK. There are things you have to manually resolve then. Like changing the ClassDefinition for OrderItem and remove all "unit" related stuff like the field "units"

**Comment by JustMe69** [comment]
how can I reinstall coreshop in a proper way?
