### ISSUE TITLE
CoreShop 3 - reinstall

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1787]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Help needed

What's the best way to reinstall CoreShop3, or update it proper to beta 1
and later on to beta 2 or stable version ?

**Comment by dpfaffenbauer** [comment]
please don't create any help tickets here, only bug/feature tickets
