### ISSUE TITLE
[CoreShop2] Ordering of countries

### ISSUE THREAD

**Issue by johnrisby** [coreshop/CoreShop#179]
The countries are ordered by ISO code but - at least the UK - named differently. So the United Kingdom which has the 2 letter ISO code of GB from Great Britain is hard to find in the list as it comes between the F's and H's but starts with U. 

It would be better to sort on the actual name rather than the ISO code.

**Comment by dpfaffenbauer** [comment]
solved with https://github.com/coreshop/CoreShop/commit/b421bc9ab1bf1fa1ef623eda5700983cb9ea090c
