### ISSUE TITLE
Save description and image of product in orderItem

### ISSUE THREAD

**Issue by breakone** [coreshop/CoreShop#1798]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no

Save also description and image of product in orderItem.

**Comment by dkarlovi** [comment]
Note, the image should in some way also be denormalized because the asset might be deleted in the meantime. Maybe store the asset ID nullable and optionally the thumbnail URL (without hostname) for fallback.

**Comment by dpfaffenbauer** [comment]
EventListener with a check for it might also work
