### ISSUE TITLE
[CoreShop2] Can't set baseCountry in a store unless country is activated in other settings first

### ISSUE THREAD

**Issue by johnrisby** [coreshop/CoreShop#180]
When you try to create a new store, or change the standard store, and set the baseCountry to a country that hasn't already been activated in the Countries page of the  Localization settings, it fails with an error saying it's not a valid country.

This is counter-intuitive and it should at least tell you why it's not valid and ask you if you want to activate the country so you can do what you went to that setting for, without having to hunt around or go to another setting first.

It's not a problem once the country has been activated, but off-putting when you first use it and you don't realise why the error is occurring.

**Comment by dpfaffenbauer** [comment]
solved with https://github.com/coreshop/CoreShop/commit/a8ad1990b598040b7540a6bbe30459aa655b5ab4

Now, only active countries are displayed, as well as the new Active Constraint, which checks if the selected value is active and gives a nicer error-message if inactive. (should not happen anymore though, cause we only display active values)
