### ISSUE TITLE
Can't install pimcore 5 + coreshop 2

### ISSUE THREAD

**Issue by mtarin** [coreshop/CoreShop#181]
Hi, i'm trying to install pimcore5 and coreshop 2 from composer but i can't make it work.

I've ran the console command to install but when i activate the registerBundle + yml config file this error appears:

Warning: glob(): Pattern exceeds the maximum allowed length of 260 characters in . (which is being imported from "\pimcore\lib\Pimcore\Bundle\CoreBundle/Resources/config/routing.yml"). Make sure there is a loader supporting the "pimcore_bundle" type.

Regards

**Comment by dpfaffenbauer** [comment]
Are you running on Windows?

If so: seems more like an Symfony issue than a CoreShop or Pimcore problem. Issues seems to be introduced in 3.3.6. Can you either try downgrading symfony to 3.3.5 and test again?

**Comment by mtarin** [comment]
Yes, on windows.

Any method to do this downgrade?

Regards

**Comment by dpfaffenbauer** [comment]
Try running

composer install symfony/symfony:3.3.5

**Comment by mtarin** [comment]
Ok i'll try and let you know.

**Comment by mtarin** [comment]
hi @dpfaffenbauer , i've tryed the version 3.3.5 but nothing distinct happened.

This log appears in the console when installing, but with the version 3.3.6 appears too.

Creating CoreShop Folders dev.
23:05:00 WARNING   [pimcore] object doesn't exist [] []
23:05:00 WARNING   [pimcore] object doesn't exist [] []
23:05:00 WARNING   [pimcore] object doesn't exist [] []
23:05:01 WARNING   [pimcore] object doesn't exist [] []
23:05:01 WARNING   [pimcore] object doesn't exist [] []
23:05:01 WARNING   [pimcore] object doesn't exist [] []
23:05:01 WARNING   [pimcore] object doesn't exist [] []
23:05:01 WARNING   [pimcore] object doesn't exist [] []
23:05:01 WARNING   [pimcore] object doesn't exist [] []
23:05:01 WARNING   [pimcore] object doesn't exist [] []
23:05:01 WARNING   [pimcore] object doesn't exist [] []

Any idea?

Regards

**Comment by dpfaffenbauer** [comment]
That's fine though. That's a Pimcore warning when creating object folders, you can ignore that. 

Everything else working now?

**Comment by mtarin** [comment]
@dpfaffenbauer no, the same error of the "glob" function...

**Comment by dpfaffenbauer** [comment]
I'll try to reproduce the problem somehow on a Virtual Machine.

Are you running IIS or Apache or Nginx on Windows?

**Comment by mtarin** [comment]
Apache 2.4 PHP 7.0 (xampp)

**Comment by dpfaffenbauer** [comment]
this seems to resolve the issue for me: https://github.com/coreshop/CoreShop/commit/2515122b726bda7bdb8215276e8525030033f3f1 can you confirm?

**Comment by mtarin** [comment]
fu***ng yeah!
