### ISSUE TITLE
Provide an exact way to use an alternative checkout manager (additional checkout-like flow)

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#1817]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

We have a use case where we need to do a "checkout-like" process for the quote, but keep the actual checkout as-is.

To do this, we've built a custom checkout manager setup with some steps being shared with the main checkout, some are fully custom. The issue here is that, currently, the checkout manager factory doesn't clearly support using additional checkout managers.

My suggestion is to update the checkout controller to allow wiring as many checkout managers automagically. This could also mean we deprecate the checkout route in favor of [route loaders which create all the routes for different checkout managers](https://symfony.com/doc/current/routing/custom_route_loader.html), for example

```
/en/shop/checkout/{step} - "default" checkout manager, using steps C1, C2, C3, C4, C5
/en/shop/offer/{step} - "offer" checkout manager, using steps 01, 02, 03
```

The checkout controller needs to know the correct routes to use and redirect to, allowing having as many checkout flows as you'd like.

**Comment by dpfaffenbauer** [comment]
Would love that, would you create a PR for that?

**Comment by dpfaffenbauer** [comment]
@dkarlovi any update on this?

**Comment by dkarlovi** [comment]
Not from my side.

**Comment by dpfaffenbauer** [comment]
we have projects where we use different checkout managers based on the cart context. we're doing this by using a seperate checkout manager factory like:

```php
<?php

namespace App\CoreShop\Checkout;

use App\Model\User;
use CoreShop\Component\Core\Context\ShopperContextInterface;
use CoreShop\Component\Order\Checkout\CheckoutManagerFactoryInterface;
use CoreShop\Component\Order\Checkout\CheckoutManagerInterface;
use CoreShop\Component\Order\Model\OrderInterface;
use CoreShop\Component\User\Model\UserAwareInterface;
use Pimcore\Model\DataObject\ASUserPermission;

class Factory implements CheckoutManagerFactoryInterface
{
    public function __construct(
        private ShopperContextInterface $shopperContext,
        private CheckoutManagerFactoryInterface $asGuest,
        private CheckoutManagerFactoryInterface $asBuyer,
        private CheckoutManagerFactoryInterface $asNonBuyer
    )
    {
    }

    public function createCheckoutManager(OrderInterface $cart): CheckoutManagerInterface
    {
        if (!$this->shopperContext->hasCustomer()) {
            return $this->asGuest->createCheckoutManager($cart);
        }

        $customer = $this->shopperContext->getCustomer();
        $hasUser = $customer instanceof UserAwareInterface && $customer->getUser();

        if (!$hasUser) {
            return $this->asGuest->createCheckoutManager($cart);
        }

        if (!$customer->getUser()->hasPermission('ONSHOP_V5')) {
            return $this->asNonBuyer->createCheckoutManager($cart);
        }

        return $this->asBuyer->createCheckoutManager($cart);
    }
}

```

Registering this with the service name: `coreshop.checkout_manager.factory.custom` and changing this config:

```yaml
core_shop_core:
    checkout_manager_factory: custom
```
