### ISSUE TITLE
Customer/user per store

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#1818]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

It might not be common, but for several most recent customers, they all wanted the shop user / customer to be per store. Namely, if I'm registered at `example.at`, I'm not registered at `example.ch`, even though they're using the same Coreshop instance (separate stores), the same customer **must** register separately on different stores.

This could in theory be made an configurable feature in core.

**Comment by dpfaffenbauer** [comment]
Possible to extend, we have an extension that allows that.
