### ISSUE TITLE
Email notification for quote fails due to "Language is not set" exception

### ISSUE THREAD

**Issue by gadget60** [coreshop/CoreShop#1821]
Having an notification rule for type "quote" with an action "Email" throws an exception "MailActionProcessor: Language is not set" in:
https://github.com/coreshop/CoreShop/blob/6fcbd95fc1c27ead48e8984fc63a23a042ce70d1/src/CoreShop/Component/Notification/Rule/Action/MailActionProcessor.php#L37-L39

Stack trace shows that the parameter "_locale" would have to be set in QuoteListener:
https://github.com/coreshop/CoreShop/blob/6fcbd95fc1c27ead48e8984fc63a23a042ce70d1/src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/QuoteListener.php#L27

Something like:
```
        $quote = $event->getSubject();
        $this->rulesProcessor->applyRules('quote', $quote, [
            '_locale' => $quote->getLocaleCode(),
        ]);
```

...as it is is done in OrderWorkflowListener:
https://github.com/coreshop/CoreShop/blob/6fcbd95fc1c27ead48e8984fc63a23a042ce70d1/src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/OrderWorkflowListener.php#L37-L47

Steps to reproduce:
- create a notification of type "quote"
- add an action "Mail"
- as a customer, create a quote in the frontend

**Comment by dpfaffenbauer** [comment]
are you on 2.x or 3.x?

**Comment by gadget60** [comment]
On 2.x. BTW, also the "recipient" is required for the mail action...

**Comment by TobiSW** [comment]
For me also reproducable in 3.x

**Comment by dpfaffenbauer** [comment]
PR https://github.com/coreshop/CoreShop/pull/1868 fixes it for 2.2

**Comment by dpfaffenbauer** [comment]
PR for 2.2 is merged

**Comment by dpfaffenbauer** [comment]
PR for 3.x as well
