### ISSUE TITLE
Passwort reset notification not sending

### ISSUE THREAD

**Issue by valentin-** [coreshop/CoreShop#1831]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Somehow the "User Reset Password" notiification won't send messages anymore. The configuration hasn't changed in the meanwhile. The "User Register" notification works fine.

Were there any changes lately? There are no errors.

![image](https://user-images.githubusercontent.com/90033/148525252-88bfbde8-a968-40c0-8c08-6e8567a53f1f.png)
![image](https://user-images.githubusercontent.com/90033/148525277-f10f417f-c076-4ebd-aeec-6ad6311787a0.png)
![image](https://user-images.githubusercontent.com/90033/148526872-c1384185-42cd-45a1-9ef2-f45cad0cbd3e.png)

**Comment by valentin-** [comment]
I also noticed that the order confirmation is sent twice. But there is only one notification rule active. Could this be related to the issue?

**Comment by dpfaffenbauer** [comment]
V2 or V3?

**Comment by valentin-** [comment]
It's V3, I've just updated to the latest version right now but the error still occurs and I can't really find out what's causing the issue. The event is getting dispatched and params in applyPasswordRequestResetRule() are getting applied, but there is no email sending. Also nothing in the logs. Other mails are sending fine.

**Comment by valentin-** [comment]
The UserTypeChecker expects a CustomerInterface. But $subject contains a CoreShopUser object, which makes sense for the passwort reset action but will never be valid.

![image](https://user-images.githubusercontent.com/90033/155111926-53a6797e-ea58-484d-a11a-9b1782591ed6.png)

Passing the customer object would fix the issue.

https://github.com/coreshop/CoreShop/blob/94c133f65a704a8486e9bb1cd9687f852028e937/src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/CustomerListener.php#L47

But there haven't been any code changes lately and it worked a few weeks earlier, do you have any idea what happened @dpfaffenbauer? Does it work in your testing environment?

**Comment by dpfaffenbauer** [comment]
that makes sense. I decoupled user and customer. Will look into that in the following days
