### ISSUE TITLE
Payment type condition for order notifications

### ISSUE THREAD

**Issue by valentin-** [coreshop/CoreShop#1832]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes

It would be nice to add a condition to send order notifications based on the selected payment type. 

![image](https://user-images.githubusercontent.com/90033/148527723-84f7a411-e225-4353-80b9-3dbadb467e7d.png)

Usecase:

- Bank transfer: Send a mail including bank details
- Other: Bank details not needed

**Comment by valentin-** [comment]
Nevermind, changing the template makes more sense.

**Comment by dpfaffenbauer** [comment]
I'll keep this open since it makes sense anyway
