### ISSUE TITLE
When stable release V3?

### ISSUE THREAD

**Issue by dominikager** [coreshop/CoreShop#1853]

**Comment by dpfaffenbauer** [comment]
When contributions?

Seriously, this is completely the wrong space for stupid questions like this. Everybody can help in making it ready for Version 3 in using it and giving constructive Feedback and Pull Requests. I use the current 3.x-dev Version already in Production for some projects. But still not enough to be super stable and comfortable enough for a final release. Either contribute to it and give constructive feedback, or leave it.
