### ISSUE TITLE
Full page cache disabled: Session in use

### ISSUE THREAD

**Issue by valentin-** [coreshop/CoreShop#1856]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Currently the full page cache is completely disabled, as there is a CoreShop Session Variable active in `_sf2_attributes`.
Is this working as intended? Or should the variable get saved in `_sf2_meta` (as this is present in `$ignoreSessionKeys`)?

This is the output from /vendor/pimcore/pimcore/lib/Cache/FullPage/SessionStatus.php:74

![image](https://user-images.githubusercontent.com/90033/152750647-0ab4d8fa-eb8f-4473-81ce-f6d42bb1a644.png)

**Comment by dpfaffenbauer** [comment]
We never implement anything specific regarding Pimcore's fullpage cache. In Theory the cache SHOULD be disabled when a session is active as the page content can differ.

**Comment by valentin-** [comment]
Yes that's true. But if the shop is a small part of the website, so the cache shouldn't get disabled completely. I've now implemented a "dirty" event listener to set the session on the ignore list if it is a document/not a coreshop route.
