### ISSUE TITLE
Implement MembersBundle for Customer Context and Frontend User Management

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#186]
https://github.com/dachcom-digital/pimcore-members

Install MembersBundle with CoreShop to take advantage of this amazing Bundle. This also enables more possibilities for authentication stuff when using CoreShop. For example:
 - Single Auth for your Shop, as well as your Forum/Blog/Website
 - Restrict certain Products/Categories to Members and let Members take care about restricting
 - Restrict certain Documents to Members and let Members take care about restricting

How To:
 - ~~leave CustomerComponent and CustomerBundle as it is~~
 - ~~leave CoreComponent and CoreBundle as it is~~
 - ~~implementation is done in MembersBridge (CoreShop\Bridge\MembersBundle)~~
 - ~~MembersBundleBridge can be activated manually if needed~~
 - add docs on what is necessary to use MembersBundleBridge
 - ~~implement MembersBundle\Adapter\User\AbstractUser in Bridge (a trait would make life easier)~~
 - ~~implement MembersBundle\Adapter\Group\AbstractGroup in Bridge (a trait would make life easier)~~
 - ~~change ProductRepository and CategoryRepository and add MembersQueries~~
 - use MembersRegistrationFormType, MembersLoginFormType, MembersForgotPasswordFormType (really necessary? can't we stick with our FormTypes?)
 - ignore members emails, is done via NotificationRules in CoreShop (maybe map Members Mails to CoreShop Customer Notification Types)

@solverat I guess I need some help here and probably some changes in MembersBundle:
 - could you create a trait for what is currently done in MembersBundle\Adapter\User\AbstractUser and MembersBundle\Adapter\Group\AbstractGroup? So I can use your trait and just implement the UserInterface and GroupInterface
 - can you check if my How-To makes sense?

**Comment by dpfaffenbauer** [comment]
@solverat need some help here from you, currently this is working as Bridge and or Core (not sure which way to go):

 - Restriction of Products and Categories
 - Customer and CustomerGroup is used as Member User and Member User Group

What I am not sure of: Should CoreShop use Members Events and Controllers as well? Or should it just stick to what its currently already doing?

**Comment by solverat** [comment]
CoreShop should use Members in Core not as Bridge. We'll have to discuss further steps in our next hackathon. ;)

**Comment by dpfaffenbauer** [comment]
closed due to too old and not sure when, how and what actually.

**Comment by dpfaffenbauer** [comment]
Closing this for now, will not happen for 2.0 and not sure if it ever gonna happen.
