### ISSUE TITLE
Quantity values - using double as Type results in DB to decimal(10,0) field

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1860]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When defining quantity values in an index, using double as Type-definition, the field created in database for taht value is a decimal (10,0) datatype.
So i.e value 1.6 ist saved a 2 in database which leads to wrong filtering

Expected: double values as Type should lead at least to 2 decimal places, or better, decimal places should be configurable.

**Comment by dpfaffenbauer** [comment]
fixed
