### ISSUE TITLE
[CoreShop2] Recommendation Engine

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#187]
## Goal
- create a RE-Workflow concept, to create super smart recommendation
- store in key/value db/table

## Examples
- up-selling products
- cross-selling products
- products with valid stock values
- most clicked products of active category
- get products, most clicked by users with gender / age (for b2b shops)

**Comment by dpfaffenbauer** [comment]
We'll wait for customer management framework before doing anything here.

**Comment by dpfaffenbauer** [comment]
Customer Management Framework can solve this.
