### ISSUE TITLE
Filter condition value can't be empty after first value select

### ISSUE THREAD

**Issue by BabovicT** [coreshop/CoreShop#1878]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Value field can't be set to empty after value is selected for the first time. Version 2 and version 3 have this bug.
![image (1)](https://user-images.githubusercontent.com/80684610/155694557-df09fd7f-36f1-4e3d-9b33-0ac402e18d82.png)

**Comment by BabovicT** [comment]
Fixed on master. I was using 3.0.0-beta.2 version

**Comment by dpfaffenbauer** [comment]
fixed by https://github.com/coreshop/CoreShop/pull/1833
