### ISSUE TITLE
Product-Feed for Marketplaces

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#188]
Allow user to create dynamic product feeds for marketplaces like google shopping, facebook e-commerce etc.

- Backend configuration: Similar to the index bundle, allow custom data mapping
- Allow specific products, categories for each feed
- Create dynamic route and endpoint: domain.com/shop/mp-feed/feed-1.json

**Comment by dpfaffenbauer** [comment]
- add dynamic filters to allow better customization
 - similar to import-definitions as well, but more like export-definitions? (i guess)

**Comment by dpfaffenbauer** [comment]
We'll wait for Pimcore Export Toolkit before we do anything here.

**Comment by dpfaffenbauer** [comment]
Export Toolkit could solve this, right? @solverat

**Comment by dpfaffenbauer** [comment]
Not gonna happen in CoreShop Context, maybe something like [ImportDefinitions](https://github.com/w-vision/ImportDefinitions) for Export Definitions.
