### ISSUE TITLE
[CoreShop2] show 404 in detailAction if product has been disabled

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#189]

**Comment by Yivan** [comment]
Thanks for opening it in CoreShop2!
Just for reference: https://github.com/coreshop/CoreShop/issues/173

**Comment by solverat** [comment]
Two ways:

## Copy Product after Sale
Copy or serialize object and implement a custom view for ordered product, so deleted, changed products will not change already locked (and payed) data (best way).

## Query Parameter
Append Query Parameter (`&force-visibility=true`) if product gets linked from the customer panel (order history)

**Comment by dpfaffenbauer** [comment]
**1** Would be the best solution anyway
**2** Is kinda a security issue

**Comment by solverat** [comment]
@Yivan ok, we just talked about it:
- coreshop will show a 404 exception if the product is disabled
- a detail link from the order history will check if the product is available and enabled. if not - remove detail link

**Comment by solverat** [comment]
+ see #174:

> until https://github.com/pimcore/pimcore/issues/1742 happened, we'll only persist the product name into the SaleItem (OrderItem, QuoteItem). After that happened, we'll store the serialized version into the SaleItem.

after that it's possible to build a specific detail view of a sold product.

**Comment by Yivan** [comment]
Thanks for your feedbacks!
Yes I agree, when serializing will be available it will help to implement this feature.
