### ISSUE TITLE
Notification rules - User-Register sended out twice

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1897]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When notification rule 'User register' is set to active, with condition configured: "User Type: New Account"
configured email is sended out twice, and both emails are listed under pimcore 'Sent Emails'

**Comment by dpfaffenbauer** [comment]
@JustMe69 I know we looked at that together on your setup, but I just tried with the demo and it worked as it should. Email gets sent only once....
