### ISSUE TITLE
[CoreShop2] Fatal Error when clicking on checkout button in cart after new register

### ISSUE THREAD

**Issue by tgrueber** [coreshop/CoreShop#191]
Type error: Argument 1 passed to CoreShop\Component\Address\Formatter\AddressFormatter::formatAddress() must implement interface CoreShop\Component\Address\Model\AddressInterface, boolean given, called in /Applications/MAMP/htdocs/zollmann/vendor/coreshop/core-shop/src/CoreShop/Bundle/AddressBundle/Templating/Helper/FormatAddressHelper.php on line 40

**Comment by dpfaffenbauer** [comment]
I couldn't kinda replicate your issue. What I did for now is: Don't try to display addresses when there are no addresses.

Are you already using the latest version?

**Comment by tgrueber** [comment]
Sorry. I’m not able to reproduce it, too. I remember that the debug email address was not set and because of that I resend the form. Perhaps this was the problem that the address was not saved.

**Comment by dpfaffenbauer** [comment]
ok, that sounds like the problem :D, so I'll close this issue then.
