### ISSUE TITLE
Product specific-price-rule is not calculated in cart and checkout

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1913]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

CoreShopVersion: 3 dev-master

defining a 'Specific Price Rule' for a product.
- rule is activated
- priority is set to 1
- Label is set in all languages
- Condition: Zone Europe
- Action: new Price. normal product price is 5400, new price 5100 Euro

no other price rules are defined for this product, not on the product level, not on global level (cart/product)

Placing an order in shop, invoice and shipping address is in Germany

Customer is logged in.
No discount is displayed in checkout, after finishing order, price is still displayed with 5400 €. In Order-object no adjustment with label 'specific_price_rule' displayed.

Expected:
Price within cart and after order is shown and calculated with new defined price. Adjustment in cart-object defined.

**Comment by dpfaffenbauer** [comment]
are you on latest dev-master? there was a fix for that last week

**Comment by JustMe69** [comment]
yes 

```
composer update --dry-run
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
```

**Comment by dpfaffenbauer** [comment]
not reproducible

**Comment by lukadschaak** [comment]
Can #2028 be part of the problem? Is it possible, that the actions of the specific price rule were shown in the UI, but not correctly saved when entering the cart and checkout?

@JustMe69 Did you check whether the specific price rules were applied on the product detail page? If so, that problem here has nothing to do the with the other issue.
