### ISSUE TITLE
Order confirmation sending 3 times

### ISSUE THREAD

**Issue by valentin-** [coreshop/CoreShop#1916]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It looks like CoreShop is sending the order confirmation mail for every state change in the state machine.

OrderWorkflowListener->applyOrderWorkflowRule() is called 3 times with different $eventName called by the EventDispatcher.

1. workflow.coreshop_order_payment.completed
2. workflow.coreshop_order.completed
3. workflow.coreshop_order_sales_type.completed

For every different state a mail will be sent. Could be related to https://github.com/coreshop/CoreShop/issues/1897 - probably the condition gets ignored.

**Comment by dpfaffenbauer** [comment]
I cannot reproduce that, I just tried and it works flawless. Can you check that all your rules are setup properly?
