### ISSUE TITLE
Error installing and activating CoreShop.

### ISSUE THREAD

**Issue by kepeder** [coreshop/CoreShop#193]
# Bug Report
  
### Expected behavior 
  Tried to activate CoreShop from PimCore Extension Manager.
### Actual behavior  
  There was thrown an 500 Error saying:
  - You have requested a non-existent service "CoreShop\Bundle\AdminBundle\Installer".
### Steps to reproduce  
- wget https://www.pimcore.org/download/pimcore-latest.zip -O pimcore-install.zip
- unzip pimcore-install.zip && rm pimcore-install.zip
- Went to http://server/install and followed the steps for installing PimCore.
- Installed CoreShop with composer
> composer require coreshop/core-shop dev-master
- Added Following Call to AppKernel's registerBundlesToCollection function
> \CoreShop\Bundle\CoreBundle\Application\RegisterBundleHelper::registerBundles($collection);
- Added the following to app/config/config.yml
> - imports:
>        - { resource: "@CoreShopCoreBundle/Resources/config/app/config.yml" }
- Ran
> php bin/console coreshop:install
- Activated AdminBundle in Pimcore Extension Manager (Here the 500 Exception was thrown)

### Environment
NGiNX reverse proxy / SSL-termination into Apache2 where it is processed using PHP7.1-FPM with FastCGI. Fresh install of PimCore and a clean DB.

**Comment by dpfaffenbauer** [comment]
Have you tried running ```bin/consolecache:clear --no-warmup```?

**Comment by kepeder** [comment]
I then got the following error:

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "pimcore_ecommerce.decimal_scale" must be defined. in /home/kepeder/beta/webroot/var/cache/dev/appDevDebugProjectContainer.php:16470
Stack trace:
#0 /home/kepeder/beta/webroot/pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PimcoreEcommerceFrameworkBundle.php(83): appDevDebugProjectContainer->getParameter('pimcore_ecommer...')
#1 /home/kepeder/beta/webroot/pimcore/lib/Pimcore/Kernel.php(143): Pimcore\Bundle\EcommerceFrameworkBundle\PimcoreEcommerceFrameworkBundle->boot()
#2 /home/kepeder/beta/webroot/pimcore/config/kernel.php(25): Pimcore\Kernel->boot()
#3 /home/kepeder/beta/webroot/pimcore/config/startup_cli.php(55): include_once('/home/kepeder/b...')
#4 /home/kepeder/beta/webroot/bin/console(33): require_once('/home/kepeder/b...')
#5 {main}
  thrown in /home/kepeder/beta/webroot/var/cache/dev/appDevDebugProjectContainer.php on line 16470`

**Comment by dpfaffenbauer** [comment]
Thats not from CoreShop, thats from the ecommerce framework. Did you activate the ecommerce framework instead of CoreShopAdmin?

**Comment by kepeder** [comment]
Huh, it seems so. I will try a clean install again.

**Comment by kepeder** [comment]
It worked after
> bin/console cache:clear --no-warmup
👍 
Thank you!
