### ISSUE TITLE
wrong Fkt-Declaration in interface and class 

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1943]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

using CoreShop 3 - dev-master

function declaration of function findForProductAndStore() (return type) is wrong. 

class: ProductStoreValuesRepository
    path: CoreShop/Bundle/CoreBundle/Doctrine/ORM/ProductStoreValuesRepository.php
interface: ProductStoreValuesRepositoryInterface
    path: CoreShop/Component/Core/Repository/ProductStoreValuesRepositoryInterface.php

wrong:
    public function findForProductAndStore(ProductInterface $product, StoreInterface $store): array

should be:
    public function findForProductAndStore(ProductInterface $product, StoreInterface $store): ?ProductStoreValuesInterface;

**Comment by dpfaffenbauer** [comment]
please create a PR in the future if you know the solution

**Comment by dpfaffenbauer** [comment]
fixed
