### ISSUE TITLE
wrong route naming: coreshop_cart_create_quote vs coreshop_cart_create_qoute

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1945]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

using CoreShop 3 - dev-master

When ordering as quote exception occurs.
route is differently defined.

Sometimes it is coreshop_cart_create_q**uo**te
Sometimes it is coreshop_cart_create_q**ou**te

Should be coreshop_cart_create_quote at all places

Wrong places:
CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml
Search code for 'coreshop_cart_create_qoute'

**Comment by JustMe69** [comment]
It's still wrong in core-code:
Search code for 'coreshop_cart_create_qoute'

Wrong places:
CoreShop/Bundle/CoreBundle/Checkout/Step/SummaryCheckoutStep.php
CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml

**Comment by dpfaffenbauer** [comment]
would you mind creating a PR?
