### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by kylepwarren** [coreshop/CoreShop#195]
*pim5, coreshop2
Can you please clarify the installation instructions some?

Do I need to git clone this or is the a deployment zip similar to pimcore? 
Do I need to put it in a pimcore bundles sub-directory?

Then I guess in there do the composer install...

Thanks

**Comment by dpfaffenbauer** [comment]
as the readme says:

```composer require coreshop/core-shop dev-master```

you need to install it using composer and follow the install steps listed there.

**Comment by kylepwarren** [comment]
In the root pimcore folder?
It's just hanging for ever here: Updating dependencies

**Comment by dpfaffenbauer** [comment]
yes, in the root pimcore folder. where the composer.json is.

Well, composer takes some time to calculate all the dependencies and check for appropriated versions. 

Unfortunately, this issue has nothing todo with CoreShop. The readme clearly states how to install CoreShop, the Docs describe it as well. If you have problems with composer and/or how to install dependencies with it, this is the wrong channel, sorry.

Feel free to open another issue if something fails during installation of CoreShop.
