### ISSUE TITLE
Notifications - defining 2 emails

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1953]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

using CoreShop 3 - dev-master (b3df17b)

Definig / configuring notifications, i.e. Order Confirmation or User Registration.
Setting up Actions -  2 Emails with different email-documents.
When saving- email-document is reset to the same document (2nd). So both emails are using the same doc. 1 emailDoc is saved for both emails.

Expected - for each email another email-doc can be saved and used.

**Comment by dpfaffenbauer** [comment]
fixed
