### ISSUE TITLE
Coreshop2 How to configure for Paypal and Sandbox Account. 

### ISSUE THREAD

**Issue by sriram246** [coreshop/CoreShop#196]
Hi Dominik,

 I have configured the Payment providers in Coreshop backend. For instance I have enetered my  Sandbox accounts with Username and Other API credentials in Backend. I can create the order. But somehow the Payment details are not made in both Paypal and Sofort. I am getting a error message like

Gateway "Paypal" does not exist. 

Can you breifly explain what to configure in the backend so that the gateway name is found correctly and payment is made. Do I need to do anything more?

**Comment by dpfaffenbauer** [comment]
Hi,

just to get the idea: you are creating the order in backend?

**Comment by sriram246** [comment]
Hi Dominik,
  No I have configured all the necessary information on the PayPal Config data Like Username, Password and Signature using my Sandbox account. But when I treid to make an order, The order number is created and so does Capture action. But I get the following exception.

Gateway "Paypal" does not exist. So I want to get an idea of how the paypal must be configured and how is it getting called so that the transaction is successfully made. thats it.

**Comment by dpfaffenbauer** [comment]
I'll look into it.

**Comment by dpfaffenbauer** [comment]
found the issue, can you please update to dev-master and try again?

Origin of the problem: Payum formerly installed paypal lib with payum-core, but they changed that a few weeks ago. If problem still appears, open a new case please.
