### ISSUE TITLE
Order missing quote state and number on beta3

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#1960]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

On Beta 3, order class is missing `quoteState` and `quoteNumber` fields by default.

Maybe needs these added to the order abstract class?

```php
public function getQuoteState(): ?string
{
    throw new ImplementedByPimcoreException(__CLASS__, __METHOD__);
}

public function setQuoteState(?string $quoteState): void
{
    throw new ImplementedByPimcoreException(__CLASS__, __METHOD__);
}

public function getQuoteNumber(): ?string
{
    throw new ImplementedByPimcoreException(__CLASS__, __METHOD__);
}

public function setQuoteNumber(?string $quoteNumber)
{
    throw new ImplementedByPimcoreException(__CLASS__, __METHOD__);
}```

**Comment by dpfaffenbauer** [comment]
no. Model Classes in CoreShop 3 are abstract, Pimcore implements the methods.
