### ISSUE TITLE
Reset onHold for stale unpaid orders

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [coreshop/CoreShop#1972]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Currently when an order is committed the quantities of the ordered items get set on hold via the `onHold` field of the product object. When the order gets paid or cancelled, the `onHold` gets reset.
But currently there is no cleanup of stale orders afaik. This means when someone commits an order but never pays, this might prevent the product from being available because when the whole stock is on hold, nobody else will be able to buy the product.

Or is there already such a cleanup mechanism which I did not see?

**Comment by dkarlovi** [comment]
Typically, you'd have a grace period here (for example, one hour), allowing a customer a specific time to pay the order. After the grace period expires without the order being resolved, it would be marked as stale and all the products would get released.

**Comment by dpfaffenbauer** [comment]
There is period for the order being able to be paid. That number is configurable. Default is 0 for infinite:

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/OrderBundle/DependencyInjection/Configuration.php#L87
