### ISSUE TITLE
[CoreShop2] Sofort Configuration

### ISSUE THREAD

**Issue by sriram246** [coreshop/CoreShop#198]
Hi Dominik,

I am working on Sofort Payment. I have configured basic details in Pimcore Admin. There is a field called as coreshop_config. It has some restrictions. Can you once explain me what to fill in those so that the payment caan  be amde successfully. Like an example data.

**Comment by dpfaffenbauer** [comment]
I guess you are talking about the red-lined field, right?

  
![bildschirmfoto 2017-11-10 um 08 25 13](https://user-images.githubusercontent.com/5981845/32647429-54779256-c5f1-11e7-8860-922417724865.png)

if so, you need to create a new account at sofort.com -> within there you create a new project, and there you'll get this:

![bildschirmfoto 2017-11-10 um 08 27 50](https://user-images.githubusercontent.com/5981845/32647443-623192d4-c5f1-11e7-87a1-79db9822d1fc.png)
