### ISSUE TITLE
Quote confirmation sending 2 times

### ISSUE THREAD

**Issue by TobiSW** [coreshop/CoreShop#1986]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no

Steps to reproduce:

- Notification Rule -> Add new rule -> Rule Type: quote -> Actions: add email
-  No condition is set.
- Request a quote -> Confirmation email is sent out twice.

It seems like that OrderWorkflowListener is triggered twice. 
OrderWorkflowListener->applyOrderWorkflowRule() is called by the EventDispatcher:
1. workflow.coreshop_order_sales_type.completed 
2. workflow.coreshop_quote.completed
```
  - { name: kernel.event_listener, event: workflow.coreshop_order_sales_type.completed, method: applyOrderWorkflowRule }
  - { name: kernel.event_listener, event: workflow.coreshop_quote.completed, method: applyOrderWorkflowRule }
```

Not sure why applyOrderWorkflowRule is needed for the transition from cart to quote. When i remove the event listener for the workflow.coreshop_order_sales_type.completed event the email is only sent once. Could be also related to #1916 

If needed i can provide a PR.

**Comment by dpfaffenbauer** [comment]
You should always set a condition, every state change triggered will trigger sending a email for you.
