### ISSUE TITLE
Hello Dominik,

### ISSUE THREAD

**Issue by sriram246** [coreshop/CoreShop#199]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [ ] This is not a security issue / vulnerability -> send them to info@coreshop.org instead
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [ ] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [ ] There's no existing ticket for the same issue
- [ ] Remove unused sections from below and this bullet points

### Code example 
```php
// your code
```

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [ ] There is no existing issue regarding the same topic

**Comment by dpfaffenbauer** [comment]
@sriram246 not sure what you mean here, this is just the template. please open a new issue regarding your actual issues.
