### ISSUE TITLE
[CoreShop2] Paypal  Payment 

### ISSUE THREAD

**Issue by sriram246** [coreshop/CoreShop#200]
Hi Dominik,

I have succesfully configured the Paypal in Admin backend. When I Buy the order It is succesfully redirected to Paypal and payment details are made. But once I made the payment then I am redirected to Error-Checkout Page. I looked into the Orders iin Admin. It creates a unique Payment URL and it captures the action. But I dont see the Thankyou Action Page being called which is the last step for Order creation. I looked into the Database It tells the PaymentAction is completed. I guess it looks fine But I just want to re-check with you and confirm if anything is not correct. 
If you need any more details I will be happy to provide.

**Comment by dpfaffenbauer** [comment]
Just tested and worked fine in my demo.

Do you have any logs which point to something didn't work right?

**Comment by dpfaffenbauer** [comment]
@sriram246 is this resolved for you?

**Comment by dpfaffenbauer** [comment]
closed due to inactivity
