### ISSUE TITLE
\CoreShop\Bundle\RuleBundle\DependencyInjection\Compiler\TraceableValidationProcessorPass::process loads all the classes of all services

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2001]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The compiler pass in question is looking for services which implement `\CoreShop\Component\Rule\Condition\RuleConditionsValidationProcessorInterface` by checking if the services class implements it. This requires *every* class on the project to be loaded, consuming a lot of memory.

A much more efficient (and Symfony-like) solution is to auto-tag all instances of that interface and then find services by tag.

**Comment by dpfaffenbauer** [comment]
yes, I agree.

**Comment by dpfaffenbauer** [comment]
@dkarlovi see https://github.com/coreshop/CoreShop/pull/2002
