### ISSUE TITLE
CoreShop Menu not working when served by Nginx

### ISSUE THREAD

**Issue by micru** [coreshop/CoreShop#2005]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The corehops menu (admin ui) seems not to work when Pimcore is served from Nginx. Probably it is because in the Pimcore template of the nginx.conf everything ending with `.js` is tried to be served statically.
Therefore, requesting the dynamically rendered menu-javascript via `/admin/coreshop/coreshop.main/menu.js` does not work, as this request never reaches the application (`CoreShop\Bundle\MenuBundle\Controller\MenuController::menuAction`)

See the relevant nginx directive here: 
https://github.com/pimcore/pimcore/blob/10.x/doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md?plain=1#L112

As a workaround, I have overwritten the relevant route configuration in my application like this (not ending with `.js`)
```
coreshop_menu:
    path:     /admin/coreshop/{type}/menu
    defaults: { _controller: CoreShop\Bundle\MenuBundle\Controller\MenuController::menuAction }
```

**Comment by dpfaffenbauer** [comment]
https://demo3.coreshop.org/admin is running on nginx in kubernetes, and it works there.
