### ISSUE TITLE
\CoreShop\Component\Product\Rule\Fetcher\MemoryCachedValidRuleFetcher doesn't work in console

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2008]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Currently, `\CoreShop\Component\Product\Rule\Fetcher\MemoryCachedValidRuleFetcher` will check its cache if the current request is the main request. But this doesn't work if you're calculating prices in CLI (say, ingesting prices into ES).

Not sure what's the best fix here, just allow if CLI?

**Comment by dpfaffenbauer** [comment]
well, difficult. As per Request we can assume that the price for one product is always the same. But for CLI you could change the context and therefore get 3 different prices (eg. for 3 different customer-groups) per product. so the cache-key would need to be the context. Context can be anything though...

**Comment by dpfaffenbauer** [comment]
I'll close this for now as I don't see a proper solution for that.
