### ISSUE TITLE
[CoreShop2] New Payment Provider

### ISSUE THREAD

**Issue by sriram246** [coreshop/CoreShop#201]
Hi Dominik,

  I have written two bundles namely PaymentBundle and VorkasseBundle on my own . I have attached thewe 2 bunles for your reference. I have followed the same structure as in the coreshop. I want to see a new option called Vorkasse in my Payment Provider Type in  Combobox in the Admin Backend Pimcore. Somehow this option is not yet loaded into my Pimcore. Can you assist me what else needs to be done or do I have to include some new files? Thats why i have attached both my bundles for your reference. Please go through it and let me know what is the actual issue so that Vorkasse Option is actually loaded into my Backend. This option is already visible in the frontend as a Payment Provider. Please let me know.

Thanks a lot
[VorkasseBundle.zip](https://github.com/coreshop/CoreShop/files/1482769/VorkasseBundle.zip)

  

[PaymentBundle - Verknüpfung.zip](https://github.com/coreshop/CoreShop/files/1482739/PaymentBundle.-.Verknupfung.zip)

**Comment by sriram246** [comment]
[PaymentBundle.zip](https://github.com/coreshop/CoreShop/files/1482789/PaymentBundle.zip)

Here comes the PaymentBundle.

**Comment by dpfaffenbauer** [comment]
I’ll look at that asap. But for Vorkasse, you don’t need a extra payment type, you can use offline to do that. Haven’t looked at the code though. I am currently only on mobile.

Offline basically is a type of Vorkasse.

**Comment by sriram246** [comment]
[PaymentBundle.zip](https://github.com/coreshop/CoreShop/files/1482799/PaymentBundle.zip)
[VorkasseBundle.zip](https://github.com/coreshop/CoreShop/files/1482800/VorkasseBundle.zip)
Ok Here are the new Bundles.

**Comment by dpfaffenbauer** [comment]
I don't really get what you are trying to accomplish here? Whats the idea of having these two bundles? As I already said, If you want to have a simple vorkasse payment, simply use payum's offline factory. 

If you want to have separate configuration fields, you need to create your own payum factory to handle your configurations.

**Comment by dpfaffenbauer** [comment]
ping @sriram246 is this resolved for you?

**Comment by dpfaffenbauer** [comment]
closed due to inactivity
