### ISSUE TITLE
CoreShopRelation Error: Undefined array key

### ISSUE THREAD

**Issue by marlonbasten** [coreshop/CoreShop#2011]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When I do a classes-rebuild on a freshly created project after enabling and installing CoreShop, I get the following error:
<img src="https://i.imgur.com/NOUI6vN.jpg" alt="Shown error">

I made a small fix, so that the error doesn't get shown anymore. But I don't know if I break any logic with it. When I only use the DataObjects that are provided by CoreShop I don't get the above error. But as soon as I create my own DataObject, the error occurs.

I'm anyway doing a PR in case this is a needed fix.

**Comment by marlonbasten** [comment]
Just saw that this is already fixed on master. Could you push it to the v3 branch? Currently using 3.0.0-beta3 because in the installation instructions it's saying to set the minimum stability to dev.

**Comment by dpfaffenbauer** [comment]
install dev-master or wait until I release beta-4. there is no v3 branch
