### ISSUE TITLE
Rich results / JSON+LD / RDF support

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2018]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

To support [JSON-LD structured metadata](https://developers.google.com/search/docs/advanced/structured-data/product#json-ld_1) for SEO extractor, Coreshop would need to:
1. update `\CoreShop\Component\SEO\Model\SEOMetadataInterface` with something like `addJsonLdBlock()`
2. update `\CoreShop\Component\SEO\SEOPresentation` to make use of it, something like
```php
        if ($blocks = $seoMetadata->getJsonLdBlocks()) {
            foreach ($blocks as $block) {
                $this->headScript->appendScript($block, 'application/ld+json');
            }
        }
```

We can then add an JSON+LD SEO extractor.

**Comment by dkarlovi** [comment]
I'm not married to the API naming BTW.

**Comment by dpfaffenbauer** [comment]
fine by me, will you PR? BTW: CoreShop actually recommends or should recommend Dachcom SEO Bundle

**Comment by dkarlovi** [comment]
OK, does that mean the SEO bundle is obsolete since there's overlapping features?

**Comment by dpfaffenbauer** [comment]
CoreShop's SEO Bundle gives just some basic SEO. We decided not to further improve it since Dachcom did a really good Job there. We still don't want to depend on them for obvious reasons, thats why our SEO Bundle is quite simple. If you need more, use Dachcoms Bundle.
