### ISSUE TITLE
Streamline shipping and payment selectors in checkout

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2021]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Currently, the shipping provider is selected via radio buttons, which allows additional information directly in the UI.

The very next step, basically the same interaction, only picking the payment provider, is a select element (dropdown). This step could be streamlined to use the radio buttons too.

**Comment by dpfaffenbauer** [comment]
the FrontendBundle will be removed in the future, so there is no need for this change anymore then.
