### ISSUE TITLE
In CategoryController, two conditions are added, but they are semantically filter preconditions

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2039]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

https://github.com/coreshop/CoreShop/blob/aeb14a9491128e377c5f3f61ab055d948a8c5deb/src/CoreShop/Bundle/FrontendBundle/Controller/CategoryController.php#L139-L140

These conditions should actually be filter preconditions because they behave exactly like that:
https://github.com/coreshop/CoreShop/blob/aeb14a9491128e377c5f3f61ab055d948a8c5deb/src/CoreShop/Component/Index/Model/FilterInterface.php#L73

**Comment by dpfaffenbauer** [comment]
PR?

**Comment by dkarlovi** [comment]
I think this is a fix specific to our usage of this, not for Coreshop in general. Closing.
