### ISSUE TITLE
Error during the install

### ISSUE THREAD

**Issue by zekuraz** [coreshop/CoreShop#2059]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

Hi,

I follow the instruction of installation, by first allow dev version to be installed :

```
composer config "minimum-stability" "dev"
composer config "prefer-stable" "true"
```

Install with composer

`composer require coreshop/core-shop:^3.0
`

Run enable Bundle command 
`php bin/console pimcore:bundle:enable CoreShopCoreBundle`

Run Install Command 
`php bin/console coreshop:install`

But, at this point, i have a error
![2022-08-24_11-14](https://user-images.githubusercontent.com/18125616/186380078-6a29584c-9598-4fad-be7c-31b9f3e45ace.png)

**Comment by dpfaffenbauer** [comment]
@zekuraz how did you install Pimcore? it seems that there is no default locale set.

**Comment by zekuraz** [comment]
@dpfaffenbauer i follow this https://www.vultr.com/docs/install-pimcore-on-ubuntu-20-04/

**Comment by dpfaffenbauer** [comment]
@zekuraz please check your system.yml for activated languages (var/config/system.yml). There should be a language configured.
