### ISSUE TITLE
jms/serializer-bundle breaking change

### ISSUE THREAD

**Issue by gjorgic** [coreshop/CoreShop#2073]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

I have installed `coreshop/core-shop: 3.0.0-beta.5` and at the some point composer pkg `jms/serializer-bundle` was updated from `4.0.1` to `4.1.0` and that cause following error

![image (23)](https://user-images.githubusercontent.com/3842488/189835317-940ed466-e00f-488a-a4a7-970cf5094a7f.png)

**Comment by jdreesen** [comment]
That's a bug in `v4.1.0` of `jms/serializer-bundle`. See [here](https://github.com/schmittjoh/JMSSerializerBundle/pull/900#issuecomment-1243582502), schmittjoh/JMSSerializerBundle#902 and schmittjoh/JMSSerializerBundle#904

**Comment by dpfaffenbauer** [comment]
maybe we should just make a conflict with 4.1.0 as 4.1.1 might fix it

**Comment by gjorgic** [comment]
so i need just put this in composer.json?
```
...
"conflict": {
    "jms/serializer-bundle": "4.1.0"
},
...
```

**Comment by dpfaffenbauer** [comment]
yes

**Comment by gjorgic** [comment]
Ok, i change this in same MR https://github.com/coreshop/CoreShop/pull/2074
