### ISSUE TITLE
Check in CI the packages installed are actually the packages expected

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2080]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Currently, the Address Bundle Composer package is only available in beta.5 version (it wasn't released on accident). The same goes for Core bundle:

```
    - coreshop/core-bundle 3.0.0 requires coreshop/wishlist-bundle ^3.0 -> could not be found in any version, there may be a typo in the package name.
```

It seems the CI should in some way check if the versions installed are the versions which are expected? Maybe some additional set of composer.json / composer.lock files which only test installability of the packages and check what got installed in some way?

**Comment by dpfaffenbauer** [comment]
We don't have new bundles all the time. This also happened only one time now. if it happens again, we'll do some CI checks
