### ISSUE TITLE
Order view switched currency fields

### ISSUE THREAD

**Issue by lukadschaak** [coreshop/CoreShop#2090]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             |no

Looks like the fields for `currency` and `base_currency` are switched. The translation files looks okay i think.

Found it on your demo3 instance.

![image](https://user-images.githubusercontent.com/2377363/193800144-2e54ba73-06b0-4224-89f4-14a3ec67215f.png)
![image](https://user-images.githubusercontent.com/2377363/193800200-fd378132-0f35-44fb-bc17-f64faeca6ec6.png)

**Comment by dpfaffenbauer** [comment]
@lukadschaak the translation file is wrong... I'll fix it

**Comment by lukadschaak** [comment]
Ah okay. Then this wayaround. Thx :)
