### ISSUE TITLE
Add a wishlist rendering header widget similar to Cart

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2098]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Equivalent to `\CoreShop\Bundle\FrontendBundle\Controller\CartController::widgetAction`.

**Comment by dpfaffenbauer** [comment]
we don't see a need for this for now.
