### ISSUE TITLE
Use renderForm() instead of render() in controllers with form handling

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2099]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

This [makes the controllers compatible with things like Symfony UX Turbo](https://symfonycasts.com/screencast/turbo/forms).

Note, `renderForm()` requires a `Form` instance, not a `FormView` instance which is currently used. It calls `createView()` for you.

Example change:

```diff
-        return $this->render($this->templateConfigurator->findTemplate('Customer/change_password.html'), [
+        return $this->renderForm($this->templateConfigurator->findTemplate('Customer/change_password.html'), [
            'customer' => $customer,
-           'form' => $form->createView(),
+           'form' => $form,
        ]);
```

Places to do:
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\CartController::summaryAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\CartController::shipmentCalculationAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\CartController::addItemAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\CheckoutController::renderResponseForCheckoutStep
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\CustomerController::addressAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\CustomerController::settingsAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\CustomerController::changePasswordAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\OrderController::reviseAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\RegisterController::registerAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\RegisterController::passwordResetRequestAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\RegisterController::passwordResetAction
- [ ] \CoreShop\Bundle\FrontendBundle\Controller\SecurityController::loginAction

**Comment by jdreesen** [comment]
Note that `renderForm()` is deprecated again in Symfony 6.2: symfony/symfony#46854

**Comment by dkarlovi** [comment]
Wow, they had 6 iterations on it already. :D

**Comment by dkarlovi** [comment]
This is obsolete on Symfony 6.2+
