### ISSUE TITLE
Allow Default Address Definition

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#210]
Allow customer to set a default address from addresses stack.

**Comment by dpfaffenbauer** [comment]
done here:
https://github.com/coreshop/CoreShop/commit/513950057276e2e7220b66d81f497931afabc05e
https://github.com/coreshop/CoreShop/commit/d5cf5a1bb92157715d14f07144bfde1d15f60f52
https://github.com/coreshop/CoreShop/commit/ebe7a023a361c88b5cf7bc73a54d5040325a2b42
https://github.com/coreshop/CoreShop/commit/847a1788dab896cb81f2f26b55a2bdbe716ab843
