### ISSUE TITLE
Order can be submitted with deactivated payment provider

### ISSUE THREAD

**Issue by lukadschaak** [coreshop/CoreShop#2107]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Moin!

### Issues desciption
It is possible to create an order with an inactive payment provider by doing following steps in CoreShop 3 Demo:
* Adding any product to cart
* Going to checkout steps always choosing defaults
* Wait on summary page
* Deactivate the only payment provider "Bankwire"
* Go back to summary page an submit the order

### Actual behaviour
The order is submitted

### Expected behaviour
The is not submitted and you will see an appropiate error message

### Additional notes
The save applies for carrier valididation. If `hide from checkout` is marked, the order should not be submitted.

**Comment by TobiSW** [comment]
use quotes is not an option for you? I was having the same usecase, and we decided to use quotes... here it was possible to "order" without payment

**Comment by dpfaffenbauer** [comment]
@lukadschaak right, the Payment Provider is never checked again if valid. This PR fixes it: https://github.com/coreshop/CoreShop/pull/2111

**Comment by dpfaffenbauer** [comment]
fixed

**Comment by lukadschaak** [comment]
thx a lot!
