### ISSUE TITLE
[CartPriceRules] - Error complete order with card price rules based on cart items

### ISSUE THREAD

**Issue by TobiSW** [coreshop/CoreShop#2115]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Referring #2057 

Setup is like the following. 

![image](https://user-images.githubusercontent.com/6861689/202176819-6d85ad1b-081b-45ce-939c-bdd464129938.png)

![image](https://user-images.githubusercontent.com/6861689/202176923-f33d4cff-4909-4180-a60e-dc159ed70c12.png)

![image](https://user-images.githubusercontent.com/6861689/202177084-fb718805-a461-481d-bd9a-b31a684a95f3.png)

After filling out the checkout steps when i click on "buy" i receive this error

![image](https://user-images.githubusercontent.com/6861689/202177259-3d88480b-d2df-43a7-9843-249d482e64c4.png)

**Comment by dkarlovi** [comment]
AFAIK this is fixed in CS 3.0.2

**Comment by dpfaffenbauer** [comment]
yes, thanks @dkarlovi
