### ISSUE TITLE
[StorageListBundle] Installation failing

### ISSUE THREAD

**Issue by aarongerig** [coreshop/CoreShop#2118]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When trying to install/enable the `CoreShopStorageListBundle` following error is thrown:
```log
You have requested a non-existent parameter "coreshop.resources".
```

**Comment by dpfaffenbauer** [comment]
fixed already
