### ISSUE TITLE
Add 10 quantity to cart prevented by stock, add 1 quantity to cart 10x is allowed

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2123]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If a product has 1 in stock and I try to add quantity=10 to cart, it's prevented. It's also prevented if I try to update cart to 10.

But if I add it quantity=1 at a time 10x, it's allowed. The add to cart feature should reuse the update cart logic.

**Comment by dpfaffenbauer** [comment]
cannot be reproduced. If I have 1 in stock and do following scenarios:

 - add 1 to the cart: allowed
 - add 2 to the cart: not allowed
 - add 1 to the cart, go back, add another one: first one allowed, second one not
 - add 1 to the cart and update quantity to 2, first one allowed, second one not.
