### ISSUE TITLE
[UX] customer order locale discoverability very low

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2126]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I was just about to suggest a new feature (remembering the customer's locale in order so we know what language to use to communicate) and I realized it's actually already there, only **really** hidden.

![comment](https://user-images.githubusercontent.com/209225/203362976-f4b9091a-4266-4e94-9b06-1e8226657708.png)

The information shouldn't be shown/hidden depending on the checkbox, it should always be visible, probably above the textarea.

The reason is, you might have already written the comment in fr, select the checkbox and see you should have used de.

**Comment by dpfaffenbauer** [comment]
sure, PR? should be fairly easy

**Comment by dpfaffenbauer** [comment]
@dkarlovi any update on this?

**Comment by dkarlovi** [comment]
Not from my side.
