### ISSUE TITLE
[BUG] The release tag is for a different package

### ISSUE THREAD

**Issue by gander** [coreshop/CoreShop#2136]
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

When updating package information, it fetches dependencies from another package, which breaks the project.

Older releases experience this issue:

+ https://github.com/coreshop/CoreShop/tree/3.0.0-beta.2
+ https://github.com/coreshop/CoreShop/tree/3.0.0-beta.3
+ https://github.com/coreshop/CoreShop/tree/3.0.0-beta.4
+ https://github.com/coreshop/CoreShop/tree/3.0.0-beta.5
+ https://github.com/coreshop/CoreShop/tree/3.0.0
+ https://github.com/coreshop/CoreShop/tree/3.0.1

**Comment by dpfaffenbauer** [comment]
fixed, thanks for letting me know. I have absolutely no idea how that could have happened!

**Comment by solverat** [comment]
@dpfaffenbauer same goes for 2.2.14. Restricted version of 2.2.9 installs 2.2.14 (?)

![image](https://user-images.githubusercontent.com/700119/204741686-152d98eb-0889-4ce8-ac6d-b1025bb04110.png)
![image](https://user-images.githubusercontent.com/700119/204741744-6c592303-e695-45f3-aec1-9708be589911.png)

**Comment by dpfaffenbauer** [comment]
@solverat also fixed
