### ISSUE TITLE
[Spam Protection] Check for Valid Customer in Password Reset Route

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2142]
| Q                | A
| ---------------- | -----
| Bug report?      | sort of
| Feature request? | no
| BC Break report? | no
| RFC?             | no

We're receiving a lot of spam activities lately:  

```bash
Call to a member function setPasswordResetHash() on null
```

```json
{   
"http.flavor": "2.0",   
"http.method": "POST",  
"http.url": "https://xy.com/de/shop/password-reset?activationMode=1&token=97a235a2033c49358493445255514f0d",   
"net.host.name": "www.xy.com", 
"net.host.port": "443",  
"route": "coreshop_customer_password_reset" 
}
```

CoreShop should check if the customer is a valid one here:

https://github.com/coreshop/CoreShop/blob/c4ddac02c7df4a94f4ee363912ddc9a1322913f3/src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php#L109

**Comment by dkarlovi** [comment]
Note, the error provided must not explain the customer is valid or invalid because that allows [enumeration](https://www.upguard.com/blog/what-is-an-enumeration-attack).
