### ISSUE TITLE
Allow multiple named wishlists per user

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2147]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

We could add support to allow multiple wishlists per user. This would mean you could manage your own wish lists and add a new one or delete old ones.

Things to consider:
1. add to wishlist could pass a new argument `name`, it would allow to auto-create the named wishlist if there's none of that name already
2. adding to a named wishlist would make that wish list "the default" so your next add to wishlist would automatically add to that one
3. "add to wishlist" form could then have a dropdown to allow selecting a current list or text input to create a new one (it would just modify the `name` argument in 1)
4. the wish list summary would have the same dropdown where you're able to switch which list you're currently looking at
5. on the summary you'd be able to delete the current list (or share it, see #2146)

Example:
1. new user arrives
2. they add a product to the wishlist without choosing, a new wishlist `Default` is created and marked as "current" (default name up for discussion)
3. they add a product to the wishlist without choosing, it goes to the `Default` wishlist
4. they add a product to a wishlist they name `Kitchen`, a new wishlist `Kitchen` is created and marked as "current"
5. they add a product to the wishlist without choosing, it goes to the `Kitchen` wishlist
6. they go to wishlist summary, `Kitchen` wishlist is displayed (current)
7. they switch to `Default`, `Default` wishlist is displayed and marked as "current"
8. they delete `Default` wishlist, it's deleted and summary shows `Kitchen` wishlist (since it was "current", we now use last modified)
9. they delete `Kitchen` wishlist, it's deleted and summary shows "No items in wishlist"
10. they add a product to the wishlist without choosing, a new wishlist `Default` is created and marked as "current" (same as 2)

**Comment by dkarlovi** [comment]
Thinking about this, the default list is actually "the wishlist", the others are "shopping lists", as in products which are in some way special for the user to be grouped together.

For example, the user could have a shopping list called "Cleaning supplies" prepared, they occasionally put the contents of that list in the cart and buy it, they still want to keep the list after they're done. They don't "wish" it, they want to have a list prepared so they don't need to always look for items they always get. This is a subtle wording difference, functionally it's exactly the same.

**Comment by BlackbitDevs** [comment]
Is this done after #2150 has been merged?

**Comment by dkarlovi** [comment]
@BlackbitDevs no, this is different: that one allows you to make a whishlist public. This issue is describing being able to have multiple wishlists.

**Comment by dpfaffenbauer** [comment]
possible now in 4.1, implemented for carts, can be adapted for wishlists as well. since both use the StorageList Component
