### ISSUE TITLE
coreshop 3 | cart-price-rule | voucher not working

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#2154]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Defining voucher rule as cart-price-rule, not product-price-rule.

See pictures below:
![grafik](https://user-images.githubusercontent.com/23456403/206128466-92cf86bb-718c-4c7a-a5c4-7bab54d013ea.png)

![grafik](https://user-images.githubusercontent.com/23456403/206128530-3ee522ee-d226-46ad-9b7f-151710010440.png)

![grafik](https://user-images.githubusercontent.com/23456403/206128589-7f8693dc-af52-4695-b9c2-614b9b038f29.png)

![grafik](https://user-images.githubusercontent.com/23456403/206128697-9de2dbbe-a772-473a-b196-53a386dba19c.png)

When trying to use generated voucher-code in cart - nothing happens, code is not applied

![grafik](https://user-images.githubusercontent.com/23456403/206129373-f114c7cf-7904-4d65-9a46-42bfbe6fa77e.png)

After apply:
![grafik](https://user-images.githubusercontent.com/23456403/206129482-b9834847-ed88-4fcb-88f1-d7205a201774.png)

No error, voucher is not applied, here 1% less of product price.

**Comment by dpfaffenbauer** [comment]
I don't understand the issue, please elaborate

**Comment by valentin-** [comment]
When pressing enter (while the input field is active), the cart update will get triggered. Pressing the button (Apply) triggers the voucher.

You also get the notification for the cart update, there would be a different notification if the voucher gets applied.

Probably that's the issue.

**Comment by dpfaffenbauer** [comment]
@valentin- thanks, I'll close this ticket for inactivity though.
