### ISSUE TITLE
coreshop 3 | double notification email on user register

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#2155]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When a new user is registered in shop, the notification email for the customer is always sent twice

Notification rule is configured as follwed:
![grafik](https://user-images.githubusercontent.com/23456403/206131267-20650b49-4585-4726-b211-9c1e01e41698.png)

![grafik](https://user-images.githubusercontent.com/23456403/206131350-1fb3b9ae-4b07-4acf-811b-7072b289cbd0.png)

![grafik](https://user-images.githubusercontent.com/23456403/206131475-9471e771-8b45-47d1-a31c-4eab1f3bb742.png)

Email to customer, here: /en/shop/email/user-registered, should only be sent once.

**Comment by dpfaffenbauer** [comment]
there have been some improvements to this and we never had the issue in our installations. therefore I'll close this.
