### ISSUE TITLE
Forgot password email not sending

### ISSUE THREAD

**Issue by valentin-** [coreshop/CoreShop#2162]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi, I've updated to the latest dev-master version. The email including the reset password link won't get send anymore. Switching back to the version I used before emails are sent again. Could you check your dev installation if it's still working using the latest version? 

I've also updated other dependencies so I'm not extactly sure if it's an CoreShop issue or probably caused by other packages.

Thanks!

**Comment by dpfaffenbauer** [comment]
did you read the changelog and added the messenger consumer? https://github.com/coreshop/CoreShop/blob/master/CHANGELOG-3.0.x.md

**Comment by valentin-** [comment]
Sorry I've missed that part, it's working now. Thanks!
