### ISSUE TITLE
Shipping rule conditions if total is 0

### ISSUE THREAD

**Issue by valentin-** [coreshop/CoreShop#2178]
| Q                | A
| ---------------- | -----
| Bug report?      | yes (amount condition from = 0)
| Feature request? | yes (amount condition based on total price)
| BC Break report? | no
| RFC?             | no

Hi, I'd like to add a shipping condition based on the total price.

- If the price is 0 there should be a shipping option with free shipping
- The other shipping rules should get applied, if the total price is > 0

Currently the amount condition is based on the subtotal, not the total price - therefore it won't apply if the total price is 0 at the end.

![image](https://user-images.githubusercontent.com/90033/213455605-6a640739-818a-43c5-ba35-cd24d8aba37b.png)

Also I'd like to set from = 0 / to = 1 for the free shipping option (and from = 1 / to = 0/null for the paid options), but setting 0 as from value is not possible currently.

![image](https://user-images.githubusercontent.com/90033/213456081-6ae1ee85-940b-4f82-b9c4-3a3b42c6d5de.png)

Thanks in advance! 
Valentin

**Comment by dpfaffenbauer** [comment]
@valentin- what is the total of your order? I guess it is has a shipping applied to it right?

**Comment by valentin-** [comment]
@dpfaffenbauer no there is no difference between selecting a shipping with/without a price, regarding the available shipping options based on the price.

It will only display if the max price is higher than the subtotal.

![image](https://user-images.githubusercontent.com/90033/216069879-15ea1290-13b6-4b13-ba26-6ff4ce048faf.png)
![image](https://user-images.githubusercontent.com/90033/216070045-67ea3cb9-4749-466a-9406-9f4ea90e8630.png)

**Comment by valentin-** [comment]
@dpfaffenbauer could we check on this again? Thank you

**Comment by dpfaffenbauer** [comment]
@valentin- sure, can you elaborate the problem more detailed pls? I cannot really seem to understand the issue.

**Comment by valentin-** [comment]
So I'd like to add shipping rule (free) with 0 € if the total cart price is 0.

- I've added a product to the cart -> 22,90
- Apply a cart rule -100%
- Subtotal -> 22,90
- Total -> 0

Therefore I'd like to add a shipping rule which shows up when the total price <= 1. 

But the max price is based on the subtotal, not on the total. Therefore the rule for max <= 1 can't be used.

The "free" shipping rule only shows up, if max price is > subtotal.

![image](https://user-images.githubusercontent.com/90033/224984846-13494205-ee21-41c6-8ad8-8f4ab5fbaa09.png)
![image](https://user-images.githubusercontent.com/90033/224985530-38e8190b-0183-4fbd-aa1b-6de2f52d8137.png)

I'd like to show the rule if the total price <= 1

![image](https://user-images.githubusercontent.com/90033/224984937-8b0fa579-d52b-4f60-a28f-f19e81dc21f9.png)

Is it clearer now? Thanks for your support.

**Comment by dpfaffenbauer** [comment]
@valentin- for me it seems to work, this is my setup:
![Screenshot 2023-03-15 at 14 57 40](https://user-images.githubusercontent.com/5981845/225331199-b2e13d72-12f7-403c-b409-a0c770a91604.png)
![Screenshot 2023-03-15 at 14 57 44](https://user-images.githubusercontent.com/5981845/225331205-a640f5d6-6976-4ae3-8e4f-2587a0ce49e5.png)
![Screenshot 2023-03-15 at 14 57 47](https://user-images.githubusercontent.com/5981845/225331208-c9c8029d-9501-467b-9ce6-953256f2cbab.png)
![Screenshot 2023-03-15 at 14 57 49](https://user-images.githubusercontent.com/5981845/225331213-dfa2d311-9d2f-46a3-a9b9-d51899d27f64.png)

**Comment by valentin-** [comment]
Hi @dpfaffenbauer, 

indeed it works with min = 0 and max = 0. But to switch the options I'd like to set following rules:

Free shipping: Min 0, Max 1 (not visible anymore) -> only works with 0/0
Other shipping (paid): Min 1, Max 0 (or 999999) -> only get's hidden if min > subtotal, not the total

Also I've experienced an error when switching from shipping method with shipping costs to a free shipping method. Should there be a summary redirect added if the cart is free (without payment)?

![image](https://user-images.githubusercontent.com/90033/226282849-5f31c5f1-18d1-4a40-99c5-705a041534c1.png)

Thanks!

**Comment by dpfaffenbauer** [comment]
Ok, I think the problem is that the shipping is part of the "total" cart value. Does it help if you add change the following line:

src/CoreShop/Component/Shipping/Rule/Condition/AmountConditionChecker.php:34 to 

```php
$totalAmount = min(0, $shippable->getSubtotal($gross) - $shippable->getAdjustmentsTotal(AdjustmentInterface::SHIPPING));
```

**Comment by dpfaffenbauer** [comment]
@valentin- then we have a fix :), I'll create a PR

**Comment by dpfaffenbauer** [comment]
@valentin- I made some changes to the PR. Basically I've added a checkbox in the amount configuration to use the total value, could you test that on your side? https://github.com/coreshop/CoreShop/pull/2238

**Comment by dpfaffenbauer** [comment]
ping @valentin-

**Comment by valentin-** [comment]
@dpfaffenbauer I was on vaccaction last week. 
I checked out the latest commit and tested it locally, works as expected. 

Thank you!
