### ISSUE TITLE
coreshop 3 - cart price rule - strange behaviour - wrong calculation

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#2180]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

a cart price rule for surcharge is defined, when order-volume is below 5000,-
the surcharge is 200,- as fixed value, not percentual.

When customer is ordering between 200+ and below 5000, the surcharge works as expectred, 200,- are added to the cart. correct 

When customer is having below 200,- in cart, the article-price seems to be added as surcharge and not 200,- - which is wrong.

definition of rule is posted below.

![image](https://user-images.githubusercontent.com/23456403/213678196-e04a9b90-823e-4d27-8948-4d814dca7b08.png)

![image](https://user-images.githubusercontent.com/23456403/213678288-bd8dd35f-7078-4c95-a96b-35d7bf1831dd.png)

![image](https://user-images.githubusercontent.com/23456403/213678359-7fd5ae6e-ca13-40fe-926e-8c11910a9402.png)

user having below 200 in cart:
![image](https://user-images.githubusercontent.com/23456403/213678502-42926115-d0e4-430f-a4a4-e2bcc744d8ae.png)
with wrong value = article-price as surcharge

user having above 200 in cart:
![image](https://user-images.githubusercontent.com/23456403/213678702-5b0fb503-826d-43d9-891e-991417f025e9.png)

**Comment by JustMe69** [comment]
Still not working.
Took actual coreshop dev-master version from today.

![image](https://user-images.githubusercontent.com/23456403/218665983-b096f847-a4dd-40a2-a3ad-c5d7be21f16f.png)

**Comment by JustMe69** [comment]
![image](https://user-images.githubusercontent.com/23456403/218666968-817ccc9c-2f23-4eaf-8616-1a962c86a90a.png)

@dpfaffenbauer 

still not working, with actual coreshop version off dev-master, today

**Comment by dpfaffenbauer** [comment]
@JustMe69 try 3.0.x-dev

**Comment by JustMe69** [comment]
@dpfaffenbauer tried, not working 
cleared cache (rm -rf), migrations are executed, deleted cart, etc
same picture

**Comment by dpfaffenbauer** [comment]
please try to make it reproducible on the demo then.

**Comment by JustMe69** [comment]
@dpfaffenbauer 
done in demo
added cart-price-rule surcharge 300, name: minOrder

![image](https://user-images.githubusercontent.com/23456403/218675137-4988dc14-fa35-4d09-b781-f37d2c348820.png)

surcharge is same price as article price

**Comment by dpfaffenbauer** [comment]
good, I'll check again then

Thanks

**Comment by dpfaffenbauer** [comment]
@JustMe69 Fix is not yet merged into master, the CoreShop Demo is deployed into master, if I apply the fix to the demo, it works. (Try again please on the demo)
