### ISSUE TITLE
Review.io Integration

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2181]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Provide an Integration for https://www.reviews.io/front/integration-library

Maybe a topic for a crowd-funded / sponsored / baked feature. :)

**Comment by solverat** [comment]
BTW: Maybe you could enable the Discussion-Section for this repo.

**Comment by dpfaffenbauer** [comment]
I don't see that as a Core Feature for CoreShop. Should be either community provided or someone creates a general Pimcore Bundle for an integration.

**Comment by solverat** [comment]
That's why i suggested opening the discussion section, because of course that should not be a core feature...
