### ISSUE TITLE
coreshop_carrier_stores has wrong column names

### ISSUE THREAD

**Issue by BlackbitDevs** [coreshop/CoreShop#2186]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | maybe
| RFC?             | no

The column names in table `coreshop_carrier_stores` are wrong. I am surprised that it nevertheless works (probably Doctrine fetches the columns via numeric indexes instead of column names):

`SHOW CREATE TABLE` returns:
```sql
CREATE TABLE `coreshop_carrier_stores` (
  `store_id` int NOT NULL,
  `carrier_id` int NOT NULL,
  ...
  CONSTRAINT `FK_E7EE2F7C21DFC797` FOREIGN KEY (`carrier_id`) REFERENCES `coreshop_store` (`id`),
  CONSTRAINT `FK_E7EE2F7CB092A811` FOREIGN KEY (`store_id`) REFERENCES `coreshop_carrier` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
```

Background:
We had an issue that a carrier did not appear in the shipping step in the checkout. We analyzed the cause and it only works when we disable result cache in https://github.com/coreshop/CoreShop/blob/100b1b3b90fbc876ce22610232b38549b5be5586/src/CoreShop/Bundle/CoreBundle/Doctrine/ORM/CarrierRepository.php#L31 by adding `->useResultCache(true)`. [Doctrine Docs](https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/reference/caching.html#result-cache) only mention that the cache gets cleared via TTL. Maybe this is the cause that when you change a configuration, the cache also has to be cleared - or does this already get done? And I don't know if this caching issue has anything to do with the wrong column names... just wanted to document it here.

**Comment by dpfaffenbauer** [comment]
What is wrong there?

**Comment by BlackbitDevs** [comment]
Please look at the foreign key. Column `carrier_id` references `coreshop_store (id)` and column `store_id` references `coreshop_carrier (id)`.

**Comment by dpfaffenbauer** [comment]
@BlackbitDevs yes, you are right. The column names are wrong. I'll write a fix and a migration for it

**Comment by dpfaffenbauer** [comment]
@BlackbitDevs could you test the migration? https://github.com/coreshop/CoreShop/pull/2187

**Comment by dpfaffenbauer** [comment]
ping @BlackbitDevs

**Comment by BlackbitDevs** [comment]
In the database it looks good, all existing data is preserved but in Pimcore backend I do not see the assigned stores:
<img width="1663" alt="Bildschirmfoto 2023-02-06 um 12 59 39" src="https://user-images.githubusercontent.com/8749138/216966057-5f17cf3a-a70c-4486-8722-94ddecb056bf.png">

Probably I have to apply the changes for the XML file, I have tried with `bin/console cache:clear`. Have I missed something?

**Comment by dpfaffenbauer** [comment]
@BlackbitDevs but they are displayed there? I guess that DPD is ID 4 and has 2 stores: animal-care_B2B and anima-care_B2C?

<img width="1007" alt="217034633-91cf8883-f92c-424a-baea-6a12967d57cb" src="https://user-images.githubusercontent.com/5981845/217193361-b7498207-a603-4903-b9d0-1ae38d174849.png">

**Comment by BlackbitDevs** [comment]
Yes, everything looks good. I think you only read the email notification - but after running `pimcore:cache:clear` I had changed my comment.
The only open question is if an additional migration is a good idea which clears the cache. Without clearing data cache, the assigned stores are not shown in the carriers settings and probably also not in frontend but I have not tested this

**Comment by dpfaffenbauer** [comment]
ah ok, gotcha. sorry, I was reading the email I got and replied to that. I don't wanna clear a Pimcore Cache with a migration, that should happen after the migration is done manually (or automated in your deployment pipeline)
