### ISSUE TITLE
Cart Item Adjustment Calculation

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2190]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

As a commerce manager, I want to add some discount/surcharge to the **cart**.

Given: 
A Cart Price Rule
![image](https://user-images.githubusercontent.com/700119/215482012-bf0aa38c-0422-48ba-b643-f487e401cab3.png)

Adding two products to the cart:
![image](https://user-images.githubusercontent.com/700119/215482333-dbd2a8aa-0a9f-4cf5-988d-0f8c80ff6f5a.png)

Expecting: 
- 🟢 The applied discount/surcharge as a standalone declared entry (given, see row "DD")
- 🟢 The applied discount/surcharge in the summary (given, see rows "surcharge inc/excl vat)
- ⚠️ Same item price as before (not given)
- ⚠️Optional: (There is also a glitch in the price view - instead of the original price, the applied adjustment total will be shown)

*** 

In CS2 the cart item looked like this:
![image](https://user-images.githubusercontent.com/700119/215483672-0b4141bf-d47f-428e-be5d-6faa8dec42eb.png)

In CS3 the cart item looks like this:
![image](https://user-images.githubusercontent.com/700119/215483788-746e2f90-9414-4853-ac9c-b6153be94624.png)

**

I guess that's happening because of the newly introduced cart/order transition. While the cart discount / surcharge gets partitioned onto each cart item, the item price itself should stay intact.

**Comment by dpfaffenbauer** [comment]
@solverat that is intentional, discounts/surcharges get applied to each single order-item. Reason for this is refunding, example:

Order Item: 100
Order Discount: 20

Order Item therefore only costs: 80

No wanna refund the customer, you can only refund him 80€ for the item, since the discount get's applied to all order-items.

**Comment by solverat** [comment]
Yes, got that. I think, internally, this should stay that way. 

But for the customer himself, the rendered view is quite confusing.
It's getting even more confusing if you're going to add a product price rule (-25%):

![image](https://user-images.githubusercontent.com/700119/215487455-0a7ca360-5603-40e1-9dce-a13b4be8f841.png)

Maybe the OrderItem should provide another method which provides the calculated item price without the charged/subtracted cart rules.

**Comment by dpfaffenbauer** [comment]
You got the subtotal on the order-item, that is the item price without adjustments

**Comment by dpfaffenbauer** [comment]
@solverat It's also on purpose this price ;) template could be more verbose to show both prices maybe. 

what ui issue you mean?

**Comment by solverat** [comment]
![image](https://user-images.githubusercontent.com/700119/215491400-4be58316-1883-4773-96b5-914781924763.png)
In this case, the reduced price should be the subtotal

**Comment by dpfaffenbauer** [comment]
@solverat No, it depends on the use-case. Surcharges are definitely a worse example than discounts. But in some use-cases you wanna show the actual price the customer pays (=subtotal) and in other cases you wanna show the non-discounted-item-price (total)

**Comment by solverat** [comment]
@dpfaffenbauer still not sure if this is good enough.

Example:
- OrderItem with 100,-
- I'm adding an extra option "Add Custom Text" (Adjustment) to the OrderItem with 20,-
- Customer expects 120,- as item total in cart

How to display that in the cart?

- I'm not able to use the `item.getTotal` in view (because of applied rules (`distributedAmount`) → misleading output)
- I'm not able to use the `item.getSubtotal` in view (because of missing applied adjustments)

I currently fixed it with a custom twig helper:

```php
public function assertItemSubtotalWithAdjustments(OrderItemInterface $item, bool $withTax = true): int
    {
        $subTotal = $item->getSubtotal($withTax);

        foreach ($item->getAdjustments('additional_options') as $adjustment) {
            $subTotal += $adjustment->getAmount($withTax);
        }

        return $subTotal;
    }
```

**Comment by dpfaffenbauer** [comment]
@solverat So how do we differentiate adjustments that should be shown and should not be shown?
