### ISSUE TITLE
Migration fails for overwritten objects

### ISSUE THREAD

**Issue by valentin-** [coreshop/CoreShop#2199]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi, I've extended the object CoreShopOrder.

![image](https://user-images.githubusercontent.com/90033/216298002-b8ce09cd-aa70-43c3-a950-0091263da9c1.png)

![image](https://user-images.githubusercontent.com/90033/216296850-75974b5b-276e-43c0-b9bc-6e7a4e5f3bca.png)

When running a migration an error is thrown 
![image](https://user-images.githubusercontent.com/90033/216298232-b3e861e5-80f9-4656-b040-a9da89dfbc6c.png)

Example migration:
https://github.com/coreshop/CoreShop/blob/c4ddac02c7df4a94f4ee363912ddc9a1322913f3/src/CoreShop/Bundle/CoreBundle/Migrations/Version20220330153600.php#L39

... as getByName() returns null, but null can't get assigned to $this->classDefinition therefore an error is thrown before the exception is triggered.

https://github.com/coreshop/CoreShop/blob/56cf0a2cfa79d146141012cb0da276d348aa451d/src/CoreShop/Component/Pimcore/DataObject/ClassUpdate.php#L33

Did I miss something in the configuration or is there a problem with migrations using custom models?

Thanks!

**Comment by dpfaffenbauer** [comment]
the Configured class always has to be a Pimcore DataObject Class, not a Pimcore Class

**Comment by valentin-** [comment]
@dpfaffenbauer I extended the data object as explained in https://docs.coreshop.org/3.0.0/Development/Extending_Guide/Extend_CoreShop_DataObjects.html

The class name is fetched by 

`$orderClassName = $this->container->getParameter('coreshop.model.order.pimcore_class_name');`

It's a Coreshop migration, how would I control this?

**Comment by dpfaffenbauer** [comment]
you did not do it right though. you have this:

![image](https://user-images.githubusercontent.com/5981845/216622563-ed26d2dd-03f6-4d13-a7e7-7e49da709379.png)

But that has to be a Pimcore DataObject. So in Order to extend the class, you should change the parent class in Pimcore's class definition.

**Comment by valentin-** [comment]
I followed the steps as described in the gitter thread, it's working now: https://gitter.im/coreshop/CoreShop?at=5f6215f4ce5bbc7ffdcb6a81

Thanks for clarification.

**Comment by dpfaffenbauer** [comment]
@valentin- Maybe you can make a PR to clarify that in the docs?
