### ISSUE TITLE
[Filters / Indexes] Index select field option label (display name) instead of value

### ISSUE THREAD

**Issue by BlackbitDevs** [coreshop/CoreShop#2222]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? |no
| RFC?             | yes

When you create an index on a select field, then the select option value will get stored in the index table. It would be good if there was a way to index the select field display names. In our case, the option values are 1, 2, 3 with speaking names as "display name". When I use this index for a filter currently shared translations with keys 1, 2, 3 get created which makes it impossible to translate because other select fields have different options with values 1, 2, 3.

Is there a way to index the select field option display name?

**Comment by dpfaffenbauer** [comment]
We either create a interpreter to index the values or you use the twig helper to get the values from the Class Definitions.

**Comment by dpfaffenbauer** [comment]
@BlackbitDevs For UI output, you are responsible for how the values are translated to text.
