### ISSUE TITLE
CoreShop\Bundle\CoreBundle\EventListener\NotificationRules\OrderWorkflowListener same state in both from and to

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2229]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When the listener is handling `Symfony\Component\Workflow\Event\CompletedEvent`, the marking is already in the "to" state, but currently it's assuming the transition is still to take place:

https://github.com/coreshop/CoreShop/blob/eda4722b05d14cc07a00a03bb4148b9ff87c5ef9/src/CoreShop/Bundle/CoreBundle/EventListener/NotificationRules/OrderWorkflowListener.php#L48-L49

At this time, the marking already changed and the "to" should be read from it, not "from".

**Comment by dkarlovi** [comment]
@dpfaffenbauer this is a bug. :smile:

**Comment by dpfaffenbauer** [comment]
@dkarlovi this is now more then a year old and hasn't caused any other issues. I'll close it for now, if its still an issue let me know.
