### ISSUE TITLE
Cart empty after logout

### ISSUE THREAD

**Issue by Nesfiran** [coreshop/CoreShop#2233]
Hi there,

I need your help. When logging out of Coreshop, the user loses his complete shopping cart and cannot continue ordering when returning to the job. He has to start his order again from the beginning. 

Is it possible to set this so that the shopping cart remains until it is sent?

Many greetings

**Comment by dpfaffenbauer** [comment]
@Nesfiran I cannot reproduce your issue. If you login or register, the cart gets attached to the user. If you then logout, the cart is gone. If you login again, you get the cart again.
