### ISSUE TITLE
Unable to register coreshop.context.cart Services

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2239]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Registering a custom cart context is not possible anymore:

```yaml
    App\MyCartContext:
        tags:
            - { name: coreshop.context.cart, priority: -778 }
```
Reason: The Initialization of `RegisterStorageListPass` in`CoreShopStorageListExtension` won't recognize services from other Bundles at this point:

https://github.com/coreshop/CoreShop/blob/75d7f0b2e8d72b9537c948d896c8e6d2e27bd356/src/CoreShop/Bundle/StorageListBundle/DependencyInjection/CoreShopStorageListExtension.php#L204-L208

**Comment by dpfaffenbauer** [comment]
@solverat can you check if this would work instead?

```php
$container->addCompilerPass(new RegisterStorageListPass(
                $list['context']['interface'],
                $contextCompositeServiceName,
                $list['context']['tag'],
            ));
```
