### ISSUE TITLE
[Index Bundle] Pimcore 10.6 compatibility

### ISSUE THREAD

**Issue by aarongerig** [coreshop/CoreShop#2290]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

When installing the latest Pimcore verison `10.6` the required `coreshop/index-bundle` with version `3.0.x-dev` does not work, respectively the CoreShop Menu doesn't show up in the Pimcore back-end.

**Comment by jdreesen** [comment]
Maybe fixed by #2285?

**Comment by dpfaffenbauer** [comment]
@jdreesen separate issue.
