### ISSUE TITLE
[Tracking] GA4 support

### ISSUE THREAD

**Issue by BlackbitDevs** [coreshop/CoreShop#2297]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Support for Google Analytics tracking with the "universal" mode ends on 31.07.23. It will be replaced by GA4. Are there any plans / existing solutions to support this tracking method?

**Comment by dpfaffenbauer** [comment]
@BlackbitDevs Yes, we will add it soon.

**Comment by BlackbitDevs** [comment]
Are you already working on it? Or can we support? Because we currently have a client who is interested in this and we may provide the implementation as a PR.

**Comment by dpfaffenbauer** [comment]
Well, we need it in about 2 weeks time, if you already have it, or need it sooner, you can create a PR ;)

**Comment by BlackbitDevs** [comment]
Currently we only have a client's requirement ;-)
Ok, then we will wait. If you need any help during implementation or testing, just notify me...

**Comment by dpfaffenbauer** [comment]
@BlackbitDevs Alright then :)
