### ISSUE TITLE
[Form] Check if Forms are submitted before dispatch Validation 

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2302]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Instead of calling instantly `$form->isValid()` we need to check `$form->isSubmitted()`.
Otherwise an exception will raise:

```Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid().```

This message occurs in our monitoring logs when spambots try to submit forms via curl (which won't work anyway because of the missing csrf token.

**Comment by dpfaffenbauer** [comment]
@solverat For what forms did you find this happening?

**Comment by solverat** [comment]
https://github.com/coreshop/CoreShop/blob/a1a456fdefaa259f791cc3a0b04c05be183948e5/src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php#L55-L58

Besides (like discussed [in #123](https://github.com/coreshop/CoreShop/discussions/2442)), `isSubmitted()` should be used generally instead of using `in_array($request->getMethod(), ['POST', 'PUT', 'PATCH'])`.

**Comment by dpfaffenbauer** [comment]
What is the Benefit of just using handleRequest and not checking the method on our own and then using handleRequest?

**Comment by dpfaffenbauer** [comment]
@solverat That is solved now. We only added the isSubmitted. Every other form does that already
