### ISSUE TITLE
[CoreShop2] FrontendBundle CategoryController::indexAction() - wrong config keys

### ISSUE THREAD

**Issue by ktallafus** [coreshop/CoreShop#232]
Hi,

"system.category.grid.per_page_default" should be "system.category.grid.per_page.default" and
"system.category.list.per_page_default" should be "system.category.list.per_page.default"

That's at least what they are called in the config table.

Regards, 
Kai

**Comment by dpfaffenbauer** [comment]
Hi,

thats right. Could you create a PR please?

Cheers

**Comment by solverat** [comment]
fixed with #233.
