### ISSUE TITLE
[PaypalExpressCheckout] - ConvertPaymentAction hardcoded to total with tax

### ISSUE THREAD

**Issue by TobiSW** [coreshop/CoreShop#2325]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Currently when using build in paypal express checkout the order total is hardcoded to include always with tax to be sent to paypal.
https://github.com/coreshop/CoreShop/blob/bdf043a4b355a0a1ce0389805dfa9f2a5f3471d3/src/CoreShop/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php#L50

I worked it around to override the ConvertPaymentAction class in my case but would be maybe nice to have this somehow configurable, any ideas?

**Comment by dpfaffenbauer** [comment]
why would you not need to gross total?

**Comment by TobiSW** [comment]
Its a B2B shop and they use only net amount for countries in the EEA

**Comment by dpfaffenbauer** [comment]
then you should change how the Tax is calculated.

**Comment by TobiSW** [comment]
Ah within a changed tax rule you mean?

**Comment by dpfaffenbauer** [comment]
Yes, or overwrite the `TaxApplicator`: src/CoreShop/Component/Core/Taxation/TaxApplicator.php

**Comment by TobiSW** [comment]
I just checked it, the changed tax rule just did the trick! Many thx, i was not having this in my mind!
