### ISSUE TITLE
Set store-specific tax rules

### ISSUE THREAD

**Issue by BlackbitDevs** [coreshop/CoreShop#2334]
Imagine a company with subsidiaries in multiple countries. The whole company uses the same Pimcore. The different subsidiaries are responsible for their sites and pages. The subsidiaries trade for own account (so on public websites subsidiary 1 has a different imprint than subsidiary 2). 
Currently the tax rules are only based on the country of the customer but not on the country of the store.

Example:
Store 1 is run by subsidiary in country DE
Store 2 is run by subsidiary in country UK

Customer 1 from DE orders in Store 1:
-> shipping rule for DE applies 19% VAT

Customer 2 from UK orders in Store 1:
-> shipping rule for UK applies 0% VAT (foreign country outside of EU)

Customer 3 from DE orders in Store 2:
-> ???

Customer 4 from UK orders in Store 2:
-> ???

Possible solutions:
1. Currently, on product level only one tax rule is selectable. For products which are sold in store 1 and 2, it is not possible to assign different tax rules. 
    Solution: Allow store-specific tax rules
2. Tax rules currently do not care about stores. If it was possible to set the stores which a tax rule shall be valid for, the problem would also be solvable.

Or is there a existing solution which I have not taken into account?

**Comment by dpfaffenbauer** [comment]
@BlackbitDevs no, you are right. TaxRule should be store related and the StoreValues should also allow to select a TaxRule.

**Comment by dpfaffenbauer** [comment]
will come with 4.1. 4.0 is targeted to be the same as 3.1 to make updates easier

**Comment by dpfaffenbauer** [comment]
lands in 4.1.0
