### ISSUE TITLE
SebastianBergmann\Diff\Differ with empty constructor not allowed

### ISSUE THREAD

**Issue by johanlindgren** [coreshop/CoreShop#2349]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

When installing the next 4.0 release on Pimcore 11 I get

----
Too few arguments to function SebastianBergmann\Diff\Differ::__construct(), 0 passed in /var/www
  /html/pimcore/var/cache/dev/ContainerTxbOp1q/getConsoleDifferService.php on line 24 and exactly
  1 expected
----

It seems to be

coreshop/core-shop/src/CoreShop/Bundle/ClassDefinitionPatchBundle/Resources/config/services.yml

that needs to be able to add SebastianBergmann\Diff\Differ with empty constructor, which is not allowed by the version used

If I require sebastian/diff  ^4.0 the problem is solved

**Comment by dpfaffenbauer** [comment]
@johanlindgren that has been fixed in 3.1. but not yet merged into next: https://github.com/coreshop/CoreShop/commit/cc8286987de690bd48191ec5d8ab9b246af7a770
