### ISSUE TITLE
CoreShop attribute newsletterActive needs PimcoreNewsletterBundle?

### ISSUE THREAD

**Issue by johanlindgren** [coreshop/CoreShop#2350]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

When installing Coreshop ^4.0 on Pimcore 11 I get 

---
In Service.php line 364:

  Could not add child array (
    'name' => 'newsletterActive',
    'title' => 'coreshop.customer.newsletter_active',
    'tooltip' => '',
    'mandatory' => false,
    'noteditable' => false,
    'index' => 0,
    'locked' => false,
    'style' => '',
    'permissions' => NULL,
    'fieldtype' => 'newsletterActive',
    'relationType' => false,
    'invisible' => false,
    'visibleGridView' => false,
    'visibleSearch' => false,
    'defaultValue' => NULL,
    'defaultValueGenerator' => '',
    'datatype' => 'data',
  )
---

The problem seems to be solved if I install PimcoreNewsletterBundle before I install Coreshop

**Comment by dpfaffenbauer** [comment]
related to https://github.com/coreshop/CoreShop/issues/2351
