### ISSUE TITLE
CoreShop 4 install documentation 

### ISSUE THREAD

**Issue by johanlindgren** [coreshop/CoreShop#2351]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

It looks like the documentation for install of CoreShop 4 on Pimcore 11 needs to be updated

- Enable of bundles needs to be done in config/bundles.php an not using console command
- Manual config of config/packages/security.yaml is needed

**Comment by dpfaffenbauer** [comment]
@johanlindgren we are aware of that, CoreShop has certain dependencies to the new pimcore bundles (for example simple-backend-search) and others too. We are on that.

**Comment by dpfaffenbauer** [comment]
@johanlindgren Better idea: CoreShop just enables and installs them ;)

**Comment by StefanRaatz** [comment]
@dpfaffenbauer @johanlindgren I'm fairly new to Pimcore and Coreshop, maybe you can help me what needs to be changed in the bundles.php and security.yaml to get CoreShop4 installed with Pimcore 11 it seems that some changes are already applied, but the install documentation still mentiones the  `php bin/console pimcore:bundle:enable CoreShopCoreBundle`, happy to write up an update for the installation documentation if I get it running.

Thanks in advanced
Stefan

**Comment by dpfaffenbauer** [comment]
@StefanRaatz what issue do you have with the installation? How can I help?

**Comment by StefanRaatz** [comment]
@dpfaffenbauer thanks for for quick reply.

I went trough the installation documentation on the github page, everything is working fine until I need to enable the bundle with the following command:

`php bin/console pimcore:bundle:enable CoreShopCoreBundle` 

It seems that the pimcore:bundle:enable command is deprecated, so I need to figure out how to enable the bundle so the 
`php bin/console coreshop:install` will work properly.

**Comment by dpfaffenbauer** [comment]
ah, gotcha. you can do it like this: https://github.com/coreshop/CoreShop/blob/4.0/src/Kernel.php#L28

**Comment by StefanRaatz** [comment]
@dpfaffenbauer thanks, will try it out and give you feedback. Thanks for you support mate.

Cheers,
Stefan

**Comment by dpfaffenbauer** [comment]
No worries, cheers mate 🍻

**Comment by StefanRaatz** [comment]
Hi @dpfaffenbauer your help moved me a step closer but now I have the problem mentioned in Issues #2366 is the fix #2362 already moved into the beta branch or do you have another dev branche which I can install?

**Comment by dpfaffenbauer** [comment]
`composer req coreshop/core-shop:4.0.x-dev`

Will do another Beta Release beginning of next week.

**Comment by StefanRaatz** [comment]
@dpfaffenbauer thanks will look at the dev branche and for the next Beta Release.
