### ISSUE TITLE
MainObjectId Setter 

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2375]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In Version 2.x, the `CartItemToSaleItemTransformer` also stored the main object ID of a given variant.
This Method has been removed without any notes, which has caused us some serious problems.

However, I don't know if you want to re-add this feature via `CartItemProcessor` but there are several orphans (especially reports, which won't work without it):

https://github.com/search?q=repo%3Acoreshop%2FCoreShop%20mainobjectid&type=code

**Comment by dpfaffenbauer** [comment]
we can for sure add it again in a Processor
