### ISSUE TITLE
Inconsistent tax calculation with higher precision

### ISSUE THREAD

**Issue by lukadschaak** [coreshop/CoreShop#2377]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

**Description**
In special price and tax rate situations the tax and subtotals get wrong rounded cent values.

**Steps to reproduce**
* Change core_shop_currency.money_decimal_factor = 10000
* Change core_shop_currency.money_decimal_precision = 4
* Make a Symfony cache:clear
* Set the Standard Store option "Store price with VAT" to true
* Change the price of an product to 186 €
* Add tax rate of 19% (Germany)
* Assign the 19% tax rate to the product
* Add the product with quantity 2 to the cart.

**Expected behaviour**
In cart
* Subtotal (incl. VAT): €372.00
* Subtotal (excl. VAT): €312.60
* Total Tax: €59.40

**Current behaviour**
In frontend, everything looks fine
![grafik](https://github.com/coreshop/CoreShop/assets/2377363/f223a6c3-e006-4071-9b7c-ca344436afd9)

But in Backend the subtotal is wrong
![grafik](https://github.com/coreshop/CoreShop/assets/2377363/133972c7-7960-4a4a-b512-c2082463b043)
![grafik](https://github.com/coreshop/CoreShop/assets/2377363/02dfe330-e92f-47ae-92d1-e0ffc524237b)

**Suggestion**
Is problem is probably caused by the `CartItemProcessor`.
The problem is that the subtotal/total is not rounded until the quantity has been applied. Or in other words, that the net price is calculated directly with quantity.
It would be better to round the subtotal/total first and then apply the quantity.

**Comment by dpfaffenbauer** [comment]
will look at it at next week and give you feedback

**Comment by dpfaffenbauer** [comment]
@lukadschaak if you check the database, you can see that the totalNet is 312,6050, it's just displayed as 312,61 cause of how the UI is rounding the number. 312,6050 is right, since 186/1,19 is 156,3025, times two is 312,6050. CoreShop uses the gross price to determine the total, so total is 186*2 = 372.

156,3025 * 2 * 1,19 actually is 371,9999. So it's a rounding issue of 0,0001.

These rounding issues will always occur. It doesn't matter how you actually calculate prices, you will always end up with rounding issues. 

So, to be honest: I don't see any issues here. Or maybe I am missing something?

**Comment by lukadschaak** [comment]
Sorry for the delayed answer (this time on my side).

I think you are right: The values in the database are correct. With the higher precision, the subtotal becomes `3126050` and the taxes become `593950` in the database. The sum is correct: `3720000` (372 €). Our issue is the rounding for the UI. When we round both values (round(0,50) = 1), we get wrong values: `312,61 + 59,40 = 372,01`.

What do you think? Are we using the precision in a wrong way? Our complete Shop uses "normal" B2C prices with a precision of 2. Is it then wrong to use a precison of 4 ?

Also: The rounding of `0,0001` what you mentioned, is not the problem.

**Comment by dpfaffenbauer** [comment]
I think you should also display 4 decimal places when using them to calculate. Is that a viable option?

**Comment by lukadschaak** [comment]
That's the problem. We display all prices with precision 2. Maybe the reason for using precision 4 was (back then) more precision for internal caluculation.

If you don't have any issues in mind with using precision 2 than maybe it's better to use that. We are not yet live and still have the possibility to do that.

**Comment by dpfaffenbauer** [comment]
If you really don't need it, don't use it ;) It makes sense for use cases when you sell things that are per part less than 1 cent. And then you also display more than 2 decimal points.

If you have the possibility to switch, please do so.

**Comment by lukadschaak** [comment]
We will discuss this internally. Thank's a lot Dominik :)
