### ISSUE TITLE
No category can assign to the product 4.0.0-beta.2

### ISSUE THREAD

**Issue by sevarozh** [coreshop/CoreShop#2394]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Core-Shop version: "4.0.0-beta.2"
Pimcore Version 11.0.12

No category can be assigned to the product, neither through search nor by drag and drop

<img width="1135" alt="Bildschirmfoto 2023-10-18 um 20 56 09" src="https://github.com/coreshop/CoreShop/assets/5694627/b2a1512a-162a-4670-8d8a-d19f481b5e1a">

**Comment by dpfaffenbauer** [comment]
fixed by #2396
