### ISSUE TITLE
Custom Product Classes Bugs

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#240]
- [ ] Using an index with a custom product class triggers `Column not found: 1054 Unknown column 'parentCategoryIds' ` - allow to use the default product class helper in custom product classes

**Comment by dpfaffenbauer** [comment]
fixed with

https://github.com/coreshop/CoreShop/commit/33c3dfa25883171e24e0505da40d11f6ee9c66f3 and https://github.com/coreshop/CoreShop/commit/3e95f62255409138ea7e0a876667f3cfbebfd0a6
