### ISSUE TITLE
Default Taxation Display Provider should respect Coreshop tax display setting

### ISSUE THREAD

**Issue by benwalch** [coreshop/CoreShop#2405]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

DefaultTaxationDisplayProvider should respect CoreShop setting "display prices with tax" by default.

**Comment by dpfaffenbauer** [comment]
@benwalch what setting do you mean?

**Comment by benwalch** [comment]
![image](https://github.com/coreshop/CoreShop/assets/7903333/9d523dfb-c03b-4b9d-b03a-59248839c722)
this one

**Comment by benwalch** [comment]
@dpfaffenbauer  see PR

**Comment by dpfaffenbauer** [comment]
I thought you mean that. But that is not a setting for the price display, it rather is a setting how the price is stored and calculated. Meaning that you could have a b2c site that uses net prices but still wants to display gross prices. Or a b2b site that stores gross prices but wants to show net prices

**Comment by benwalch** [comment]
i see. maybe an additional setting to control the displaying prices would be nice here.

**Comment by dpfaffenbauer** [comment]
Yes, maybe using CoreShop -> Settings?

**Comment by solverat** [comment]
I just came across this with the exact purpose, @dpfaffenbauer described: Client stores prices with tax (defined in store settings) but based on given parameters in context (b2b based on customer), he also wants to display prices without taxes.

That said, the service `DefaultTaxationDisplayProvider` is fine like it is. CoreShop can't resolve it for every project - just returning `true` is totally fine.

**Comment by dpfaffenbauer** [comment]
thanks for your feedback @solverat
