### ISSUE TITLE
Use String Casting for Tracking Numbers

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2411]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Steps to reproduce:
- Create an order
- Add a Shipment, add `996003263000037805` as tracking code
- Checkout the overview:

![image](https://github.com/coreshop/CoreShop/assets/700119/a24fee84-a6db-428d-bbbd-836eab1160e7)

The tracking code changed to `996003263000037800`. This is not a coreshop bug per se but a json (javascript) parsing issue:

- https://www.irt.org/script/1031.htm
- https://jsoneditoronline.org/indepth/parse/why-does-json-parse-corrupt-large-numbers/

Changing the serializer type to `string` should fix this.

**Comment by dpfaffenbauer** [comment]
merged, thanks @solverat
