### ISSUE TITLE
Category tree can only be expanded to 1 level in the frontend

### ISSUE THREAD

**Issue by sevarozh** [coreshop/CoreShop#2416]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no

PImcore 11.0.12
CoreShop 4.0.x-dev

Category tree can only be expanded to 1 level in the frontend

admin:
<img width="290" alt="Bildschirmfoto 2023-10-25 um 20 28 07" src="https://github.com/coreshop/CoreShop/assets/5694627/6c1df285-d30c-4e4c-8d32-7c3db1b39723">

by direct link is breadcrumb correct:
 
<img width="830" alt="Bildschirmfoto 2023-10-25 um 20 24 56" src="https://github.com/coreshop/CoreShop/assets/5694627/75d45a1e-dc8f-48ef-bb3e-edac1bb1fb47">

However, level 2 is not displayed in the category tree and can therefore not be reached:
<img width="420" alt="Bildschirmfoto 2023-10-25 um 20 25 50" src="https://github.com/coreshop/CoreShop/assets/5694627/8eba6178-04f6-42ed-a5be-36c7e2d0daa2">

If I click on subcategory 1 level, the next level is not opened, but only parent is displayed:
<img width="876" alt="Bildschirmfoto 2023-10-25 um 20 33 27" src="https://github.com/coreshop/CoreShop/assets/5694627/8f3cc21e-28a7-4985-9c45-09b052f20775">

**Comment by dpfaffenbauer** [comment]
Frontend is only a Demo and it's just not implemented there.
