### ISSUE TITLE
[Bug] Payment after revising does not work properly

### ISSUE THREAD

**Issue by rberneder** [coreshop/CoreShop#2417]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In the revise action the `PaymentType` form is used and validated just as during the checkout process. However when revising, the order already has the `SaleState` "order" what means the items are already on hold. As of now the `CardStockAvailabilityValidator` performs its check again. When one has the last item available reserved in the order, this check will fail, leading to not being able to checkout.

**Comment by dpfaffenbauer** [comment]
has been solved with this https://github.com/coreshop/CoreShop/pull/2461
