### ISSUE TITLE
Gift Item not respecting Unit Definition

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2421]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Go to demo
- Create price rule
  - no voucher rule
  - condition: product id 114 ("Aerodynamic Silk Wallet"), a product with units
  - action: product id 111 ("Incredible Linen Shoes"), a product with units
- Add product to cart
- Check cart object:
  - product id 114: 
![image](https://github.com/coreshop/CoreShop/assets/700119/9d46ab79-f147-48b0-93df-28e7f90b09f7)
  - product id 111 has been added as gift, but without unit: 
![image](https://github.com/coreshop/CoreShop/assets/700119/23f583ab-b231-4e86-8358-7c494f11021c)

**Comment by solverat** [comment]
That's a quite challenging thing. I've added a custom cart processor `coreshop.cart_processor` with a low prio `-255`.

```php
<?php

namespace App\CoreShop\Processor;

final class CartGiftItemsProcessor implements CartProcessorInterface
{
    public function process(OrderInterface $cart): void
    {
        /** @var OrderItemInterface $item */
        foreach ($cart->getItems() as $item) {

            $product = $item->getProduct();

            if (!$item->getIsGiftItem()) {
                continue;
            }

            if (
                $product instanceof ProductInterface &&
                $product->hasUnitDefinitions() &&
                $product->getUnitDefinitions()?->getDefaultUnitDefinition() instanceof ProductUnitDefinitionInterface
            ) {
                $item->setUnitDefinition($product->getUnitDefinitions()?->getDefaultUnitDefinition());
                $item->setDefaultUnitQuantity(1);
            }
        }
    }
}

```

**Comment by dpfaffenbauer** [comment]
Units should be considered from where the product is added to the cart. So in that case the GiftActionProcessor right?

**Comment by solverat** [comment]
Yes, that's right.

**Comment by dpfaffenbauer** [comment]
@solverat WDYT? https://github.com/coreshop/CoreShop/pull/2422
