### ISSUE TITLE
[Bug] coreshop.expression_language doesn't use a local cache

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#2427]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

`@coreshop.expression_language` is used all over and doesn't define a cache, but since `autowire: true` is in place, `cache.app` will be autowired. If this was not case, it would use `ArrayAdapter` (in memory) one.

This means your expression language will talk to your Redis, but the expected workflow is expression language is meant to be cheap so a local cache like `cache.system` should explicitly be used instead.

**Comment by dpfaffenbauer** [comment]
@dkarlovi are you sure autowire is enabled there? CoreShop doesn't use that internally.

**Comment by dkarlovi** [comment]
The service is used at least by Datadefs. We've fixed it on a project by wiring `cache.system` explicitly and the performance issue is now gone.

**Comment by dpfaffenbauer** [comment]
Well, in CoreShop if it hasn't any cache configured, it is using ArrayAdapter as fallback, maybe thats the performance problem?

**Comment by dkarlovi** [comment]
Yes, that's what I'm saying. :laughing: The service should explicitly wire `cache.system` to ensure a valid local cache is used.

**Comment by dpfaffenbauer** [comment]
gotcha. Will make a PR for it.
