### ISSUE TITLE
[Bug] decorated service HttpFoundationRequestHandler is out of sync

### ISSUE THREAD

**Issue by hethehe** [coreshop/CoreShop#2429]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no (maybe)

The main problem is similar like in #2426. 
Symfony changed the $parameterBag->get() method to scalar return values only.

The decorated CoreShop\Bundle\ResourceBundle\Form\Extension\HttpFoundation\HttpFoundationRequestHandler service still use $request->query->get(..) for named forms
=> for example in the search controller.

Easy solution is to just change ->get() to ->all().

But I'm wondering why CoreShop decorates the HttpFoundationRequestHandler, is this still necessary or was this just a legacy fix?

If still necessary, please let me know and I will create a PR for the ->get()/->all() change.

**Comment by dpfaffenbauer** [comment]
It was necessary to have JSON Requests automatically encode automatically for forms. You can make the same change as for filters :)

**Comment by hethehe** [comment]
I created a pull request that fix the problem.

If you, me or someone else find time, I think it would be good to find a solution other than overwriting the Symfony class, maybe this can have some bad impact for other solutions and future updates.
