### ISSUE TITLE
[BUG] [CHECKOUT] Shipping Address Unselectable

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2430]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Regression of https://github.com/coreshop/CoreShop/pull/2387/files (since 3.1)

To reproduce the issue, I've changed the decorated service like above on `demo3.coreshop.org` (it's still 3.0.4):

- Create at least two shipping addresses
- Go to checkout
- Deselect `Invoice Address is Shipping Address`
- Select second shipping address
- click `proceed`
- go back to address
- Shipping address is invalid

Because `StoreBasedCartContext` is changing the default address here:

https://github.com/coreshop/CoreShop/blob/b2e4df7ffb305787f92f2b0aa7b21b2a56682aa5/src/CoreShop/Component/Core/Context/StoreBasedCartContext.php#L81-L90

And also because of the changed decorator, this context kicks in before the checkout step is completed.

***

However, if I'm changing the decorator back to `CoreShop\Component\Order\Context\CartContext`, the `StoreBasedCartContext` never gets triggered, so I'm not sure what's the real issue here.

**Comment by dpfaffenbauer** [comment]
simply adding a check if the cart has an address and only then set it?

**Comment by dpfaffenbauer** [comment]
@solverat I fixed it properly, the problem was: the StoreBasedContext should only decorate the "FactoryContext". That is only triggered when no cart is available and a new one is created.

**Comment by dpfaffenbauer** [comment]
Demo is also updated know.
