### ISSUE TITLE
[Bug] SearchController tries to obtain services from container that do not exist

### ISSUE THREAD

**Issue by hethehe** [coreshop/CoreShop#2438]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If you search there is an error:
Service "CoreShop\Component\Store\Context\StoreContextInterface" not found: even though it exists in the app's container, the container inside "CoreShop\Bundle\FrontendBundle\Controller\SearchController" is a smaller service locator that only knows about the ...
... Try using dependency injection instead.

How would you like to handle this? Should I create a PR that uses dependency injection for these services?

**Comment by dpfaffenbauer** [comment]
like here: https://github.com/coreshop/CoreShop/blob/4.0/src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php#L389
