### ISSUE TITLE
[BUG] Order Expire Tasks Cancels too early

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2441]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Within several projects, we noticed that orders suddenly got cancelled way too early. The reason is simple:

https://github.com/coreshop/CoreShop/blob/102fa45561d3514f7fb8f53bdf2ba6fde32effd3/src/CoreShop/Bundle/OrderBundle/Pimcore/Repository/OrderRepository.php#L189-L190

Since the order is also a cart object, the `o_creationDate` is not a valid factor anymore, since the cart may have existed for much longer → which leads to instant order cancellation in some worst case scenarios.

Changing the condition to `orderDate` could be a proper fix.

**Comment by dpfaffenbauer** [comment]
@solverat Yes, that would be the right way

**Comment by solverat** [comment]
This has been fixed in https://github.com/coreshop/CoreShop/pull/2371 but got lost somehow...

**Comment by dpfaffenbauer** [comment]
@solverat not lost, but never merged up. I will merge it up now

**Comment by dpfaffenbauer** [comment]
@solverat merged now and part of 3.1, 3.2 and 4.0
