### ISSUE TITLE
[CoreShop 3.1] Dynamic Dropdown Options are loaded unreliably

### ISSUE THREAD

**Issue by aarongerig** [coreshop/CoreShop#2444]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Pimcore: v10.5.25
CoreShop: v3.1.0

I have noticed a very specific behavior with Pimcore and CoreShop. A customer has reported that when he opens products (the reported Pimcore DataObject class contains CoreShop Dynamic Dropdowns), it happens that for certain objects some of these fields are marked as "edited" (dirty), a new draft is created and thus the objects are "changed" when the editor saves the object.

This is probably because the option request returns an empty response and therefore no option can be selected when loading the object. Pimcore then flags the field as dirty.

I have now tried to reproduce this and it seems that this problem only occurs sporadically and not consistently. Sometimes it can load the Dynamic Dropdown Options, sometimes not. I have attached a screenshot of my Chrome network tab where you can see that some of these option requests get a 302 redirect and some even fail completely with the message: "Too many login attempts. Please try again."

<img width="685" alt="dynamic_dropdown_options" src="https://github.com/coreshop/CoreShop/assets/17384333/33e4ec61-bfea-4e44-a291-a4c9c8dcf7a0">

**Comment by dpfaffenbauer** [comment]
the loading part and logout part is an issue with Pimcore that has been fixed already: https://github.com/pimcore/pimcore/issues/15671

**Comment by dpfaffenbauer** [comment]
@aarongerig I cannot reproduce your issue with 10.6.9 and CoreShop 3.1.4

**Comment by dpfaffenbauer** [comment]
@aarongerig did the update solve that?

**Comment by aarongerig** [comment]
@dpfaffenbauer After the update I couldn't reproduce the issue anymore and we also didn't hear back from the customer. So I'd suppose this is solved. Gonna close the issue here. Thanks!
