### ISSUE TITLE
[Bug] NestedConditionChecker NOT validation broken

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2445]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Within [this huge commit](https://github.com/coreshop/CoreShop/commit/efbcf5197f699902e184cf083fd3ed17d5cb226e), the variable `$valid` changed to `$conditionValid`:

![image](https://github.com/coreshop/CoreShop/assets/700119/7f4ddedc-ed9a-4cc1-99bb-b3ea42b0b36d)

That means, that if you're using the `NOT` operator, `$valid` will always be `false` and therefor the rule always returns `true`.

**Comment by dpfaffenbauer** [comment]
thanks a lot for the PR @solverat
