### ISSUE TITLE
The discount is applied to the net amount and not as expected to the gross amount

### ISSUE THREAD

**Issue by ghost** [coreshop/CoreShop#2463]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
Hey I found a bug

### Steps to reproduce ###
* Switch store to incl. VAT
* Create Cart Price Rule
* Add a cart item under Actions
* Here under Conditions, select Products and add a product
* Create a Discount Amount under Actions with 10%

Actual behaviour
![Screenshot from 2023-11-30 17-10-25](https://github.com/coreshop/CoreShop/assets/121110142/48861a3b-acde-49e3-9c2f-352930e1212e)

Expected
The discount is applied to the net amount and not as expected to the gross amount

**Comment by dpfaffenbauer** [comment]
@Steph81190 see https://github.com/coreshop/CoreShop/pull/2464

**Comment by dpfaffenbauer** [comment]
fixed in 3.1, 3.2 and 4.0
