### ISSUE TITLE
Missing change quantity function in Cart

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#247]
Cart does have input fields for quantity, but no update function implemented.

**Comment by solverat** [comment]
the `updateCartAction` does not respect the inventory of the updated item. currently it's possible to update the item amount to any number.

**Comment by dpfaffenbauer** [comment]
![bildschirmfoto 2018-01-22 um 18 15 29](https://user-images.githubusercontent.com/5981845/35234084-3f23cb8e-ffa0-11e7-8c31-011ddf0071a7.png)

works for me. But: I just changed the summaryAction, it now updates the cart directly without usage of a extra action. This is necessary to display form errors.

**Comment by solverat** [comment]
works now! i also updated the flash message behaviour.
