### ISSUE TITLE
[CS4] GeoLiteBasedRequestResolver Missing

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2471]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Class `CoreShop\Component\Address\Context\RequestBased\GeoLiteBasedRequestResolver` is not available in CS4 anymore.

**Comment by dpfaffenbauer** [comment]
Yes, cause Pimcore removed it too

**Comment by solverat** [comment]
Awesome.
