### ISSUE TITLE
[CS5] Remove o_* Prefixes

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2472]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

There are plenty of prefixed `o_*` statements: 

- https://github.com/search?q=repo%3Acoreshop%2FCoreShop%20o_id&type=code
- https://github.com/search?q=repo%3Acoreshop%2FCoreShop+o_creation&type=code
- https://github.com/search?q=repo%3Acoreshop%2FCoreShop+%27o_&type=code

**Comment by dpfaffenbauer** [comment]
`oo_id` still exists. o_id for everything Index and Filter related stayed the same for BC reasons. I still found some and created a PR (https://github.com/coreshop/CoreShop/pull/2473)
