### ISSUE TITLE
Handle Orders with Pending Payments

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2478]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

If you're using an payment provider like stripe which allows klarna / sofort, the payment confirmation is a delayed process. In that case, the user will return to coreshop with a payment state of "processing" (`PaymentInterface::STATE_PROCESSING`). For coreshop, this state is not a "success" state:

https://github.com/coreshop/CoreShop/blob/a1a456fdefaa259f791cc3a0b04c05be183948e5/src/CoreShop/Bundle/PayumBundle/Action/ResolveNextRouteAction.php#L44-L56

Which means, that a user retrieves the revise page which tells him, that the payment failed, and he needs to choose another payment.

What to do?

### I. Improve Revise Page
In Sylius for example, they also render a similar thing to CoreShop's revise process:

[src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig](https://github.com/Sylius/Sylius/blob/1.13/src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig)

... but in a smarter way: If the payment state is in `awaiting_payment` state, they're showing a "Pay" button above the order. In my example, the payment would be "processed" so no payment button but a valid  ("on-hold") summary page - so no confusion for the customer who's just successfully paid for the order. 

![image](https://github.com/coreshop/CoreShop/assets/700119/a93197f1-6c0f-40e0-b949-99b1adfe3ba0)

### II. Order Confirmation
The order should get confirmed, if a payment is in `PaymentInterface::STATE_PROCESSING` state. 

Two checks to extend:

https://github.com/coreshop/CoreShop/blob/a1a456fdefaa259f791cc3a0b04c05be183948e5/src/CoreShop/Bundle/PayumBundle/Action/ConfirmOrderAction.php#L39-L42

https://github.com/coreshop/CoreShop/blob/a1a456fdefaa259f791cc3a0b04c05be183948e5/src/CoreShop/Bundle/PayumBundle/Extension/UpdateOrderStateExtension.php#L94-L98
=> In my tests, the `UpdateOrderStateExtension` never triggered (see next section " Adjust Payment Bundles").

### III. Resolve awaiting payment state in resolver
Same as here: https://github.com/Sylius/Sylius/pull/11535

### IV. Adjust Payment Bundles
Nothing to do in coreshop core, but I had to add an additional `UpdatePaymentStateExtension` extension (see section "Payment State not updating") otherwise the payment state won't get updated: https://github.com/coreshop/PayumStripeBundle/issues/10

**Comment by dpfaffenbauer** [comment]
# I. Improve Revise Page
Sylius always shows a "order" detail page, where as we show either the confirmation page or a revise page. We cannot change how that is done now without a BC break or a feature flag. If we make `processing` a valid state and confirm the order, this part is not really necessary anway.

# II. Order Confirmation
What are the possible side effects of this? We never had any issue before with that.

# III. Resolve awaiting payment state in resolver
That is clearly the consequence and a must have when II is implemented.

# IV. Adjust Payment Bundles
Looks rather like a issue in the Stripe Bundle?

**Comment by solverat** [comment]
1. Yes, I also thought about that. I don't see any issues, if we allow `processing` to enter the thank-you page (If the order gets canceled later on, notification rules take over to inform user or something like that
2. I don't see any side effects. It's "just" a workflow dispatcher from "new" to "confirmed". Since we also show the thank-you page, a possible order-confirmation mail (which gets dispatched via "confirm") is valid
3. ok
4. yes, just like I said. :) I've had to implement a custom [UpdatePaymentStateExtension.php](hhttps://github.com/coreshop/PayumStripeBundle/issues/10), not sure why since CoreShop already comes with a UpdateOrderStateExtension - but it works.

PR?

**Comment by dpfaffenbauer** [comment]
> PR?

Yes, I don't see any side effect either.
