### ISSUE TITLE
Thank-you and pay URLs are accessible without login

### ISSUE THREAD

**Issue by yariksheptykin** [coreshop/CoreShop#2479]
It looks like order confirmation page does not require the user to be logged in. I just did a quick purchase on demo store and then curled the confirmation URL without cookies. Brute-forcing order token might leak personal information such as address or phone no. Here I am grepping for my fake name on the confirmation page:

```
curl https://demo3.coreshop.org/en/shop/checkout-thank-you/NoOLrFeRxd | grep -A 10 'Invoice Address'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16072    0 16072    0     0  19993      0 --:--:-- --:--:-- --:--:-- 19990
                    Invoice Address
                </h4>
            </div>
            <div class="card-body panel-delivery-address">
                Test<br />
Mrs. Test Tester<br />
Teststr 1<br />
28219 Bremen<br />
Austria<br />

            </div>
```

"pay"-URL seem to be more dangerous. It has a form of https://demo3.coreshop.org/en/shop/pay/123. Guessing the right pay number redirects to the thank-you page of that order. The 123 seems like a incrementing integer, making brute-forcing even easier. So doing something like this can reveal personal information of all customers:

```shell
for i in $(seq 123 321); do curl -s -L https://demo3.coreshop.org/en/shop/pay/$i | grep -A 10 'Invoice Address'; done
                    Invoice Address
                </h4>
            </div>
            <div class="card-body panel-delivery-address">
                Test<br />
Mrs. Test Tester<br />
Teststr 1<br />
28219 Bremen<br />
Austria<br />

            </div>
                    Invoice Address
                </h4>
            </div>
            <div class="card-body panel-delivery-address">
                Coreshop<br />
Mrs. Corina Shopper<br />
Coreshopallee 1<br />
19999 Coreshopwille<br />
Austria<br />
0123456789
            </div>
```

I would expect this information to be accessible to the owner of the order only.

**Comment by solverat** [comment]
While this is true the idea was to prevent the cookie same_site "issue" when customers get redirected back from an external payment page (offsite payment).

Regarding pay url: not sure but if someone wants to pay my order, go for it! :)

**Comment by dpfaffenbauer** [comment]
## 1. Order Confirmation

That is actually on purpose, since depending on your session cookie settings, you might get logged out after a redirect back from the payment provider. Since that URL is using the a Token to determine the Order, Brute Forcing is not a viable method of gathering data. would take too long actually get anything.

## 2. Paying
Yes, there we can add a check for the User/Order Relation.

**Comment by dpfaffenbauer** [comment]
Regarding pay: Not also a viable option to check for a user in the session, since a guest user doesn't have a user in the session. It would be better to use a token there as well.

**Comment by yariksheptykin** [comment]
> Regarding pay url: not sure but if someone wants to pay my order, go for it! :)

It looks like the pay/123 URL would be redirecting to the the thank-you page if the order was payed already. What I observe is after going through the checkout, paying (pay/123), and landing on thank-you page, I can still curl without a session cookie the same pay URL (pay/123) and land on the thank-you page. I might be that behavior here is different for online payments like PP, but for offline payments like bank transfer, guessing the pay URL should take you to the thank-you of that order, disclosing address of the customer.

If my understanding is true, this behavior makes using tokens for the thank-you page less useful, as I can guess the token by guessing the pay "id".

**Comment by yariksheptykin** [comment]
> Regarding pay: Not also a viable option to check for a user in the session, since a guest user doesn't have a user in the session. It would be better to use a token there as well.

I agree. I would suggest that we then issue short lived tokens, so that they are valid only once and only for some limited time, if this is not the case already. If I understand correctly this tokes are only need to show thank-you page. That page should not be available forever. We should rather show the order details in the private section of that customer like "my orders" or something.

**Comment by dpfaffenbauer** [comment]
@yariksheptykin still, but what you do with Guests? What if the Guest wants to check the Order Page after like 6 months? The token is not short-lived, it is long-lived

**Comment by yariksheptykin** [comment]
> @yariksheptykin still, but what you do with Guests? What if the Guest wants to check the Order Page after like 6 months? The token is not short-lived, it is long-lived

I would expect that guests get an email with order details & a PDF of some kind. But this is probably a design issue, and you should decide how to handle this.

Personally to me it seems like a very risky topic, so I would implement this very defensively by default. Maybe allowing to enable risky long-lived tokens via some configuration, but I would not default to this.

**Comment by yariksheptykin** [comment]
@dpfaffenbauer  how would I use tokes to protect the /pay/ action? Could you point me to an example of how you think this should be done? Maybe I could draft a MR.

**Comment by dpfaffenbauer** [comment]
Order Token (same as from confirmation page) is used to identify the order. So it's also a short long lived token. It already is supported, by default we use the OrderId to redirect that.

The token is a 10 Char string, uniquely generated, with lowercase a-z, uppercase A-Z and number 0-9. so there are 62^10 combinations. (839.299.365.868.340.224). Assuming you can do 1 Billion tries per second (which is unrealistic anyway), it would still take 9.714 to get through all of them.

If somebody wants super badly to get to your data, he will find a more efficient way right.

If you're still unsure about bruteforcing, increase the length to 20 and it becomes even more impossible to guess.

**Comment by yariksheptykin** [comment]
@dpfaffenbauer could you also give a hint on how I use that token in "/pay/123" URL? If I use https://demo3.coreshop.org/en/shop/pay/NoOLrFeRxd I get 404. If I understand this right /pay/xxx maps to https://github.com/coreshop/CoreShop/blob/4.0/src/CoreShop/Bundle/PayumBundle/Controller/PaymentController.php#L47. Scanning quickly through the code I see some code dealing with tokens. How can I force those pay URLs to use the order token just like /thanks-you?

Sorry if I am asking stupid questions, and thanks for your quick replies!

**Comment by dpfaffenbauer** [comment]
@yariksheptykin The Checkout always uses the `pay/123`. We could change that to use `pay/token`.

**Comment by yariksheptykin** [comment]
> @yariksheptykin The Checkout always uses the `pay/123`. We could change that to use `pay/token`.

@dpfaffenbauer I think we should, because this makes thank-you/token less secure. `pay/123` seems to always redirect to `thank-you/token` even after a payment was completed. If this is true, guessing `thank-you/token` is not necessary, because guessing `pay/123` will redirect to thank-you/token` achieving the same.

Either we should stop redirecting to thank-you from pay after the payment is complete, or we should use token for `pay` as well. 
Disabling redirect from `pay/123` to `thank-you/token` for orders which are already payed could reasonable anyways. That should throw some order state exception like "Cannot apply 'pay' transition to order in state Payed" or something like that.

Does this make sense? I might be misunderstanding the checkout workflow.

**Comment by dpfaffenbauer** [comment]
Yes it makes sense. I see what I can do without any BC breaks

**Comment by yariksheptykin** [comment]
> Yes it makes sense. I see what I can do without any BC breaks

@dpfaffenbauer do you have any update on this issue? Should I try to make a PR?

**Comment by dpfaffenbauer** [comment]
@yariksheptykin Didn't hat time yet, I would appreciate a PR though :)

**Comment by yariksheptykin** [comment]
@dpfaffenbauer I put up a rough draft of the implementation. This is a WIP just to get your quick feedback on the overall idea. Do you consider route definitions a part of coreshop API? Would changing the definition of `coreshop_payment` be a BC break? If not than we can just update the static route definition and write a migration to update this definition in existing installations.

**Comment by dpfaffenbauer** [comment]
@yariksheptykin it looks actually fine. the route could be considered a BC break, but the Action of it (PaymentController) already accepted both, token and order. I would still prefer to have both options for bc reasons. There are projects where that is overwriten. So what do you think if we introduce a new route called `coreshop_payment_token` that we use in core?
