### ISSUE TITLE
QPR ranges stored in reverse order when persisting

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2497]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Create a simple QPR:
  ![image](https://github.com/coreshop/CoreShop/assets/700119/4c3affb8-05a9-48ba-ab4f-2425b5b956fd)
- Hit Save Button
- After the refresh, all ranges are reversed:
   ![image](https://github.com/coreshop/CoreShop/assets/700119/4c04d030-5cdc-4cbc-b85d-b7216fec3351)

It also happens if you create CPR with PHP API.

The range is fine until the `flush` method will be executed here:

https://github.com/coreshop/CoreShop/blob/a5baa41d3669e41752a0f8d42fb42dfa53cea4ab/src/CoreShop/Bundle/ProductQuantityPriceRulesBundle/CoreExtension/ProductQuantityPriceRules.php#L401

Not sure if this discussion is related (Because it worked before?): https://github.com/doctrine/orm/pull/11058#issuecomment-1809728021

If this is the case, we should sort the range based on `rangeStartingFrom` because the calculation heavily depends on this!

**Comment by dpfaffenbauer** [comment]
https://github.com/coreshop/CoreShop/pull/2498
