### ISSUE TITLE
Category pages in demo v4 seem broken

### ISSUE THREAD

**Issue by yariksheptykin** [coreshop/CoreShop#2517]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I was browsing demo4 and noticed that all links to category pages render an 500 page. It this a known bug? The page says that some trained monkey are already looking into this issue :)

![Screenshot from 2024-01-23 14-49-01](https://github.com/coreshop/CoreShop/assets/636846/9d2a1852-e203-4071-b74e-4c89fa5b0395)

**Comment by dpfaffenbauer** [comment]
@yariksheptykin thanks for the report, quite interesting, error is:

```[2024-01-23T19:02:55.033549+01:00] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/en/movies" is not callable: Controller "CoreShop\Bundle\FrontendBundle\Controller\CategoryController:detailSlugAction" does neither exist as service nor as class." at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 76 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/en/movies\" is not callable: Controller \"CoreShop\\Bundle\\FrontendBundle\\Controller\\CategoryController:detailSlugAction\" does neither exist as service nor as class. at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php:76)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"CoreShop\\Bundle\\FrontendBundle\\Controller\\CategoryController:detailSlugAction\" does neither exist as service nor as class. at /var/www/html/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:54)\n[previous exception] [object] (Error(code: 0): Class \"CoreShop\\Bundle\\FrontendBundle\\Controller\\CategoryController:detailSlugAction\" not found at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php:131)"} []```

I will look into it

**Comment by dpfaffenbauer** [comment]
figured it out, the category route was wrongly defined, it needs two :: between controller and action, there was only one.
