### ISSUE TITLE
Clarify Transaction Notes

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#252]
There are [some comments and disabled code](https://github.com/coreshop/CoreShop/blob/a7b783a3ac957851fb55b5ef9497b28fdd5a754c/src/CoreShop/Bundle/OrderBundle/Controller/OrderController.php#L210) about transaction notes.

The Idea behind this was to create a human readable timeline of actions during a payment transaction. Something like [this](https://docs.woocommerce.com/wp-content/uploads/2015/03/Edit_Order_%E2%80%B9_WooCommercesvn_-_A_WordPress_Site_%E2%80%94_WordPress1.png). Either we remove this feature completely (which would be sad) or we implement something like a _order transaction notifier_. At first, this notifier only tracks state changes (maybe [here](https://github.com/coreshop/CoreShop/blob/903ce862c034fa212def5e28320e4d79a0dbda64/src/CoreShop/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php#L80)). We already have all the transaction info in the detail section, but no history of changed states/actions.

**Comment by dpfaffenbauer** [comment]
any idea on how to implement that?

**Comment by solverat** [comment]
This will be a future feature: Create a payment notes entity and allow custom payment notes within a payum extension.

**Comment by solverat** [comment]
implemented. usage example from a coreshop payum bundle:

## Register
```yml
CoreShop\Payum\PowerpayBundle\Event\ConfirmEvent:
     arguments:
          - '@coreshop.workflow.order_history_logger'
```

## Service
```php
public function confirm(OrderInterface $order)
{
     $orderId = $order->getId();
     $this->orderHistoryLogger->log($orderId, 'payment confirmed');
}
```
