### ISSUE TITLE
Cart Rules: Solidify Cart Calculation

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#253]
- [x] If discount is bigger than cart amount, the final cart amount should be `0.00`.
- [x] If cart amount is `0.00`, the PG should be changed to offline.

**Comment by dpfaffenbauer** [comment]
done here: https://github.com/coreshop/CoreShop/pull/263

can you review please?

**Comment by solverat** [comment]
@dpfaffenbauer reviewed and merged! 
Only thing: discount should also respect shipping / payment fees etc!

**Comment by dpfaffenbauer** [comment]
should be working now, can you review again please?

**Comment by solverat** [comment]
@dpfaffenbauer if discount is greater than the cart amount, the negative price difference will show up as a positive total.
- product: 100,-
- voucher: 150,-
total: 50,-

**Comment by solverat** [comment]
and also: if payment is empty in cart/order object, do we have some side effects we need to handle? (like paymentprovider is null in twig)

**Comment by solverat** [comment]
i just tested the negative case: works now. so hopefully this is fixed...
