### ISSUE TITLE
Checkout /pay/token leads to 404

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2539]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

We currently struggle with a serious issue. On a P11 Installation, we receive a lot of failed orders without any error logs. After checking a lot of access logs, I found a coherence.

All these failed orders are coming from a 404 when entering `/_locale/shop/pay/{token}}`:

![image](https://github.com/coreshop/CoreShop/assets/700119/db4198df-dc72-40c3-b669-c7c715703c70)

A status 404 can be thrown here:
https://github.com/coreshop/CoreShop/blob/f1f118cad6cc63713853d713850645b2e96d5825/src/CoreShop/Bundle/PayumBundle/Controller/PaymentController.php#L47-L64

After checking the order versions:
![image](https://github.com/coreshop/CoreShop/assets/700119/ed49509d-5b37-41d8-bafb-ffb0d5adcaf6)

On exact 12:25:21, the order changes its state from `cart` to `order`. If the time is right, `orderRepository()->findOneBy()` won't find any order because of… I'm not sure? Runtime-Cache? Cache generally? Locks?

Any help would be appreciated!

**Comment by jdreesen** [comment]
Maybe related to #2511 / #2515?

**Comment by dpfaffenbauer** [comment]
for sure related to that, but the token is generated when the cart is created. so quite interesting... can we somehow further dbeug?

**Comment by dpfaffenbauer** [comment]
It also cannot be locks or runtime cache. the listing always queries the database and since said before, the token is generated on cart creation.

**Comment by solverat** [comment]
We also have non existing token issues (users with old cart before there was the token feature) but this is not the issue here, the token is definitely available. I'm quite sure, that it's about the order state (as you can see, the state changed in the same second as the the user gets redirected). It's also not happening all the time, which is also a cache related indication to me.

**Comment by dpfaffenbauer** [comment]
It doesn't really matter what state it is, as long as the order has a token, it has to be found.

**Comment by dpfaffenbauer** [comment]
What if we add a specific function to the repository to get Order by Token and use that? Maybe the findOneBy does something weird there?

**Comment by solverat** [comment]
The token is available, but the order has to be in state "order", which is most probably not the case since the state changed at the same time.

**Comment by dpfaffenbauer** [comment]
no it hasn't, the Payment Controller only gets the Order, creates the Payment and redirects to payum.

**Comment by dpfaffenbauer** [comment]
What if you visit the link later? Like if you thing it is a race-condition, it should work like a second later or so

**Comment by solverat** [comment]
Not sure. I'll check it on monday. The only thing i know (and as you can see in the screenshot), the state (see version screenshot) changed in the same second then the access log recorded the 404 (see log screenshot).

**Comment by solverat** [comment]
Btw! Maybe its a route issue? Coreshop delivers two routes with an almost same endpoint: /pay/{token} and /pay/{order}.
The order route has a numeric validation on {order}. Don't know, I have to test it.

**Comment by dpfaffenbauer** [comment]
Yes, also sounds reasonable. Maybe delete the old one? or change priorities?

**Comment by solverat** [comment]
Jop, found it. The issue starts here:

https://github.com/coreshop/CoreShop/blob/f1f118cad6cc63713853d713850645b2e96d5825/src/CoreShop/Bundle/FrontendBundle/Resources/install/pimcore/staticroutes.yml#L138-L139

All tokens of our failed orders are starting with a numeric character (See example above): `4TqEHjxRIp`. This will match with the route `coreshop_payment` (`pay/([0-9]+)$`) first, which leads to the wrong identifier here:

https://github.com/coreshop/CoreShop/blob/f1f118cad6cc63713853d713850645b2e96d5825/src/CoreShop/Bundle/PayumBundle/Controller/PaymentController.php#L53-L54

Removing the route `coreshop_payment` fixes this. This is quite a thing, because this increases bounce rates (since you may just think, the customer just didn't want to complete his order).

**Comment by dpfaffenbauer** [comment]
Increasing the priority of the `coreshop_payment_token` helps?

**Comment by solverat** [comment]
Yes, the prio should be switched also (the legacy route prio is currently higher than the new one).

**Comment by dpfaffenbauer** [comment]
Ok, I will create a PR and do a release monday/tuesday

**Comment by solverat** [comment]
Btw. with #2511, all existing carts can't be used for a valid checkout, because the token is missing.

**Comment by dpfaffenbauer** [comment]
@solverat token will be generated here: https://github.com/coreshop/CoreShop/blob/4.0/src/CoreShop/Component/Order/Factory/OrderFactory.php#L43, that is in there since https://github.com/coreshop/CoreShop/pull/2265

Should we still add a migration for missing tokens?

**Comment by dpfaffenbauer** [comment]
or a fallback that if no token is there, create one first in the checkout controller

**Comment by dpfaffenbauer** [comment]
```php
 if (!$order->getToken()) {
     //Fallback for Orders/Carts without token (eg. legacy carts)
    $tokenGenerator = new UniqueTokenGenerator();
    $order->setToken($tokenGenerator->generate(10));
    $order->save();
}
```

In the checkout-controller before generating the payment route

**Comment by solverat** [comment]
I'll open another issue for that!

**Comment by solverat** [comment]
To confirm: It's still better to remove the `coreshop_payment` if you're not using it in a custom override or something similar, right?

**Comment by dpfaffenbauer** [comment]
yes.

**Comment by dpfaffenbauer** [comment]
we kept it for BC reasons, in case somebody uses it in custom overrides
