### ISSUE TITLE
Cart/Order Token Missing / Not Unique

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2541]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Since #2511, the checkout requires a valid token, to complete the order. 

We're struggling with two issues here:

- The token is not unique per se: Back-Check if an order exists with generated token? I know, changes are low, but it's not unique
- Carts which have been created before ##2265, don't come with any token => 404 in checkout (It's quite old, but still valid). 

Possible Solution: https://github.com/coreshop/CoreShop/issues/2539#issuecomment-1937492184

Or migrate it:

```php
protected function execute(InputInterface $input, OutputInterface $output): int
{
    $listing = new CoreShopOrder\Listing();
    $listing->setUnpublished(true);
    $listing->addConditionParam('token = "" OR token IS NULL');
    $listing->addConditionParam(sprintf('saleState = "%s"', OrderSaleStates::STATE_CART ));

    foreach ($listing->getObjects() as $cart) {

        $token = $this->tokenGenerator->generate(10);

        $output->writeln(sprintf('<comment>Set missing token %s for cart %d', $token, $cart->getId()));

        $cart->setToken($token);
        $cart->save();
    }

    return Command::SUCCESS;
}
```

**Comment by dpfaffenbauer** [comment]
@solverat a migration can be very heavy on the database. So I'd rather use the fallback approach, WDYT?

**Comment by dpfaffenbauer** [comment]
I'd prefer a migration anyway ;).

**Comment by solverat** [comment]
:D yes, probably a fallback would be smoother

**Comment by dpfaffenbauer** [comment]
follow up ticket for uniqueness check: https://github.com/coreshop/CoreShop/issues/2546
