### ISSUE TITLE
Migration Version20240211090209 broken in CoreShop 3.2.4

### ISSUE THREAD

**Issue by benwalch** [coreshop/CoreShop#2549]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

This migration [here](https://github.com/coreshop/CoreShop/blob/3.2/src/CoreShop/Bundle/CoreBundle/Migrations/Version20240211090209.php) in coreshop 3.2.4 branch which supports pimcore X (not pimcore 11), relies on Pimcore's 
StaticRouteBundle, which was first introduced in Pimcore 11.
Executing migrations up after upgrading to version 3.2.4 raises an error:
 ```
 In Version20240211090209.php line 23:
                                                                                                   
  Attempted to load class "Staticroute" from namespace "Pimcore\Bundle\StaticRoutesBundle\Model".  
  Did you forget a "use" statement for "Pimcore\Model\Staticroute"?
```

**Comment by dpfaffenbauer** [comment]
🙈

**Comment by dpfaffenbauer** [comment]
interesting that the tests didn't catch it
