### ISSUE TITLE
Disable Versions for various CoreShop Objects

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#255]
CoreShop creates and updates a lot of pimcore objects. Some of them do not need any versioning, so disable it:

- [ ] ~CoreShopAddress~
- [x] CoreShopCart _(most prio)_
- [x] CoreShopCartItem _(most prio)_
- [ ] ~CoreShopCustomer (?)~
- [ ] ~CoreShopCustomerGroup (?)~
- [x] CoreShopOrder _(most prio)_
- [x] CoreShopOrderInvoice _(most prio)_
- [x] CoreShopOrderInvoiceItem _(most prio)_
- [x] CoreShopOrderItem _(most prio)_
- [x] CoreShopOrderShipment _(most prio)_
- [x] CoreShopOrderShipmentItem _(most prio)_

**Comment by dpfaffenbauer** [comment]
CoreShopAddress: I think it makes sense to store versions here.
CoreShopCustomer: Well, the customer can update his data himself, so versioning it would make sense.
CoreShopCustomerGorup: Is saved directly inside of Pimcore, no chance of changing the version behaviour there.

**Comment by dpfaffenbauer** [comment]
guess thats fixed now?

**Comment by solverat** [comment]
done!
