### ISSUE TITLE
Changing quantity of a suborder items to 0 has no result

### ISSUE THREAD

**Issue by alex-jungwirth** [coreshop/CoreShop#2553]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When changing the quantity to 0 of a suborder in order detail view, nothing happens.

\coreshop\core-shop\src\CoreShop\Bundle\OrderBundle\Controller\OrderController.php:330
$orderItem->getQuantity() has the initial value, not 0.

Expected behavior should be: if the suborder contains only one item or another item with quantity of 0, suborder should be canceled.

Installed Versions: Coreshop 3.2.5, Marketwarehouse Bundle dev-main 67e9211.

**Comment by dpfaffenbauer** [comment]
@alex-jungwirth I just tested it and it worked. same versions as you. the quantity changed to 0.

**Comment by dpfaffenbauer** [comment]
ping @alex-jungwirth
