### ISSUE TITLE
null check in CartItemQuantityModifier

### ISSUE THREAD

**Issue by breakone** [coreshop/CoreShop#2556]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             | yes/no

Bug in`CartItemQuantityModifier`: null check for defaultUnitQuantity on cart creation is never used, because `$currentQuantity === $targetQuantity`.

**Comment by dpfaffenbauer** [comment]
Problem is in the projects implementation, not CoreShop

**Comment by dpfaffenbauer** [comment]
anybody ever facing the same issue, if you create a cart-item that you want to add to the cart, you have to use the cart-modifier to set the quantity, not setting it direcly:

false: 

```php
$cartItem->setQuantity(1);
```

right:

```php
/**
  * @var CoreShop\Component\Core\Order\Modifier\CartItemQuantityModifier $itemQuantityModifier
 */
$itemQuantityModifier->modify($cartItem, 1);
```

**Comment by jdreesen** [comment]
Maybe we should add some PHPDoc, so people are aware of it?

**Comment by dpfaffenbauer** [comment]
in the setQuantity function?

**Comment by jdreesen** [comment]
Yes, if it's not to be used directly in projects, I think it should be specified (and what to use instead). Otherwise, people *will* probably use it.
