### ISSUE TITLE
Payment Provider Rules -> Actions display bug

### ISSUE THREAD

**Issue by alintentu** [coreshop/CoreShop#2561]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hello @dpfaffenbauer,

![image](https://github.com/coreshop/CoreShop/assets/19413038/aad288e5-3f89-441f-b876-e10bc634ef8e)
it seems there is an bug on the Payment Provider Rules -> Actions -> coreshop_action_paymentProviderRule

there is no reason to have this, the fix on this seem not to work. This is on the demo3.coreshop.org/admin.

 Best regards!

**Comment by dpfaffenbauer** [comment]
@alintentu The idea behind this is to re-use other rules like we have with shipping rule conditions/actions. If it's not working, we need to fix it ;)
