### ISSUE TITLE
Add address addition (Adresszusatz), to CoreShop order view

### ISSUE THREAD

**Issue by alintentu** [coreshop/CoreShop#2563]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Hello @dpfaffenbauer,

We have a requirement from a customer and I would like to hear your opinion on this.
The customer will like to have the “Address Addition” (Adresszusatz) to the order detail view in the admin backend.
Here:
![image](https://github.com/coreshop/CoreShop/assets/19413038/63d7406b-5f3e-40f8-a0f4-c263bf06830c)

Best regards!

**Comment by dpfaffenbauer** [comment]
@alintentu and what addresses should be shown here?

**Comment by alintentu** [comment]
![image](https://github.com/coreshop/CoreShop/assets/19413038/56aed2fb-0fe0-41b6-90a7-38a54cfd287d)
they have a Address Addition (Adresszusatz), sorry, i'm not a German speaker.

**Comment by dpfaffenbauer** [comment]
Ah, you can just use the address Format in the Country Configuration to display that. That uses a twig format to generate the address output.

**Comment by alintentu** [comment]
hey, 
It seems that will be a good solution but we would have to update the default addressFormat to contain {{ addition }}, since it seems that is a bad idea to update it for each country in particular. 
Do you have any suggestion on how to update this default addressFormat?

**Comment by alintentu** [comment]
Hey,
is it possible for you to add an "addition" to the $addressFormatReplaces in the CountryFixture file in CoreShop, or do you think this will not fix our issue.
this addition can be left empty if someone does not have a need for it, as it is just a string.
best regards!

**Comment by alintentu** [comment]
i will close the issue, the client will not use the addition field.
