### ISSUE TITLE
[Pimcore 11 / Bug] Add PimcoreSimpleBackendSearchBundle as dependency

### ISSUE THREAD

**Issue by aarongerig** [coreshop/CoreShop#2564]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

CoreShop should add and install the PimcoreSimpleBackendSearchBundle in order to prevent the following error in the browser console, when loading in the Pimcore backend.

```log
Uncaught TypeError: Cannot read properties of undefined (reading 'element') at:
coreshop.selector.object = Class.create(pimcore.bundle.search.element.selector.object, { ... });
```

**Comment by dpfaffenbauer** [comment]
we already do check here: https://github.com/search?q=repo%3Acoreshop%2FCoreShop%20PimcoreSimpleBackendSearchBundle&type=code
