### ISSUE TITLE
Fix Reports

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#257]
- [x] fix report sql errors
- [x] remove product dependency, always use order item, if not possible, iterate through `coreshop.implementations.coreshop.product` 
- [x] implement `mainObjectId` and `objectId` into orderItem to keep reports even if products and variants get deleted.
- [x] add missing reports
- [x]  add voucher report see #244 
- [x] improve report ux
- [x] allow to choose product type: `all types`, `only main product`,  `only variants` 
- [x] fix dashboard widgets, improve them to show some real nice numbers!
- [ ] set a default backend currency so reports can be displayed in right currency context

**Comment by dpfaffenbauer** [comment]
- [ ] set a default backend currency (in settings?) so reports can be displayed in right currency context
   - [ ] currency should be resolved from cart/order

**Comment by solverat** [comment]
merged.
