### ISSUE TITLE
Wrong Order Subtotal / Total Calculation when using Adjustments

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2572]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Add adjustment to order item via `coreshop.cart_processor` and priority `590` (for example `10.-`)
- Check total price in cart ⇾ should be ok
- Complete order
- Check total price in order ⇾ not ok

First, I was not sure if it has something to with the new immutable stuff (which is a hefty bc-break for custom cart processors and was undocumented).

But then I ran into other issues, and so I debugged it again. Still not sure, but I think the `CartSubtotalProcessor` is not allowed to recalculate adjustments in cart ⇾ order processing workflow:

```php
if ($cart->isImmutable()) {
    return;
}
```

After I've changed that, it works fine. Also, not sure why we didn't recognize it earlier... most probably, because my adjustment is not a discount but a simple surcharge on item layer.

**Comment by dpfaffenbauer** [comment]
I don't quite understand. You're saying that the `CartSubtotalProcessor` should also return when immutable?

**Comment by solverat** [comment]
Exactly. 

Because it triggers the `$cart->recalculateAdjustmentsTotal()` and that shouldn't be done, if the cart has been transformed => but that's something you may have to confirm.

**Comment by dpfaffenbauer** [comment]
can you show me how your custom processor looks?

**Comment by solverat** [comment]
```php
# tagged via coreshop.cart_processor, priority: 590
<?php declare(strict_types=1);

use CoreShop\Component\Order\Factory\AdjustmentFactoryInterface;
use CoreShop\Component\Order\Model\OrderInterface;
use CoreShop\Component\Order\Model\OrderItemInterface;
use CoreShop\Component\Order\Processor\CartProcessorInterface;
use CoreShop\Component\Product\Model\ProductInterface;
use CoreShop\Component\Registry\ServiceRegistryInterface;

final class MyAdjustmentProcessor implements CartProcessorInterface
{
    public function __construct(
        protected ServiceRegistryInterface $registry,
        protected AdjustmentFactoryInterface $adjustmentFactory
    ) {
    }

    public function process(OrderInterface $cart): void
    {
        if ($cart->isImmutable()) {
            return;
        }

        /** @var OrderItemInterface $item */
        foreach ($cart->getItems() as $item) {

            $product = $item->getProduct();
            if (!$product instanceof ProductInterface) {
                continue;
            }
            
            $amountNetTotal = 10;
            $amountGrossTotal = 20;

            $item->addAdjustment(
                $this->adjustmentFactory->createWithData(
                    'my_adjustment',
                    '',
                    $amountGrossTotal,
                    $amountNetTotal,
                )
            );
        }
    }
}
```

and my adjustment clearer:

```php
# tagged via coreshop.cart_processor, priority: 640

public function process(OrderInterface $cart): void
{
    if ($cart->isImmutable()) {
        return;
    }

    $cart->removeAdjustmentsRecursively('my_adjustment');
}

**Comment by dpfaffenbauer** [comment]
@solverat Problem is rather the `CartItemsImmutableProcessor`, it re-calculates the cart-item-total but never considers the adjustment. When I add `$item->recalculateAdjustmentsTotal();`, after the `processCartItem` it works

**Comment by solverat** [comment]
But why is this necessary? I might need some help to understand it right.

All other processors are not allowed to modify the values if the cart / item is immutable. No adjustments will be added but also not removed. Which is the basic idea behind it, right?

I've also added this check to my custom processor: Don't add / remove adjustments, if the order is immutable. Is this the right way to do it?

So I'm wondering why the `recalculateAdjustmentsTotal` should get called.

**Comment by dpfaffenbauer** [comment]
The idea is to allow different Processors for new Orders and committed Orders. When we want a feature to allow for editing the order in the backend after it has been created, we still need Processor for calculation. Since we don't want to get new prices from price-rules after the order has been committed, we mark them as immutable and use separate processor for re-calculation. 

It works/doesn't work by accident really. Since before we always added the adjustment and `recalculateAdjustmentsTotal` always got called. Now, after the order has been committed, we don't do that anymore, but the Item Calculation still happens. Since now the Immutable items processor is used (`CartItemsImmutableProcessor`), that one re-sets the cart-items total and never re-calculates the adjustments.

**Comment by solverat** [comment]
Alright, still difficult for me to understand - it feels a bit weird, that some parts won't get recalculated (like the parts within the `CartItemsProcessor`) and others don't (like adjustments). 

However, is it required for me, to add the `$cart->isImmutable()` check to my custom adjustment processor (like the 5 cents rounding thing, which is available in probably all of our projects)?

***

I just added your proposed change, but the order total is still wrong. Skipping the `CartSubtotalProcessor` if the order is immutable is my current hotfix-solution.

**Comment by dpfaffenbauer** [comment]
Skipping the `CartSubtotalProcessor` also breaks the re-calculation feature when you change the quantity in the backend after the order has been created. so thats not the real solution.

What happens if your processor doesn't check for immutable and always applies the rounding?

**Comment by solverat** [comment]
Ok. It's getting weirder. The adjustment is fine, with or without `isImmutable()` check.

The calculation is wrong as soon a price rule gets applied! Sum-Up:
- Product: 100,-
- Adjustment on Item with 10,-
- Price rule, 100,- Surcharge, all the time
- Summary Total: 210,- => OK!
- Summary Total in Order-Object AFTER ordering: 310,- (the surcharge price rule gets applied twice)

We just tested it on different projects, it's occurs at all of them.

**Comment by solverat** [comment]
I probably found something:

- In my processor, the `addAdjustment` triggers the `recalculateAdjustmentsTotal` method. 
- CartSubtotalProcessor also calls the `recalculateAdjustmentsTotal` method

Both will sequentially increase the adjustment amount. All this, because the adjustment clearer is disabled at this state:

https://github.com/coreshop/CoreShop/blob/1ca9f58651ebb314a56a942d5c7e1df5e89eb423/src/CoreShop/Component/Core/Order/Processor/CartAdjustmentClearer.php#L25-L30

**Comment by dpfaffenbauer** [comment]
well, the main reason is a priority and calculation issue.

1. We calculate the item prices
2. We sum them to cart-subtotal
3. We apply cart-rules which can change item-prices
4. We never sum the changed subtotal

When we are immutable we do

1. We calculate the item prices and include the adjustments (with my change from a previous comment)
2. We calculate the order adjustments and combine them

Since Cart Price Rules are always applied against the item, we now have it applied twice. It is a calculation and priority issue. I am working on a solution.
