### ISSUE TITLE
MailProcessor adds Recipient twice

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2581]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Create a Mail Template
- Add "demo@coreshop.org"  in `To:` field
- Use notification rule or just use `$this->mailProcessor->sendMail($mailDocument, $order, null, [], $mailParams);`
- Mail gets submitted twice

Reason:

https://github.com/coreshop/CoreShop/blob/b814c70d1ef36b7f43ace5e877735617d4235464/src/CoreShop/Component/Pimcore/Mail.php#L53-L61

Which is just a duplicate of pimcores internal mail processor:

https://github.com/pimcore/pimcore/blob/3b9af529ec41cc6a9723dde96714df67b65d6078/lib/Mail.php#L378-L382

**Comment by dpfaffenbauer** [comment]
where does pimcore add the to again?

**Comment by solverat** [comment]
@dpfaffenbauer: Pimcore doesn't, CoreShop does. Because coreshop uses the `$mail->setDocument()`, pimcore internally calls `setDocumentSettings()` which applies all recipients. 

After that, coreshop also adds them here:

https://github.com/coreshop/CoreShop/blob/b814c70d1ef36b7f43ace5e877735617d4235464/src/CoreShop/Component/Pimcore/Mail.php#L53-L61

Most of the time, shop mails property `$to` is empty, because they should be dynamically sent to the customer. But using notification rules with a defined recipient, the mail will be submitted twice.

**Comment by dpfaffenbauer** [comment]
So we should stop adding that then right? or at least check for duplicates?

**Comment by solverat** [comment]
Removing this part should be safe, I guess?

https://github.com/coreshop/CoreShop/blob/b814c70d1ef36b7f43ace5e877735617d4235464/src/CoreShop/Component/Pimcore/Mail.php#L51-L57

This part is covered in `MailProcessor->setDocument()` which triggers the `setDocumentSettings()` method.
