### ISSUE TITLE
PimcoreGoogleMarketingBundle installation causes ExtJs errors

### ISSUE THREAD

**Issue by lukadschaak** [coreshop/CoreShop#2583]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hello Dominik,

i have the feeling, that `PimcoreGoogleMarketingBundle` is not working properly when it is installed.

* Install Coreshop as described in docs
* `bin/console pimcore:bundle:install PimcoreGoogleMarketingBundle`
* Open Admin Backend and the JS console show this error:
![Bildschirmfoto vom 2024-03-14 13-52-52](https://github.com/coreshop/CoreShop/assets/2377363/90243105-5b2c-4b28-84c0-5c2db200adff)
Side effect: Some of the main menu buttons (as well as the Coreshop button) does not work, because the script exists very early.

I gues the reason are cuncurrent bundle priorities.

The `CoreShopTrackingBundle` is loaded with priority 2000. It requires the [PimcoreGoogleMarketingBundle](https://github.com/coreshop/CoreShop/blob/4.0/src/CoreShop/Bundle/TrackingBundle/CoreShopTrackingBundle.php#L33) with priority 1000.

The `PimcoreGoogleMarketingBundle` then requires the [PimcoreCustomReportsBundle](https://github.com/pimcore/google-marketing-bundle/blob/1.x/src/PimcoreGoogleMarketingBundle.php#L76) with priority 20.

The priorities 2000 > 1000 > 20 takes action, after the `PimcoreGoogleMarketingBundle` is installed. It's ExtJs files are added to the minified scripts before the ones of the `PimcoreCustomReportsBundle`, which causes the error.

Maybe a different priority would help. On the other hand this can be solved by overwriting the priority in the `Kernel.php` (which was fixed a few patch versions of Pimcore ago). But this seems unintuitive to me.

**Comment by dpfaffenbauer** [comment]
I think it helps if we use the same Priorities as Pimcore for Pimcore Bundles right?

**Comment by lukadschaak** [comment]
I guess this is up to you :D But for me this sounds like a good approach

**Comment by solverat** [comment]
Same here. `CoreShopTrackingBundle` gets loaded with prio 2000, => which requires `PimcoreGoogleMarketingBundle` => which requires `PimcoreCustomReportsBundle` first => which gets loaded by coreshop with a low prio of 10.

After fixing that, I have another issue: 

![image](https://github.com/coreshop/CoreShop/assets/700119/758d1263-371a-4a51-ba4b-7bfa4f06efcd)
![image](https://github.com/coreshop/CoreShop/assets/700119/8bb84512-cdd8-4a28-a117-3eee6cf7eff0)

After adding `CoreShop\Bundle\ProductQuantityPriceRulesBundle\CoreShopProductQuantityPriceRulesBundle::class` to the ` bundles.php` before `CoreShop\Bundle\CoreBundle\CoreShopCoreBundle::class`, the error is gone.

**Comment by dpfaffenbauer** [comment]
does this https://github.com/coreshop/CoreShop/pull/2606 fix it for you too?

**Comment by lukadschaak** [comment]
Tested it locally and works for me :+1:

**Comment by solverat** [comment]
@dpfaffenbauer still not working in my projects after updating to 4.0.5 (I've added your #2606 changes too):

![image](https://github.com/coreshop/CoreShop/assets/700119/38670f9f-7677-46d4-814c-65c3bfdcff8f)
![image](https://github.com/coreshop/CoreShop/assets/700119/c93fd9a5-6953-4f44-8f60-7120481375f2)

My current fix is adding `CoreShop\Bundle\ProductQuantityPriceRulesBundle\CoreShopProductQuantityPriceRulesBundle::class` to my project `bundles.php`

**Comment by solverat** [comment]
btw. but everything else seems to work so far.

**Comment by dpfaffenbauer** [comment]
I'll check again then

**Comment by dpfaffenbauer** [comment]
@solverat I cannot reproduce the issue with the Quantity Price Rules Extension. It works for me. Can you show me how and what bundles you have registered in which order?

**Comment by dpfaffenbauer** [comment]
@solverat How do you have the CoreShop Core Bundle registered?

**Comment by dpfaffenbauer** [comment]
@JustMe69 @solverat can you both provide me the output of `bin/console pimcore:bundle:list` so I can see the priorities of the bundles loaded?

**Comment by solverat** [comment]
@dpfaffenbauer I tested it again with https://github.com/coreshop/CoreShop/pull/2606, this time with a cache clear (which i forgot last time…) and it works (I'm adding coreshop core to the `bundles.php`. 

Hint: I only had to change the priority from `1600` to `$collection->addBundle(new CoreShopCoreBundle(), 100);` in `CoreShopFrontendBundle` - all other changes weren't required on my side to make it work.

**Comment by dpfaffenbauer** [comment]
ok good. then I consider this as fixed.

@lukadschaak you wanna test as well?

**Comment by lukadschaak** [comment]
Nope, the current solution is fine for me :)
