### ISSUE TITLE
Gift Product with Tracked Stock: ceil(): Argument #1 ($num) must be of type int|float, null given

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2589]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Create a cart price rule with a gift product
- the gift product needs to have tracked stock
- go to cart, check if gift product is there
- go to checkout and finalize
- exception:

![image](https://github.com/coreshop/CoreShop/assets/700119/002ed11f-6208-4273-ae1d-5632db2ad0ff)

Setting the default unit quantity happens here in gift product action
https://github.com/coreshop/CoreShop/blob/445201ae696420fdf149d297ca38a969e400e27e/src/CoreShop/Component/Core/Cart/Rule/Action/GiftProductActionProcessor.php#L78-L84

and I guess it should be similar to this:
https://github.com/coreshop/CoreShop/blob/445201ae696420fdf149d297ca38a969e400e27e/src/CoreShop/Component/Core/Order/Modifier/CartItemQuantityModifier.php#L51-L55

**Comment by solverat** [comment]
Setting ` $item->setDefaultUnitQuantity(1);` outside the if-clause should be enough. 

It is still wrong, but in the gift product action, we don't know which unit definition to choose.

**Comment by dpfaffenbauer** [comment]
the unit should be choosen in the price rule action, right?

**Comment by dpfaffenbauer** [comment]
but for now, as a fix we can use the default unit.

**Comment by solverat** [comment]
@dpfaffenbauer Of course, that would be premium. :)  If a product has multiple unit definitions, the action should show them in a dropdown. This would allow us to set `$item->setUnitDefinition` and `$item->setDefaultUnitQuantity` definitely correct. 

Maybe second prio.
