### ISSUE TITLE
Unify Price Formatting

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#259]
Always use same price formatting. Currently there are multiple implementation `100 €`, `€100`..

**Comment by dpfaffenbauer** [comment]
where? It actually should use the MoneyFormatter (https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/MoneyBundle/Formatter/MoneyFormatter.php) class

**Comment by solverat** [comment]
- carrier fee has €xx
- reports (uses $this->moneyFormatter->format) has €xx
- default has xx €

**Comment by dpfaffenbauer** [comment]
guess thats a locale issue...

**Comment by dpfaffenbauer** [comment]
Carrier fee: https://github.com/coreshop/CoreShop/commit/d90ae1b63364df3d03b769c253780223da2c9ee9

**Comment by dpfaffenbauer** [comment]
https://github.com/coreshop/CoreShop/commit/6c598e7d4fe577e508f2a15fc571065ecd5e7e90 and https://github.com/coreshop/CoreShop/commit/951cb7d046ce039847a899c218819ee0988e26fa fixes this issue.

Note: It seems like the locale de and de_CH differently format money. de is 100 € and de_CH is € 100. There is no admin locale for de_CH, therefore it will be displayed differently in backend than as in frontend.

**Comment by solverat** [comment]
well i think we can live with that. thanks!
