### ISSUE TITLE
Replace plugin style with event listener

### ISSUE THREAD

**Issue by tip-top-b** [coreshop/CoreShop#2595]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes

Can you replace it with event listener: `src/CoreShop/Bundle/ResourceBundle/Resources/public/pimcore/js/selector/object.js`?

**Comment by dpfaffenbauer** [comment]
sorry what do you mean?

**Comment by tip-top-b** [comment]
I've installed the latest version of `coreshop` in Pimcore 11.2.2 instance, but I'm getting this error

![Screenshot from 2024-04-04 10-04-24](https://github.com/coreshop/CoreShop/assets/122413891/33aabfd6-0930-4c52-9b9b-11ca83132f0b)
and 
![Screenshot from 2024-04-04 10-04-39](https://github.com/coreshop/CoreShop/assets/122413891/99c6db58-9a4e-4303-82fb-61b27cc8d342).

According to the latest version of Pimcore, using plugins is deprecated, and it's replaced with event listener, in this case, you have to remove 'pimcore.bundle.search.element.selector.object' from:
```
pimcore.registerNS('coreshop.selector.object');
coreshop.selector.object = Class.create(pimcore.bundle.search.element.selector.object,{
    fieldObject: {},
    gridType: 'object',
```

**Comment by dpfaffenbauer** [comment]
no, thats not the issue. Issue is that you probably didn't activate the BackendSearchBundle

**Comment by tip-top-b** [comment]
I had activated it, but it was a cache issue. Thanks anyway.
