### ISSUE TITLE
Gift Item: Product Name missing in Order Item

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2599]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When a gift product gets added to the cart, the product name does not get applied to the order item itself => which leads to an empty row in the order detail view!

![image](https://github.com/coreshop/CoreShop/assets/700119/3f536c9c-577c-4885-9037-8d11d2e4b361)

**Comment by dpfaffenbauer** [comment]
@solverat fix is here: https://github.com/coreshop/CoreShop/pull/2602

Problem comes down to priorities of the Cart Processor
