### ISSUE TITLE
Add MessengerBundle permissions

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#2608]
### Discussed in https://github.com/coreshop/CoreShop/discussions/2607

<div type='discussions-op-text'>

<sup>Originally posted by **NiklasBr** April 17, 2024</sup>
Which permissions do we need to enable to allow non-admin users to view the menu item and dashboard?</div>

**Comment by dpfaffenbauer** [comment]
@NiklasBr PR is ready

**Comment by dpfaffenbauer** [comment]
is done.

**Comment by NiklasBr** [comment]
Thanks a lot!
