### ISSUE TITLE
E-Mail Notification doesn't consider themes

### ISSUE THREAD

**Issue by hethehe** [coreshop/CoreShop#2610]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If you have a multi site instance and try to send an reset password e-mail, the themes are ignored.
It doesn't consider the Store setting (Template) and neither the document property.

In the front end it works.

**Comment by dpfaffenbauer** [comment]
@hethehe I assume your PR fixes this right?

**Comment by dpfaffenbauer** [comment]
@hethehe if so, please close this

**Comment by hethehe** [comment]
@dpfaffenbauer 
Unfortunately not

But I will try to create a PR for it.
May you have any idea where I should start to investigate?

**Comment by hethehe** [comment]
@dpfaffenbauer 

I just realized that the error is mine, it looks like I had the wrong folder structure for the bundle theme.

I close it.
Sorry for the inconvenience.
