### ISSUE TITLE
Backend indices configuration: JS Error due to missing global function ts()

### ISSUE THREAD

**Issue by gadget60** [coreshop/CoreShop#2633]
In coreshop's "indices" configuration where available fields are listed, an exception is thrown if any field of type objectbrick, classification store or fieldcollection exists.

There is a global function "ts" expected - don't know if it used to exist in former Pimcore versions, but in current v11 it is undefined.
This makes all of these special fields unlisted and therefore unselectable.

The function gets called here:

https://github.com/coreshop/CoreShop/blob/b8e4349c76726677f96b5fd43a9904fba24ae0e8/src/CoreShop/Bundle/IndexBundle/Resources/public/pimcore/js/index/fields.js#L310

... and two more times on following lines.

```
script-proxy?storage…ea4fe3eb8f505:32022 Uncaught ReferenceError: ts is not defined
    at klass.initLayoutFields (script-proxy?storage…fe3eb8f505:32022:25)
    at Object.callback (ext-all.js?_dc=8fbf4…fe3eb8f505:1827:134)
    at constructor.onComplete (ext-all.js?_dc=8fbf4…4fe3eb8f505:2655:25)
    at constructor.onStateChange (ext-all.js?_dc=8fbf4…fe3eb8f505:2652:746)
    at ext-all.js?_dc=8fbf4…fe3eb8f505:2652:601
    at Object.elevate (ext-all.js?_dc=8fbf4…fe3eb8f505:1547:178)
    at XMLHttpRequest.<anonymous> (ext-all.js?_dc=8fbf4…fe3eb8f505:2652:579)
﻿
```

**Comment by aarongerig** [comment]
For reference: https://github.com/pimcore/pimcore/blob/11.x/doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md?plain=1#L246

> Use `t()` instead of `ts()` for translations.

**Comment by dpfaffenbauer** [comment]
@gadget60 Hey, how are you? Long time no see :)

Would you mind to create a PR? We will do a release tomorrow and I am kind of busy until then
