### ISSUE TITLE
The service "CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController" has a dependency on a non-existent service "Pimcore\Security\User\TokenStorageUserResolver".

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2642]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Release [3.2.8](https://github.com/coreshop/CoreShop/releases/tag/3.2.8) is broken. Don't know why tests have passed here https://github.com/coreshop/CoreShop/commit/1a0e629e8053d757eb01f63c9abceb68fb38539d since this will crash the whole application?

**Comment by dpfaffenbauer** [comment]
@solverat I keep this open since until the min requirement of 10.6 is merged
