### ISSUE TITLE
The "serializer" service or alias has been removed

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2657]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

https://github.com/coreshop/CoreShop/blob/820258ecc5707ebbe9683dff985d6d00788390e8/src/CoreShop/Bundle/CoreBundle/Controller/ReportsController.php#L70

https://github.com/coreshop/CoreShop/blob/820258ecc5707ebbe9683dff985d6d00788390e8/src/CoreShop/Bundle/CoreBundle/Controller/PortletsController.php#L69

Both will end up with an exception `The "serializer" service or alias has been removed or inlined when the container was compiled.` which is weird, because the `serializer` is available within the subscribed services in symfonys AbstractControlller.

**Comment by dpfaffenbauer** [comment]
version?

**Comment by solverat** [comment]
Latest 4.
