### ISSUE TITLE
Incompatibility with Pimcore 11.3.1

### ISSUE THREAD

**Issue by BlackbitDevs** [coreshop/CoreShop#2663]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

In https://github.com/pimcore/pimcore/pull/17281 Pimcore has changed the return type for `slug` fields, see https://github.com/pimcore/pimcore/blob/b9474dceca772073d6d4c26763099fc727fa90ad/models/DataObject/ClassDefinition/Data/UrlSlug.php#L550

This conflicts with https://github.com/coreshop/CoreShop/blob/52781b3bb4e6f8f6a50a1333b022d2873cf2b342/src/CoreShop/Component/Pimcore/Slug/SluggableInterface.php#L37C29-L37C41

Cannot really understand why they do such BC breaks in a patch version but anyway, latest Coreshop is not compatible with latest Pimcore anymore. Have also askes this in https://github.com/pimcore/pimcore/commit/05fee2c74cab47277e15558ee5aacf8f716a4a25#r144367054 (because https://github.com/pimcore/pimcore/pull/17281 is already closed without any chance to add a comment there...)

**Comment by dpfaffenbauer** [comment]
🙈

**Comment by fashxp** [comment]
why not just create an issue at pimcore/pimcore for that?

**Comment by dpfaffenbauer** [comment]
@BlackbitDevs Pimcore reverts this change, we could add a conflict with Pimcore 11.3.1.

**Comment by dpfaffenbauer** [comment]
@fashxp because sometimes there is things we can do on our end ;) and Pimcore 11.3.1 is incompatible now and we might add a conflict.

**Comment by fashxp** [comment]
Sure, but this is obviously a bug, and moaning somewhere else and adding comments somewhere in PRs (which might get overseen), it might be better to create an Issue ... that's why I'm asking. 
Anyway, revert is on the way.

**Comment by dpfaffenbauer** [comment]
@fashxp ok?

**Comment by BlackbitDevs** [comment]
@fashxp The main cause for creating the issue here is the setting that comments are not allowed in closed PRs, for me https://github.com/pimcore/pimcore/pull/17281 looks like this:
<img width="1008" alt="Bildschirmfoto 2024-07-18 um 09 54 06" src="https://github.com/user-attachments/assets/99c73f7b-a378-4cee-a6c7-1ac66556f377">

For this reason I notified you in https://github.com/pimcore/pimcore/commit/05fee2c74cab47277e15558ee5aacf8f716a4a25#r144367054

To be honest, I did not know which code variant was correct - I only noticed that CoreShop's and Pimcore's latest versions were not compatible anymore.

**Comment by NiklasBr** [comment]
I think this [was reverted](https://github.com/pimcore/pimcore/pull/17363) so CoreShop can allow 11.3.2 now, right?

**Comment by dpfaffenbauer** [comment]
only 11.3.1 is conflicting.

**Comment by NiklasBr** [comment]
You're right, 11.3.2 was blocked by a composer update so I instinctively thought it was this conflict, but it was actually this change causing my troubles: https://github.com/pimcore/pimcore/pull/17258

Had to downgrade `symfony/string` to version 6 to get it installed.
