### ISSUE TITLE
State labels not translated correctly

### ISSUE THREAD

**Issue by benwalch** [coreshop/CoreShop#2673]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

State labels in backend order overview are not translated correctly.
The custom operator `OrderState` does not respect the language of the grid configuration/the current backend user.

![image](https://github.com/user-attachments/assets/5ac162cf-110c-40ca-8975-69757d4d3bfd)

**Comment by dpfaffenbauer** [comment]
@benwalch see https://github.com/coreshop/CoreShop/pull/2677
