### ISSUE TITLE
Wishlist Retains Items from Previous User

### ISSUE THREAD

**Issue by nsd0sketzler** [coreshop/CoreShop#2683]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Steps to reproduce
- I register myself in the demo shop and add a product to my wishlist. After that, I log out.
- Then I create another customer account, log in, and check the wishlist.

Acutal behavior
- I am still seeing the wishlist of the previously logged-in user. The share link doesn't change either.
- here with user pia

![Screenshot from 2024-08-12 12-05-49](https://github.com/user-attachments/assets/15d69645-aad5-42ce-bdb7-1aadac04425f)

- here with user test

![Screenshot from 2024-08-12 12-05-19](https://github.com/user-attachments/assets/fd3eaa60-58a6-408d-8486-3e73420ed710)

Expected
- I expect that when I log out, no products should be visible in the wishlist.
- When another user logs in on the same PC, the wishlist should be empty.

**Comment by dpfaffenbauer** [comment]
@nsd0sketzler see #2684
