### ISSUE TITLE
PayumBundle import naming conflict

### ISSUE THREAD

**Issue by la-lisa** [coreshop/CoreShop#2688]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

`Payum\Bundle\PayumBundle\EventListener\ReplyToHttpResponseListener::__construct(): Argument 1 ($replyToSymfonyResponseConverter) must be of type Payum\Bundle\PayumBundle\ReplyToSymfonyResponseConverter, CoreShop\Bundle\PayumBundle\Exception\ReplyToSymfonyResponseConverter given.`

It seems like there is a namespace conflict between Payum\Core\Bridge\Symfony\ReplyToSymfonyResponseConverter and Payum\Bundle\PayumBundle\ReplyToSymfonyResponseConverter in ** CoreShop\Bundle\PayumBundle\Exception**
When changing the import to Payum\Bundle\PayumBundle\ReplyToSymfonyResponseConverter in the Exception the error is fixed. 

Pimcore V11.3.0
Coreshop V4.0.9
PHP 8.2

**Comment by dpfaffenbauer** [comment]
@la-lisa we also ran into that issue and fixed it by removing minimum-stability from composer.json like here: https://github.com/coreshop/CoreShop/commit/8d995ebedda0b4f6cf27b2595ce6fe5ec08268c4

Can you confirm this fixes it?

**Comment by la-lisa** [comment]
@dpfaffenbauer 
Well this is fixes it. Thanks. 
Maybe a hint in the docs would be helpful or fixing the issue in the next version, as pimcore recommends adding the minimum stability in its docs. Also their demo composer.json has the min stability stated.

**Comment by dpfaffenbauer** [comment]
Where does pimcore state that? I also checked the Demo Repo and I could not see the minimum stability there: https://github.com/pimcore/demo/blob/2024.x/composer.json

**Comment by jdreesen** [comment]
> I also checked the Demo Repo and I could not see the minimum stability there: [pimcore/demo@2024.x/composer.json](https://github.com/pimcore/demo/blob/2024.x/composer.json?rgh-link-date=2024-08-20T13%3A36%3A09Z)

Here it is: https://github.com/pimcore/demo/blob/2024.x/composer.json#L16-L17

**Comment by dpfaffenbauer** [comment]
@jdreesen gotcha, we got this fix now: https://github.com/coreshop/CoreShop/pull/2689

**Comment by dpfaffenbauer** [comment]
fixed with https://github.com/coreshop/CoreShop/pull/2689
