### ISSUE TITLE
Split (specific) Price Rules

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#269]
We'll discuss this first internally. The Idea: Split price and discount action:

## Price Definition
- define new price

## Price Discount
- amount discount
- percentage discount

The rules stays the same. Workflow:
- Iterate Price Definitions first (global than specific)
- Iterate Price Discount second (global and specific)
- Allow pre and post event in loop
- Add applied price and calculator to Iterator as a Stack

**Comment by dpfaffenbauer** [comment]
done. well, not exactly as described here, but as we discussed.
