### ISSUE TITLE
DataObjectBatchListing ignores ->setOffset()

### ISSUE THREAD

**Issue by hethehe** [coreshop/CoreShop#2714]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If we create a `Listing `and set a offset with `$listing->setOffset(100)` and use it with the `CoreShop\Component\Pimcore\BatchProcessing\DataObjectBatchListing` it gets ignored.

I think the problem is that you get the [`loadIdList()`](https://github.com/coreshop/CoreShop/blob/38d6eca36bc3116a0c23218007e79f3f24e5b0bc/src/CoreShop/Component/Pimcore/BatchProcessing/DataObjectBatchListing.php#L106) and the [`getTotalCount()`](https://github.com/coreshop/CoreShop/blob/38d6eca36bc3116a0c23218007e79f3f24e5b0bc/src/CoreShop/Component/Pimcore/BatchProcessing/DataObjectBatchListing.php#L84) from the `DAO` instead directly from the `$list`

Is there a special reason you use the `$dao` instead the `$list` directly?

**Comment by dpfaffenbauer** [comment]
@hethehe honestly, not sure... we never actually had in mind that the BatchList can use a offset :D.

**Comment by hethehe** [comment]
@dpfaffenbauer We tried to set an offset for the `coreshop:index` command, as sometimes it would be nice not to include all products ;)

Are you interested in a PR that changes the `$dao` to `$list`? I don't see anything that could break, WDYT?

**Comment by dpfaffenbauer** [comment]
@hethehe yes, we are interested. it should be tested anyway, maybe you can add another test for offests?

**Comment by hethehe** [comment]
Just realized, that this is not a problem of your `BatchListing `but from Pimcore's `getTotalCount()` 
see: https://github.com/pimcore/pimcore/issues/17618

**Comment by dpfaffenbauer** [comment]
gotcha, then we can close this?

**Comment by hethehe** [comment]
yes, closed

**Comment by kingjia90** [comment]
Can this issue be opened again please? 
I believe the initial issue would be fixed if we replace `getTotalCount()` to `getCount()` in there

https://github.com/coreshop/CoreShop/blob/38d6eca36bc3116a0c23218007e79f3f24e5b0bc/src/CoreShop/Component/Pimcore/BatchProcessing/DataObjectBatchListing.php#L86-L94

see also https://github.com/pimcore/pimcore/issues/17618#issuecomment-2353334021

**Comment by dpfaffenbauer** [comment]
@hethehe can you give it a test?
