### ISSUE TITLE
Store Context in Messenger Queue Missing

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#2726]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Given:
- No pimcore site
- Just one store

Using the context within the order confirmation mail template will rise an `StoreNotFoundException`.

Reason: When starting `messenger:consume coreshop_notification`, the `CachedStoreContext` instantly gets triggered ⇾ no store could be found ⇾ `initialized` will be set to `true` ⇾ never gets checked again in incoming messages.

However, this worked before https://github.com/coreshop/CoreShop/pull/2562, because of the `cachedStore === null` check.

Since the messenger may not provide a request, this is correct anyway, but to provide a store within the messenger context? Currently, i just created custom store resolver with a low priority which loads the default store.

**Comment by dpfaffenbauer** [comment]
@solverat https://github.com/coreshop/CoreShop/pull/2727 should fix it. But usually, in a Mail, you should not rely on the StoreContext. You should rather use the Store assigned to the Order.
