### ISSUE TITLE
Multiple StoreValue Data-Fields in Object

### ISSUE THREAD

**Issue by la-lisa** [coreshop/CoreShop#2746]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes/no

Steps to reproduce:
We added multiple storeValue fields in our product class, one for overall price and one for different shipping prices per product. 
![Bildschirmfoto 2024-11-05 um 11 19 48](https://github.com/user-attachments/assets/75d3d6a9-6fbc-4c47-a698-287201e1fc70)

When filling in prices for both those fields then, there occurs a unique constraint violation in the product_store_values table when saving, because the fields reference is not saved in the table (only productid and store). If filling in only one of the fields, saving is possible but the values are the same in both data fields then. 
![Bildschirmfoto 2024-11-05 um 12 28 10](https://github.com/user-attachments/assets/b2dce1a7-793e-45d0-b906-7d1455a99133)

Is it not possible anymore to have multiple coreShopStoreValues typed fields in one object? In previous versions it was possible to have multiple.

**Comment by dpfaffenbauer** [comment]
@la-lisa it never was meant to be used multiple times, we could try to enable that though.

**Comment by dpfaffenbauer** [comment]
what version you are having issues with?

**Comment by la-lisa** [comment]
> what version you are having issues with?

Newest Version. 4.0.11

**Comment by la-lisa** [comment]
> @la-lisa it never was meant to be used multiple times, we could try to enable that though.

Okay, good to know. A note in the docs or a validation on class definition save would be nice then. Because it can be added multiple times but has weird effects than.
In old versions it was possible although... We have a coreshop 2 where this works. Maybe with the product_store_prices table then or something like this.

**Comment by dpfaffenbauer** [comment]
@la-lisa I actually like the idea of having it multiple times. I see what I can do

**Comment by dpfaffenbauer** [comment]
@la-lisa https://github.com/coreshop/CoreShop/pull/2747
