### ISSUE TITLE
Implement Payment Settings

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#283]
Store PaymentProvider as Objectbrick to allow custom settings in frontend.

**Comment by dpfaffenbauer** [comment]
Implementation is finished, can you confirm?

**Comment by solverat** [comment]
I'm not sure about the paymentsetting stuff, but i think it's okay for now.

**Comment by solverat** [comment]
`paymentSettings`is only available during migration and is missing in install classes.
