### ISSUE TITLE
Finalize Order Revise

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#286]
With the new Order Revise mode, it's possible to:
- Create orders in backend and allow customer to complete the order within a separate payment selection step
- Return to payment selection step if payment has been cancelled or during a failure.

## Todo's

- [x] If the user comes back from a failed or cancelled payment, we need to allow him to cancel the order and restore the cart: If the cart id is available in session, show a "cancel order and restory my cart" button: This form needs to trigger the state machine `cancel` event on `coreshop_order` workflow.
- [x] Provide Custom Gateways a way to show some custom messages or even better a custom view above the payment selection

**Comment by dpfaffenbauer** [comment]
2. What about something like sonata? Like Events in views? Therefore the payment-bundle could hook into the "confirmation" page and display whatever it wants

**Comment by solverat** [comment]
1. create a coreshop payment error message by default which can be used by a custom payment bundle (in payment revise, check if message is available, otherwise display default cancel eg. error message.
2. implement payment provider resolver which will trigger an event for each payment provider

**Comment by dpfaffenbauer** [comment]
done :)
