### ISSUE TITLE
Use Pimcore Grid Configuration in Order List

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#291]
<img width="1124" alt="bildschirmfoto 2018-01-21 um 17 45 13" src="https://user-images.githubusercontent.com/700119/35196507-3e3b95e4-fed3-11e7-90f7-b25a31b2074e.png">

<img width="972" alt="bildschirmfoto 2018-01-21 um 17 51 38" src="https://user-images.githubusercontent.com/700119/35196545-c64250e0-fed3-11e7-93f1-17781350b1a2.png">

- [x] implement pimcore order state operator
- [x] grid element in sales list should open coreshop sales detail not object
- [x] remove delete context menu in list view

**Comment by solverat** [comment]
- [x] implement pimcore currency formatter operator
- [x] add grid config migration (create default grid configs
- [ ] add grid config to coreshop installer @dpfaffenbauer 

![bildschirmfoto 2018-01-22 um 11 06 09](https://user-images.githubusercontent.com/700119/35215390-5d6d10fa-ff64-11e7-83fb-f09d7f39bd06.png)
![bildschirmfoto 2018-01-22 um 11 06 02](https://user-images.githubusercontent.com/700119/35215391-5d87abea-ff64-11e7-87f2-1bf3639cec9d.png)

**Comment by dpfaffenbauer** [comment]
done
