### ISSUE TITLE
Respect Store in Index

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#301]
Keep bundle abstraction!

- [ ] ~implement `id` row in index~
- [ ] ~implement `store` row in index~
- [ ] ~implement `lang` row in index~
- [ ] ~remove views to allow elastic search adapter to use localized data~

**Comment by solverat** [comment]
After some tests this is not the right way to go. There should be a similar approach like it has been done in the memberBridge branch.

**Comment by dpfaffenbauer** [comment]
solved using localized index.
