### ISSUE TITLE
Cannot save payment provider correctly after changing it's type

### ISSUE THREAD

**Issue by EMDeKey** [coreshop/CoreShop#302]
# Bug Report
After a payment provider is created, it's probably use only the currently stored "GatewayConfigurationFormType" for checking the form variables.

So it's not possible to change an incorrect selected PaymentType.

**Comment by dpfaffenbauer** [comment]
this is actually expected behaviour, changing the factory of a provider could cause other issues with existing payments. I improved the UI, so a change is not possible in UI as well.
