### ISSUE TITLE
Password reset not working - redirect to home

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#307]
When you click on password reset, it's a redirect to shop home, the route is not working.
Url: /LOCALE/shop/password-reset-request, i think password-reset does not work too.

**Comment by GALCF** [comment]
I had the same problem and resolved it by setting different priorities.

**Comment by albertmueller** [comment]
when i set the priority to 0 for this route, then it works, but this fix just the route for /LOCALE/shop/password-reset-request, /LOCALE/shop/password-reset does not work then anyway
