### ISSUE TITLE
Install CoreShop in Pimcore 5.1.3

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#308]
If languages activated for example de and en_GB, then the install fails, the installation on sites with LANGUAGE_COUNTRY is not possible, i changed that then to en without _GB.
The installer continue then and i got the next error:
1/6 [░░░░░                       ]  16% Install Document /shop
In Document.php line 520:

[Exception]
ParentID and ID is identical, an element can't be the parent of itself.

**Comment by dpfaffenbauer** [comment]
can't really reproduce your issue... Is there maybe something customized?

**Comment by dpfaffenbauer** [comment]
as discussed, has nothing todo with CoreShop. More something with configuration or Pimcore.
