### ISSUE TITLE
coreshop.form.customer.email.unique Error

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#320]
# Bug Report
### Expected behavior 
  Be able to save profile in demo
### Actual behavior  
  Profile not saveable because the error coreshop.form.customer.email.unique is thrown unstyled
### Steps to reproduce  
  Setup Coreshop demo, create account in frontend. Login. Try to edit profile - do not change email adress, error coreshop.form.customer.email.unique is thrown because email does exist - but email is our current email so we should be allowed to use it.

**Comment by dpfaffenbauer** [comment]
Yeah, just encountered the same issue, this is a very new feature we implemented, a fix will be provided asap.
