### ISSUE TITLE
Wrong price displayed in admin

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#327]
# Bug Report
### Expected behavior 
  Display the proper price for a product in Pimcore Admin.
### Actual behavior  
  While the price in the database (visible through versions for example) is 419.14, Pimcore admin will show a price of 4.19 in the admin view while editing the product.
### Steps to reproduce  
  Setup a default coreshop instance with the default product class and use the CSV import for example to set the value of a Product WholesalePrice to 419.14.

Used Firefox latest (58.0.2).

**Comment by dpfaffenbauer** [comment]
Are you using the latest version? We encounterned an issue yesterday regarding prices.

A bit of a context for you: CoreShop stores price-information as integer. So, while a price in database shows 10000, the actuall price is 100,00.

**Comment by Cruiser13** [comment]
Installed it today at 13:00 directly from github dev-master.

**Comment by Cruiser13** [comment]
Prices need to be imported as integer, not using comma. 419.14 needs to be 41914 for coreshop. Thanks @dpfaffenbauer . It's working now.
