### ISSUE TITLE
Problem with the demo installation

### ISSUE THREAD

**Issue by nicogasque** [coreshop/CoreShop#331]
Hello,

I have successfully installed Coreshop and I'm trying to install the demo in Pimcore 5.1.3 and I have the following error after I run the command (php bin/console coreshop:install:demo):

Fatal error: Uncaught InvalidArgumentException: Unable to find file "@CoreShopCoreBundle/Resources/fixtures/3.jpeg". in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:307
Stack trace:
#0 /var/www/pimcore/vendor/coreshop/core-shop/src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php(76): Symfony\Component\HttpKernel\Kernel->locateResource('@CoreShopCoreBu...')
#1 /var/www/pimcore/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php(121): CoreShop\Bundle\CoreBundle\Fixtures\Data\Demo\ProductFixture->load(Object(Doctrine\ORM\EntityManager))
#2 /var/www/pimcore/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php(88): Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load(Object(Doctrine\ORM\EntityManager), Object(CoreShop\Bundle\CoreBundle\Fixtures\Data\Demo\ProductFixture))
#3 [internal function]: Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closur in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 307

Do I'm missing any data?

Thanks

**Comment by dpfaffenbauer** [comment]
can you pull again and re-try?

**Comment by nicogasque** [comment]
Hi,

Yes, and now I miss the image 1.jpg but almost the same error:

pimouser@CT1000:/var/www/pimcore$ php bin/console coreshop:install:demo
 0/1 [░                           ]   0%
Fatal error: Uncaught InvalidArgumentException: Unable to find file "@CoreShopCoreBundle/Resources/fixtures/1.jpeg". in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:307
Stack trace:
#0 /var/www/pimcore/vendor/coreshop/core-shop/src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php(76): Symfony\Component\HttpKernel\Kernel->locateResource('@CoreShopCoreBu...')
#1 /var/www/pimcore/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php(121): CoreShop\Bundle\CoreBundle\Fixtures\Data\Demo\ProductFixture->load(Object(Doctrine\ORM\EntityManager))
#2 /var/www/pimcore/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php(88): Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load(Object(Doctrine\ORM\EntityManager), Object(CoreShop\Bundle\CoreBundle\Fixtures\Data\Demo\ProductFixture))
#3 [internal function]: Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closur in /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 307

**Comment by dpfaffenbauer** [comment]
did you even pull the latest changes?

The fixture installer gets one of three images per random:

https://github.com/coreshop/CoreShop/blob/db65820142085f84e85ab6fd21f3a03ce4e39b42/src/CoreShop/Bundle/CoreBundle/Fixtures/Data/Demo/ProductFixture.php#L76

**Comment by nicogasque** [comment]
Yes I did now it works thank you very much.

I have a small question.
I know CoreShop is not 100 % finish but is it possible to start working with CoreShop in production as a PIM? 

Thanks for your help.

**Comment by dpfaffenbauer** [comment]
sure it is. There are already production website using CoreShop 2.
