### ISSUE TITLE
Column configuration operators not working

### ISSUE THREAD

**Issue by GALCF** [coreshop/CoreShop#333]
# Bug Report

The column configuration operators PriceFormatter and State do not work in custom folder column configurations.
## Example 
Filtering DataObject Invoice in folder "coreshop/orders":

Adding State operator with the state field as a child always outputs "--".
Adding PriceFormatter operator with the totalNet field as a child always outputs pure integer cent prices (e.g. "12300" for "123.00€").

**Comment by solverat** [comment]
State Operator: Only works with a valid label (see order grid config to get a clue)
Price Formatter: Only works if the element is an instance of SaleInterface

So inn general those operators are only available for order elements for now.
