### ISSUE TITLE
Improve Document Installer

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#344]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Currently CoreShop installs documents in / regardless which sites has been configured.

Document tree if you having multiple sites and a lot of languages running in pimcore before CoreShop install:

```
- site1.com
---- de
---- en
- site.2.com
---- fr
---- de_CH
```

After installation the document tree will look like this:

```
- site1.com
---- de
---- en
- site.2.com
---- fr
---- de_CH

- de
---- shop
- en
---- shop
- fr
---- shop
- de_CH
---- shop
```

## Possible Solution
Do not install documents automatically. Create a command (`coreshop:install:documents`) with `--root-document [id]` and `--language [de|en]` argument.

**Comment by dpfaffenbauer** [comment]
Well, but this would add a new install command and would also complicate things a bit more.

**Comment by solverat** [comment]
Na, nothing complicated here. Just need to add an additional line to the install manual. In some projects, we had several pages and about 30 locales installed. After the CoreShop installation all the new data were just a bunch of id-wasted documents without any usage. :)
