### ISSUE TITLE
CoreShop workflows are registered twice

### ISSUE THREAD

**Issue by sstunitb** [coreshop/CoreShop#353]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Creating an order (in the backend via "Create an order" and in the frontend via regular shop logic) results in:
> At least two workflows match this subject. Set a different name on each and use the second (name) argument of this method.

It fails in \Symfony\Component\Workflow\Registry (ln 54) because every Workflow from Coreshop is listed in there twice.

**Comment by dpfaffenbauer** [comment]
Guess you recently updated or installed CoreShop?

Please follow the Changelog https://github.com/coreshop/CoreShop/blob/master/CHANGELOG.md#200-alpha4-to-200-beta1 and adapt it to your installation.

Basically what happened: CoreShop now uses the dependent bundles feature from Pimcore and registers all Bundles + Configurations automatically. So you need to remove manual loading of bundles/configs.
