### ISSUE TITLE
Payment state buttons are missing

### ISSUE THREAD

**Issue by darkbind** [coreshop/CoreShop#359]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hey there again,

in the order view when you want to change the payment state there are the state buttons missing.
From order/state/changeState.js
``` 
window = new Ext.window.Window({
            width: 450,
            height: 170,
            modal: true,
            resizeable: false,
            title: t('coreshop_change_state'),
            layout: 'fit',
            items: [{
                xtype: 'label',
                margin: '20 0 20 20',
                border: 0,
                text: t('coreshop_change_state_description')
            },
                {
                    xtype: 'fieldcontainer',
                    layout: 'hbox',
                    margin: '30 20 20 20',
                    border: 0,
                    style: {
                        border: 0
                    },
                    items: buttons
                }]
        });
```
I guess it should be resolved if you change the window layout to 'vbox'.

Thanks.

**Comment by dpfaffenbauer** [comment]
can you provide a screen shot? it seems to be fine for me:

![bildschirmfoto 2018-03-08 um 10 52 50](https://user-images.githubusercontent.com/5981845/37144607-ded89eb6-22be-11e8-845d-02a604f97098.png)

**Comment by darkbind** [comment]
Here are the 2 different views (1. with layout fit and 2. vbox) .. hm, even with my changes it looks not like yours :disappointed: 
In my case the label box got the wrong height and pushes the fieldcontainer out of the view.
I tested it with Chrome and Firefox.

![view_with_fit_layout](https://user-images.githubusercontent.com/7676818/37145313-db22670a-22c0-11e8-9b12-1890d8e78c8a.png)
![view_with_vbox_layout](https://user-images.githubusercontent.com/7676818/37145314-db407240-22c0-11e8-8171-beba55422bd9.png)

**Comment by dpfaffenbauer** [comment]
What OS? And what exact browsers + versions?

**Comment by darkbind** [comment]
OS Ubuntu 16.04 LTS and Chrome Version 64.0.3282.119 64-bit / Firefox Quantum for Ubuntu 58.0.2 (64-Bit).

**Comment by dpfaffenbauer** [comment]
Can you try investigating that a bit more? I currently don't have any test env for Ubuntu? Can you also reproduce the issue on ```demo2.coreshop.org``` with ```username: admin password: coreshop```?

**Comment by darkbind** [comment]
Funny, on demo2.coreshop.org it looks like your screenshot.
 
There are no errors in the console while bringing up the order view or opening the mentioned popup.

**Comment by dpfaffenbauer** [comment]
thats odd... do you have anything special? any customization/changes? anything that makes this reproducible?

**Comment by dpfaffenbauer** [comment]
ping @darkbind any updates on this one?

**Comment by dpfaffenbauer** [comment]
closed due to inactivity. If still an issue, open another issue please.
