### ISSUE TITLE
Join / left join in Product Listing?

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#365]
Is it possible to add the functionality of join / left join in vendor/coreshop/core-shop/src/CoreShop/Component/Index/Listing/ListingInterface.php?

Something like that is already available in the default ecommerce framework:
pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
$this->getQuery()->join(
['product' => 'object_query_' . (int)$classId],
'product.oo_id = orderItem.product__id',
''
);

I need it to access a another class for pre filtering the product list.

Currently i use a anonymous class to overwrite the objects, but that's not a clean solution.

**Comment by dpfaffenbauer** [comment]
Currently there is nothing in master. There is something in MembersBridge branch that could be merged for that purpose. I'll have a look at that.

**Comment by dpfaffenbauer** [comment]
this is implemented now: https://www.coreshop.org/docs/2.0.0/Development/Index_and_Filters/Index/Extension.html
