### ISSUE TITLE
Ecommerce Tracking Enhancements

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#368]
| Q                | A
| ---------------- | -----
| Bug report?      | partly
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- `Pimcore\Google\Analytics` is deprecated. Use `Pimcore\Analytics\Google\Tracker` instead. 
- Also check if google tag manager data layer works after changing tracker (which does not currently)

**Comment by Cruiser13** [comment]
If you are at it please don't focus google only, Matomo (Piwik) should be thought of too.

**Comment by dpfaffenbauer** [comment]
done

**Comment by solverat** [comment]
1. Add Google Tag Manager Datalayer:
- simple (just checkout)
- enhanced (create coreShop* events)

2. Allow to disable tracker (universal should not get mixed with ga enhanced ec)

**Comment by solverat** [comment]
done with #397.
