### ISSUE TITLE
Shipping Rules Fallback not implemented

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#386]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

<img src="https://user-images.githubusercontent.com/700119/38190924-c46f64e0-3666-11e8-919c-76dbc1aaecb5.png">

Changing the "When no rule found" drop-down does not have any effect. Currently the rule gets disabled if no rule has been found (which is ok imo and should be the default).

**Comment by dpfaffenbauer** [comment]
feature has been removed due to never been implemented.
