### ISSUE TITLE
Add option for dynamic shipping costs

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#388]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

We do need to set the cost of shipping depending on the weight of the cart.
We can set shipping rule for lower as 4 kilogramms -> 4€ shipping costs.
Now we'd like to set every additional kilogramm 1€. So 6 kilogramm = 6 € shipping costs, 77 kilogramm = 77 € and so on.
It'd be great to have the possibility to add dynamic shipping costs somehow or to be able to self-implement rules using PHP.

Note that weight would be an example, could be depending on height or any other product attribute too.

**Comment by dpfaffenbauer** [comment]
already possible, you can add custom-actions as described here https://www.coreshop.org/docs/2.0.0/Development/Extending_Guide/Extending_Rule_Actions.html and implement a custom action which does exactly what you want.
