### ISSUE TITLE
Plus Buttons gone after adding payment

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#393]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If you edit an order in the admin area and add a payment using the plus button, the other plus buttons for shipment and invoice will be gone:
![plus-buttons](https://user-images.githubusercontent.com/2771909/38369964-443dca8e-38e9-11e8-89c0-2cf1cb6a2f0c.png)
They'll not return by using the reload button upper left but they are back again if you close the order completely and reopen it.

Latest Firefox 59.0.2 (64bit)

**Comment by dpfaffenbauer** [comment]
Well, they shouldn't be there in the first place. They should only be there when the order is actually paid.

**Comment by Cruiser13** [comment]
I'd propose to change this behaviour. You might need to generate an invoice to send out to a customer before being paid. Technically, this should be no problem. There is a check in CoreShop\Bundle\OrderBundle\Controller\OrderInvoiceController but $payments is not used for the invoice at all:
```php
        if (count($payments) === 0) {
            return $this->viewHandler->handle(['success' => false, 'message' => 'Can\'t create Invoice without valid order payment']);
        }
```
So we could remove this check and enable invoices before payments easily.

**Comment by dpfaffenbauer** [comment]
I propose you this solution: https://github.com/coreshop/CoreShop/commit/40ad1fe222c8c9b374750f931d7bc48b4a9c90b2

Having one single responsible class to determine if a invoice/shipment can be processed. If you then need to change the default CoreShop behaviour, go ahead an decorate the service.

**Comment by dpfaffenbauer** [comment]
PR is merged, you can now change the behaviour as you wish
