### ISSUE TITLE
Missing Bricks in Index Configuration

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#400]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Since a system upgrade to Pimcore 5.2.1, i cannot select fields from object bricks anymore to built up the CoreShop index, previously selected fields still there on "indexed fields".

**Comment by dpfaffenbauer** [comment]
can you give me more details? What is exactly not working? how does your configuration look like?

**Comment by albertmueller** [comment]
ahhh got it, it's a view bug, when you have many fields, more then 70 then it shows only "fields", with a whitespace after the fields, when i close "fields", then i can see the other types
