### ISSUE TITLE
Nice Urls Macro

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#413]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

The default coreshop routing creates ugly urls like: `shop/fr/Monogram%20Canvas%20Montaigne%20BB~p62`.

## Suggestion
We should implement a macro file which allows devs to create nice looking urls without changing all the templates. Affected routes:

- `coreshop_product_detail`
- `coreshop_category_list`

So instead of 

```twig
{{ path('coreshop_category_list', {name: category.getName, category: category.getId}) }}
```

we should use

```twig
{% import '@CoreShopFrontend/Common/Macro/routing.html.twig' as routing %}
{{ routing.nice_path('coreshop_category_list', {name: category.getName, category: category.getId}) }}
```

By default the macro will return the same url to prevent BC breaks.

## Open Question
What about routes which get generated via api (without template engine), they also should get transformed the same way.

**Comment by dpfaffenbauer** [comment]
Only viable solution would be a template helper that generates routes + a separate service. What do you think about that?

**Comment by dpfaffenbauer** [comment]
btw, you can already do that anyway. Why create a separate service for that when this is already symfony standard?

**Comment by solverat** [comment]
After some research. Basically we should use the [pimcore link generator](https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Link_Generator.html).

## Service
First, we need a global CoreShop service called `LinkGenerator`. This one can be injected and used to create urls in php context (links in mails for example):

```php
<?php

class LinkGenerator
{
    public function getLink(Concrete $entity, string $name, array $params)
    {
        $params['routeName'] = $name;
        $params['entity'] = $entity;

        if ($linkGenerator = $entity->getClass()->getLinkGenerator()) {
            $_params = array_merge($params, [
                'document'     => $this->documentResolver->getDocument();
                'context'      => $this
            ]);

            return $linkGenerator->generate($entity, $_params);
        }

        // throw exception if no link generator has been found for given class.
    }
}
```

## Twig
Create a Twig Extension (which calls `getLink()` from the service above) to generate links in templates:

```twig
{{ coreshop_link(product, 'coreshop_product_detail') }}
```

## Link Generator
Then CoreShop should provide a link generator service for each class (`product`, `category` should be enough?)  Add the services to the link generator in pimcore class configuration.
For example the product link generator

```php
<?php

class ProductDetailLinkGenerator implements LinkGeneratorInterface
{
    public function generate(Concrete $object, array $params = []): string
    {
        if (isset($params['document']) && $params['document'] instanceof Document) {
            // do something with given document
        }

        $staticRoute = Staticroute::getByName($params['coreshop_product_detail']);
        $path = $staticRoute->assemble([
            // generates nice slugs like my-awesome-url
            'name'      => $this->slugify($object->getName(),
            'product'   => $object->getId()
        ]);

        return $path;
    }

    public function slugify($string)
    {
        return strtolower(trim(preg_replace('~[^0-9a-z]+~i', '-', html_entity_decode(preg_replace('~&([a-z]{1,2})(?:acute|cedil|circ|grave|lig|orn|ring|slash|th|tilde|uml);~i', '$1', htmlentities($string, ENT_QUOTES, 'UTF-8')), ENT_QUOTES, 'UTF-8')), '-'));
    }
}
```

That's it. If you want to modify the Link Generator, just create your own and change the service in the pimcore class configuration.

**Comment by dpfaffenbauer** [comment]
sounds good, I'll have a look at that.

**Comment by dpfaffenbauer** [comment]
done
