### ISSUE TITLE
Store Product with Price 0.00 not get stored

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#414]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Products with Price `0.00` get skipped during the save process (db value = `null`). Since a product also could be a container product, they should get stored in db regardless its price.

**Comment by dpfaffenbauer** [comment]
doesn't that just happen on migrations?

I don't see any condition on saving them: https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php#L248
