### ISSUE TITLE
JS UI Issue on indizes / filter

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#422]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Indizes:
If i drag&drop a attribute from class definition to the indexed fields column, then i can just add one attribute, if i set one, then i can't add more. If i save the index and open again, then it's possible to add the next field.

Filter:
I use a pre filter, i selected there a value, when i save it and open the filter again, then it's not possible to change the value on this pre filter.

**Comment by dpfaffenbauer** [comment]
fixed with this two commits:

https://github.com/coreshop/CoreShop/commit/1ce5091598a18d1f5de61947df41985b25e7d163
https://github.com/coreshop/CoreShop/commit/8b2ca87344d6c0eed74db2eb091c626c40cc92b1
