### ISSUE TITLE
Enable multiple store price properties per product 

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#426]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Currently only one property is possible to be a store price. I think it would be an advantage to be able to add multiple store price properties to one product.

**Comment by dpfaffenbauer** [comment]
@davidhoeck not very easy possible. Since CoreShop StorePrice uses a doctrine entity and one doctrine entity can only be used for one table. 

I think it would be better to create a custom solution, what do you think?

**Comment by davidhoeck** [comment]
My approach would be to add a field called `property` to the `coreshop_product_store_price` table. 
For example we a have a `Product` Object Type and it has `defaultPrice` and `compareAtPrice` as `StorePrice` properties. 
The table would look like that: 

| id | productId  | price  | storeId  | property  |
|---|---|---|---|---|
| 1 | 70  | 2500  | 1  |  defaultPrice |
| 2 | 70  |  3000 |  1 |  compareAtPrice |

**Comment by dpfaffenbauer** [comment]
Quite happy with that, would you also create a PR for that?

**Comment by dpfaffenbauer** [comment]
@davidhoeck can you check PR #459

**Comment by davidhoeck** [comment]
Nice work! Exactly how I thought to do! @dpfaffenbauer

**Comment by dpfaffenbauer** [comment]
done
