### ISSUE TITLE
Add Subcategory Query to Category Condition

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#427]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

If you're having thousands of categories, you don't want to add them all to the category condition in price / shipment rules manually. 

Add a checkbox below the multihref element ("include subcategories") which respects recursive all children of every dropped category.

**Comment by dpfaffenbauer** [comment]
Wouldn't that mean we need to resolve the hierarchy to get all the ID's?

**Comment by solverat** [comment]
done with #435.
