### ISSUE TITLE
Fix Deprecations

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#428]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The goal is to remove all deprecation logs caused by coreshop (Calling private services in controller for example)

**Comment by dpfaffenbauer** [comment]
I guess it only happens in private services. Easiest solution would be to make them all public, but that is also the ugliest one :)

We have to take care about migrations as well. Sometimes we need to access services from there, so, what would be the best solution to that?

Controllers are easier, we could either use constructor injection or argument injection (not sure if thats the right name)
