### ISSUE TITLE
Custom Views: Quick Open

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#430]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Sometimes customer wants to have some filtered data. Pimcore comes already with a dedicated feature, called [custom views](https://pimcore.com/docs/5.x/Development_Documentation/Objects/Object_Classes/Class_Settings/Custom_Views.html).  CoreShop has a nice list and detail view but they are not connected via custom tree views. 

## Real Life example
The Customer wants to access all orders with`orderState` => `"confirmed"` and `shipmentState` = `"new"`. 

1. He just could type that query into the query selector but that's not really intuitive. 
2. You're going to provide a custom view:

```php
<?php
return [
    'views' => [
        [
            'treetype'        => 'object',
            'name'            => 'New Orders',
            'condition'       => null,
            'icon'            => '/bundles/coreshoporder/pimcore/img/shipment.svg',
            'id'              => 1,
            'rootfolder'      => '/coreshop/orders',
            'showroot'        => false,
            'classes'         => '',
            'position'        => 'left',
            'sort'            => '1',
            'expanded'        => false,
            'having'          => '(o9.orderState = "confirmed" AND o9.shippingState = "new")',
            'joins'           => [
                [
                    'type'      => 'left',
                    'name'      => ['o9' => 'object_9'],
                    'condition' => 'objects.o_id = o9.oo_id',
                    'columns'   => ['shippingState', 'orderState']
                ]
            ],
            'where'           => '',
            'treeContextMenu' => [
                'object' => [
                    'items' => [
                        'add'                => 0,
                        'addFolder'          => 0,
                        'importCsv'          => 0,
                        'paste'              => 0,
                        'copy'               => 0,
                        'cut'                => 0,
                        'publish'            => 0,
                        'unpublish'          => 0,
                        'delete'             => 0,
                        'rename'             => 0,
                        'searchAndMove'      => 0,
                        'lock'               => 0,
                        'unlock'             => 0,
                        'lockAndPropagate'   => 0,
                        'unlockAndPropagete' => 0,
                        'reload'             => 1
                    ]
                ]
            ]
        ]
    ]
];
```
To combine the greatness of the custom views and the CoreShop Order Management view, i just added a "quick open" feature, see video below:

![quick open](http://g.recordit.co/BYTqeiiqzq.gif)

**Comment by solverat** [comment]
We shouldn't bypass pimcore's default object handler. Objects should be editable at any time.

**Comment by dpfaffenbauer** [comment]
Yes, but in case of orders that shouldn’t happen anyway. Fields are always readonly cause of consistency of data. 

But: we still could have an option to open Pimcore Default object view

**Comment by dpfaffenbauer** [comment]
Ok, changing the default opening behaviour of Pimcore is not possible. You can't interrupt the opening flow of Pimcore. So, should we stick with your quick open solution then?

**Comment by dpfaffenbauer** [comment]
https://github.com/pimcore/pimcore/issues/2833

**Comment by dpfaffenbauer** [comment]
done. When pimcore allows to intercept the opening of an object, will implement that.
