### ISSUE TITLE
Field Name consistency 

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#434]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

 ## Current Payment Provider Fields
- identifier 
- position
- name (translated, used in the left list sidebar)
- description (translated)

## Current  Carrier Fields
- name (used in the left list sidebar)
- label
- description (translated)
*** 

 ## Suggestion Payment Provider Fields
- identifier (use`identifier` in left sidebar instead of `name`)
- position
- name (translated)
- description (translated)

## Suggestion  Carrier Fields
- identifier (renamed from `name`)
- implement position?
- name (rename from `label` and translate it)
- description (translated)

Keep current methods and mark them as deprecated.

**Comment by dpfaffenbauer** [comment]
@solverat Cannot rename Carrier Field `label` to `name` and `name` to identifier. That would be a huge BC as we change the meaning of a field completely

**Comment by solverat** [comment]
## Payment

<table>
  <tr>
    <th>PAYMENT BEVOR</th>
    <th>PAYMENT AFTER</th>
  </tr>
  <tr>
    <td>function getIdentifier() {  <br>&nbsp;&nbsp;return "unique_identifier;<br>}</td>
    <td>function getIdentifier() {<br>&nbsp;&nbsp;return "unique_identifier";<br>}</td>
  </tr>
  <tr>
    <td>function getPosition() {<br>&nbsp;&nbsp;return 0;<br>}</td>
    <td>function getPosition() {<br>&nbsp;&nbsp;return 0;<br>}</td>
  </tr>
  <tr>
    <td>function getName() {<br>&nbsp;&nbsp;return "translated_value";<br>}</td>
    <td>// deprecated<br>function getName() { <br>&nbsp;&nbsp;return $this-&gt;getTitle();<br>}</td>
  </tr>
  <tr>
    <td>function getDescription() {<br>&nbsp;&nbsp;return "translated_value";<br>}</td>
    <td>function getDescription() {<br>&nbsp;&nbsp;return "translated_value";<br>}</td>
  </tr>
  <tr>
    <td></td>
    <td>// new<br>function getTitle() {<br>&nbsp;&nbsp;return "translated_value";<br>}</td>
  </tr>
</table>

## Carrier
<table>
  <tr>
    <th>CARRIER BEVOR</th>
    <th>CARRIER AFTER</th>
  </tr>
  <tr>
    <td>function getName() {<br>&nbsp;&nbsp;return "unique_identifier";<br>}</td>
    <td>// deprecated<br>function getLabel() {<br>&nbsp;&nbsp;return $this-&gt;getTitle();<br>}</td>
  </tr>
  <tr>
    <td>function getLabel() {<br>&nbsp;&nbsp;return "translated_value";<br>}</td>
    <td>// deprecated<br>function getName() { <br>&nbsp;&nbsp;return $this-&gt;getIdentifier();<br>}</td>
  </tr>
  <tr>
    <td>function getDescription() {<br>&nbsp;&nbsp;return "translated_value";<br>}</td>
    <td>// new<br>function getTitle() {<br>&nbsp;&nbsp;return "translated_value";<br>}</td>
  </tr>
  <tr>
    <td></td>
    <td>// new<br>function getIdentifier() {<br>&nbsp;&nbsp;return "unique_identifier";<br>}</td>
  </tr>
<tr>
    <td></td>
    <td>function getDescription() {<br>&nbsp;&nbsp;return "translated_value";<br>}</td>
  </tr>
  <tr>
    <td></td>
    <td>// new (?)<br>function getPosition() {<br>&nbsp;&nbsp;return 0;<br>}</td>
  </tr>
</table>
