### ISSUE TITLE
Default country for country selection in address

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#437]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

If you have a list of available countries, then it would be nice, that i can preselect a country, that are selected as default when a customer add a new shipping address. And it would be also nice to select a few countries for a preferred selection, if you have a long list of allowed countries.

**Comment by dpfaffenbauer** [comment]
@albertmueller have you tried this? http://symfony.com/doc/current/reference/forms/types/choice.html#empty-data

Don't think that is an CoreShop Issue and needs to be solved in a project context.
