### ISSUE TITLE
Index boost for CoreShop index tables

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#439]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I would like to add indexes for specific fields in the CoreShop index tables to boost the access time on this tables for example in category overviews. Maybe it's possible to add a checkbox in the index configuration popup, where i can setup the columns.

**Comment by dpfaffenbauer** [comment]
need to think about that, cause an index doesn't need to be MySQL, that could be Elasticsearch/Doofinder or anything else as well.

It is already possible for each type to add custom stuff, I'll look at that.

**Comment by dpfaffenbauer** [comment]
done
