### ISSUE TITLE
Wrong category sorting

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#460]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Coreshops getHierarchy function does not seem to proper sort categories:
![coreshop-category-sorting](https://user-images.githubusercontent.com/2771909/40610651-914192a8-6273-11e8-8441-fc881cc73809.png)
Category sorting in pimcore backend does differ from sorting in the coreshop frontend (1-9 a-z wanted).

**Comment by dpfaffenbauer** [comment]
The real problem here is that Pimcore doesn't support sorting of objects in general. In the backend it solely does it by using keys. Which is not a 100% right as well

**Comment by Cruiser13** [comment]
Sorting it by keys in the frontend would be a good first step I think. We can always override the getHierarchy action with a custom sort parameter from our object if we need to.
But i'd prefer to keep it simple and pimcore-like in the first step.

**Comment by dpfaffenbauer** [comment]
@Cruiser13 PR #463 is implemented. Can you check please?

**Comment by Cruiser13** [comment]
The PR works for me with the latest changes. Thanks!

**Comment by dpfaffenbauer** [comment]
done
