### ISSUE TITLE
Use right Invoice / Shipment Context in OrderMail

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#478]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

## Wrong State Context
Use right State context `InvoiceStates` instead of  `OrderInvoiceStates`, see here:
https://github.com/coreshop/CoreShop/blob/2592a1d4cf2065f23366ac7f7acd6242d728453c/src/CoreShop/Bundle/CoreBundle/Order/OrderMailProcessor.php#L131

Use right State context `ShipmentStates` instead of  `OrderShipmentStates`, see here:
https://github.com/coreshop/CoreShop/blob/2592a1d4cf2065f23366ac7f7acd6242d728453c/src/CoreShop/Bundle/CoreBundle/Order/OrderMailProcessor.php#L145

## RFC: Correct State Cycle
Also: which invoice / shipment state is the right one? I think `getDocumentsNotInState` is not correct. We always need the last one with `STATE_COMPLETE`.

**Comment by dpfaffenbauer** [comment]
done
