### ISSUE TITLE
CartItem custom price field

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#491]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

It would be nice to have a custom price field or function, to set individual prices for products. For example i have an configurator and the price is a summary of item price, setup and wape costs, i would like to save this custom price in cart item, that the customer can process the checkout with this price.

**Comment by dpfaffenbauer** [comment]
Use Custom Cart Processors to do that, this allows you to set a custom cart-item price.
