### ISSUE TITLE
[FrontendBundle]: Install configuration declaration has wrong node type

### ISSUE THREAD

**Issue by khusseini** [coreshop/CoreShop#497]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/FrontendBundle/DependencyInjection/Configuration.php declares all nodes in `pimcore_admin.install` as scalar nodes, however, they should be array nodes

**Comment by dpfaffenbauer** [comment]
done
