### ISSUE TITLE
Allow adding Shipments without completed Payment 

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#501]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I'm having a payment type "_Invoice_". Usually i ship the order before any payments has been made. Currently it's not possible to add a shipment before the payment enters the `payed` state.

**Comment by Cruiser13** [comment]
Basically similar to #393 where the invoice could not be created without the payment.

**Comment by solverat** [comment]
with this one it's possible to add payments and shipments regardless the payment state.
only exception: if order has been cancelled there is no way to add shipments or invoices.

**Comment by solverat** [comment]
also: it's possible to add payments to a cancelled order. i think we should disable this feature since a cancelled order is the end of the line...

**Comment by solverat** [comment]
done with #506.
