### ISSUE TITLE
Allow different redirect after adding product to cart

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#502]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Like the `registerAction` in `RegistrationController` handles custom redirects, it could be also useful to use the same behavior in `addItemAction` of the `CartController`. By default, the user reaches the cart after he added a product (which still should be the default).

Adding a `_redirect` parameter could be the solution:

```php
$redirect = $request->get('_redirect', $this->generateCoreShopUrl($this->getCart(), 'coreshop_cart_summary'));
```

Then we only need to pass a `_redirect` parameter and the the user gets redirect back to the product after he has added it to the cart.
```twig
{% set href = coreshop_path(product, 'coreshop_product_detail') %}
{{ coreshop_path(coreshop.cart, 'coreshop_cart_add', {product: product.id, _redirect: href}) }}
```

**Comment by solverat** [comment]
+ Also add this to the `WishListController` since it works the same way.

**Comment by Cruiser13** [comment]
Does this still show the message that the product has been palced in the cart @solverat ?
I like the idea of redirecting the user to the produkt again but we should also inform him that his action - adding the product to the cart - has been successful.

**Comment by dpfaffenbauer** [comment]
yes, if you display flashes in the template, that still works the same

**Comment by solverat** [comment]
@Cruiser13 yup - just check your `Product/detail.html.twig`, you need the include the flash messages partial:

```twig
 {% include '@CoreShopFrontend/Common/flash_messages.html.twig' %}
```
