### ISSUE TITLE
Mail Text placeholders missing

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#516]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The %Text(firstname); %Text(lastname); in the user-registered mail are not working.
Mail will look like
Hello , instead of Hello Max Mustermann,

Didn't check the other mail templates yet. Reproducable in coreshop demo and in customer instance.

**Comment by solverat** [comment]
I cannot reproduce it at all. Do you use the `order mail` action in your notification rule?

**Comment by dpfaffenbauer** [comment]
No, guess he is talking about the regular mail.

**Comment by Cruiser13** [comment]
I found the bug in the **user-registered** mail which does ship with coreshop. Didn't check the other mails yet.

**Comment by dpfaffenbauer** [comment]
done
