### ISSUE TITLE
new backend order with variants fails

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#534]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Currently it's not possible to create a backend order with variants. Message: `"Product [ID] has no valid TaxRuleGroup"`. Maybe because of the missing `getGetInheritedValues` method.

**Comment by dpfaffenbauer** [comment]
solved
