### ISSUE TITLE
Backend Order Creation: Payment missing

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#546]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Create Backend Order
- Choose Payment
- Create Order
Payment is missing in Order Details

**Comment by dpfaffenbauer** [comment]
thats not right, actually you don't create a payment, you simply choose a payment provider.

Creating a Payment should be done by the revise link sent automatically to the customer. (currently not implemented, but to be done)
