### ISSUE TITLE
Backend Order Creation: Price Modification

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#549]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | sort of

In the finalization state of a backend order creation, a admin may wants to modify the total price.

## Discount
There are some discount fields in total. How do they get applied?

## Rules
I think it's not a good idea to allow adding rules in backend order creation. Most of the time a e-commerce manager wants to create a order simple and fast. Otherwise he has to create rules just for a backend order which is simply a bad workflow.

## Price Adjustments
It would be great to have something like a order adjustment feature (see [spreecommerce adjustments for example](https://guides.spreecommerce.org/developer/adjustments.html)). This could be also useful in many other situations (custom price additions or payment fees for example).

**Comment by dpfaffenbauer** [comment]
Order Adjustment feature is already done ;)

Adding adjustments should now also be possible, we just have to think about taxes.

**Comment by dpfaffenbauer** [comment]
https://github.com/coreshop/CoreShop/pull/1324/commits/f4b2a3d417b660312fdeca815d05605de4957a2d
