### ISSUE TITLE
[PRICERULE] Items Amount + Merchandise Value Conditions

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#562]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Cart Value
Rename "Amount" condition to "Cart Value". 

## Cart Items Amount
Create new cart condition "Cart Items Amount":

### Min
Type: `numeric`
Description: Allow to define minimum items in cart

### Max
Type: `numeric`
Description: Allow to define maximum items in cart

### Deep Amount
Type: `checkbox`
Description:
- Unchecked: Only calculate product items. (Default) 
  - Example: Product A (1x), Product B  (2x) in cart. Items: 2
- Checked: Calculate product items + Amount.
  - Example: Product A  (1x), Product B (2x) in cart. Items: 3

**Comment by dpfaffenbauer** [comment]
PR if still needed.
