### ISSUE TITLE
[PRICERULE] Tag Condition

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#564]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

 🏷️ There should be a Tag Condition.

## Options
- **Tag-Selector**: Allow to select tags
- **Checkbox**: Include all Subcategories

### Global Price Rule
Tags of all products

### Cart Rule
Tags of all products in given cart

**Comment by dpfaffenbauer** [comment]
PR if still needed
