### ISSUE TITLE
Additional Store-Price field not working properly

### ISSUE THREAD

**Issue by micru** [coreshop/CoreShop#573]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Adding an additional store price field to CoreShopProduct does not work properly. Creating a new Product object and adding prices does work. However any subsequent changes on any price field are not beeing saved. There is no error in Pimcore admin when saving, but after reloading the object, all price fields hold their initial value, not the updated one. 

## Steps to reproduce

1. add a store price field to `CoreShopProduct` class (with different name than the default one)
2. create a CoreShopProduct and fill the default prices as well as your newly added price field
3. save your product
4. change some prices
5. save your product again
6. reload the product object => the price fields will hold the old, initial price informations

**Comment by dpfaffenbauer** [comment]
hmmm.... I just tried it in my dev setup and on demo2.coreshop.org and it works. can you try to reproduce it on demo2.coreshop.org?

**Comment by micru** [comment]
Looks like it was a Pimcore Bug. We cannot reproduce it on your demo2.coreshop.org. We were on Pimcore 5.2, after migrating to 5.4 we are not able to reproduce it anymore.. there where a lot of changes in both `Controller/Admin/DataObjectController` and `\Model\DataObject`. Therefore i assume this isses could be resolved
