### ISSUE TITLE
Wrong availability check when adding items to the cart 

### ISSUE THREAD

**Issue by s-ormanns** [coreshop/CoreShop#574]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When adding an item to the cart, the availability of the item is only checked against the requested quantity, not against both: the sum of the quantity already in the cart + the requested one.

**Steps to reproduce**
1. Keep adding items to the cart, even after the "On hand"-value is exceeded

**Comment by dpfaffenbauer** [comment]
@s-ormanns PR is ready, can you test please?

https://github.com/coreshop/CoreShop/pull/595

**Comment by dpfaffenbauer** [comment]
merged.
