### ISSUE TITLE
Missing Discount on initial Cart View

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#576]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- create a simple cart price rule (condition: store, action: 10,- discount)
- add product to cart
- go to cart: discount field is missing and not available
- click "update cart": discount is visible

**Comment by dpfaffenbauer** [comment]
Did you check if the discount got applied in the backend?

**Comment by solverat** [comment]
No discount values available.
