### ISSUE TITLE
[IndexBundle] Range Filter doesn't have a template

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#611]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no

**Comment by dpfaffenbauer** [comment]
hmmm... the thing is that bootstrap 4 doesn't come with a range slider per default.

**Comment by solverat** [comment]
Just use a default html5 slider? https://www.html5tutorial.info/html5-range.php

**Comment by dpfaffenbauer** [comment]
thats not a range, thats just a slider
