### ISSUE TITLE
[Voucher Price Rule] Multiple Codes not working

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#614]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Create a voucher cart rule
- Add voucher condition
  - max usage per code: `1`
  - allow only one voucher cart: `false`
- Add two codes: `xx` and `xy`
- Apply code `xx` to cart: success
- Apply code `xy` to cart: invalid code error

**Comment by dpfaffenbauer** [comment]
That has nothing to do with the condition, every price-rule is only allowed once per cart. If you need to allow another one, you have to add another price rule.
