### ISSUE TITLE
Locale Context: Check if Locale is allowed

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#620]
| Q                | A
| ---------------- | -----
| Bug report?      | sort of
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The`PimcoreLocaleService` returns the locale from a given request (if available) regardless if it's a valid system locale:

https://github.com/coreshop/CoreShop/blob/fa37674351b00d183893a749ac623e98684784fb/src/CoreShop/Component/Locale/Context/PimcoreLocaleContext.php#L37

We should check if the locale is a valid system locale and if not the default locale should be returned.

**Comment by dpfaffenbauer** [comment]
fixed
