### ISSUE TITLE
allow CSV import/export of Store Prices

### ISSUE THREAD

**Issue by myrdd** [coreshop/CoreShop#637]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

CoreShop does not yet support import/export of the `storePrice`:

https://github.com/coreshop/CoreShop/blob/6a03ec5468badc4802c8816d96027c567fbdb776/src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php#L445-L459

I need this feature at least for the single-shop (one shop only) case.

For the multi-shop export case, I guess the easiest solution is to concatenate all prices using a delimiter:

```php
return implode("|", $prices);
```

I'll try to implement this feature.

**Comment by dpfaffenbauer** [comment]
```php
return implode("|", $prices);
```

is to less, you need to export the StoreId as Identifier as well.

**Comment by myrdd** [comment]
Okay. Any preference for the format? Json array of objects? Json array of tuples? Non-Json (e.g. `1:123|2:987`)?

**Comment by dpfaffenbauer** [comment]
Json KeyValue?


```json
{
    "1": 10000,
    "2": 80000
}
```

**Comment by myrdd** [comment]
I guess that when importing, the new values need to be ”merged into“ the current values, no?

1. create a new `StorePrice`, that is, `$storePrice = $factory->createNew();`
2. use all prices from `$importValue`
3. use those prices from `$object` which have been missing in `$importValue`

https://github.com/coreshop/CoreShop/blob/6a03ec5468badc4802c8816d96027c567fbdb776/src/CoreShop/Bundle/CoreBundle/CoreExtension/StorePrice.php#L456

**Comment by dpfaffenbauer** [comment]
yep

**Comment by myrdd** [comment]
Some more questions. I'll get the old store prices using `$repo->findForProductAndProperty`.

- Is it ”acceptable“ to re-use the `StorePrice` objects in the repo for unchanged prices?
- Is it acceptable even to re-use them for changed prices, i.e., simply use `setPrice($newPrice)`?
- `getFromCsvImport` will return the array of `StorePrice` objects, right?

**Comment by dpfaffenbauer** [comment]
1. yes, don't persist the StorePrice when nothing has changed
2. yes, just persist them using the doctrine entity manager
3. not sure if `getFromCsvImport` even returns something. If pimcore does it in there editables, yes, we return an array.

**Comment by myrdd** [comment]
FTR, as far as I understand, `getFromCsvImport` only should return the new value, and not yet persist. This is the code which calls `getFromCsvImport`:

https://github.com/pimcore/pimcore/blob/v5.4.4/lib/DataObject/Import/ColumnConfig/Value/DefaultValue.php#L95-L108

So shortly after `getFromCsvImport`, `setStorePrice` is called on the product.

**Comment by dpfaffenbauer** [comment]
OK, so don't persist it, but use the existing StorePrice Objects, or create a new one if it doesn't exist.

How do we handle csvData for stores that don't exist? Should we throw an exception or just ignore them?

**Comment by myrdd** [comment]
> How do we handle csvData for stores that don't exist? Should we throw an exception or just ignore them?

IMHO it's better to throw an error than silently ignoring... at least for now.

**Comment by dpfaffenbauer** [comment]
👍

**Comment by myrdd** [comment]
Pimcore issue: https://github.com/pimcore/pimcore/issues/3363
Pimcore PR: https://github.com/pimcore/pimcore/pull/3364
