### ISSUE TITLE
Voucher Credit

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#640]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? |no
| RFC?             | yes

We should consider a voucher credit case: 
- add product (price of `10.00`)
- add voucher (amount of `15.00`)

## Currently
Remaining amount of `5.00` will be lost.

## Possible Feature
Create a new voucher (with a relational link to the originally one) with remaining amount and:
 - add it to a customers profile section (what happens to guests?)
 - add it to confirmation mail?

**Comment by dpfaffenbauer** [comment]
This also means having the possibility of paying with a credit.

**Comment by dpfaffenbauer** [comment]
@khusseini There is not much to refactor about that. You can use adjustments now to minimize the cart-value and thats basically it. I do like your approach. It is similar to what @solverat did in a project. Maybe we could create a separate bundle with exactly that functionality?

**Comment by dpfaffenbauer** [comment]
@khusseini could you share your implementation once you finished upgrading?

**Comment by dpfaffenbauer** [comment]
ping @khusseini

**Comment by khusseini** [comment]
@dpfaffenbauer we still didn't upgrade to the newest release, however this hopefully will happen in the coming weeks

**Comment by dpfaffenbauer** [comment]
ping @khusseini 

We are thinking about implementing some sort of Customer Credit anyway, maybe your solution could help here a lot.

**Comment by dpfaffenbauer** [comment]
part of it is implemented in core, the other part is a extension
