### ISSUE TITLE
[bug] csv import of storePrice: invalid json gets ignored silently

### ISSUE THREAD

**Issue by myrdd** [coreshop/CoreShop#643]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Import a product via csv with `storePrice` being something invalid like `{"1": 0123}` (the integer must not start with a zero), and the storePrice will silently get ignored, because `json_decode` does not throw, but instead returns an empty value.

I'll create a PR.

**Comment by dpfaffenbauer** [comment]
already merged and fixed
