### ISSUE TITLE
front-end language switcher not working

### ISSUE THREAD

**Issue by myrdd** [coreshop/CoreShop#648]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

The language switcher (frontend) is currently not working. Clicking on the locale simply shows a hash (`#`) in the browser's address bar.

![spectacle lh7472](https://user-images.githubusercontent.com/4286829/46024141-aabed400-c0d5-11e8-8889-11c536537f34.png)

I guess the implementation should be similar to the currency switching:

* path: `/en/shop/switch-language/de`
* route: `coreshop_switch_language`
* implement `LanguageController::switchAction`

**Comment by dpfaffenbauer** [comment]
you are absolutely right. This has never been properly implemented for the demo. To be honest: this was never on our schedule, cause in every project we have a custom UI/Design and therefore implement that in there anyway. But it should be fixed in this demo as well.

**Comment by myrdd** [comment]
Are you already working on this? I've got a quick-and-dirty fix.

**Comment by dpfaffenbauer** [comment]
Please no dirty fixes ;)

You still can make a PR and we can talk about it though.

**Comment by dpfaffenbauer** [comment]
@myrdd I just created a PR for that.

**Comment by dpfaffenbauer** [comment]
done
