### ISSUE TITLE
Do not reset password for guest-accounts

### ISSUE THREAD

**Issue by micru** [coreshop/CoreShop#662]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

There should be a check if a customer has only a guest account before resetting the password. Currently if a customer puts their email into the _forgot password_ form only the existance of a customer with this email is checked. If this email belongs to a guest, the customer gets an reset password mail anyways but will not ne able to login after setting a new password. This is very confusing.

Checking if the customer is guest here https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/FrontendBundle/Controller/RegisterController.php#L96 and directing back to the _forget password form_ if so, should do the trick for now.

**Comment by dpfaffenbauer** [comment]
are you sure? cause `findCustomerByEmail` checks on if it is a customer and not a guest.

**Comment by micru** [comment]
You are right.. unfortunately we got 2 Customer with the same email. One is a guest, the other not. Looks like this is the real problem. We will investigate this further and might open a new issue if we found the reason why this happened. Guess you might close this issue

**Comment by dpfaffenbauer** [comment]
Yes, we are aware of that and already thought about splitting that up into 2 objects -> User and  Customer

**Comment by dpfaffenbauer** [comment]
superceded by https://github.com/coreshop/CoreShop/issues/665
