### ISSUE TITLE
Split User and Customer into two Objects.

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#665]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes

With the current implementation, it is quite hard to decide and understand what user is a customer and what "just" a guest customer, in order to make that better dividable, split the entities into two.

**Comment by dpfaffenbauer** [comment]
@solverat this should also make the Members Integration easier right?

**Comment by dpfaffenbauer** [comment]
I disagree. In terms of separating concerns, it should be divided. The customer is the person who actually buys. The user is the entity that we authenticate against. Currently we use the same for both.

Current solution could also raise issues with CMF, cause a guest user is no a customer per se. And we store them to the CMF currently.

**Comment by dpfaffenbauer** [comment]
Well, at least not a recurring customer we can perform CMF actions against

**Comment by Cruiser13** [comment]
Upvoting this.

**Comment by dpfaffenbauer** [comment]
will not happen for now. as discussed internally

**Comment by Cruiser13** [comment]
Too bad. Would have brought a lot of benefits in my opinion. If it is not planned for now but not off the table - maybe leave it open and work on this at a later point?

**Comment by dpfaffenbauer** [comment]
we had a discussion on the weekend that the benefits aren't that great to bring that big of a bc break. what would be your benefits?

**Comment by Cruiser13** [comment]
Here are some:

- allow browsing store without cookies (DSGVO compliant)
- allow customers (for example B2B) without accounts
- allow registrations (for a free service for example) without customer details such as customer ID
- allow other kind of customers (for example one company customer with 3 different employees each having a user account but using the same customer account)
- easy implementation of different members and customer classes. If you setup a coreshop customer implementing members and CMF the class is extremly huge and hard to handle atm - also slows down the system

In my opinion they are just two separate data models which should kept separately therefor.

**Comment by dpfaffenbauer** [comment]
1. AFAIK: CoreShop doesn't trigger a session until the customer is logged in, so there would be no change
2. Thats already possible using the "isGuest" Flag. But true, I would prefer the other solution to solve this more
3. You still need to have a Customer to put future order against, so thats not valid
4. True
5. True

@solverat What is your opinion about this arguments?

**Comment by Cruiser13** [comment]
@dpfaffenbauer if you run a freemium service point 3 is still valid because you'll end up with a lot of customer ids which are not being used if you auto-assign one to each free registration member. Customer object could be created at a point where the user switches to a paid plan. In terms of gdpr/dsgvo you're not allowed to collect more data as you absolutely need - so for free accounts a email adress might be enough but for a paid account (customer object) I'll need firstname, lastname, address and so on.

**Comment by solverat** [comment]
I still don't see any benefits of having two objects in core. The given pro-list only implies that there is a need for a very slim customer object. Currently there is:

- `salutation`
- `firstname`
- `lastname`
- `email`
- `password`
- `newsletter_fields ` (_not required.._)
- `gender` (_not required..._)
- `locale`
- `relation_fields`_(group and addresses)_

That's not really "extremely huge"...

**Back to your List:**

1. Not dispatched/required until registration or login process has been invoked
2. No difference with one or two objects and also not related? Skip the account part and your good to got
3. You always need an id if you're working with pimcore objects. What's the point of having two pimcore objects, if you "just" need a temporary customer? 
4. Point to you and also a good b2b feature for sure! BUT! Solving this by splitting the customer object is not the right way. This could be done with a custom "sub-customer" relational object in your project for example. Adding them to the customer object and hook into the symfony authorize process.
5. Like described above, there is no "extremely huge" customer object.

**So let's sum things up:**

- Maybe we could clean up the customer object down to the most required fields
- **New Feature**: We should discuss multiple logins per customer feature
- **New Feature**: We should discuss temporary customers e.g. on-the-fly checkouts and customer journeys

I'm with you, when it comes to simplicity and GDPR. But splitting user and customer into two objects will not improve things – rather the opposite.

**Comment by Cruiser13** [comment]
Just a short clearification: With customer id I did not mean the pimcore oo_id but rather the customer number (like a contract number or invoice number).

Proposal for split objects would be a very slim user object:
user:
- email
- auth (e.g. password, SSO, login with Amazon/Facebook...)
- locale

strictly separated from the customer object:
- customer number
- relation_fields (group and addresses)
may be extended with company details if customer is company like
- vat number
- company name
or may be extended with person details if customer is a person
- firstname
- lastname
- gender
- salutation


Invoices and orders belong to the customer object. The relation of a user to a customer can be implemented in different ways - might even be a n:m relation.

**Comment by dpfaffenbauer** [comment]
implemented now
