### ISSUE TITLE
Wrong Translations

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#670]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Payment
![bildschirmfoto 2018-10-09 um 10 22 31](https://user-images.githubusercontent.com/700119/46656003-4f98e100-cbad-11e8-9c4a-7480cc1f3ee9.png)

Instead of `coreshop_quantity` it should be `coreshop_amount`

## State
The`coreshop_state` is used in Address and state machine context. 
- keep `coreshop_stated` for address context
- use `coreshop_order_state` in state machine context.

**Comment by dpfaffenbauer** [comment]
# Payment
see PR #674 

# State
no idea what you mean and where it is used.
