### ISSUE TITLE
Use ShippableInterface in throughout the whole shipping cost calculation process

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#678]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Currently some parts like the `DefaultCarrierResolver` and so on are using the `ShippableInterface`.  Shipping rule conditions and actions are requiring the `CartInterface`. That means if the shippable object is no cart, the whole shipping cost calculation won't work. 
So my suggestion would be to implement a function in the `ShippableInterface` called `getSale` and use the `ShippableInterface` throughout the whole process. If conditions or actions need some information like the store or currency of the sale, they just call `getSale` and get the cart or order or any other object that implements the `SaleInterface`

**Comment by dpfaffenbauer** [comment]
Well, not a 100 percent right... Shipping rule conditions and actions still require a Shippable, but the default implementations of some conditions/actions require that shipable is a cart, therefore you potentially could overwrite those.

But, you are definitely right that the current solution is not ideal

**Comment by dpfaffenbauer** [comment]
Think thats already done now
