### ISSUE TITLE
Cannot access protected property Product::$specificPriceRules - Pimcore v5.5.0 and higher 

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#683]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Due to major changes in Pimcore 5.5.0 (Document, Asset and DataObject properties are now protected instead of public) I get this error inside the `CartToOrderTransformer`. 
I think it's a bug on the CoreShop side - but I am not really sure ...

**Comment by dpfaffenbauer** [comment]
Already fixed on RC.1 branch and master

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php#L104

**Comment by dpfaffenbauer** [comment]
I will close this for now, cause I think thats already solved.
