### ISSUE TITLE
[PRICERULES] Respect Store VAT Settings

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#684]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Scenario
- Create store with **unchecked** "store prices with VAT"
- Create a product (price: € 100)
- Create AT TaxRule (20%)
- Create a cart rule `TEST`: 
  - Condition: Store
  - Amount: `min amount: 120`
  - Action: `free shipping`
- Add product to cart

## Currently
Cart Rule `TEST` gets applied because the rule processor always calculates with taxes. 

## Expected
Store-Setting `with/without VAT` needs to be involved in the rule calculation.

**Comment by dpfaffenbauer** [comment]
I don't agree with you that this is considered a bug, this is simply not supported currently, also cause it can be quite confusing actually. (Well, it already is, but still).

A Price rule potentially affects any store (based on rules), so in one store, its 100€, the other 120€. It would consider this more like either a feature/enhancement.

**Comment by dpfaffenbauer** [comment]
I will close this for now, since this will make things pretty difficult and confusing
