### ISSUE TITLE
[INDEX] Accessibility Improvements

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#692]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Currently we can't use the filter without a category.

## Example
I want to show some products based on a predefined filter (populated with a single pre-condition for example). I also need the same settings and layout from my category list view (`CategoryController` => `indexAction`).

## Suggestion
Provide an Area-Element to set a CoreShop Filter (With optional category selector and a filter selector) on any document => render same view as category indexAction does and also use the same settings (like the grid settings, defined in store)

**Comment by dpfaffenbauer** [comment]
I would much rather go for a more generic approach. Your suggestion only works with the whole CoreShop Suite, where as this brick would perfectly work for IndexBundle alone. Except the Category thing and configurations.

Also, you cannot render the category action for every use-case. This maybe works for some, but not in all cases -> at least not in the onces I had already.

**Comment by dpfaffenbauer** [comment]
I still see that project specific.
