### ISSUE TITLE
Change Doctrine Collation to utf8mb4_general_ci

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#695]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

The default collation in Pimcore is utf8mb4_general_ci, but the default for Doctrine is utf8mb4_unicode_ci, if u compare strings between a Pimcore table and a Coreshop table then you got there no result.

**Comment by dpfaffenbauer** [comment]
actually, it is the other way around, Pimcore sets unicode charset, but uses general instead:

https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/config/pimcore/default.yml#L55

I will talk to Pimcore and see what it should be

**Comment by dpfaffenbauer** [comment]
https://github.com/pimcore/pimcore/commit/cd359aeb8eeea68bc1e814fd6c5aa767edfa06db -> fixed by Pimcore
