### ISSUE TITLE
Crash on Checkout/ Payment

### ISSUE THREAD

**Issue by grammit** [coreshop/CoreShop#696]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

Checkout crash on Payment step. Reproducible on https://demo2.coreshop.org/

Attempted to call an undefined method named "getName" of class "CoreShop\Component\Core\Model\PaymentProvider".

**Comment by dpfaffenbauer** [comment]
fixed in PR #697

**Comment by solverat** [comment]
This needs to be reverted. Now we have identifier labels instead of translated titles.

**Comment by dpfaffenbauer** [comment]
wrong. `getTitle` should be used, `getName´ was deprecated and removed. Thats the wrong issue here.
