### ISSUE TITLE
Disable Customer Deletion if bounded Orders are available

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#707]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | sort of

## Current Situation
Since we've had some bugs within the guest/customer workflow, one of our clients decided to delete customer objects to create them again. Those customer objects had some ongoing and completed orders which are now orphans.

## Solution
Throw an Exception on Pre-Delete if a customer object is involved in one or more orders.

**Comment by dpfaffenbauer** [comment]
shouldn't we do the same for products?

**Comment by solverat** [comment]
No. Products should be cloned after they have been ordered. Imagine thousands of products with just one item in stock...

**Comment by dpfaffenbauer** [comment]
that means thousand of cloned products just for history -> don't think thats better.

**Comment by solverat** [comment]
"Just"... Yes! I need to see which product exactly my customer bought 5 years ago. I also need some crazy statistics, customer journeys, etc. But yes, there could be a different approach: "archive products". CoreShop does not allow to delete bought products but change their state to "archived" for example. Archived products needs to be moved into a specific tree for example. Maybe we should do some more research and discussion about that. However, it's unrelated to this topic.

**Comment by dpfaffenbauer** [comment]
we would need an "archive" status anyway, cause once you copy the product, it is potentially available in the store anyway because there is no identifier that says what kind of product that now is. Having a separate class would probably work, but that also implies that they are the same which is hard to manage with complicated product classes.

**Comment by dpfaffenbauer** [comment]
But, sure, it is a different topic.
