### ISSUE TITLE
Allow Preview for unpublished Products

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#716]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

There is no way to display a product on front end until it's published. We should check:
- `pimcore_object_preview` query fragment is available in product / category url request
- User is backend user

-> Display product!

**Comment by dpfaffenbauer** [comment]
I am not really sure that CoreShop is even responsible for that. Just think about Multi-Store sites, how to decide which theme to show the product for? And themes can potentially be very very different to each other.

**Comment by solverat** [comment]
Right, that's not a part of coreshop. But allow displaying products in preview mode should be possible. It's just about checking if particularly query-fragment (pimcore_object_preview) is available (and user is a logged-in pimcore user): 

https://github.com/coreshop/CoreShop/blob/ac40d1e589e540277339fd9023ff5305e654bc27/src/CoreShop/Bundle/FrontendBundle/Controller/ProductController.php#L47-L48

Everything else: DIY in a custom link generator.

**Comment by solverat** [comment]
That's the way pimcore works. While editing an unpublished product, it should be possible to allow editors to preview their upcoming products (like documents for example).

**Comment by dpfaffenbauer** [comment]
Sure, but thats not an argument for having backend logic in frontend controllers.

**Comment by dpfaffenbauer** [comment]
as discussed, I don't see CoreShop responsible for this, as the solution would only solve a small percentage of use-cases.

**Comment by solverat** [comment]
wut?

**Comment by dpfaffenbauer** [comment]
think about themes, B2B stores where you need to be authenticated, different previews for different customer-groups, etc. its more than just show a "preview".
