### ISSUE TITLE
Countries are removed when removing Store

### ISSUE THREAD

**Issue by adrozdek** [coreshop/CoreShop#745]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When I create a store and choose allowed countries they are removed when Store is removed:

Creating Store:
![demo2 coreshop org pimcore](https://user-images.githubusercontent.com/16477689/49727116-cadf4780-fc6f-11e8-8f60-c039a1b39fa6.png)
Countries: 
![demo2 coreshop org pimcore 1](https://user-images.githubusercontent.com/16477689/49727139-d3378280-fc6f-11e8-9af8-b1235d589f0a.png)
Store is removed:
![demo2 coreshop org pimcore 2](https://user-images.githubusercontent.com/16477689/49727144-d6cb0980-fc6f-11e8-96e2-8d8083097104.png)
Missing countries:
![demo2 coreshop org pimcore 3](https://user-images.githubusercontent.com/16477689/49727146-d7fc3680-fc6f-11e8-885a-bcda86db859b.png)

**Comment by dpfaffenbauer** [comment]
@adrozdek can you check PR #746 pls?
