### ISSUE TITLE
Provide Solid Backend Translations

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#792]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

We should provide some solid translations for all our coreshop classes. Our Support-Team needs to translate all the keys in every upcoming project from scratch which leads to slightly different translations each time (and it's also a bit annoying :)).

## To-Do
- We should use symfony translation keys. So, every layout label needs to be called like:
  - `coreshop.class.product.information`
  - `coreshop.class.product.meta_title`
  - and so on...
- Only for new installations: Do not touch already running instances

**Comment by dpfaffenbauer** [comment]
I absolutely agree

**Comment by dpfaffenbauer** [comment]
done
