### ISSUE TITLE
Voucher rule with gift product action  error

### ISSUE THREAD

**Issue by s-ormanns** [coreshop/CoreShop#795]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When having a voucher rule with a gift product defined in an action and after applying this rule to the cart (via voucher code), I expect to end up with a cart holding the products originally added + the free gift product (it shouldn't cost something right?)? But instead the item is added to the cart and marked as a gift item, but it has a price and increases the total price of the cart too.

**Comment by dpfaffenbauer** [comment]
fixed
