### ISSUE TITLE
No CoreShop icon shown after install (Pimcore nightly)

### ISSUE THREAD

**Issue by patrickfabrizius** [coreshop/CoreShop#81]
Not sure if this plugin is supposed to work with 3.1.1 (doesn't say), but following the installation instructions with Pimcore 3.1.1 doesn't seem to work: 

* Clean install of Pimcore 3.1.1
* Git clone CoreShop into plugins/CoreShop
* Git clone website-example into website/ (overwriting defaults, but keeping default var/ directory)

When I enable the extension in Pimcore everything seems fine, but when I click Install, I get the following error: "No resource implementation found for: CoreShop\Model\Configuration"

Seems like the plugin is unable to find it's own lib?

**Comment by dpfaffenbauer** [comment]
CoreShop is not compatible with Pimcore 3.1.1. Please try it with the latest Build.

**Comment by patrickfabrizius** [comment]
Ok!

**Comment by patrickfabrizius** [comment]
I just re-tried with Pimcire nightly, same procedure for installing, it worked better now :) However, I don't get any CoreShop icon inside Pimcore (as described in the "getting started")?

**Comment by dpfaffenbauer** [comment]
do you get any error? did the installation work?

**Comment by patrickfabrizius** [comment]
The installation worked, no errors there .. I reloaded Pimcore, but can't find any CoreShop icon? 
When navigating the site (clean install mind you, so just the website-example files), I get: "Route 'coreshop_index' for building the URL not found".

**Comment by dpfaffenbauer** [comment]
looks like there was a problem with the installation. could you please delete everything (also the database) and re-try it? please take a look at the developer-console for any errors in the installation process.

**Comment by patrickfabrizius** [comment]
I've already tried that, wiped everything, clean install, git clone coreshop / website-example (into plugins/CoreShop and website/ respectively) but exactly the same behavior .. 

There's a lot of CoreShop related errors in debug.log so attaching it. (I'm currently trying on MAMP with php 5.6.7 / MySQL 5.5.42 btw).

[debug.log.txt](https://github.com/coreshop/CoreShop/files/145044/debug.log.txt)

**Comment by patrickfabrizius** [comment]
I saw that CoreShop package.json mentions "installer-plugin" as requirement, could that have something to do with it?

**Comment by dpfaffenbauer** [comment]
i did find a bug. could you please re-try again?

**Comment by dpfaffenbauer** [comment]
oh, pimcore changed the layout within the latest build. thats why there is no icon. i will fix this and get back to you

**Comment by patrickfabrizius** [comment]
Ok, great! :)
Thanks!

**Comment by dpfaffenbauer** [comment]
so. now it should work.

i downloaded the latest build (with the new UI layout ;) ) and installed coreshop. you dont need to care about the composer requirement "installer-plugin". this one is only needed when installing coreshop via composer.

**Comment by patrickfabrizius** [comment]
Ok, gonna give it a try, will let you know shortly! Thanks!

**Comment by patrickfabrizius** [comment]
It works!

**Comment by dpfaffenbauer** [comment]
great :)
