### ISSUE TITLE
Price batch assignment

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#817]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I believe it'd be handy to have an option to batch-assign prices to products. For example raise the price of all products of the category X by 2 percent.
It's hard for a user to achieve that because the prices are stored in a special table. We solved this by running queries like UPDATE coreshop_product_store_price SET price=price*(100+2)/100 in the database but this is ugly.
We can't use price rules for this because they'll still show the old price (which is lower in this case) and they do not persist the changes. Having the same option price rules for products do provide but persist them (and make the percents actually go up instead only handling price reductions) would be useful.

**Comment by dpfaffenbauer** [comment]
I don't see that currently as a main requirement for CoreShop. You can run queries directly against the DB to do that anyway. I guess that is topic of a plugin
