### ISSUE TITLE
Stock Sufficient Check on Checkout

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#820]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

- Add a product with active store tracking and **one** item in stock
- Open two browsers and add product to cart and process to final checkout summary
- Hit "buy" on browser 1: ok
- Hit "buy" on browser 2: also ok - which is obviously wrong.

**Comment by davidhoeck** [comment]
How about holding back the stock that is in the cart? when the cart expires the stock will be released again?

**Comment by dpfaffenbauer** [comment]
well, what about bots that trigger the add-to-cart form and reserve stock then?

**Comment by davidhoeck** [comment]
@dpfaffenbauer I think the stock should only be reserved if the checkout process has been started.
That's harder for bots to reserve stock.

**Comment by dpfaffenbauer** [comment]
no. Stock will be reserved when the user decided to actually buy it. We open a bunch of more problems introducing different ways of reserving stock then.

**Comment by solverat** [comment]
I think that's not a big issue here. Just check stock sufficiency after these lines and we're good to go: 

https://github.com/coreshop/CoreShop/blob/b3f85464e9f9e77728ae5e4e704844b361bb3c8b/src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php#L170-L177

**Comment by dpfaffenbauer** [comment]
I think so too

**Comment by davidhoeck** [comment]
For sales such as the Black Friday, it is essential to reserve the stock at the beginning of the checkout process, otherwise it may happen that in the end no stock is over.

**Comment by dpfaffenbauer** [comment]
yes, first come first serve principle -> once you ordered it, it is reserved, once you paid it, it will be shipped.

If you need that in your application -> you can do that, but its not something for the default implementation.

**Comment by davidhoeck** [comment]
ok 👍
