### ISSUE TITLE
Exception error at homepage

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#83]
![error_details](https://cloud.githubusercontent.com/assets/9025839/13847138/e15a11f2-ec4b-11e5-8894-f585261ea694.png)
Hello,

First of all, thanks a lot for sharing this great project. So much work, and good work on it you have done!

I just want to report a problem when trying to test the online demo. The homepage send an exception (Whopps!).

Here the details:

URL: http://coreshop.lineofcode.at/en/shop

Whoops \ Exception \ ErrorException (E_ERROR)
Call to a member function getSymbol() on a non-object
…/­plugins/­CoreShop/­lib/­CoreShop/­Tool.php, line 44

I joined a capture.
I tested with Firefox last version, language French, country France, windows 7.
All cookie/cache cleaned, and fresh open of the url put this error.

Hope you can have a look!

Best regards.

**Comment by dpfaffenbauer** [comment]
Hy Yivan,

could you please try it again? The Problem has something todo with the wrong configuration of the DEMO Shop. CoreShop is a multi-country and multi-currency Shop-System. And, well, i did not configure France with a Currency.

I also made a small fix to return the configured base currency if the country is wrong configured.

hope it works now.

Best Regards

**Comment by dpfaffenbauer** [comment]
PS: The official DEMO is also my Developer Version, so you might find other bugs as well ;)

**Comment by Yivan** [comment]
Thanks all is working great now!
I will tell you if i found another problem.
Best regards

**Comment by dpfaffenbauer** [comment]
great, glad i could help you :)
