### ISSUE TITLE
Shipping/Invoice Adress Identifier

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#830]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

There is a new law in town and within the new geo-blocking regulation it's not allowed to block EU users anymore ( if your store is based in the EU).

>  All EU countries should be listed in your billing address options. No matter whether your store actually delivers to those countries or not.

Currently, coreshop does not make any differences if you're adding a new shipping or invoice address. So it's impossible to restrict the country selection for shipping but not for invoice addresses.

- We should identify the address type by adding an additional field to the address class: `type`.
- We should add two buttons instead of one in the addresss step: `add new invoice address` and `add new shipping address`.

**Comment by dpfaffenbauer** [comment]
merged into 2.0 and 2.1
