### ISSUE TITLE
Remove PHP5 sort fix issue

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#840]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

remove all `@usort` things: https://github.com/coreshop/CoreShop/blob/2.0/src/CoreShop/Bundle/AddressBundle/Form/Type/ZoneChoiceType.php

**Comment by solverat** [comment]
merged with #862.
