### ISSUE TITLE
Multiselect filter doesn't render with a good structure

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#841]
Hello,

On the last coreshop version, multiselect filter doesn't seems to be correctly rendered for the structure of the options.

Here is a way to reproduce it:
- on the product class, add a multiselect field named "multisection"
![multiselect-classe](https://user-images.githubusercontent.com/9025839/53423087-ffe27700-39e0-11e9-9446-59d63789275b.png)

- create an index
![multiselect-index](https://user-images.githubusercontent.com/9025839/53423096-04a72b00-39e1-11e9-9f00-4d27faa216e9.png)

- create a filter
![multiselect-filter](https://user-images.githubusercontent.com/9025839/53423106-083ab200-39e1-11e9-806d-cc47b434687f.png)

- create two products, one having "gamme1" and "gamme2" selected, and the other having "gamme2" and "gamme3" selected.

- calling preparedCondition this way:

````
        $page = $request->get('page', 0);
        $defaultPerPage = 5;
        $perPage = $request->get('perPage', $defaultPerPage);
        
        $filter = $this->get('coreshop.repository.filter')->find(1); //Get Filter by ID 1
        $filteredList = $this->get('coreshop.factory.filter.list')->createList($filter, $request->request);
        $filteredList->setLocale($request->getLocale());
        $filteredList->setVariantMode(\CoreShop\Component\Index\Listing\ListingInterface::VARIANT_MODE_HIDE);

        $filteredList->load();
        
        $currentFilter = $this->get('coreshop.filter.processor')->processConditions($filter, $filteredList, $request->query);
        $preparedConditions = $this->get('coreshop.filter.processor')->prepareConditionsForRendering($filter, $filteredList, $currentFilter);  
````

A dump of $preparedConditions returns:
```
  1 => array:6 [▼
    "type" => "multiselect"
    "label" => "multisection"
    "currentValues" => []
    "values" => array:2 [▼
      0 => array:2 [▼
        "value" => ",gamme1,gamme2,"
        "count" => "1"
      ]
      1 => array:2 [▼
        "value" => ",gamme3,gamme2,"
        "count" => "1"
      ]
    ]
    "fieldName" => "multisection"
    "quantityUnit" => null
  ]
```

It should return the following values:
```
    "values" => array:3 [▼
      0 => array:2 [▼
        "value" => "gamme1"
        "count" => "1"
      ]
      1 => array:2 [▼
        "value" => "gamme2"
        "count" => "2"
      ]
      2 => array:2 [▼
        "value" => "gamme3"
        "count" => "1"
      ]
    ]
```

Here is a screenshoot of the rendering using the default twig template for multiselect:
![multiselect-render](https://user-images.githubusercontent.com/9025839/53423194-328c6f80-39e1-11e9-9c82-28eb56895bc3.png)

It should be 3 checkbox... "gamme1", "gamme2" and "gamme3".

Thanks.

**Comment by dpfaffenbauer** [comment]
thats actually not possible to solve with CoreShop Index. the problem is following: There is only one entry per product in the mysql-index. So, its not possible to store `gamme1` and `gamme2` into two separate lines. It is possible with relations though, but not with a simple multiselect.

**Comment by Yivan** [comment]
Thanks for having looking into it.

But how can we use filter for multiselect fields so ?

**Comment by dpfaffenbauer** [comment]
use relations

**Comment by Yivan** [comment]
I will try it, i didn't know that relation can be used with multiselect fields (i was thinking it was just for relation field).
Thanks.

**Comment by Yivan** [comment]
@dpfaffenbauer Hello, i just tried to use the "Relational Multiselect" for the multiselect from my use case (see first post).

In the values fields, i get some strange results:

![filter-config](https://user-images.githubusercontent.com/9025839/54764039-4f3e5080-4bf7-11e9-89d1-241e667910b8.png)

And in the frontend, the filter is not displayed (because objects is empty).

I really don't get it how to filter my multiselect class field with this relational multiselect filter...
Documentation seems to not mentions all the filter (`https://www.coreshop.org/docs/2.0.0/Development/Index_and_Filters/Filter/index.html`), I will open a separate issue for this.

**Comment by dpfaffenbauer** [comment]
You did understand me wrong -> the relational multiselect should be used with relational types. My idea was for you to create a separate Pimcore Object and use that for the select.

**Comment by Yivan** [comment]
Thanks a lot for your return, and so fast! I understand better.

Unfortunatly, I cannot break all my multiselect fields to relationnal fields... It is not at all conveniant for enduser to use relation object, just for a multiselect fixed list. And moreover as it is an already existing projet we cannot change such as the model.

In the end, it means there no way of making filter on multiselect fields as it out of the box on CoreShop ?? : ( (we have to develop our own ?). I really think it is an important one which should be provided natively. `select` and `multiselect` are the most class field used for filtering, after comes `bolean` and `number`.

By the way i noticed, that bolean filter is no more present as filter choice in the tab filter of the Pimcore GUI. Is it intended or replaced by another one ?

**Comment by dpfaffenbauer** [comment]
I never had the need for a multiselect filter based on a textual multiselect in Pimcore, thats why its not there.

Boolean Select will come back, we just didn't implement it in CoreShop 2

**Comment by Yivan** [comment]
I think it depends use case and starting modeling knowing this. But really we use it at least on each our ecommerce project : (

Do you think you could open a new feature for making a select and multiselect for multiselect field.
As well there will be (like the native ecommerce of pimcore):
- Select for Select field
- Multiselect for Select field
- Select for Multiselect field
- Multiselect for Multiselect field
Adding bolean is important too, this is great if it is planned.

We currently are starting using ecommerce extension for our projects, and we like CoreShop but for now as we need more index/filter capabilities that is why we are trying it. And those filters will be really a good thing for CoreShop I think to have them embedded natively.

Just a side question please, for bolean we can use "select" filter type (like the native ecommerce pimcore), or we need to implement our one ?

**Comment by dpfaffenbauer** [comment]
you can open a feature request, if the ecommerce framework can handle that, we can too. The CoreShop Index/Filter is heavily inspired by the ecommerce framework.

yes, you can. The idea behind the Boolean was to mix and match different fields into one big filter with checkboxes, something like:

```
#### Features
 - [ ] 12gb ram
 - [ ] 16gb ram
 - [ ] intel i7
 - [ ] intel i9
```

Hope you get the idea.

**Comment by Yivan** [comment]
Great, so the "Bolean filter" has another use (it seems powerfull if it agregates several field!), and we must use "Select filter" for simple checkbox field class.
Ok, i open a separate ticket for the new feature.
