### ISSUE TITLE
Adding the missing "range" template for filter.

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#842]
Hello,

All default filters have their template, only the `range` type filter is missing.
https://github.com/coreshop/CoreShop/tree/master/src/CoreShop/Bundle/FrontendBundle/Resources/views/Category/filter

It would be nice to have it implemented by default, so all default filter can be easily rendered.

Thanks.

**Comment by dpfaffenbauer** [comment]
that's in purpose missing, there is no easy/light solution available for bootstrap 4

**Comment by Yivan** [comment]
Ok thanks for you fast answer on this!
