### ISSUE TITLE
Setup filters on the online demo.

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#843]
Hello,

As purpose to have exemples for developpers and guidelines, and as visual testing too, it would be nice to have index/filters enabled on the CoreShop online demo.
Actually zero filters are defined and neither used in the frontend on the demo.

Thanks.

**Comment by dpfaffenbauer** [comment]
that is the case, but the demo is not setup automatically every day for technical reasons I didn't had time yet to fix them.

**Comment by Yivan** [comment]
Ok great, last time i checked filter was empty, so was this issue. Thanks again.
