### ISSUE TITLE
Wrong once per cart check in VoucherConditionChecker

### ISSUE THREAD

**Issue by s-ormanns** [coreshop/CoreShop#860]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Wrong check in once per cart condition in https://github.com/coreshop/CoreShop/blob/d37aa3bb1657fe19f233815a6dd2011ed5a05875/src/CoreShop/Component/Order/Cart/Rule/Condition/VoucherConditionChecker.php#L70

Shouldn't it be `$rule->getVoucherCode() === $storedCode->getCode()`?

**Comment by dpfaffenbauer** [comment]
no, thats fine as it is.
