### ISSUE TITLE
Cannot add a tax rule

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#865]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

currently it's not possible to add new tax rules, i got this error:

URL: /admin/coreshop/tax_rule_groups/save
Method: post
Message: An exception occurred while executing 'INSERT INTO coreshop_tax_rule (behavior, creationDate, modificationDate, taxRuleGroupId, taxRateId, countryId, stateId) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [0, null, null, 5, 2, null, null]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'creationDate' cannot be null

pimcore 5.6.3 - coreshop 2.0.4

**Comment by dpfaffenbauer** [comment]
Cannot be reproduced on a fresh 2.0 installation

**Comment by solverat** [comment]
@albertmueller @dpfaffenbauer I'm facing the exact same issue after a composer update (No coreshop update, only sub dependencies) but on with a different entity (payment): 

Version: 3.0.6

```
An exception occurred while executing 'INSERT INTO coreshop_payment (state, orderId, datePayment, details, creationDate, modificationDate, number, description, total_amount, currency_code, `order`, payment_provider_id, currency_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["new", 358784, "2023-08-02 15:47:54", "[]", null, null, "O29789_155396276688406", null, 21446, "CHF", 358784, 2, 33]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'creationDate' cannot be null
```

Now, the funny part: If I'm enabling the debug mode on stage/production, everything works fine.

**Comment by dpfaffenbauer** [comment]
https://github.com/doctrine-extensions/DoctrineExtensions/issues/2600

**Comment by dpfaffenbauer** [comment]
On Debug Mode, there is no Entity Metadata Cache. With, there is. I haven't found a proper solution yet, other than hotfixing ExtensionMetadataFactory

**Comment by solverat** [comment]
... ok. Thanks for the hint, @dpfaffenbauer!
