### ISSUE TITLE
[CoreBundle] StorePrice CoreExtension not working with Pimcore 5.7 > Lazy Loaded field methods renamend

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#868]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In Pimcore v5.7.0 the methods for lazy loaded fields have been refactored, therefore the StorePrice extension is not working anymore.

**Comment by dpfaffenbauer** [comment]
Already known, will be fixed later today

**Comment by dpfaffenbauer** [comment]
fixed
