### ISSUE TITLE
Store product in cart session

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#87]
after adding a product to cart, the original product object is still bounded in the cartItem object.

- it's impossible to manipulate the product price before adding to cart.
- the product price could get changed which already has been placed in a user cart.

**Comment by dpfaffenbauer** [comment]
It would be possible to create a CoreShopCartProduct/CoreShopOrderProduct Object.

**Comment by dpfaffenbauer** [comment]
cc7aaa157c2f1950c3f657d2b49e9a199f2e6f6a should solve your problem. You can store the price somewhere in the cart-item and overwrite these methods
