### ISSUE TITLE
[IndexBundle] Handle Store Prices in the index out-of-the-box

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#882]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

If there are prices for multiple stores CoreShop should create a index table for every store, exactly like the localized index tables, to allow sorting and filtering for store prices out of the box.

**Comment by dpfaffenbauer** [comment]
There is more to prices than just the Store Price. That’s the reason we don’t have a price index yet. Since this would only a half solution, it’s not implemented and will not happen this way

**Comment by davidhoeck** [comment]
So what would be your way of having the storePrice in the index table to display a range slider or something else?

**Comment by dpfaffenbauer** [comment]
Add it to the index. But as soon as someone creates a pricing rule, it doesn’t work anymore

**Comment by dpfaffenbauer** [comment]
you could also just `join` the store table prices on index queries. thats possible with an index extension.
