### ISSUE TITLE
Can't change store price in variant

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#884]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The option "allow inheritance" is allowed in my class (variants disallowed).
I can set the store price in the main product, if i create a sub product and change the price there then i can save the object, but after a reload it shows me the price of the main product again.

pimcore 5.6.3 - coreshop 2.0.4

**Comment by dpfaffenbauer** [comment]
which version? 2.0 or 2.1.x-dev?

**Comment by albertmueller** [comment]
coreshop 2.0.4

**Comment by dpfaffenbauer** [comment]
cannot be reproduced. I just created a new 2.0.x-dev Installation and tried what you said.

It also doesn't make any sense for me, cause prices are NOT inheritable.
