### ISSUE TITLE
Cannot save notification rule

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#885]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Cannot save notification rule "order shipped", if i link the exist email template in the actions "order mail" and click on save, i got an error "de: This value is not valid."
Same on "order comment", i think it's a general issue on "order mail" actions.

pimcore 5.6.3 - coreshop 2.0.4

**Comment by dpfaffenbauer** [comment]
fixed
