### ISSUE TITLE
Adding missing filters to the documentation

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#887]
Hello,

On the filter documentation page `https://www.coreshop.org/docs/2.0.0/Development/Index_and_Filters/Filter/index.html` only 4 filters are explained.

Actually, there is 7 types of filters:

![filter-types](https://user-images.githubusercontent.com/9025839/54764667-83664100-4bf8-11e9-94c2-97998ae2b559.png)

It would be great if like the all 7 filters are explained on this page.
Especially relational ones which seems advanced. Nested seems more self explaining.
It could be added that "select" and "multiselect" filter can only be used for "select" (not "multiselect") field class object.

I noticed on the documentation bolean filter is mentionned, but it seems to not exist anymore, maybe it should be removed ?

Thanks!

**Comment by Yivan** [comment]
It could be add in the documentation that handling bolean field classe can be done with the `select` filter type.

**Comment by Yivan** [comment]
Hello, you closed this issue, but it seems the documentation is not up-to-date as it mentions only 4 conditions filters, where actually there is 9 on the demo. Do I miss something ? Thanks!

![image](https://user-images.githubusercontent.com/9025839/125637253-8587582b-55a4-4714-b1f4-63b5cd3e3cf4.png)

**Comment by dpfaffenbauer** [comment]
ticket is open for more than 2 years and nobody provided documentation for it.... that's why I closed it. it is stale
