### ISSUE TITLE
[New feature] Adding filters for multiselect field of Pimcore classes.

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#888]
Hello,

Actually the `select` and `multiselect` filters work only with single `select` field of Pimcore classes.
Like the native Pimcore e-commerce, it would be great to have those two filters for the `multiselect` field of Pimcore classes.

Here is a screenshot of native Pimcore e-commerce framework:

![filter-native](https://user-images.githubusercontent.com/9025839/54773518-0a6fe500-4c0a-11e9-8a79-01616d7462bb.png)

As CoreShop filters use the same logic, it should be feseable.

So there will be 4 filters:
- Select for Select field => already exists
- Multiselect for Select field => already exists
- Select for Multiselect field => new one, proposed in this issue
- Multiselect for Multiselect field => new one, proposed in this issue

Original discussion was here: https://github.com/coreshop/CoreShop/issues/841
Documentation should be updated too: https://github.com/coreshop/CoreShop/issues/887

Thanks.

**Comment by dpfaffenbauer** [comment]
done

**Comment by Yivan** [comment]
Great news ! Thanks
