### ISSUE TITLE
[Documentation] Improve documentation for setting elasticsearch.

### ISSUE THREAD

**Issue by Yivan** [coreshop/CoreShop#889]
Actually, setting Elasticsearch for CoreShop is not documented.
The only page mentions it: `https://www.coreshop.org/docs/2.0.0/Development/Index_and_Filters/Index/index.html`.

It would be nice to know where to set elasticsearch url, port, etc. so it is proposed as choice in the GUI:
![elastic](https://user-images.githubusercontent.com/9025839/54774251-946c7d80-4c0b-11e9-8190-138a439d0730.png)

I imagine after initial setting of Elasctic connection, all is handled automatically, if not some help could be great.

Thanks!

**Comment by dpfaffenbauer** [comment]
There is no elastic implemented, so that’s why there is no documentation for that

**Comment by Yivan** [comment]
Ha ok !! So i think you should remove it from the index page https://www.coreshop.org/docs/2.0.0/Development/Index_and_Filters/Index/index.html
It make me think it was implemented !
Thanks.
