### ISSUE TITLE
AddToCartAvailability Validation Not Cart Changes Aware

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#893]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Changing the quantity in cart should also trigger the AddToCartAvailability Validation  (and also the new AddToCartQuantity validator).

**Comment by dpfaffenbauer** [comment]
No! It should not. The AddToCart specifically is only for the AddToCartForm. There is a separate one to check if the quantity is available for quantity changes:

https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/CoreBundle/Validator/Constraints/CartStockAvailabilityValidator.php
