### ISSUE TITLE
[Redis] Can't change store price

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#895]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If redis is enabled, then it's not possible to change the store price in pimcore backend.

pimcore 5.6.3 - coreshop 2.0.4

**Comment by solverat** [comment]
Hey @albertmueller,

I hope you're still able to reproduce it. If so, please try this one:

Go to `CoreShop\Bundle\CoreBundle\Doctrine\ORM\ProductStorePriceRepository` and change all `useResultCache` to:

`->useResultCache(false);`.

**Comment by dpfaffenbauer** [comment]
that should be fixed now
