### ISSUE TITLE
CoreShopCart Object GarbageCollector

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#90]
add a maintenance script and some options:

- [ ] delete anonymous carts older than `[0-9]` days.
- [ ] delete user carts older than `[0-9]` days.
- [ ] ~~only delete carts without stored items~~ (Does not occur any more)

**Comment by dpfaffenbauer** [comment]
fixed with #4ceae98db725e0c999c5a752535d8b75d61d8ae5
