### ISSUE TITLE
Add default to StoreValues

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#903]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Having multiple stores also makes you have to maintain a lot of prices for every store. It would be easier to have a default one, once the default one is set, the others use the same value.

**Comment by solverat** [comment]
Maybe use a fallback flag in each store (like locales in pimcore)?

**Comment by dpfaffenbauer** [comment]
will be postponed to 2.2.0, since 2.1.0 is now stable and almost final

**Comment by dpfaffenbauer** [comment]
Not that easy as I thought originally, how do we handle different currencies for stores?
