### ISSUE TITLE
CoreShopProduct haslazykey method doesnt exist

### ISSUE THREAD

**Issue by edgarmiadzieles** [coreshop/CoreShop#927]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | yes

When creating a new product object from product class an error is thrown: CoreShopProduct has no method haslazykey. Storeprice assumes that given object in preGetData has this method implemented.

**Comment by dpfaffenbauer** [comment]
Already fixed in the upcoming 2.0.6 release. Will be released on Monday.
