### ISSUE TITLE
swedish is missing as a language on crowdin

### ISSUE THREAD

**Issue by kmpm** [coreshop/CoreShop#928]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I'm missing a Swedish translation and that language is also missing at crowdin.
Please add to crowdin so that I can start translating

**Comment by dpfaffenbauer** [comment]
https://crowdin.com/project/coreshop/sv-SE# there you go :)
