### ISSUE TITLE
Whats the best method to translate the frontend bundle?

### ISSUE THREAD

**Issue by kmpm** [coreshop/CoreShop#935]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Using crowdin I can translate the admin interface but what about the FrontendBundle?
Do i edit the translations.yml directly and create a pull-request?

**Comment by dpfaffenbauer** [comment]
you mean the translations that get imported into pimcore right? So Yes: you have to create a PR. But I guess we could add that to crowdin as well somehow.

**Comment by kmpm** [comment]
That's good enough for me but crowdin is kind of convenient.
