### ISSUE TITLE
Translation for Currency Names

### ISSUE THREAD

**Issue by kmpm** [coreshop/CoreShop#936]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

There is no way of translating currency names.
Would be fine to use same method as translating country names.

**Comment by dpfaffenbauer** [comment]
what about intl extension?

https://symfony.com/doc/current/components/intl.html#currencies

**Comment by kmpm** [comment]
Looks like a very good fit.

**Comment by dpfaffenbauer** [comment]
ok, so I will close this for now then.
