### ISSUE TITLE
Show a default for non translated Countries

### ISSUE THREAD

**Issue by kmpm** [coreshop/CoreShop#937]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

When using a non English language in admin it's quite difficult to administer countries.
In the list where you select country all non translated countries show as empty string.
Default fallback to English or ISO code would be great if possible.
![Language Translation](https://user-images.githubusercontent.com/96618/55864343-97102200-5b7c-11e9-9a40-b39c0590c677.png)

**Comment by dpfaffenbauer** [comment]
👍

**Comment by dpfaffenbauer** [comment]
fallsback now to isoCode
