### ISSUE TITLE
More gender options

### ISSUE THREAD

**Issue by kmpm** [coreshop/CoreShop#941]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

It is a controversial issue but in this day and age it should at least be optional to register which gender you are. 
If CoreShop want to be really progressive there should be a configurable set of genders.

**Comment by dpfaffenbauer** [comment]
Actually, that is not really a CoreShop issue. We use Pimcore's 'gender' type here... We should talk to Pimcore about that, can you create a ticket on there GitHub pls?

**Comment by kmpm** [comment]
Will do.
