### ISSUE TITLE
Make salutation optional or configurable per country/language

### ISSUE THREAD

**Issue by kmpm** [coreshop/CoreShop#942]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? |no
| RFC?             | no

I would say that no one in Sweden is even comfortable with using Mr./Mrs. or any other salutation.
If there would be more gender options as well ( #941 ) then only having Mr/Mrs fails as well.
You can remove Salutations on a Country but it does not seem to have any effect on the registration form.
Salutation should at least be an optional field.

**Comment by dpfaffenbauer** [comment]
We in Austria use the german pandon for it: 'Herr' and 'Frau' and I think that every country has some sort of that for a formal greeting, don't you do that in Sweden? Those salutations are changeable, so you can use whatever you want. You can also translate them into different languages by using Pimcore's Shared Translations.

**Comment by kmpm** [comment]
It's extremely rare in Sweden to use salutations and titles. Started to go out of fashion  in the 60s. Won't even use lastname that much. A swede will feel awkward having to use and chose a salutation. If that's a good or bad thing could be discussed endlessly :)

Even so... If connected to the gender issue I mentioned, if you don't want to disclose gender you probably do not want to disclose if you would like to be called Mr or Mrs either since the gender information very much could be derived from that (could with high probability be derived using firstname as well but you have to draw the line somewhere and a full name is a legal requirements)

It's not a big thing but I thought it could be worth creating a feature request out of it.

**Comment by dpfaffenbauer** [comment]
ok.

The salutation isn't a required field, so you can Extend the Form-Type and remove the field from there. Guess that is the easiest solution. Happy with that?

**Comment by kmpm** [comment]
Good enough.
Thanks for the good service by the way.
