### ISSUE TITLE
Error Unknown column type "pimcoreObject" requested.

### ISSUE THREAD

**Issue by tymon82** [coreshop/CoreShop#947]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When install on newest pimcore demo error display with migration:

` [RuntimeException]
  An error occurred when executing the ""pimcore:migrations:migrate -s pimcore_core -n"" command:

                      Pimcore Core Migrations

  WARNING! You have 1 previously executed migrations in the database that are not registered migrations.
      >> 2019-04-05 11:27:07 (20190405112707)
  Migrating up to 20190402073052 from 20190402073052

    ++ migrating 20180904201947

       -> Changing Database schema for new workflows. Please see upgrade notes for migration of data!
  Migration 20180904201947 failed during Execution. Error Unknown column type "pimcoreObject" requested. Any Doctrine
   type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the kn
  own types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then yo
  u might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTyp
  eMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might h
  ave a problem with the cache or forgot some mapping information.

  In DBALException.php line 267:

    Unknown column type "pimcoreObject" requested. Any Doctrine type that you use has to be registered with \Doctrine
  \D
    BAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(
  ).
     If this error occurs during database introspection then you might have forgotten to register all database types
  fo
    r a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#ge
  tM
    appedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping in
  fo
    rmation.

**Comment by dpfaffenbauer** [comment]
where? how to reproduce?

**Comment by dpfaffenbauer** [comment]
is CoreShop enabled?

**Comment by tymon82** [comment]
Done 3 things:
copy pimcore demo basic source
`./vendor/bin/pimcore-install`
`composer require coreshop/core-shop ^2.0`

**Comment by dpfaffenbauer** [comment]
I don't see how that could cause any issue. Since the `pimcoreObject` Dbal Type is only enabled and used once CoreShop is enabled

**Comment by tymon82** [comment]
I got this error and proof is in 1st comment ;) Maybe ist because pimcore demo version instead raw pimcore ?

**Comment by dpfaffenbauer** [comment]
Just did exactly the same and no errors. I am wondering why it even executes migrations for you... something is odd with your setup, can you start again?

**Comment by jahwood** [comment]
same Error on enable and install PimcoreEcommerceFrameworkBundle

**Comment by dpfaffenbauer** [comment]
What does this have todo with the EcommerceFramework? Did you install CoreShop and disabled it again?

**Comment by jahwood** [comment]
> What does this have todo with the EcommerceFramework? Did you install CoreShop and disabled it again?

no just install raw skeleton pimcore with composer, than enabled EcommerceFramework, after that install it and get error

**Comment by dpfaffenbauer** [comment]
well, since you didn't install CoreShop, it can't have anything to do with it

**Comment by jahwood** [comment]
is coreshop required to use e.com.framework bundle? 

> well, since you didn't install CoreShop, it can't have anything to do with it

**Comment by dpfaffenbauer** [comment]
nope
