### ISSUE TITLE
Wrong Total Tax Calculation

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#971]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

**order.getTaxes** shows a different tax amount as order.getTotalTax:
![image](https://user-images.githubusercontent.com/2986829/57219148-77dba780-6ff7-11e9-89f2-6202df96be03.png)

**Comment by dpfaffenbauer** [comment]
give a bit more context please: how many products, whats the price per product, whats the tax rate

**Comment by albertmueller** [comment]
Just one product, price including tax is 105 Euro, tax rate 19%.
CoreShop Version 2.0.6

**Comment by dpfaffenbauer** [comment]
fixed
